### ISSUE TITLE
Forever Stranded cant find java version issue

### ISSUE THREAD

**Issue by Khodiisonsteam** [AllTheMods/ATM-3#1002]
hello im trying to start a forever stranded server for me and my friends to play however im getting an error that says "java version or path error", so naturally i tried redownloading java and deleting all other versions of it and it still wont work.

heres the server log if that helps
----------------------------------------------------------------- 
INFO: Starting batch at 20220625:182714 
----------------------------------------------------------------- 
 
DEBUG: Current Dir is C:\Users\switc\Desktop\serverfolder\Forever+Stranded-1.9.9.1+Server+Files -- trying to change to C:\Users\switc\Desktop\serverfolder\Forever+Stranded-1.9.9.1+Server+Files\ 
INFO: Checking that settings.cfg exists 
DEBUG: settings.cfg Found. Logging full contents below: 
;Details/Help Found here: https://github.com/AllTheMods/Server-Scripts

MAX_RAM=5G; 
JAVA_ARGS=-server -d64 -Xms1G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:UseSSE=3;
CRASH_COUNT=10; 
CRASH_TIMER=600; 
RUN_FROM_BAD_FOLDER=0; 
IGNORE_OFFLINE=0; 
IGNORE_JAVA_CHECK=0; 
USE_SPONGE=0;

MODPACK_NAME=Forever Stranded;
MCVER=1.10.2;
FORGEVER=12.18.3.2511; 
FORGEURL=DISABLE; 
 
INFO: Loading variables from settings.cfg 
DEBUG: Starting variable definitions: 
DEBUG: MC_SERVER_MAX_RAM=5G 
DEBUG: MC_SERVER_FORGE_JAR= 
DEBUG: MC_SERVER_SPONGE_BOOT= 
DEBUG: MC_SERVER_JVM_ARGS=-Xmx5G -server -d64 -Xms1G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval 
DEBUG: MC_SERVER_MAX_CRASH=10 
DEBUG: MC_SERVER_CRASH_TIMER=600 
DEBUG: MC_SERVER_IGNORE_OFFLINE=0 
DEBUG: MC_SERVER_RUN_FROM_BAD_FOLDER=0 
DEBUG: MC_SERVER_MCVER=1.10.2 
DEBUG: MC_SERVER_FORGEVER=12.18.3.2511 
DEBUG: MC_SERVER_FORGESHORT=2511 
DEBUG: MC_SERVER_FORGEURL=DISABLE 
DEBUG: MC_SERVER_SPONGE=0 
DEBUG: MC_SERVER_PACKNAME=Forever Stranded 
DEBUG: MC_SERVER_SPONGEURL= 
DEBUG: MC_SERVER_SPONGEBOOTSTRAPURL= 
DEBUG: MC_SERVER_ERROR_REASON=Unspecified 
DEBUG: MC_SERVER_TMP_FLAG=0 
DEBUG: MC_SERVER_CRASH_COUNTER=1 
DEBUG: MC_SERVER_CRASH_YYYYMMDD=20220625 
DEBUG: MC_SERVER_CRASH_HHMMSS=182714 
DEBUG: Current directory file listing: 
 Volume in drive C is Windows
 Volume Serial Number is 70E4-F880

 Directory of C:\Users\switc\Desktop\serverfolder\Forever+Stranded-1.9.9.1+Server+Files

06/25/2022  06:27 PM    <DIR>          .
06/25/2022  06:27 PM    <DIR>          ..
06/25/2022  06:20 PM    <DIR>          config
06/25/2022  06:20 PM             3,237 LICENSE.md
06/25/2022  06:20 PM    <DIR>          mods
06/25/2022  06:20 PM            11,544 README.md
06/25/2022  06:20 PM    <DIR>          scripts
06/25/2022  06:20 PM            40,518 ServerStart.bat
06/25/2022  06:27 PM             2,060 serverstart.log
06/25/2022  06:20 PM             9,751 ServerStart.sh
06/25/2022  06:20 PM               539 settings.cfg
06/25/2022  06:20 PM    <DIR>          world
               6 File(s)         67,649 bytes
               6 Dir(s)  46,909,349,888 bytes free
DEBUG: JAVA version output (java -d64 -version): 
ERROR: Could not find 64-bit Java 1.8 or 1.9 installed or in PATH 
ERROR: Error flagged, reason is: ""JavaVersionOrPathError"" 
WARN: Server startup script is exiting. Dumping current vars: 
DEBUG: MC_SERVER_MAX_RAM=5G 
DEBUG: MC_SERVER_FORGE_JAR= 
DEBUG: MC_SERVER_SPONGE_BOOT= 
DEBUG: MC_SERVER_JVM_ARGS=-Xmx5G -server -d64 -Xms1G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval 
DEBUG: MC_SERVER_MAX_CRASH=10 
DEBUG: MC_SERVER_CRASH_TIMER=600 
DEBUG: MC_SERVER_IGNORE_OFFLINE=0 
DEBUG: MC_SERVER_RUN_FROM_BAD_FOLDER=0 
DEBUG: MC_SERVER_MCVER=1.10.2 
DEBUG: MC_SERVER_FORGEVER=12.18.3.2511 
DEBUG: MC_SERVER_FORGESHORT=2511 
DEBUG: MC_SERVER_FORGEURL=DISABLE 
DEBUG: MC_SERVER_SPONGE=0 
DEBUG: MC_SERVER_PACKNAME=Forever Stranded 
DEBUG: MC_SERVER_SPONGEURL= 
DEBUG: MC_SERVER_SPONGEBOOTSTRAPURL= 
DEBUG: MC_SERVER_ERROR_REASON="JavaVersionOrPathError" 
DEBUG: MC_SERVER_TMP_FLAG=0 
DEBUG: MC_SERVER_CRASH_COUNTER=1 
DEBUG: MC_SERVER_CRASH_YYYYMMDD=20220625 
DEBUG: MC_SERVER_CRASH_HHMMSS=182714 
DEBUG: Current directory file listing: 
 Volume in drive C is Windows
 Volume Serial Number is 70E4-F880

 Directory of C:\Users\switc\Desktop\serverfolder\Forever+Stranded-1.9.9.1+Server+Files

06/25/2022  06:27 PM    <DIR>          .
06/25/2022  06:27 PM    <DIR>          ..
06/25/2022  06:20 PM    <DIR>          config
06/25/2022  06:20 PM             3,237 LICENSE.md
06/25/2022  06:20 PM    <DIR>          mods
06/25/2022  06:20 PM            11,544 README.md
06/25/2022  06:20 PM    <DIR>          scripts
06/25/2022  06:20 PM            40,518 ServerStart.bat
06/25/2022  06:27 PM             4,117 serverstart.log
06/25/2022  06:20 PM             9,751 ServerStart.sh
06/25/2022  06:20 PM               539 settings.cfg
06/25/2022  06:20 PM    <DIR>          world
               6 File(s)         69,706 bytes
               6 Dir(s)  46,909,845,504 bytes free
DEBUG: JAVA version output (java -d64 -version): 
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

BITSADMIN version 3.0
BITS administration utility.
(C) Copyright Microsoft Corp.

0 out of 0 jobs canceled.

**Comment by Pelotrio** [comment]
Well this is not really the place to ask this but you need to use java 8 instead of never java versions.
