### ISSUE TITLE
replace advanced rocketry with galacticraft

### ISSUE THREAD

**Issue by RConTRS** [AllTheMods/ATM-3#1003]
for enhancement purpose, i recommend replacing advanced rocketry with galacticraft, since it's on curseforge but that doesn't matter
anyways it's more fun and simple to play that mod instead

**Comment by Pelotrio** [comment]
This pack is pretty old and a legacy pack will not receive any major content mod changes. Also they are custom planets for this modpack. The state of advanced rocketry itself is also not that great but I will probably update to the latest version on Curseforge as this will hopefully fix a few of the problems advanced rocketry has.

**Comment by RConTRS** [comment]
true... space mods are really complex, especially the way they work.
still one of my fav packs though

**Comment by Pelotrio** [comment]
Nice that you enjoy the pack it is also my favourite. You are of course free to just replace it for yourself if you haven't already done that.
