### ISSUE TITLE
[ATM3](Version: 3.0) Recipe Conflict.

### ISSUE THREAD

**Issue by PandaPaw** [AllTheMods/ATM-3#102]
Pam's HarvestCrafts: Saucepan and Chisels: (Iron)Chisel conflicts with each other.

**Comment by Darkere** [comment]
They dont ...at least not in the newest version. Chisel takes Iron Saucepan need brick.

**Comment by OrdinatorStouff** [comment]
confirmed; latest versions saucepan uses brick not iron
