### ISSUE TITLE
Crashing world

### ISSUE THREAD

**Issue by Bamseoejne** [AllTheMods/ATM-3#103]
Hey

I got a problem that's happened on two worlds now. Closing down the world and such by all the right protocols and such. Still the day after when I try to enter the world again it shows a blue-ish/grey screen and just crashes.
I'm not sure what's causing it, but here's a crash report:
[crash-2017-08-27_09.57.03-client.txt](https://github.com/AllTheMods/ATM-3/files/1254217/crash-2017-08-27_09.57.03-client.txt)

**Comment by OrdinatorStouff** [comment]
Code Chicken Lib in the crash log basically means the log is useless. The real crash happened before and CCL is just "catching" it. Forge 2456 in the log makes me think it's from pack ver 3.0 which was quite old until recently updated. I'm hoping some of the most recent mod updates have resolved whatever this was. If not please re-open a new issue but also including the `latest.log` as well as the crash report.
