### ISSUE TITLE
[V3.0] Unable to Craft "Garden Trowel" from "Water Strainers Mod"

### ISSUE THREAD

**Issue by msoehnchen** [AllTheMods/ATM-3#104]
Issue:

Receipe of the "Garden Trowel" from the "Water Strainers Mod" makes the Trowel from "Binnie's Botany"

not able to craft the Water-Strainers Trowel to obtain Worms for the Strainers.

**Comment by Darkere** [comment]
Use the Forestry Worktable to get conflicting recipes for now.

**Comment by OrdinatorStouff** [comment]
confirmed conflict -- will need to fix in next update with custom recipes

**Comment by OrdinatorStouff** [comment]
fixed in latest versions of pack
