### ISSUE TITLE
Cannot craft Pam's Barley seeds

### ISSUE THREAD

**Issue by zininzinin** [AllTheMods/ATM-3#105]
When you try to craft it produces flour instead. This is not game breaking as natura barley produces seeds when broken, but annoying because natura plants don't support right click to harvest :(

**Comment by Darkere** [comment]
Use the Forestry Worktable to get conflicting recipes for now.

**Comment by OrdinatorStouff** [comment]
remove barley and wheat flour recipes and replace with a recipe that makes sense like the pams flour using mortar and pestle or a macerator recipe

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
