### ISSUE TITLE
Can't swap Quark & Rustic Planks

### ISSUE THREAD

**Issue by jc2xs** [AllTheMods/ATM-3#106]
The script put in to swap Rustic and Quark planks shows in JEI.  But because a single shapeless plank is the recipe for a button that overrides the craft tweaker script.

I've changed this by using a 9x9 of planks for the swap instead of single.  For example.

`	recipes.addShapeless("colorplank001", <quark:stained_planks:0> * 9,
		[<rustic:painted_wood_white:0>,<rustic:painted_wood_white:0>,<rustic:painted_wood_white:0>,
		<rustic:painted_wood_white:0>,<rustic:painted_wood_white:0>,<rustic:painted_wood_white:0>,
		<rustic:painted_wood_white:0>,<rustic:painted_wood_white:0>,<rustic:painted_wood_white:0>]);`

Let me know if you want the full script I'll be happy to supply it.

**Comment by OrdinatorStouff** [comment]
damn, you're right -- I made that script and didn't even think of buttons.... I'll get that fixed.

IDEAS: 4 corners or 4 sides (so recipe is divisable by 8 evenly)

**Comment by OrdinatorStouff** [comment]
fixed in latest versions of pack
