### ISSUE TITLE
EXU2 Demon Ingots not melting down in tinkers smeltery in SMP

### ISSUE THREAD

**Issue by fallenangel820** [AllTheMods/ATM-3#107]
As the title says the Demon Ingots won't meltdown even though all the recipes for demon ingot tools and weapons require liquid demon metal and it says it has a melting point of 650 in a smeltery.

**Comment by Darkere** [comment]
Fixed on newest version

**Comment by OrdinatorStouff** [comment]
confirmed working in latest versions 
![image](https://user-images.githubusercontent.com/6283913/30046367-0669646a-91bf-11e7-8d42-e4a08d19172b.png)

**Comment by fallenangel820** [comment]
I just tested this and it does indeed work in single player, but not with the server files provided.  I re-downloaded the 3.1 files and created a fresh server to test and they still will not melt down when on the server.

**Comment by OrdinatorStouff** [comment]
Re-opening for me to test again after next pack update

**Comment by Chefbarbie** [comment]
Add to this Magical Ingots and I would assume evil as well. 

SS for proof: https://imgur.com/a/gq7HV

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
