### ISSUE TITLE
Can't melt EU2 Demon Ingot while on ATM3 server

### ISSUE THREAD

**Issue by fallenangel820** [AllTheMods/ATM-3#109]
The single player side works without issue, but upon downloading the ATM3 3.1 server files and generating a brand new server I am still unable to melt Demon Ingots in the Tinkers smeltery.

**Comment by OrdinatorStouff** [comment]
I'll test in a server instance and see that's odd.

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
