### ISSUE TITLE
Not being able to craft any chest Interface from Colossal Chests

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#11]
CC version: 1.12-1.6.2
forge version: 14.21.1.2396

As said in the title, unable to craft any chest interface.

![](https://puu.sh/wEExm/71eee72355.png)

**Comment by Boomflex** [comment]
Have reported this to the relevant Dev.

Will update when fixed.

**Comment by whatthedrunk** [comment]
Looks to be fixed in 2.1
