### ISSUE TITLE
Pulverizer won't accept wheat

### ISSUE THREAD

**Issue by TheElectricCake** [AllTheMods/ATM-3#111]
According to GhandiTooBad, the Pulverizer won't accept Minecraft Wheat even though there is a JEI recipe for it.

This is a minor problem since any crafting table converts wheat to wheat flour (which is what the pulverizer should do) so I don't think it's really an issue unless people WANT to spend RF to convert their wheat into flour.

**Comment by Boomflex** [comment]
No longer a bug.

Working correctly.
