### ISSUE TITLE
Wrong textures at night while mipmap level 4

### ISSUE THREAD

**Issue by Demoox** [AllTheMods/ATM-3#112]
Just downloaded the 3.2 version, logged in the server and went on the graphical settings to set mipmap to 4, waited for those 50/60 seconds and then all the textures were wrong.
![2017-09-07_11 01 37](https://user-images.githubusercontent.com/7397855/30155702-cd07de76-93bd-11e7-9107-bc0afd5bb1ed.png)

Then I turned mipmap off, thinking that that could have been the cause: after that everything turned white when I was getting near it
![2017-09-07_11 05 37](https://user-images.githubusercontent.com/7397855/30155797-0d86491a-93be-11e7-86ec-571b4b93cdeb.png)
 And the lava is lapis ore
![2017-09-07_11 05 45](https://user-images.githubusercontent.com/7397855/30155715-d493364a-93bd-11e7-9c30-d16fcd8c6405.png)

**Comment by OrdinatorStouff** [comment]
This is just a forge/minecraft bug that the texture atlas gets messed up if you change mipmaps (or even just reload resources) while in-game. If you change it and relog, or change it in options.txt before starting it should be fine.
