### ISSUE TITLE
[ATM 3 | Alpha v3.2] Immersive Engineering - Missing Metal Press Recipes

### ISSUE THREAD

**Issue by Xerxeth** [AllTheMods/ATM-3#114]
![allthemodsv32-nometalpressrecipes](https://user-images.githubusercontent.com/31745355/30182816-6ce3bb4c-93d5-11e7-8ed3-84c0116e7975.png)
**Issue:**
Can not create plates nor gears using the metal press. The plates don't even have an option to use the press _(besides uranium, but even then its missing the material to craft it)_. Gears show up as craftable, but with no legitimate way to craft them with the press.

Misc:
In v3.0, you were able to craft plates, but not gears.

**Comment by DietmarKrause** [comment]
> In v3.0, you were able to craft plates, but not gears.
at least there were (are?) gear casts in tinkers. You can try them. I would prefer to have casts dor plates and steel rods through. Is that possible?

**Comment by TheElectricCake** [comment]
This is working correctly in the latest update (ATM 3 v 3.2) in both SP and MP. Checked with all gears (except diamond and stone, which are craftable through other means and should not be part of the press recipes).

**Comment by TheElectricCake** [comment]
@OrdinatorStouff please close this as solved in the latest update (tested in both SP and MP).
