### ISSUE TITLE
Kicked from server when opening Magic Books GUI

### ISSUE THREAD

**Issue by AtaroBlade** [AllTheMods/ATM-3#115]
Hello,

Everytime I attempt to open the Spell GUI from Magic Books, I get kicked from the server with a 'A fatal error has occurred, this connection is terminated' error.

I tried changing the button assignment (just in case it was assigned over other buttons), which didn't seem to help. Perhaps there is something else I'm doing wrong, like not having a certain item?

**Comment by ellis-** [comment]
Same for me.

**Comment by OrdinatorStouff** [comment]
this now seems to be crashing the server completely now instead of just kicking the player. The mod dev is aware and looking into it but for now avoid pressing the keybind to open the gui

**Comment by OrdinatorStouff** [comment]
This should be fixed with the most recent version of MagicBooks
