### ISSUE TITLE
IE Storage Crates and disapearing contents

### ISSUE THREAD

**Issue by WatcherShadows** [AllTheMods/ATM-3#116]
A IE storage crates inventory is disappearing when I break crate and replace it. I have 3 storage crates in my inventory, 2 empty and stacking and 1 that is supposed to have contents and thus not stacking. When I place the one that is supposed to have contents. The contents aren't there.

**Comment by OrdinatorStouff** [comment]
I have seen this myself too and right not now sure what's causing it -- if it's an IE bug or an interaction bug

**Comment by WatcherShadows** [comment]
Strange thing is. It works fine in single player.

**Comment by WarBird25** [comment]
I have the same problem in single player

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
