### ISSUE TITLE
There's no way to craft marble dust(TechReborn)

### ISSUE THREAD

**Issue by gmunaro** [AllTheMods/ATM-3#118]
So, there's no recipe for the Techreborn grinder, which is a machine that is needed to make marble dust. I would suggest making it craftable through the ice macerator, or something like that. Tnx

**Comment by OrdinatorStouff** [comment]
I added TE pulverizor and AA crusher recipes that don't seem to be working -- I need to further test and confirm.

**Comment by Beannsss** [comment]
I just saw this after noticing... Is there any reason in particular that the tech reborn grinder has no recipe?

**Comment by OrdinatorStouff** [comment]
to be fixed (again, hopefully) in 5.0 -- reopen issue if not
