### ISSUE TITLE
Thermal expansion machines weird side reset?

### ISSUE THREAD

**Issue by gmunaro** [AllTheMods/ATM-3#119]
So, when i log out for a while and i log in again, my thermal expansion machines have all the sides randomly set into input, output, etc... Just like as if my config has been reset when the server restarted, or something like that.

**Comment by OrdinatorStouff** [comment]
What version of the pack? Have you tried the alpha 3.2a?

**Comment by gmunaro** [comment]
Im in the 3.2a

**Comment by gmunaro** [comment]
And it happens in the server side, not only client side.

**Comment by Yoosk** [comment]
had the same on our official server... all my machines reverted to normal ones and lost upgrades on 3.2.

**Comment by xlxAciDxlx** [comment]
I can also confirm this on 3.2a as well.

**Comment by Wenoc** [comment]
Happens in 3.2b too. And 3.1, and 3.0.

Can't say why, servos are missing, machine upgrades missing, configurations missing. Cables aren't connected to eachother etc.

**Comment by OrdinatorStouff** [comment]
There is a widespread issue affecting multiple mods, TE just seems to be the most obvious or "hardest hit" so far.

**Comment by Morpheus1101** [comment]
TE is also 2 versions out of date

**Comment by OrdinatorStouff** [comment]
@Morpheus1101 2 versions out of date from what source? I tried manually checking curseforge files and seems to be the latest even still. (I also checked the other thermal mods as well)

![image](https://user-images.githubusercontent.com/6283913/30461487-a5a3c1e0-9973-11e7-9a36-a4b1655e19b7.png)

**Comment by Morpheus1101** [comment]
My bad, i had EnderStorage in mind lol, head isnt quite with it yet

**Comment by xlxAciDxlx** [comment]
*King Lemming* wrote [here](https://github.com/CoFH/Feedback/issues/535):
> This is caused by another mod which shreds NBT and corrupts your world. It's not us. HarvestCraft used to do this but has been patched.
> 
>Update everything, only advice I have for you. But I 100% know it isn't us.

Just figured I'd relay that since I'm not sure if that was a known thing here or not.

**Comment by Chefbarbie** [comment]
This is also happening to botania. For the past two days I've had to realign my mana spreaders and rebind my producers.

**Comment by Morpheus1101** [comment]
I believe this was a forge issue? Which in theory should be solved in the newer forge vers as im using *.2479 on my server and havent had this reported since

**Comment by xlxAciDxlx** [comment]
Unless the Forge changelog is missing something, I don't think it's on Forge's end as there's nothing in the changelog that suggests anything with NBT being fixed. (Though I haven't checked the GitHub commits yet)

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
