### ISSUE TITLE
Steve's Carts 2 Chunkloader and Assembler

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#12]
Steve's Cart 2 version:1.12-2.4.4.25
forge version: 14.21.1.2396

Only OP's can activate the chunkloader on a cart kicks anybody who is not opped and tries it.
People crash when trying to assemble a cart. Only occurred a few times now

**Comment by OrdinatorStouff** [comment]
Steve's carts has been very buggy for a while. recommend to disable chunk load module anyway outright.

**Comment by OrdinatorStouff** [comment]
SC chunkloader has been disabled as well as some others
