### ISSUE TITLE
Immersive Engineering: invisible blocks

### ISSUE THREAD

**Issue by WarBird25** [AllTheMods/ATM-3#120]
since I updated to ATM3 3.2a some of the IE blocks are invisible. Those I have in my single player world and are invisible:
- water weel + kinetic dynamo (war visible before 3.2a update)
- metal press (only the stamp is visible)
- LV, MV, HV connectors and relays

**Comment by MrEvilCookie** [comment]
I have the same thing, hope will be fixed. Also redstone connectors and all wires are invisible.

**Comment by LordGalvatron** [comment]
Same issue for me too. I just built a Diesel generator and the second you hit it with the hammer to form the multiblock all the blocks go invisible.

**Comment by kittykiller** [comment]
It's a foamfix issue
"Immersive Engineering: Textures/models disappear with FoamFix 0.8.0 beta 3 and above. Fixed on IE's side, please downgrade to 0.7.4 until IE updates."

**Comment by OrdinatorStouff** [comment]
Wow! very nice find @kittykiller! Thank you! I'll work that into next update then.

**Comment by TheElectricCake** [comment]
Fixed in 3.3.

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
