### ISSUE TITLE
All the mods 3 modpack lag/stuttering issue

### ISSUE THREAD

**Issue by GizliKodcu** [AllTheMods/ATM-3#122]
Alright so here is the problem. When try to chop a log it finishes and a little lag happens and the log is not being harvested. Similar thing happens to leaves as well. When logs are finished sometimes it takes a little time to be updated i guess. By the way pack has instant leave despawning mod. Also The One probe ui frequently say "waiting for server". I allocated 8 gb ram. I have latest intel kaby lake i7700 processor and gtx 1050 with 4 gb. Any help is appriciated.

**Comment by TheElectricCake** [comment]
First: Is this a single-player world?
Second: Does this also happen with stone/ore/dirt? Or is it specific to logs and trees? Thank you.

**Comment by OrdinatorStouff** [comment]
Sounds like TPS lag, possibly from garbage collection thrashing. Are the server and client running on same server (or like @TheElectricCake asked is this single player?)

**Comment by GizliKodcu** [comment]
Yes this is single player world and yes it happens some blocks too. But this issue was really visible when i play modpack on Technic Launcher. Now Twitch got updated i switched to it and issue degree has decreased. Sometimes i have the issue with leaves despawning.

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
