### ISSUE TITLE
Forced difficulty mode (possible JED interaction)

### ISSUE THREAD

**Issue by BattleProgramer** [AllTheMods/ATM-3#123]
Peaceful mode will auto set to Normal... And ...  I was Killed by a creeper... Hahahaha...
version 3.2a

**Comment by AkaruC** [comment]
I've had the same, and found a workaround for now, if you set your game to allow cheats, lock the difficulty with the lock button in the menu, and then if you want to change it use the /difficulty command to change it.

**Comment by Darianna77** [comment]
For me it switch always to hard... oO
I change to peaceful...but it wont work.

In default options config the difficult is to easy....in the normal option file its on peaceful....but in game...its hard.... why?

**Comment by BattleProgramer** [comment]
Uh I find something...  JustEnoughDimensions Pack Cause this Problem  and the BonusChest comeback when i exclude it.

**Comment by OrdinatorStouff** [comment]
I have edited the DefaultOptions config to exclude setting a gamemode and the JustEnoughDimensions thing might have been related I can see that. I planned on updated the JED config anyway for next update

**Comment by OrdinatorStouff** [comment]
related to https://github.com/maruohon/justenoughdimensions/issues/14
bonus chest also fixed in mod ver 1.5.5

will be resolved in next pack update
