### ISSUE TITLE
Plant recollector from industrial foregoing + Mystical Agriculture

### ISSUE THREAD

**Issue by galfalek** [AllTheMods/ATM-3#125]
Sometimes the plant recollector will destroy or duplicate a seed (did the test with inferium seed(tier2)).

Version 3.2a

**Comment by TheElectricCake** [comment]
Hello Galfalek,

Thank you for reporting this. Could you please give some more details of your setup? Is the recollector feeding into something else? Or does the seed in question never get into the recollector's own inventory? Does it happen with all seeds/saplings or only specific ones?

Thanks.

**Comment by galfalek** [comment]
All the seeds from Mystical Agriculture (i have another farm with trees and it does not seem to dupe sapplings).

It's a 3x3 farm with a Plant Sower below the dirt, who plant the seed, the plant recollector harvest them and the dupe happen in it's inventory.

Also with inferium seed, you only get 1 inferium essence whatever the tier of the seed.
(The plant recollector breaks harvestable seeds like the old MFR one.)
PS: You can come to my house if you want to try it.

**Comment by OrdinatorStouff** [comment]
Reported to Industrial Foregoing dev since I'm 99% sure Mystical Agriculture stuff needs to be handled specially in-code.

**Comment by OrdinatorStouff** [comment]
This should have already been fixed with changes in **Integration** Foregoing the IF addon. Any persistent issues please report to integration mod github
