### ISSUE TITLE
garden closh of immersive engineering, Vers. 3.2a

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-3#126]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2480
 i made  a request to enhance the garden closh of immersive in a way so that there is a blacklist for modpack makers.

**Comment by OrdinatorStouff** [comment]
Thank you for the suggestions. We stand by our decisions to "balance" but we are also working on something to help players easily switch to a "simplified" recipe set that wish to play without our intended pack-wide balance changes.
