### ISSUE TITLE
[ATM3 v2.8] AE2 Autocrafting is broken

### ISSUE THREAD

**Issue by kagenin** [AllTheMods/ATM-3#128]
Started with a ATM3 v2.6 world, migrated to 2.8, and since this issue has surfaced for me, I've tried to update AE2 with the latest version (rv5-alpha-2 -> alpha-4), but that didn't fix the issue.  Yes I know AE2 for 1.12 is still in alpha and probably not quite ready for prime time, but I was hoping that it would be stable enough if it were included in packs like ATM.  That said, I'm still not sure if the mod itself is the issue or an interaction issue, but I don't know what else it could be.

My AE2 network is still pretty simple - a wall of Storage Drawers on a Storage Bus, and a single ME drive with a handful of 4k disks, a very simple autocrafting setup (just a single interface/assembler pair, and 4k crafting cpu), a processor autocrafting setup, fluix and pure crystal growing setup, etc... I don't even have any interfaces on any real machines yet, not a single import or export bus yet.

Whenever I try to craft something, the ingredients are consumed, but I can't pull the finished product from the system.  I go to make 30 blank patterns, for instance - the glass and quartz dust are all consumed to make the quartz glass, but when I try to pull the 30 patterns that appear to be in my ME drives, they don't end up in my hand, and they just disappear from the listing in my terminal.

I can try to post a video illustrating the issue if need be.

**Comment by OrdinatorStouff** [comment]
I'm not sure about the stuff outright dissappearing, but I wonder if there are enough crafting CPUs/Coprocessors for the jobs, or if the items aren't being stored/pulling into and interface or exported or something somewhere.

A video would be appreciated just to make sure I'm seeing exactly what you're seeing.

**Comment by kagenin** [comment]
I think I figured it out.

I was starting the crafting with unlocked, empty drawers in my wall o' storage.  The storage bus had a higher priority than the drive, and somewhere in the process, it tried to put something like, quartz glass if I were making fluix cable, into the drawers or something.

After locking all drawers, the issue seems to have remedied.

**Comment by OrdinatorStouff** [comment]
Ahh great, glad to hear you were able to figure it out!
