### ISSUE TITLE
Infinite powercell 

### ISSUE THREAD

**Issue by gmunaro** [AllTheMods/ATM-3#129]
Powercells don't have a limit, they can go infinite positive or infinite negative... So, yeah... bug-report. 
![untitled](https://user-images.githubusercontent.com/8467760/30331025-12c2ec2e-97ad-11e7-9d44-b94a3b8cbaad.png)

**Comment by gmunaro** [comment]
Its in the 3.2a version(same as the server). Not many details, the input cell is connected to a powercube and a hardned leadstone fluxduct, and the output cells are scattered all over my base.

**Comment by Darianna77** [comment]
For me in singleplayer the Powercell works normal

**Comment by DaePrice** [comment]
It seems to be hit and miss. It doesn't seem to happen when i am on, if i pick up all the cells before i log off.

**Comment by djcosmic2** [comment]
https://imgur.com/a/U6e9E in 3.3 still doing it

**Comment by OrdinatorStouff** [comment]
I think this might have been related to the weird chunk/nbt issues we saw back then. McJty was notified of this happening and it's been months since I've heard of this so closing issue. Make new ticket if new issues still exist in pack ver 5.0+
