### ISSUE TITLE
TE Invar dupe.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#13]
TF version: 1.12-2.3.0.3/2.3.1.5
TE version: 1.12-5.3.0.4/5.3.1.6
TD version: 1.12-2.3.0.4/2.3.1.6
Forge version: 14.21.1.2396/2405

Dupe works like this: 
U can uncraft 2 invar blend into 2 iron dust 1 nickel dust which gives u 3 invar blend when combined.
Blocks used: Centrifugal Separator.

**Comment by Boomflex** [comment]
Reported to CoFH Team.

Will close when new version is released.

**Comment by OrdinatorStouff** [comment]
now takes 3 invar 
![image](https://user-images.githubusercontent.com/6283913/30014409-db829898-9100-11e7-8859-9cd278cab09d.png)
