### ISSUE TITLE
ic2 carbon plates oredict

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-3#130]
`<ore:plateCarbon>.add(<ic2:crafting:15>);`
Right now Extreme Reactors are uncraftable due to not being able to use ic2 carbon plates but TR plates not obtainable due to compat interaction between TR and IC2

Also should check other ic2 items for missing oredict entries

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.

**Comment by Skazz1** [comment]
im on the latest version 5.12.1 and i have the same problem

**Comment by FallenEagle1** [comment]
I would open a new issue skazz just because of the age of this one
