### ISSUE TITLE
Suddenly Everyone is Jesus. (Water Walking)

### ISSUE THREAD

**Issue by TheElectricCake** [AllTheMods/ATM-3#131]
Immediately after the 3.2 update everyone can walk on liquids (of all types tested). Shift lets you 'dive' down into the liquid but you can stand, walk or run normally if you jump above the surface.

Darkere thinks this is an effect added by Cyclic as one of its armor sets, but no one on the server was using such armor at the time.

EDIT: Searched Cyclic and water walking and found this, so it is a known Cyclic bug with a pending update:
https://github.com/PrinceOfAmber/Cyclic/issues/503

(Ord: I know you know all of this but I've been telling folks to ticket all bugs so that people know if they're new or not, so I figure I oughta put this here until it's resolved anyway)

**Comment by OrdinatorStouff** [comment]
ticket is appreciated regardless

this is related to a desync issue curse is having. the cyclic version with this fix was posted 2 days ago and is "release" status but is still not shown in the twitch app as an option to update. https://imgur.com/a/Eu2vL

I have sent curse staff a message inquiring more about this issue

**Comment by OrdinatorStouff** [comment]
https://support.curse.com/hc/en-us/requests/206503

**Comment by OrdinatorStouff** [comment]
Closing this ticket as it's a major known issue with Curse right now and as soon as Curse's issues are sorted out this mod and others will be able to be updated fully.
