### ISSUE TITLE
Draconic Evolution Energy Cell

### ISSUE THREAD

**Issue by Blorxben** [AllTheMods/ATM-3#132]
The server that my friend and I host/play on with only ourselves crashes and we need to rollback about 3 minutes into charging the draconic evolution energy cell.

Thanks for your help!

**Comment by TheElectricCake** [comment]
Please confirm which version of ATM3 you are using on your server, and describe the incident more specifically:

How are you charging the cell? Which devices please, and explain how they are connected. Also please try charging it in a chunk with no devices except the ones which are absolutely necessary so we can eliminate things like C&B conflicts.
What does "we need to roll back" mean? Is the world crashing/corrupting/getting unplayable tps lag?

The more information you give us about what is happening, the more easily we are able to solve the problem. Your ticket is very close to saying "It doesn't work." You did tell us what 'it' is (Draconic Evolution Energy Cell) but didn't give much other info!

Thanks.

**Comment by Blorxben** [comment]
Sorry for not being more specific last night, was in a bit of a mood. I have found out about this glitch in ATM3 version 3.2 alpha and checked once again on the latest version(3.2b). Keep in mind that this is a world that we keep using through versions. We roll back the server because even though it successfully launches when we try to connect to the world it kicks us then gives us the message, "Server Closed" we then roll back to before I started to power the energy cell and we are able to play fine. As for the error code that is linked below. The configuration I was using at the time was a tier 4 draconic evolution energy cell and was piping energy into the energy pylon with mekanism's ultimate universal cable. If you have any other questions please feel free to reply, I really appreciate that support is easy to comeby. Sorry for my previous comments, and once again thanks!

[crash-2017-09-12_18.34.40-server.txt](https://github.com/AllTheMods/ATM-3/files/1301251/crash-2017-09-12_18.34.40-server.txt)

**Comment by OrdinatorStouff** [comment]
The crash log hints at an interaction with AE2 and Mek, not the Draconic storage specifically.

Are you using a ForgeEnergy P2P somewhere, and is that connected to Mek cables? Also, are you using Draconic's wireless relays at all or no?

**Comment by Blorxben** [comment]
We are not using Draconic's Wireless relays at all, I have a few p2p energy things but they havent broken at all and have worked fine. I think since i have the power line im using to charge the reactor also go into a p2p tunnel that may be the issue now that you brought it up, i will disconnect it and get back to you, Thanks once again

**Comment by OrdinatorStouff** [comment]
Well that's probably a mod interaction that should be reported. I'll leave this open and see if we can't report it to Mek and AE2 to prevent in the future

**Comment by OrdinatorStouff** [comment]
As far as I know this was never reported to mod authors but the issue as reported was solved for op so closing ticket
