### ISSUE TITLE
Advanced Generator and Actually Additions Fuels

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#135]
Actually additions Canola based fuels dont work in the Advanced Generator

**Comment by OrdinatorStouff** [comment]
Thanks for the report @djcosmic2 -- I've wanted to play with Adv Generator's customization options so this is now a valid reason to justify spending time on

**Comment by OrdinatorStouff** [comment]
Can someone help re-confirm if in 5.6+ pack ver the canola products work or not? I thought I heard they do work now

**Comment by MoreMagnets** [comment]
Can confirm working as of 5.6

**Comment by OrdinatorStouff** [comment]
Thanks, I was pretty sure they do now too. If I'm wrong anyone is free to open a new issue again, please.
