### ISSUE TITLE
Black Quartz Ore not double-able in Macerator

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#136]
Add Macerator recipe for Black Quartz Ore yields 2 Crushed Black Quartz?

**Comment by OrdinatorStouff** [comment]
Are you referring to IC2 macerator?
does it process into single black quartz, or none at all (no compatibility?)

**Comment by djcosmic2** [comment]
no compatability in IC2 Macerator

**Comment by OrdinatorStouff** [comment]
I'll see if I can get JAOPCA to pick it up for ic2 support... if that doesn't work I have no other options at this time (IC2 is not yet supported in CraftTweaker/ModTweaker)

**Comment by whatthedrunk** [comment]
If CraftTweaker isn't supported there isn't much we can do about it. If/when it gets support we will make sure to add it.
