### ISSUE TITLE
Chunk crashes game on load when TCon tool is placed using Draconic Evolution place block

### ISSUE THREAD

**Issue by PhantomWillie** [AllTheMods/ATM-3#137]
Oops, enter in the title field posted issue.

Anyway, Take a Tinkers' Construct tool, like a wooden hammer, then point at a block and use the place item button from Draconic Evolution (default P) now leave and reenter the chunk (or relog) in single player the game will crash upon attempting to load the saved file, on multiplayer everyone on the server will time out.

EDIT: Forgot to mention I am running ATM3 Version 3.1 (the latest release version, I believe)

**Comment by PhantomWillie** [comment]
It seems I goofed and this is not a real problem. Sorry. The single player problem was something else entirely and the multiplayer problem was some other sort of chunk corruption or something, whatever it is, we can't get it to happen in multiplayer again. The testing in single player made us really sure that this was it, but it turned out it was not the case.

Sorry about making this issue.

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
