### ISSUE TITLE
Using Shaders via Optifine causes sun/skybox problems

### ISSUE THREAD

**Issue by urikkiru** [AllTheMods/ATM-3#138]
If I install Optifine, and Kuda Shaders, I get a very strange issue where the sky lighting seems to follow my mouse cursor. The sky also has a weird mirror bowl like band to it. 

This works fine if I do a custom profile on 1.12.1, with Forge, Optifine, and Kuda shaders.

**Comment by Doomgull** [comment]
Try enabling the "WeakRenders" option in the Astral Sorcery config.

**Comment by whatthedrunk** [comment]
We don't really support shaders but if the problem still happens in ATM3 4.0+ with/without the suggested config change let me know and I will look more into it.
