### ISSUE TITLE
IC2 Iron Plates used in recipe for Basic Machine Casing make TechReborn Machine Casing

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#139]
Simple solution: Custom recipe for a 1 to 1 swap. that or specify that IC2 plates make IC2 casing, and TR Plates make TR casing. Latter would probably be better

**Comment by Morpheus1101** [comment]
I guess itd depend on if the config option for them to be compatible with eachother is enabled to if this is an actual bug

**Comment by djcosmic2** [comment]
only ic2 machine you can use a TR casing with is the generator.

**Comment by OrdinatorStouff** [comment]
#89 #84 #33 similar dupes
the real "ISSUE" to be looked into is:
TECH REBORN and IC2 still have recipe conflicts and some missing oredict support

**Comment by OrdinatorStouff** [comment]
@Morpheus1101 the config option **is** enabled but it's not perfect

**Comment by OrdinatorStouff** [comment]
might as well turn the config off and do it myself in CrT

**Comment by Morpheus1101** [comment]
basically yes, its a heck of a lot of doin for a CrT script, but the config is buggy as we found out on ATC

**Comment by OrdinatorStouff** [comment]
TR and IC2 machine frames are now interchangeable
