### ISSUE TITLE
Resourceful Crops - seed recipes not working.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#14]
RC version; 1.12-2.0.3-60
forge version: ...-. 2405

Unable to craft any seed.

![](https://puu.sh/wG9gV/61cc537f12.png)

**Comment by Boomflex** [comment]
This has been reported to the Dev.

Will close when completed.

**Comment by whatthedrunk** [comment]
Mod has been removed. Either that or Mystical will be added soon.
