### ISSUE TITLE
[ATM3 v3.2b] items placed into Engineers Toolbox Disappear

### ISSUE THREAD

**Issue by Morpheus1101** [AllTheMods/ATM-3#140]
This also maybe another thing related to foamfix. To reproduce hold an Engineers Toolbox in your hand, place an item in it and memorise the slot. Close an reopen an said item is missing an despite being able to shift click that spot an the appearance of an item being taken out occurs, no item actually appears in your inventory.

**Comment by OrdinatorStouff** [comment]
I was reading about this on IE issue tracker as well. IE had an update today hopefully addressing all this (and not needing to revert foamfix)

**Comment by Morpheus1101** [comment]
Its worth noting that while this occurs when toolbox is placed on the ground, simply re-opening shows the items back up

**Comment by Boomflex** [comment]
This doesn't seem to still be an issue on latest version of the pack.
