### ISSUE TITLE
Wolf spawnage

### ISSUE THREAD

**Issue by 8ong8ong** [AllTheMods/ATM-3#143]
we seem to have an unusually high spawnage rate of wolves on our ALL THE MODS 3 server. A group of us can play on the server and at the end of the play session we can have up to 100 wolves running around our town. Not sure what is causing them all to appear, i thought it could be related to terraqueous turning hostile mobs into neutral ones, any help would be appreciated. Please advise.
Thanks

**Comment by whatthedrunk** [comment]
Let me know if this is still happening on ATM3 4.0+

**Comment by OrdinatorStouff** [comment]
I'm 99% sure this was due to the Trickster Bloom that would convert hostile mobs into passive mobs that was fixed a couple versions back.
