### ISSUE TITLE
Unlimited free energy from advanced generators to mekanism cables/energy cube

### ISSUE THREAD

**Issue by imme40** [AllTheMods/ATM-3#144]
Create a syngas producer (advanced generators), and have it pipe syngas into a gas generator (advanced generators).  I used a basic mechanical pipe (mekanism) for this. Then use a redstone flux ouput from the gas generator through a universal cable (mekanism, tier doesn't seem to matter) into an energy cube (mekanism, tier doesn't seem to matter).  You can now pull energy from that system without burning any fuel in the generators by pulling energy from the energy cube.  Configuration of the advanced generators doesn't seem to make a difference.  Not sure which of the two mods is causing it to work this way, as it seems to be transferring from advanced generators fine, but no fuel is burned.  Using pack ATM3 3.2b.

**Comment by TheElectricCake** [comment]
This should no longer be possible in 3.3.

Please check and report back, thank you.

**Comment by imme40** [comment]
Looks to be fixed.  My test world is behaving properly (using fuel).
