### ISSUE TITLE
Monastic bees are not sold by villagers

### ISSUE THREAD

**Issue by zininzinin** [AllTheMods/ATM-3#145]
I have creative spawned like 50 of the apiarist villagers and none are selling the monastic bees. I'm not sure why, but this means they are not possible to aquire

**Comment by TheElectricCake** [comment]
This is for version 3.2b.

Is this even after doing multiple trades with them?

Thanks.

**Comment by OrdinatorStouff** [comment]
a tiny bit of testing looks like yes multiple trade unlocks would be needed. I didn't confirm 100000% that a monastic drone came up BUT I'm assuming it takes RNG + trade unlocks. no issues reported on forestry to assuming this is moot.

psst: gendustry I think can get monastic too? maybe?

**Comment by DangerDr** [comment]
2 years later

Is this confirmed? I'm playing on a a FTB infinity evolved server and I'm only getting ender drones. No monastic bees
