### ISSUE TITLE
Pipes for some strange reason mess up. not sure how to describe. picture attached

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#148]
![2017-09-17 01_16_31-new notification](https://user-images.githubusercontent.com/7881152/30518231-e5c61d6c-9b45-11e7-9b3e-53a37fc00516.png)

**Comment by djcosmic2** [comment]
Block update fixed it

**Comment by djcosmic2** [comment]
kinda not really. had to break and replace the pipes to get liquid to flow

**Comment by ellis-** [comment]
Is there a chunk boundary passing between the barrels and the generators?
I'm asking as i'we had massive issues with pipes and cables bugging out because of chunkloading being limited by the forge chunkloading ticket system.

**Comment by TheElectricCake** [comment]
Please check to see if this is happening in 3.3.

**Comment by Trinsec** [comment]
I've got the exact same issue. I've upgraded to 3.3, and after a bit I saw all those pipes reverting to their wrong state right in front of my eyes. Unfortunately the update hasn't fixed this. All the pipes became unconnected, and the servo(s) on them disappeared.

**Comment by mrdeadlocked** [comment]
Same issue on 3.3. If you place a torch next to the broken pipes they update and reconnect.

**Comment by Trinsec** [comment]
Yeah, if you place a block next to the disconnected pipes, they'll all reconnect. Even when they weren't supposed to (because you seperated them with a wrench before). The servos are still lost.

**Comment by mrdeadlocked** [comment]
I noticed the same thing with servos. I've lost so many of them now lol

**Comment by Trinsec** [comment]
Okay, it's been 3 days since I changed a setting that solved this issue for me.
In forgeChunkLoading.cfg have the line: I:dormantChunkCacheSize=0
The default in ATM3 seems to be 50, setting the value to 0 has solved my issues. So far so good.

**Comment by mrdeadlocked** [comment]
@Trinsec Giving this a try now. Updating my server with those settings.

**Comment by mrdeadlocked** [comment]
After 16 hours of playtime on my server no one has experienced this issue again after changing the forgeChunkLoading.cfg have the line: I:dormantChunkCacheSize=0.

**Comment by whatthedrunk** [comment]
We have this changed in the next update going out tonight/tomorrow. If anyone get's this problem on 4.0+ please reopen.
