### ISSUE TITLE
When attempting to assemble a Steves Cart cart, error occurs

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#149]
![image](https://user-images.githubusercontent.com/7881152/30518377-4dbb62ca-9b4a-11e7-8c1e-31ad2da96f26.png)

**Comment by TheElectricCake** [comment]
This error is still present in 3.3. I've got logs but they don't say much.

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
