### ISSUE TITLE
Wings of Bats and Wing Charm interaction

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#15]
Actually Additions version: 1.12-r114
Cyclic version: 1.12-1.5.11
Forge version: 2405

Unlimited creative flight with those 2 in inventory. Even when the Wings of Bat are recharging I have creative flight.
Same with the Launch enchant I can continuously use it.

**Comment by OrdinatorStouff** [comment]
wing charm = inf freefall
can you elaborate more.

NOTE: wtd prefers to "nerf" easy flight so these can be "balanced" with some more details on what you mean

**Comment by OrdinatorStouff** [comment]
![image](https://user-images.githubusercontent.com/6283913/30014585-e47b5d8a-9101-11e7-92f4-4a4aeee4de6a.png)
