### ISSUE TITLE
Unable to craft Angel Ring

### ISSUE THREAD

**Issue by otub** [AllTheMods/ATM-3#151]
Version: 3.2b
Crafting recipe seems to not work, seen here: https://i.imgur.com/mF39Qia.gifv

**Comment by Darkere** [comment]
It works use an empty jetpack

**Comment by OrdinatorStouff** [comment]
I can see about making the recipe take the jetpack in any condition though thanks for the report

**Comment by OrdinatorStouff** [comment]
should be better in pack version 3.3+ let me know if it's still annoying though
