### ISSUE TITLE
[ATM3 v3.2b] Writing in Darkoak Desk BiblioCraft

### ISSUE THREAD

**Issue by Morpheus1101** [AllTheMods/ATM-3#152]
When attempting to write a paragraph in a book an quill on the desk, you can do 1 line and 1 character, then it stops allowing any further typing to show or appear.

**Comment by OrdinatorStouff** [comment]
Kind of an oddly-specific report but thanks for taking the time to report it nonetheless 👍

**Comment by OrdinatorStouff** [comment]
confirmed still a problem in ~5.0+ -- should report to mod authors

**Comment by Boomflex** [comment]
Mod issue that can't be fixed by Modpack.

Please report to Mod Dev.
