### ISSUE TITLE
Duping Glitch

### ISSUE THREAD

**Issue by Dumpgrah** [AllTheMods/ATM-3#154]
The Hydrator from cyclic doubles any item you shift-click from your inventory into it. it doesn't work if you do it from your hot bar tho

**Comment by Darkere** [comment]
ah -.- thats why it didnt work for me when I tested if it was fixed...

**Comment by TheElectricCake** [comment]
This is a bug which existed in the previous patch which apparently is still a problem.

**Comment by OrdinatorStouff** [comment]
Can we get a follow-up on this in pack ver 4.0 if it's still a problem?

**Comment by Kojikun** [comment]
This is still a problem in v4.0

**Comment by DaePrice** [comment]
This has been fixed as of v4.3
