### ISSUE TITLE
Mod Suggestion: Unlimited Chisel Works

### ISSUE THREAD

**Issue by Jadziyah** [AllTheMods/ATM-3#155]
I posted this for discussion in the ATM3 discord suggestions channel, but wanted to put it here for official consideration

https://www.reddit.com/r/feedthebeast/comments/70nhj5/new_mod_unlimited_chisel_works/
http://asie.pl/Projects/Minecraft/Mods/Unlimited_Chisel_Works

It uses several mods already in the pack and would offer a ton of new decorating options for builders. I think it would be a very positive addition to ATM3

**Comment by whatthedrunk** [comment]
Added to the suggestion list. Please use this area for future suggestions thanks!
