### ISSUE TITLE
Mod Suggestion: Antighost

### ISSUE THREAD

**Issue by mrdeadlocked** [AllTheMods/ATM-3#157]
This mod is great to help with ghost blocks caused by fast mining speed weapons.

https://mods.curse.com/mc-mods/minecraft/273279-antighost

**Comment by TheElectricCake** [comment]
Thank you again. This will be considered for future.

**Comment by whatthedrunk** [comment]
Added to the suggestion list. Please use this area for future suggestions thanks!
