### ISSUE TITLE
Recipe Conflict: better builder wands/Scan tool

### ISSUE THREAD

**Issue by mrdeadlocked** [AllTheMods/ATM-3#159]
The recipe for better builders wands and the scan tools from MineColonies are conflicting. This also bring about a possible mod suggestion of:

https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict

This would allow the end user to pick what they want from conflicting recipes.

**Comment by TheElectricCake** [comment]
Thank you for reporting this problem.

As a temporary solution, you can try using a Forestry crafting table. It will allow you to select between conflicting recipes.

We will look further into fixing the recipe conflict. Someone else will need to make the call regarding the inclusion of the mod you recommended, but thanks for the suggestion!

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
