### ISSUE TITLE
Unable to craft graphite block

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#16]
Extreme Reactors version: 1.12-0.4.5.33
Forge version: 2405
Can't craft the block.

![](https://puu.sh/wGj8f/6abdad221a.png)

**Comment by OrdinatorStouff** [comment]
must've been fixed already 
![image](https://user-images.githubusercontent.com/6283913/30014512-8bdc4ce8-9101-11e7-8ba2-897fd9716041.png)
