### ISSUE TITLE
IC2/TechReborn Recipe Issues; Reinforced Glass

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#161]
Recipe for ic2 Reinforced glass makes TR Reinforced glass

**Comment by OrdinatorStouff** [comment]
1) first and foremost thank you for taking the time to report it here so we can fix it and keep track of it.
2) there's no need to be a smartass in the description/title, that doesn't help anyone.

**Comment by djcosmic2** [comment]
Intention wasn't to be a smartass - sorry

**Comment by ProsperCraft** [comment]
My users are having the same issue.

**Comment by OrdinatorStouff** [comment]
[Fixed in pack version 4.0](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2485186)
