### ISSUE TITLE
ATM 3 (3.3) Server error

### ISSUE THREAD

**Issue by MJpyroman** [AllTheMods/ATM-3#162]
Hi, I've downloaded the server file for ATM 3 (3.3), when I launch ServerStart.bat I've this: "Settings.cfg_Error:MAX_RAM", I've try this : http://bit.ly/2jMw6m8 and reduce MAX_RAM but dosn't work so if anyone know what's the problem^^ thx in advance
![capture d ecran 98](https://user-images.githubusercontent.com/32174661/30709578-0b680e7a-9f03-11e7-91fa-3a2d1dcf3bfc.png)

**Comment by OrdinatorStouff** [comment]
Can you upload your "serverstart.log" file contents please?

**Comment by MJpyroman** [comment]
----------------------------------------------------------------- 
INFO: Starting batch at 9/01:192716 
----------------------------------------------------------------- 
 
DEBUG: Current Dir is C:\Users\ticho\Desktop\ServerFiles_ATM3-3.3 -- trying to change to C:\Users\ticho\Desktop\ServerFiles_ATM3-3.3\ 
INFO: Checking that settings.cfg exists 
DEBUG: settings.cfg Found. Logging full contents below: 
;Details/Help Found here: https://github.com/AllTheMods/Server-Scripts


MAX_RAM=5G; 
JAVA_ARGS=-server -d64 -Xms1G -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary;
CRASH_COUNT=10; 
CRASH_TIMER=600; 
RUN_FROM_BAD_FOLDER=0; 
IGNORE_OFFLINE=0; 
IGNORE_JAVA_CHECK=0; 
USE_SPONGE=0;

MODPACK_NAME=All The Mods 3;
MCVER=1.12.1;
FORGEVER=14.22.1.2485;
FORGEURL=DISABLE; 
ERROR: Error flagged, reason is: "Settings.cfg_Error:MAX_RAM" 
WARN: Server startup script is exiting. Dumping current vars: 
DEBUG: MC_SERVER_MAX_RAM= 
DEBUG: MC_SERVER_FORGE_JAR= 
DEBUG: MC_SERVER_SPONGE_BOOT= 
DEBUG: MC_SERVER_JVM_ARGS= 
DEBUG: MC_SERVER_MAX_CRASH= 
DEBUG: MC_SERVER_CRASH_TIMER= 
DEBUG: MC_SERVER_IGNORE_OFFLINE= 
DEBUG: MC_SERVER_RUN_FROM_BAD_FOLDER= 
DEBUG: MC_SERVER_MCVER= 
DEBUG: MC_SERVER_FORGEVER= 
DEBUG: MC_SERVER_FORGESHORT= 
DEBUG: MC_SERVER_FORGEURL= 
DEBUG: MC_SERVER_SPONGE= 
DEBUG: MC_SERVER_PACKNAME= 
DEBUG: MC_SERVER_SPONGEURL= 
DEBUG: MC_SERVER_SPONGEBOOTSTRAPURL= 
DEBUG: MC_SERVER_ERROR_REASON=Settings.cfg_Error:MAX_RAM 
DEBUG: MC_SERVER_TMP_FLAG=0 
DEBUG: MC_SERVER_CRASH_COUNTER=1 
DEBUG: MC_SERVER_CRASH_YYYYMMDD=9/01 
DEBUG: MC_SERVER_CRASH_HHMMSS=192716 
DEBUG: Current directory file listing: 
 Le volume dans le lecteur C s'appelle OS
 Le num‚ro de s‚rie du volume est 0000-0CE0

 R‚pertoire de C:\Users\ticho\Desktop\ServerFiles_ATM3-3.3

21/09/2017  19:27    <DIR>          .
21/09/2017  19:27    <DIR>          ..
20/09/2017  00:24    <DIR>          config
18/09/2017  04:38         4ÿ855ÿ842 forge-1.12.1-14.22.1.2485-installer.jar
14/07/2017  01:34             3ÿ237 LICENSE.md
12/09/2017  22:00            16ÿ615 manifest.json
20/09/2017  00:40    <DIR>          mods
14/07/2017  01:34            11ÿ782 README.md
19/09/2017  23:57    <DIR>          resourcepacks
12/09/2017  22:56    <DIR>          resources
19/09/2017  18:00    <DIR>          scripts
12/09/2017  22:56    <DIR>          server-resource-packs
14/07/2017  01:34            39ÿ897 ServerStart.bat
21/09/2017  19:27             1ÿ815 serverstart.log
21/09/2017  19:18               523 settings.cfg
               7 fichier(s)        4ÿ929ÿ711 octets
               8 R‚p(s)  88ÿ162ÿ615ÿ296 octets libres
DEBUG: JAVA version output (java -d64 -version): 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

BITSADMIN version 3.0
BITS administration utility.
(C) Copyright 2000-2006 Microsoft Corp.

BITSAdmin is deprecated and is not guaranteed to be available in future versions of Windows.
Administrative tools for the BITS service are now provided by BITS PowerShell cmdlets.

0 out of 0 jobs canceled.

**Comment by OrdinatorStouff** [comment]
I'm 95% sure the script is erroring out because of the French system language. We had an incompatibility before with non-English language that we fixed that reminds me of this. I'll take a look at the script and see if I can figure out a fix but for now I don't have an ETA for you.

**Comment by MJpyroman** [comment]
OK, thank you for having taken time to look

**Comment by whatthedrunk** [comment]
Going to close this here but if you still have the problem when 4.0 comes out tonight/tomorrow please submit the issue here https://github.com/AllTheMods/Server-Scripts/issues thanks! Just trying to clean up issues a bit here.
