### ISSUE TITLE
ATM3 Batching Chunk Crash

### ISSUE THREAD

**Issue by mrdeadlocked** [AllTheMods/ATM-3#164]
Have this crash randomly. Has happened twice.

https://pastebin.com/CRNsRKfD

**Comment by DietmarKrause** [comment]
do you use optifine? I have seen this issue with optifine
https://github.com/iChun/IssueTracker-Mods/issues/61

**Comment by mrdeadlocked** [comment]
No optifine. I removed foam fix and it seemed to stop for now.

**Comment by mrdeadlocked** [comment]
I am now completely locked out of my base. I cant join/go home without my client crashing.

**Comment by phit** [comment]
caused by https://github.com/MatrexsVigil/harvestcraft/issues/12

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
