### ISSUE TITLE
MineColonies related CTD and multiple villagers

### ISSUE THREAD

**Issue by TheElectricCake** [AllTheMods/ATM-3#165]
Server TPS was under 7, so I decided to teleport to various locations with Minecolonies EntityCitizens which showed up individually as the worst offenders. (I admit, with intent to kill).

I was in gamemode 1 and I crashed to desktop IMMEDIATELY on teleporting to the chunk one of these citizens was in. Log attached.

Minecolonies needs to _go_.

[crash-2017-09-22_16.01.23-client.txt](https://github.com/AllTheMods/ATM-3/files/1326088/crash-2017-09-22_16.01.23-client.txt)

**Comment by TheElectricCake** [comment]
Additionally, for whatever reason, minecolonies has been cloning multiple copies of the same citizens at both Teufler80s and Willy's claims I saw 2-3 of each villager, colliding with each other trying to do the same things and causing much TPS trouble.
![2017-09-22_16 13 15](https://user-images.githubusercontent.com/20430595/30768120-4c768562-9fb8-11e7-91b1-56ccdfa649e6.png)

**Comment by mrdeadlocked** [comment]
I had this same issue on my server. I also had trouble placing the Town Hall Book (crashed my client a few times).

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
