### ISSUE TITLE
Botania recipes not workinbg

### ISSUE THREAD

**Issue by 8ong8ong** [AllTheMods/ATM-3#166]
Hello
Trying to make the endoflame flower in the pedestal (the way the lexicon tells you) is not working. The pedestal is not accepting the mushrooms. Any help appreciated . Thanks

**Comment by 8ong8ong** [comment]
Ok so apparently to make you use the petals, The book clearly states mushrooms, very confusing

**Comment by OrdinatorStouff** [comment]
what does the recipe say in JEI, out of curiosity?

**Comment by 8ong8ong** [comment]
Interesting question.
The  lexica has one recipe showing muushrooms.
The JEI has the two recipes. One using mushrooms and one using petals.
Nether thought to check the JEI.

**Comment by Boomflex** [comment]
Botania bug. 

Please report to Vazkii.
