### ISSUE TITLE
game crash wile rendering block in new update

### ISSUE THREAD

**Issue by cyberhiker1965** [AllTheMods/ATM-3#167]
whenever i go near my base in the new update the game crashes. here is the report:The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.NoSuchMethodError: org.cyclops.cyclopscore.helper.BlockHelpers.getSafeBlockStateProperty(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/block/properties/IProperty;Ljava/lang/Object;)Ljava/lang/Object;

**Comment by mrdeadlocked** [comment]
Can you pastebin the full crash report.

**Comment by cyberhiker1965** [comment]
for some reason i cant click on the view crash report button

**Comment by cyberhiker1965** [comment]
i figured out how
[crash-2017-09-24_16.13.33-client.txt](https://github.com/AllTheMods/ATM-3/files/1327699/crash-2017-09-24_16.13.33-client.txt)

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
