### ISSUE TITLE
render crash

### ISSUE THREAD

**Issue by nexonas** [AllTheMods/ATM-3#168]
crash report: https://pastebin.com/3GjvXFSu

crached just staying in my room with mekanism mashines and some thermal expansion, crashing using fluxduckts and universal cables don't know whats causing it
edit : https://i.gyazo.com/38765e000e193c54471fdd93b8b4f35e.png 
crashed by joining in the same room scrolled trou my hotbar and I crashed...

**Comment by Darkere** [comment]
do you have items placed in the world via draconic evolution? there is a hotkey for that

**Comment by nexonas** [comment]
I placed some books on the wall via draconic

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
