### ISSUE TITLE
After upgrade to 1.4b The One Prob is not displayed

### ISSUE THREAD

**Issue by nomaed** [AllTheMods/ATM-3#17]
There is no TOP UI after the upgrade from 1.3 to 1.4b
Installed via Twitch/Curse client.

**Comment by gefailter71** [comment]
Go into your TOP configs and overwrite it. 
Should be fixed next update :)

![](https://puu.sh/wGzyB/a8da424dea.png)

gef~

**Comment by nomaed** [comment]
Thanks, I should've checked that file ;)

**Comment by whatthedrunk** [comment]
Looks to be fixed now.
