### ISSUE TITLE
[v3.3-Simplified] No recipe for Graphite bar.

### ISSUE THREAD

**Issue by JaSpr** [AllTheMods/ATM-3#170]
It seems that there is no recipe for Graphite bar in the simplified recipes version.  Can't cook coal, and two graphite plates in a crafting table does nothing.

**Comment by OrdinatorStouff** [comment]
confirmed -- normal graphite smelting was removed in configs and balance script is only place recipe exists.

Will add recipe for simplified mode

**Comment by OrdinatorStouff** [comment]
[Fixed in pack version 4.0](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2485186)
