### ISSUE TITLE
Botania Mana in a Bottle server crash

### ISSUE THREAD

**Issue by scarfkitten** [AllTheMods/ATM-3#173]
Certain results from Botania's bottled mana can cause the server to crash due to a ticking entity error. Server and client are both on ATM3.3, with no custom mods or additions. 

Reproduction steps: drink Mana in a Bottle until you get the "signal flare" result, which will cause an explosion sound, and disconnect the client, crashing the server and rolling back a couple minutes. 

Crash log below.
https://pastebin.com/6jC72uJK

**Comment by OrdinatorStouff** [comment]
Thanks for the report. [Looks like it's fixed on Botania's side](https://github.com/Vazkii/Botania/issues/2389) and just needs to come down the pipeline in an update. Closing issue as "resolved" pending next pack update(s)
