### ISSUE TITLE
Backpack and cocoa beans

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#176]
Cocoa beans are going in the mining backpack when we take it from the ground, or from the inventory :
![Cocoa screen and mining shot](https://user-images.githubusercontent.com/13626201/30860927-9b5abc5c-a2fb-11e7-8813-a14813795437.JPG)

**Comment by Kileahh** [comment]
The Bone Meal go into too

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
