### ISSUE TITLE
[Issue] (IE) LV Wire Connector (maybe all) and (Actually Additions) Coal Generators

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#177]
The CF are not extracted from the coal generator wire IE LV 
wire connector, I test top, front ans left faces, and it doesn't work, but it works well with the oil generator
![2017-09-27_02 31 37](https://user-images.githubusercontent.com/13626201/30877562-9ed33932-a32c-11e7-8c2b-1ef3e84cb5c3.png)
![2017-09-27_02 31 41](https://user-images.githubusercontent.com/13626201/30877560-9e9ffdb0-a32c-11e7-94c5-ff0ce2ee16fa.png)
![2017-09-27_02 31 43](https://user-images.githubusercontent.com/13626201/30877561-9ebe7b82-a32c-11e7-9c25-0e18d944d75d.png)

**Comment by OrdinatorStouff** [comment]
It's okay to close your own issues as you figure them out (and encouraged!) but please do not edit out all of the content, that's not necessary and only adds confusion.
