### ISSUE TITLE
Gendustry Machines Cover Dupe Bug

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#178]
When you break a gendustry machine with a gendustry cover on it, it returns the machine and the cover

When you place the machine again it still has the cover

**Comment by OrdinatorStouff** [comment]
confirmed still happening in 5.0+ -- need to report to mod authors

**Comment by Boomflex** [comment]
Reported to Mod Author: https://github.com/bdew/gendustry/issues/261

**Comment by Boomflex** [comment]
Mod issue that can't be fixed by Modpack.

Please report to Mod Dev.
