### ISSUE TITLE
ServerStart.sh missing in v3.3 server package

### ISSUE THREAD

**Issue by ouroborus** [AllTheMods/ATM-3#179]
as seen [here](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2481881) on Curse.

https://github.com/AllTheMods/Server-Scripts/issues/12 (cross-posting)

**Comment by ouroborus** [comment]
https://github.com/AllTheMods/Server-Scripts/issues/12

**Comment by whatthedrunk** [comment]
Thanks for reporting it! We have a new 4.0 coming out tonight/tomorrow moving us to 1.12.2 I will make sure all the server files are there.
