### ISSUE TITLE
About oregen

### ISSUE THREAD

**Issue by Waisse** [AllTheMods/ATM-3#18]
ATM 3 v1.4b with IE added.

Mithril ore from NoMansLib : why ? It has no practical uses.

Bauxite Ore from TechReborn : now used by Immersive Engineering too, but processing only possible via TechReborn machines (or IE Arc Furnace).

Platinum Ore from NoMansLib : It's supposed to be an extremely rare endgame resources for Thermal Expansion, current oregen is way too high.

Diamond ore : seems to be extremely rare, dunno if I'm unlucky or not thought.

**Comment by whatthedrunk** [comment]
Oregen should be good now. Let me know if you see any dupe ores in new chunks.
