### ISSUE TITLE
[3.3][Game crash] IE Engineer's Manual

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#180]
I was reading IE Engineer's Manual and game closed by itself

[hs_err_pid11404.log](https://github.com/AllTheMods/ATM-3/files/1335899/hs_err_pid11404.log)
[replay_pid11404.log](https://github.com/AllTheMods/ATM-3/files/1335900/replay_pid11404.log)

**Comment by Kileahh** [comment]
Same crash

[hs_err_pid3552.log](https://github.com/AllTheMods/ATM-3/files/1335978/hs_err_pid3552.log)
[replay_pid3552.log](https://github.com/AllTheMods/ATM-3/files/1335979/replay_pid3552.log)

**Comment by Kileahh** [comment]
Still crashing in 4.0. The minecraft laucher after game's crash crash itself.

**Comment by Doomgull** [comment]
That's a generic memory related error code coming from the JVM. Assuming your drivers are up to date, and you've tried fully uninstalling and reinstalling java, I'd recommend running a memtest against your memory itself.

**Comment by Kileahh** [comment]
My memory has no problem, and I reinstall java and rerun a test(well, I think this second test was not useful). And the crash continue in 4.0, but it doesn't produce crash report.

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
