### ISSUE TITLE
[3.3 easy mode] crash while breaking industrial apiary from gendustry

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-3#181]
https://pastebin.com/RpVBcLzL
edit: it is a Single player survival world. After relog i had the apiary in the  hand world was fine. there is a sound muffler near the apiary, a few moments before the world crashed the sound was not reduced (there are 20 or so cows behind the wall....). Not sure if that is important. The crashlog implies a problem with the one probe it seems.......

**Comment by Darkydider** [comment]
Im having this problem also 
It looks like you are using an unsupported modified version of the game.
The game crashed whilst tesselating block in world
The game crashed whilst tesselating block in world
Error: java.lang.ClassCastException: net.bdew.gendustry.machines.apiary.TileApiary cannot be cast to cofh.thermalexpansion.block.storage.TileCell

will  get full msg when i retest this

**Comment by Boomflex** [comment]
Update to v4.3
