### ISSUE TITLE
"Skyblocks" mod skyblock render error crash

### ISSUE THREAD

**Issue by scarfkitten** [AllTheMods/ATM-3#182]
When placing a Skyblock block from the titular mod, the client will crash due to a render error. The server is unaffected.

Reproduction steps: obtain a skyblock block via crafting, creative, JEI, or a random drop from a Magic Bean crop, then place it in the world. As soon as the client attempts to render the block, the game will crash.
Any attempt to load back into the affected chunk will cause a crash.

Temporary solution: disable the Skyblocks mod, then when the world is loaded the erroring block will be removed. Alternatively, you can use the fill command via server console to replace the block.

Crash log: https://pastebin.com/ydXg3GnV

**Comment by Boomflex** [comment]
Hi @scarfkitten, can you try adding https://minecraft.curseforge.com/projects/excore/files/2464558 and trying again?

**Comment by scarfkitten** [comment]
@Boomflex Yup, that did the trick. The twitch pack could be updated to add that coremod next release. It's unusual that the mod didn't claim it required the core mod before the game launched though.

**Comment by Boomflex** [comment]
@scarfkitten It was already planned for the next update.

It is not a bug that happens 100% of the time, so has been hard to track down.
