### ISSUE TITLE
Rustic NPE crash when right clicking an empty glass bottle

### ISSUE THREAD

**Issue by scarfkitten** [AllTheMods/ATM-3#184]
Description: as the title indicates, right clicking the air with an empty glass bottle will cause a NPE client side, crashing the player.

Reproduction steps: obtain an empty glass bottle, then right click the air with it - could potentially be caused by drinking a potion then holding right click afterwards.

Crash log: https://pastebin.com/dhZtj0w8

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
