### ISSUE TITLE
Blockcraftery recipie conflict 

### ISSUE THREAD

**Issue by PhantomWillie** [AllTheMods/ATM-3#185]
Blockcraftery's 'Framed Block' cannot be crafted in the regular crafting table, instead a 'this item is disabled' from Applied Energistics is crafted instead.

EDIT: In version 4.0

**Comment by mrdeadlocked** [comment]
You can also craft them in the Forestry Worktable (for anyone on 4.0 that needs a quick fix).

**Comment by ouroborus** [comment]
https://github.com/AllTheMods/ATM-3/issues/190

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
