### ISSUE TITLE
[4.0][Issue] Immersive Engineering Data Error

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#186]
Since the update, when we look at the pump of Immersive Engineering, we can't see the port and opposite port configuration, it shows an error :

![Screenshot](https://user-images.githubusercontent.com/13626201/31025456-4f6fab3c-a575-11e7-934b-341c278c0f0c.png)

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
