### ISSUE TITLE
[4.0 (and before maybe)][Recipe]Paper

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#187]
The craft of the paper with 3 sawdusts gives 6 papers (from any mod comptatible, it's only a screenshot) is more efficiency than 4 sawdusts and 1 water buckets which gives 2 papers.

(Idea : 3 sawdusts craft can be deleted or gives only 3 papers, and 4 sawdusts + 1 water bucket craft can give 6 papers (~1.33x more efficiency than others recipes))

![Screenshot](https://user-images.githubusercontent.com/13626201/31029685-4306c8ca-a585-11e7-8d37-075c3dbe59fc.JPG)

**Comment by ouroborus** [comment]
I've also noticed this. I didn't think to much about it outside of maybe it had something to do with the difference between dustWood and pulpWood. (An annoying difference when trying to make a cardboard box.)

**Comment by Boomflex** [comment]
Minor issue and not one that we will be changing for now.
