### ISSUE TITLE
Technic stuck on v3.1

### ISSUE THREAD

**Issue by ouroborus** [AllTheMods/ATM-3#189]
I've noticed that, while ATM3 has moved on to a 4.0 release on Curse, Technic is still on 3.1. I'm not sure if Technic is officially supported or if it's just coincidence that it has followed as far as it has. Can you set me straight on this?

**Comment by OrdinatorStouff** [comment]
There's a bit of manual work involved with updating Technic and as a result
it tends to lag behind the official releases a bit. We have been putting
them on there "officially" and as far as I know have not decided to
discontinue that BUT like I said it's just whenever we can get the
time/resources to make it happen.

**Comment by ouroborus** [comment]
Fair enough, keep up the awesome work.
