### ISSUE TITLE
[1.4b] Loaded game; drawers rotated and display is incorrect

### ISSUE THREAD

**Issue by nomaed** [AllTheMods/ATM-3#19]
After upgrading to 1.4b and loading my game (started in 1.1, played through 1.3), Drawers (basic and basic 1x2) that I have placed in my base are all facing north and items are not displayed on the front.

_Update:_
After closing the game ("save and quit to title") and trying to re-load the save-game, it got stuck on "loading...".
However, after force quitting Minecraft and reloading, game was loaded and drawers got back to being okay.

MC on Mac

**Comment by whatthedrunk** [comment]
Going to assume this is fixed now. Please reopen if you have any new information. Thanks!
