### ISSUE TITLE
[4.0][Craft conflict] Blockcraftery's Framed Block and AE2

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#190]
Hello,

I try to craft the **Framed Block** from _Blockcraftery_ but there is a conflict with an other craft (but This Item is Disabled) from _Applied Energestics 2_ 

![Crafting Station screen, and same result with standart crafting table](https://user-images.githubusercontent.com/13626201/31048196-1a3e0e6e-a64b-11e7-958f-7d3c78252ce6.png)

**Comment by ouroborus** [comment]
https://github.com/AllTheMods/ATM-3/issues/185
