### ISSUE TITLE
[3.3] Missing recipes for bio-mash

### ISSUE THREAD

**Issue by Volaunis** [AllTheMods/ATM-3#191]
Greetings,
The recipes for bio-mash are missing from JEI. However, if you put the materials into craft it (knife surrounded by foodstuffs) it shows and can craft it.
Playing on own linux server, with SpiceOfLife-mc1.12-1.3.10.jar and oeintegration-2.2.0.jar disabled serverside.

**Comment by ouroborus** [comment]
@Volaunis You seem to be asking for every food items' bio-mash recipes to show in JEI which is a huge number of recipes.

Bio-mash itself does show in JEI as a single item. This item links to the Actually Additions Manual entry which says: "Bio-Mash can be crafted from any type of food item by putting any number of it together in a crafting grid with a Knife. The resulting amount of Bio-Mash will vary depending on the food's saturation and healing levels."

**Comment by Volaunis** [comment]
That's true, good point
