### ISSUE TITLE
Crash on loading after updating to technic version 4.0, critical error, binary discrepancy

### ISSUE THREAD

**Issue by RedstoneMaster256** [AllTheMods/ATM-3#192]
I simply cannot start the 4.0 version on Technic. I opened console, and saw these lines at the end of the log (there were no exceptions or stacktraces):

[B#353]  [08:49:34] [main/FATAL] [FML]: There is a binary discrepancy between the expected input class b$1 (b$1) and the actual class. Checksum on disk is 51416ed6, in patch 52fe6ed7. Things are probably about to go very wrong. Did you put something into the jar file?
[B#353]  [08:49:34] [main/FATAL] [FML]: The game is going to exit, because this is a critical error, and it is very improbable that the modded game will work, please obtain clean jar files.

**Comment by RedstoneMaster256** [comment]
I should probably mention, I am using Java 8, I have tried reinstalling. There are no other errors or stacktraces, just these two lines

**Comment by ouroborus** [comment]
I'm seeing this as well. If I had to guess, I'd say Technic still thinks this is a 1.12.**1** modpack but the pack is a 1.12.**2** modpack.

**Comment by splintercat** [comment]
I'm having the same error, like exactly the same hash value mismatch.  I'm on Linux, using OpenJDK-8 64bit.
I cleaned out the techinic folder and reinstalled the modpack, and got the same issue.
My friends who are on Windows are having the same issues as well.

**Comment by ouroborus** [comment]
I believe Technic is still set to use the 1.12.1 client but ATM3 has moved to 1.12.2.

What's working for me:

1. Install as usual via Technic launcher.
2. Click "Play" button.
    - Client crashes. This is expected.
    - This installs all the other stuff that's needed.
3. Download 1.12.2 client jar.
    - I got mine at https://mcversions.net/
4. Replace `minecraft.jar` with this download.
    - You'll need to rename your download.
    - My `minecraft.jar` was at `AppData\Roaming\.technic\modpacks\all-the-mods-3-official\bin\minecraft.jar`. Your location may differ.
5. Hit the "Play button" again
    - If everything went properly, it should launch as though nothing was wrong.

**Comment by splintercat** [comment]
I can confirm that the workaround from @ouroborus work for me.
Under Linux the relevant files to swap out is here:
` ~/.technic/modpacks/all-the-mods-3-official/bin/minecraft.jar`
I got the binary by telling technic to download the latest vanilla, and then moved the jar over.

**Comment by ouroborus** [comment]
This has been fixed. In the Technic launcher, select "Mod Options" and then "Reinstall Pack".
