### ISSUE TITLE
[4.0][Recipe] Inscriber Press's from Applied Energestics 2

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#194]
There is an issue, to make the inscriber press's, the recipe said we can use metallurgic infuser with skystone dust and pulverized/dust, redstone or more, but it don't craft.

And the infusing factory didn't even accept tin pulverized/dust [maybe other too]

**Comment by OrdinatorStouff** [comment]
this seems to be working fine in 5.0+ please re-report if still having problems
