### ISSUE TITLE
[4.0][Recipe]Quartz from AE2

### ISSUE THREAD

**Issue by Kileahh** [AllTheMods/ATM-3#195]
We can't get dust from AE2's quartz dust from crystal with crusher from Mekanism (only with grindstone from AE2, macerator from IC2, and pulverizer from TE).

**Comment by OrdinatorStouff** [comment]
Can you explain why you need AE2's version of quartz dust specifically? All recipes that USE quartz dust should work with any quartz dust from any mod right?

**Comment by Kileahh** [comment]
Because I'm using AE2, and if I have a good remember recipes only use this quartz. Maybe I don't wait enough time on JEI, but I didn't see quartz dust from others mods

**Comment by Boomflex** [comment]
All variants of Quartz Dust will work.

No longer an issue.

Please update to latest version.

**Comment by Yoosk** [comment]
Wrong, some ae2 recipes use specifically dustCertusQuartz.
https://i.imgur.com/whTE1oz.png
