### ISSUE TITLE
Crash when joining server (v 4.1)

### ISSUE THREAD

**Issue by pyr02k1** [AllTheMods/ATM-3#196]
Earlier today, worked without issue. This evening, goes to Logging In, Loading Terrain for a quarter of a second, then lags out for a long time as it writes a massive log, ends with A Fatal Error has Occurred. I wiped the instance, tried again. First try ended with a Connection Reset by Peer. Server appeared to still be up. Second try returned to Fatal Error. 

System is a Thinkpad T430s. 4GB assigned on all attempts except latest (as it was earlier).  Attempted with 5GB to the same result. MultiMC on Manjaro Linux, fully updated as of yesterday. v3.3 had run without issues, 4.1 worked this morning and on 2 subsequent joins during the same system session. No longer works this evening, new session after a reboot.

Attached latest-Crash1.log which I believe was for the Connection Reset by Peer. latest.log is the recent with 5GB assigned. Both in .tar.gz due to size (Crash1 shows to be 12MiB, compressed to 115KiB. logs.tar.gz has the latest, which shows 2.6MiB, but I don't know why. I've added the fml logs to this archive as well.)

[logs.tar.gz](https://github.com/AllTheMods/ATM-3/files/1354647/logs.tar.gz)

[latest-Crash1.tar.gz](https://github.com/AllTheMods/ATM-3/files/1354635/latest-Crash1.tar.gz)

I did note one regarding Mekanism Voice. I attempted to disable this before the wipe to the same result.

Running against them with `sort latest-Crash1.log | uniq | tee truncated.log` yields a lot of errors, but not much for context i suppose. 

I'll attempt OneClient a bit later or tomorrow and see if the result is any different. Any help is appreciated.

Thanks,
John

**Comment by pyr02k1** [comment]
Here is a fresh log from a Windows 10 install with 6GB allotted. Same problem.


[logs.zip](https://github.com/AllTheMods/ATM-3/files/1358066/logs.zip)

**Comment by ProsperCraft** [comment]
Astral Sorcery- 

https://gist.github.com/ProsperCraft/746a1043480f682ae99b0502be24d695

**Comment by ProsperCraft** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/299

**Comment by pyr02k1** [comment]
Verified with 2 other ProsperCraft users that the issue was present for them as well. They'd assumed it was local only as I had. Removing AS seems to have fixed it for them as well

**Comment by Doomgull** [comment]
Can you replicate it with a server reboot in-between occurrences? There was an AS issue way back that wasn't replicable easily to try to learn where it was triggering that was resolved by a server restart, wondering if it's similar.

**Comment by pyr02k1** [comment]
The server was restarted some time during the events, but no change according to the other users. Possibly Goshen ( @ProsperCraft ) could readd it and we can test this evening? It'd be worth a try to make absolutely sure.

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
