### ISSUE TITLE
C&B Crash on joining server (v 4.1)

### ISSUE THREAD

**Issue by pyr02k1** [AllTheMods/ATM-3#197]
Filed with C&B as that appears to be the culprit. 

Occurred while placing a chiseled stone brick panel on some mek pressurized pipes. unable to join since. 

https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310

**Comment by pyr02k1** [comment]
See 
https://github.com/amadornes/MCMultiPart/commit/c36f9f1a4567b86ad5f18f3251ab0afbec4fc568
For
https://github.com/amadornes/MCMultiPart/issues/92

**Comment by Boomflex** [comment]
Update to v4.3

**Comment by PapiDimmi** [comment]
@Boomflex 4.3 doesn’t fix this problem.
