### ISSUE TITLE
ATM3 4.0, Industrial Forgoing Duplication Glitch 

### ISSUE THREAD

**Issue by PhantomWillie** [AllTheMods/ATM-3#198]
Running ATM3 V.4.0 a duplication bug exists with the black hole controller.

This is pretty easy to reproduce, so here are instructions to do so:

Items needed:
1 Item you wish to duplicate
2 black hole units
1 black hole controller
2 other items

First take two black hole units, place the item you wish to duplicate into one and at least one other item into the other. I’m using Diamonds and Dirt. Pick up both black hole units and place them into the Black hole controller.

The items you placed into the black hole units should be shown in the bottom row of the black hole controller. Take the black hole unit holding the item you wish to duplicate out of the Black Hole Controller, observe that the item you wish to duplicate is still in the bottom row of the Black Hole Controller. Move the black hole unit that contains another item into the slot that once held the BHU that contained the item you wish to duplicate in it. Take note that the bottom row still has the item you wish to duplicate in it, despite the black hole unit in the row above being for a different item. Place item that belongs in the black hole unit into the top row and see that it creates another of the item you wish to duplicate. Place items into the black hole unit until you have a full stack of the item you wish to duplicate. You can repeat this indefinitely.

I hope that made sense, If not here is a video of the glitch in action: 
https://youtu.be/bNbbqR3yNXs

**Comment by Boomflex** [comment]
Please update to latest version of the pack (v4.3)
