### ISSUE TITLE
Crash on Opening Controls Menu

### ISSUE THREAD

**Issue by trainzkid** [AllTheMods/ATM-3#2]
That's about it, I just loaded up ATM3, went to options, and clicked on the controls button to open up controls. 

MC 1.12
ATM v0.1

[Pastebin of crash](https://pastebin.com/aSeK984a)

**Comment by Boomflex** [comment]
This is a known Forge issue that has now been fixed after v2322.

**Comment by whatthedrunk** [comment]
Fixed.
