### ISSUE TITLE
Steve's Carts 2: crash when breaking Cart Modifier

### ISSUE THREAD

**Issue by nomaed** [AllTheMods/ATM-3#20]
Attached a Upgrade: Cart Modifier to a Cart Assembly block (per https://ftbwiki.org/Upgrade:_Cart_Modifier instructions).

When breaking the block (with pickaxe), server crashes (local game).

**Comment by OrdinatorStouff** [comment]
Steves Carts 2 very buggy in general

maybe this better by now: 
![image](https://user-images.githubusercontent.com/6283913/30014737-bc0629ce-9102-11e7-9b94-bf1820d89a4c.png)
