### ISSUE TITLE
Missing inventory models for Mekanism machines

### ISSUE THREAD

**Issue by craft90** [AllTheMods/ATM-3#200]
I'm running ATM 3 v.4.1 on a server and I noticed in JEI that certain Mekanism machines didn't have a texture in particular all the generators, energy cubes and atomic disassembler. Then there was some other bits and bobs which were missing their texture. I'm familiar with this issue and I do believe it's a render issue between conflicting mods. I'm aware it isn't the newest issue so I do not know if it was fixed but there was no mention of it in the change log. I personally don't know how to fix the issue other than removing the mod causing the issue. But I thought I should report it anyway.

**Comment by ouroborus** [comment]
I'm noticing this as well: Blank icons in NEI for a number of Mekanism items.

**Comment by Boomflex** [comment]
Fixed in newer mod version
