### ISSUE TITLE
[4.0][Recipe]OpenComputer Diamond chip

### ISSUE THREAD

**Issue by galfalek** [AllTheMods/ATM-3#202]
You can't make Diamond chip from OpenComputer, it instead make Diamond nugget whom are not usable in opencomputer recipe.

**Comment by Kileahh** [comment]
You can do it in the Workbench from Forestry (I don't know what is your level with OC, but I will maybe need your help with computronics)

**Comment by Boomflex** [comment]
No loner an issue as of v4.3
