### ISSUE TITLE
[4.1]Aluminium and steel dust not smeltable in mekanism energised smelter.

### ISSUE THREAD

**Issue by Electrofried** [AllTheMods/ATM-3#203]
As per title pack version is 4.1

The energised smelter from mekanism does not accept mekanism steel dust as smeltable, or aluminium dust (Thermal foundation).

**Comment by namstor** [comment]
Same issue

**Comment by OrdinatorStouff** [comment]
steel dust not being smeltable is intended. Aluminum I'm not sure about however

**Comment by namstor** [comment]
so that is a config setting for steel dust? As a server owner where can I change that back? I have players with automated mekanism setups that aren't working now.

**Comment by OrdinatorStouff** [comment]
That setting was made back in like 3.3 and it was a design choice among
many others. You can try to modify just that one part of the one recipe
script but the exact same change would need to be made on any/all clients
connecting to the same server.

Another option is changing server and all clients over to "simplified" mode
in packmode.cfg where many other of these intended, standard pack design
choices are also disabled but that affects many things than just steel dust
and again,. all client would need to also change the config and restart to
connect.

**Comment by Electrofried** [comment]
This is my major problem with ATM3 creeping towards an expert mode pack as it's default mode. With the way craft tweaker works now, server admins are unable to manage or disable things without requiring all players who join to have an understanding of how to modify scripts or provide a custom "ATM3-(Servername).zip" with custom configs that each person has to copy over their install. Both options are horrible and not feasible on larger public servers.   
Making these changes are fine, but imo it should be a separate pack called "ATM 3: Upgraded" or something. Totally changing the modpack from a kitchen sink pack to a customised pack balanced around what you consider fair (ignoring that the mod devs have already balanced their mods how they want them) and requiring people to use a hacked in pack mode that has to be manually changed for each client is not really a good idea imo.

**Comment by Boomflex** [comment]
Hi there @Electrofried, many thanks for your input on our pack design.

Here at All the Mods, we do not simply want our packs to be "put mods in a folder and press play"... We want there to be a little more structure, a little more thought out and a little more balanced.

"Making these changes are fine", well thank you for your permission :)

"Totally changing the modpack" is a MASSIVE overstatement.

If this pack no longer fits whats your vision was, then that is obviously sad to hear, however, they are our packs and ones that we make for ourselves to play (It just so happens that over 1million others seemed to want to too).

We hope you stick around and managed to figure out alternatives to your issues :)

Thanks!
