### ISSUE TITLE
crash and cant figure it out

### ISSUE THREAD

**Issue by Craigschultze30** [AllTheMods/ATM-3#204]
[crash-2017-10-08_12.56.32-server.txt](https://github.com/AllTheMods/ATM-3/files/1367084/crash-2017-10-08_12.56.32-server.txt)
 as soon as i load my world i get this crash. i think it has to do with the extra util quarry. i went back to my save before i buit it and it is fine.

**Comment by Boomflex** [comment]
Please update to latest version of the pack.
