### ISSUE TITLE
When i try to relog it stucks at "Loading World" screen and console says this :

### ISSUE THREAD

**Issue by GizliKodcu** [AllTheMods/ATM-3#205]
21:23:46 | FML | Server thread | fatal | Fatal errors were detected during the transition from SERVER_STOPPING to SERVER_ABOUT_TO_START. Loading cannot continue
-- | -- | -- | -- | --
21:23:46 | FML | Server thread | fatal | States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored  	\| State       \| ID                        \| Version                         \| Source                                              \| Signature                                \| 	\|:----------- \|:------------------------- \|:------------------------------- \|:--------------------------------------------------- \|:---------------------------------------- \| 	\| UCHIJAAAAAA \| minecraft                 \| 1.12.1                          \| minecraft.jar                                       \| None                                     \| 	\| UCHIJAAAAAA \| mcp                       \| 9.19                            \| minecraft.jar                                       \| None                                     \| 	\| UCHIJAAAAAA \| FML                       \| 8.0.99.99                       \| forge-1.12.1-14.22.1.2485.jar                       \| e3c3d50c7c986df74c645c0ac54639741c90a557 \| 	\| UCHIJAAAAAA \| forge                     \| 14.22.1.2485                    \| forge-1.12.1-14.22.1.2485.jar                       \| e3c3d50c7c986df74c645c0ac54639741c90a557 \| 	\| UCHIJAAAAAA \| foamfixcore               \| 7.7.4                           \| minecraft.jar                                       \| None                                     \| 	\| UCHIJAAAAAA \| opencomputers\|core        \| 1.7.0.4                         \| minecraft.jar                                       \| None                                     \| 	\| UCHIJAAAAAA \| actuallyadditions         \| 1.12.1-r119                     \| ActuallyAdditions-1.12.1-r119.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| baubles                   \| 1.5.1                           \| Baubles-1.12-1.5.1.jar                              \| None                                     \| 	\| UCHIJAAAAAA \| actuallybaubles           \| 1.1                             \| ActuallyBaubles-1.12-1.1.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| additionalbanners         \| 1.5.39                          \| AdditionalBanners-1.12-1.5.39.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| aiimprovements            \| 0.0.1.1                         \| AIImprovements-1.12.1-0.0.1b1.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| akashictome               \| 1.2-10                          \| AkashicTome-1.2-10.jar                              \| None                                     \| 	\| UCHIJAAAAAA \| chisel                    \| MC1.12-0.0.14.18                \| Chisel-MC1.12-0.0.14.18.jar                         \| None                                     \| 	\| UCHIJAAAAAA \| crafttweaker              \| 4.0.6                           \| CraftTweaker2-1.12-4.0.6.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| mtlib                     \| @VERSION@                       \| MTLib-3.0.0.jar                                     \| None                                     \| 	\| UCHIJAAAAAA \| modtweaker                \| 4.0.2                           \| modtweaker-4.0.2.jar                                \| None                                     \| 	\| UCHIJAAAAAA \| jei                       \| 4.7.8.95                        \| jei_1.12.1-4.7.8.95.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| mantle                    \| 1.12-1.3.1.21                   \| Mantle-1.12-1.3.1.21.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| tconstruct                \| 1.12-2.7.3.30                   \| TConstruct-1.12-2.7.3.30.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| extrautils2               \| 1.0                             \| extrautils2-1.12-1.6.3.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| flyringbaublemod          \| 0.3.0_1.12-306787e              \| angelRingToBauble-1.12-0.3.0.46+306787e.jar         \| None                                     \| 	\| UCHIJAAAAAA \| applecore                 \| 2.2.2                           \| AppleCore-mc1.12.1-2.2.2.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| appleskin                 \| 1.0.8                           \| AppleSkin-mc1.12-1.0.8.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| appliedenergistics2       \| rv5-alpha-4                     \| appliedenergistics2-rv5-alpha-4.jar                 \| None                                     \| 	\| UCHIJAAAAAA \| aroma1997core             \| 1.3.0.0.b122                    \| Aroma1997Core-1.12.1-1.3.0.0.b122.jar               \| dfbfe4c473253d8c5652417689848f650b2cbe32 \| 	\| UCHIJAAAAAA \| aroma1997sdimension       \| 2.0.0.0.b56                     \| Aroma1997s-Dimensional-World-1.12.1-2.0.0.0.b56.jar \| None                                     \| 	\| UCHIJAAAAAA \| astralsorcery             \| 1.6.1                           \| astralsorcery-1.12-1.6.1.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| atmtweaks                 \| 1.1                             \| atmtweaks-1.1.jar                                   \| None                                     \| 	\| UCHIJAAAAAA \| morphtool                 \| 1.2-16                          \| Morph-o-Tool-1.2-16.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| psi                       \| r1.1-53                         \| Psi-r1.1-53.jar                                     \| None                                     \| 	\| UCHIJAAAAAA \| quark                     \| r1.3-110                        \| Quark-r1.3-110.jar                                  \| None                                     \| 	\| UCHIJAAAAAA \| autoreglib                \| 1.3-13                          \| AutoRegLib-1.3-13.jar                               \| None                                     \| 	\| UCHIJAAAAAA \| badwithernocookiereloaded \| 1.12.1-1.7                      \| badwithernocookiereloaded-1.12.1-1.7.jar            \| None                                     \| 	\| UCHIJAAAAAA \| base                      \| 3.2.0                           \| base-1.12-3.2.0.jar                                 \| None                                     \| 	\| UCHIJAAAAAA \| bdlib                     \| 1.14.2.8                        \| bdlib-1.14.2.8-mc1.12.1.jar                         \| None                                     \| 	\| UCHIJAAAAAA \| bedbugs                   \| @VERSION@                       \| BedBugs-1.12-1.0.1.jar                              \| None                                     \| 	\| UCHIJAAAAAA \| betterbuilderswands       \| 0.11.1                          \| BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar     \| None                                     \| 	\| UCHIJAAAAAA \| bibliocraft               \| 2.4.3                           \| BiblioCraft[v2.4.3][MC1.12.0].jar                   \| None                                     \| 	\| UCHIJAAAAAA \| ic2                       \| 2.8.16-ex112                    \| industrialcraft-2-2.8.16-ex112.jar                  \| de041f9f6187debbc77034a344134053277aa3b0 \| 	\| UCHIJAAAAAA \| natura                    \| 1.12-4.3.0.17                   \| Natura-1.12-4.3.0.17.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| forestry                  \| 5.5.6.197                       \| forestry_1.12.2-5.5.6.197.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| binniecore                \| unspecified                     \| binnie-mods-1.12.1-2.3.0.60.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| binniedesign              \| 1.0                             \| binnie-mods-1.12.1-2.3.0.60.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| genetics                  \| 2.3.0.60                        \| binnie-mods-1.12.1-2.3.0.60.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| botany                    \| 2.3.0.60                        \| binnie-mods-1.12.1-2.3.0.60.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| extrabees                 \| 2.3.0.60                        \| binnie-mods-1.12.1-2.3.0.60.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| extratrees                \| 2.3.0.60                        \| binnie-mods-1.12.1-2.3.0.60.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| biomesoplenty             \| 7.0.0.2291                      \| BiomesOPlenty-1.12-7.0.0.2291-universal.jar         \| None                                     \| 	\| UCHIJAAAAAA \| blockdrops                \| 1.3.0                           \| blockdrops-1.12-1.3.0.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| blur                      \| 1.0.4-14                        \| Blur-1.0.4-14.jar                                   \| None                                     \| 	\| UCHIJAAAAAA \| bookshelf                 \| 2.1.441                         \| Bookshelf-1.12.1-2.1.441.jar                        \| d476d1b22b218a10d845928d1665d45fce301b27 \| 	\| UCHIJAAAAAA \| botania                   \| r1.10-347                       \| Botania r1.10-347.jar                               \| None                                     \| 	\| UCHIJAAAAAA \| codechickenlib            \| 3.1.2.297                       \| CodeChickenLib-1.12-3.1.2.297-universal.jar         \| f1850c39b2516232a2108a7bd84d1cb5df93b261 \| 	\| UCHIJAAAAAA \| redstoneflux              \| 2.0.1                           \| RedstoneFlux-1.12-2.0.1.2-universal.jar             \| d4f1503fbacd9b9fb767720420c5395104239ec9 \| 	\| UCHIJAAAAAA \| brandonscore              \| 2.3.2                           \| BrandonsCore-1.12-2.3.2.129-universal.jar           \| None                                     \| 	\| UCHIJAAAAAA \| ceramics                  \| 1.12-1.3.2                      \| Ceramics-1.12-1.3.2.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| chameleon                 \| 1.12-4.1.3                      \| Chameleon-1.12-4.1.3.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| chiselsandbits            \| 14.7                            \| chiselsandbits-14.7.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| clarity                   \| 1.0                             \| clarity-1.0.jar                                     \| None                                     \| 	\| UCHIJAAAAAA \| cofhcore                  \| 4.3.5                           \| CoFHCore-1.12-4.3.5.13-universal.jar                \| None                                     \| 	\| UCHIJAAAAAA \| cofhworld                 \| 1.0.1                           \| CoFHWorld-1.12-1.0.1.8-universal.jar                \| None                                     \| 	\| UCHIJAAAAAA \| cyclopscore               \| 0.10.18                         \| CyclopsCore-1.12-0.10.18.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| colossalchests            \| 1.6.5                           \| ColossalChests-1.12-1.6.5.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| commoncapabilities        \| 1.4.0                           \| CommonCapabilities-1.12-1.4.0.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| contenttweaker            \| 1.12-4.0.0                      \| ContentTweaker-1.12-4.0.0.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| controlling               \| 3.0.2                           \| Controlling-3.0.2.jar                               \| None                                     \| 	\| UCHIJAAAAAA \| cookingforblockheads      \| 6.3.6                           \| CookingForBlockheads_1.12.1-6.3.6.jar               \| None                                     \| 	\| UCHIJAAAAAA \| cosmeticarmorreworked     \| 1.12.2-v1                       \| CosmeticArmorReworked-1.12.2-v1.jar                 \| aaaf83332a11df02406e9f266b1b65c1306f0f76 \| 	\| UCHIJAAAAAA \| craftingtweaks            \| 8.1.5                           \| CraftingTweaks_1.12.1-8.1.5.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| ctgui                     \| 1.0.0                           \| CraftTweaker2-1.12-4.0.6.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| crafttweakerjei           \| 2.0.0                           \| CraftTweaker2-1.12-4.0.6.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| ctm                       \| MC1.12-0.2.2.7                  \| CTM-MC1.12-0.2.2.7.jar                              \| None                                     \| 	\| UCHIJAAAAAA \| cucumber                  \| 1.0.2                           \| cucumber[1.12]-1.0.2.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| custombackgrounds         \| 1.0                             \| CustomBackgrounds-MC1.12-1.1.1.jar                  \| None                                     \| 	\| UCHIJAAAAAA \| custommainmenu            \| 2.0.7                           \| CustomMainMenu-MC1.12.1-2.0.7.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| cyclicmagic               \| 1.8.4                           \| Cyclic-1.12-1.8.4.jar                               \| None                                     \| 	\| UCHIJAAAAAA \| darkutils                 \| 1.7.171                         \| DarkUtils-1.12.1-1.7.171.jar                        \| d476d1b22b218a10d845928d1665d45fce301b27 \| 	\| UCHIJAAAAAA \| defaultoptions            \| 9.2.4                           \| DefaultOptions_1.12.1-9.2.4.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| dldungeonsjdg             \| 1.9.3                           \| DoomlikeDungeons-1.9.3-MC1.12.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| draconicevolution         \| 2.3.3                           \| Draconic-Evolution-1.12-2.3.3.261-universal.jar     \| None                                     \| 	\| UCHIJAAAAAA \| elevatorid                \| 1.3.4                           \| ElevatorMod-1.12-1.3.4.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| embers                    \| 0.221                           \| embers-0.221.jar                                    \| None                                     \| 	\| UCHIJAAAAAA \| enderstorage              \| 2.4.0.122                       \| EnderStorage-1.12-2.4.0.122-universal.jar           \| f1850c39b2516232a2108a7bd84d1cb5df93b261 \| 	\| UCHIJAAAAAA \| valkyrielib               \| 1.12-2.0.1a                     \| valkyrielib-1.12.1-2.0.2c.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| environmentaltech         \| 1.12.1-2.0.2d                   \| environmentaltech-1.12.1-2.0.2d.jar                 \| None                                     \| 	\| UCHIJAAAAAA \| mcmultipart               \| 2.2.2                           \| MCMultiPart-2.2.2.jar                               \| None                                     \| 	\| UCHIJAAAAAA \| mekanism                  \| 9.4.1                           \| Mekanism-1.12.1-9.4.1.326.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| thermalfoundation         \| 2.3.5                           \| ThermalFoundation-1.12-2.3.5.14-universal.jar       \| None                                     \| 	\| UCHIJAAAAAA \| thermalexpansion          \| 5.3.5                           \| ThermalExpansion-1.12-5.3.5.19-universal.jar        \| None                                     \| 	\| UCHIJAAAAAA \| exchangers                \| 1.12-2.4                        \| Exchangers-1.12-2.4.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| shadowmc                  \| 3.8.0                           \| ShadowMC-1.12-3.8.0.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| extrarails                \| 1.3.0                           \| ExtraRails-1.12-1.3.0.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| zerocore                  \| 1.12-0.1.0.9                    \| zerocore-1.12-0.1.0.9.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| bigreactors               \| 1.12-0.4.5.34                   \| ExtremeReactors-1.12-0.4.5.34.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| fairylights               \| 2.1.1                           \| fairylights-2.1.1-1.12.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| fencejumper               \| 1.0.0                           \| fencejumper-1.12-1.0.0.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| flatcoloredblocks         \| mc1.12-6.5                      \| flatcoloredblocks-mc1.12-6.5.jar                    \| None                                     \| 	\| UCHIJAAAAAA \| foamfix                   \| 0.8.0-1.12                      \| foamfix-0.8.0-1.12-anarchy.jar                      \| None                                     \| 	\| UCHIJAAAAAA \| forgelin                  \| 1.5.1                           \| Forgelin-1.5.1.jar                                  \| None                                     \| 	\| UCHIJAAAAAA \| ftbl                      \| 0.0.0                           \| FTBLib-4.1.3.jar                                    \| None                                     \| 	\| UCHIJAAAAAA \| ftbu                      \| 0.0.0                           \| FTBUtilities-4.1.3.jar                              \| None                                     \| 	\| UCHIJAAAAAA \| funkylocomotion           \| 1.0                             \| funky-locomotion-1.12-alpha-0.0.1.jar               \| None                                     \| 	\| UCHIJAAAAAA \| gendustry                 \| 1.6.5.4                         \| gendustry-1.6.5.4-mc1.12.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| pressure                  \| 1.3.1.6                         \| pressure-1.3.1.6-mc1.12.1.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| advgenerators             \| 0.9.20.7                        \| generators-0.9.20.7-mc1.12.1.jar                    \| None                                     \| 	\| UCHIJAAAAAA \| gravestone                \| 1.9.0                           \| gravestone-1.9.0.jar                                \| None                                     \| 	\| UCHIJAAAAAA \| mb                        \| 1.0                             \| MagicBooks-2.1.3.jar                                \| None                                     \| 	\| UCHIJAAAAAA \| mobtotems                 \| 1.12.1-0.3.0                    \| mobtotems-1.12.1-0.3.0.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| guideapi                  \| 1.12-2.1.4-57                   \| Guide-API-1.12-2.1.4-57.jar                         \| None                                     \| 	\| UCHIJAAAAAA \| harvest                   \| 1.12-1.2.6-18                   \| Harvest-1.12-1.2.6-18.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| theoneprobe               \| 1.4.18                          \| theoneprobe-1.12-1.4.18.jar                         \| None                                     \| 	\| UCHIJAAAAAA \| immersiveengineering      \| 0.12-72                         \| ImmersiveEngineering-0.12-72.jar                    \| 4cb49fcde3b43048c9889e0a3d083225da926334 \| 	\| UCHIJAAAAAA \| immersivepetroleum        \| 1.1.3                           \| immersivepetroleum-1.12-1.1.3.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| teslacorelib              \| 1.0.9                           \| tesla-core-lib-1.12-1.0.9.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| industrialforegoing       \| 1.12-1.12                       \| industrialforegoing-1.12-1.3-58.jar                 \| None                                     \| 	\| UCHIJAAAAAA \| industrialwires           \| 1.6-20                          \| IndustrialWires-1.6-20.jar                          \| 7e11c175d1e24007afec7498a1616bef0000027d \| 	\| UCHIJAAAAAA \| integrateddynamics        \| 0.9.1                           \| IntegratedDynamics-1.12-0.9.1.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| integrateddynamicscompat  \| 1.0.0                           \| IntegratedDynamics-1.12-0.9.1.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| integratedtunnels         \| 1.3.2                           \| IntegratedTunnels-1.12-1.3.2.jar                    \| None                                     \| 	\| UCHIJAAAAAA \| mysticalagriculture       \| 1.6.4                           \| mysticalagriculture-1.12-1.6.4.jar                  \| None                                     \| 	\| UCHIJAAAAAA \| mysticalagradditions      \| 1.2.4                           \| mysticalagradditions[1.12]-1.2.4.jar                \| None                                     \| 	\| UCHIJAAAAAA \| rftools                   \| 6.13                            \| rftools-1.12-6.13.jar                               \| None                                     \| 	\| UCHIJAAAAAA \| integrationforegoing      \| 1.12-1.1                        \| IntegrationForegoing-1.12-1.1.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| inventorytweaks           \| 1.63+beta.108.6ff67c4           \| InventoryTweaks-1.63+beta.108.jar                   \| 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe \| 	\| UCHIJAAAAAA \| ironchest                 \| 1.12-7.0.31.818                 \| ironchest-1.12-7.0.31.818.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| jaopcaadditions           \| 1.12-1.2.2                      \| JAOPCAAdditions-1.12-1.2.2.jar                      \| None                                     \| 	\| UCHIJAAAAAA \| jaopca                    \| 1.12-2.2.2.44                   \| JAOPCA-1.12-2.2.2.44.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| oredictinit               \| 1.12-2.2.0.55                   \| JAOPCA-1.12-2.2.2.44.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| jeibees                   \| 0.9.0.4                         \| jeibees-0.9.0.4-mc1.12.1.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| journeymap                \| 1.12.1-5.5.0b4                  \| journeymap-1.12.1-5.5.0b4.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| justenoughdimensions      \| 1.5.5                           \| justenoughdimensions-1.12.1-1.5.5.jar               \| 2b03e1423915a189b8094816baa18f239d576dff \| 	\| UCHIJAAAAAA \| jeresources               \| 0.8.4.25                        \| JustEnoughResources-1.12.1-0.8.4.25.jar             \| None                                     \| 	\| UCHIJAAAAAA \| kleeslabs                 \| 5.3.2                           \| KleeSlabs_1.12-5.3.2.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| lostcities                \| 1.0.0                           \| lostcities-1.12-1.0.0.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| mekanismgenerators        \| 9.4.1                           \| MekanismGenerators-1.12.1-9.4.1.326.jar             \| None                                     \| 	\| UCHIJAAAAAA \| mekanismtools             \| 9.4.1                           \| MekanismTools-1.12.1-9.4.1.326.jar                  \| None                                     \| 	\| UCHIJAAAAAA \| minecolonies              \| 1.12.1-0.8.4000                 \| minecolonies-universal-1.12.1-0.8.4000.jar          \| None                                     \| 	\| UCHIJAAAAAA \| modnametooltip            \| 1.9.0                           \| modnametooltip_1.12.1-1.9.0.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| moreoverlays              \| 1.12                            \| moreoverlays-1.12-mc1.12.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| morpheus                  \| 1.12-3.3.2                      \| Morpheus-1.12-3.3.2.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| mousetweaks               \| 2.8                             \| MouseTweaks-2.8-mc1.12.1.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| nmsot                     \| 1.2.1-mc1.12                    \| NoMobSpawningOnTrees-1.2.1-mc1.12.jar               \| None                                     \| 	\| UCHIJAAAAAA \| recipehandler             \| 0.9                             \| NoMoreRecipeConflict-0.9(1.12).jar                  \| None                                     \| 	\| UCHIJAAAAAA \| neid                      \| 1.5.4.1                         \| NotEnoughIDs-1.5.4.1.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| notenoughwands            \| 1.5.9                           \| notenoughwands-1.12-1.5.9.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| oreexcavation             \| 1.4.105                         \| OreExcavation-1.4.105.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| oeintegration             \| 2.2.0                           \| oeintegration-2.2.0.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| opencomputers             \| 1.7.0.4                         \| OpenComputers-MC1.12.1-1.7.0.4.jar                  \| None                                     \| 	\| UCHIJAAAAAA \| openglider                \| @VERSION@                       \| OpenGlider-1.12.1-1.1.0.jar                         \| None                                     \| 	\| UCHIJAAAAAA \| overloaded                \| 0.0.38                          \| Overloaded-1.12.1-0.0.38.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| packmode                  \| 1.0.0                           \| packmode-1.0.0.jar                                  \| None                                     \| 	\| UCHIJAAAAAA \| harvestcraft              \| 1.12.1c                         \| Pam's HarvestCraft 1.12.1c.jar                      \| None                                     \| 	\| UCHIJAAAAAA \| personalcars              \| 1.4                             \| PersonalCars-1.4.jar                                \| None                                     \| 	\| UCHIJAAAAAA \| reborncore                \| 3.4.3.114                       \| RebornCore-1.12.2-3.4.3.114-universal.jar           \| 8727a3141c8ec7f173b87aa78b9b9807867c4e6b \| 	\| UCHIJAAAAAA \| quantumstorage            \| 4.4.0                           \| QuantumStorage-1.12-4.4.0.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| quickleafdecay            \| 1.2.4                           \| QuickLeafDecay-MC1.12.1-1.2.4.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| rainboaks                 \| 1.0.4                           \| RainbowOaks-1.12-1.0.4.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| rangedpumps               \| 0.5                             \| rangedpumps-0.5.jar                                 \| None                                     \| 	\| UCHIJAAAAAA \| reauth                    \| 3.5.1                           \| ReAuth-3.5.1.jar                                    \| aa395513cd0890f9c69d4229ac5d779667421c85 \| 	\| UCHIJAAAAAA \| redstonearsenal           \| 2.3.5                           \| RedstoneArsenal-1.12-2.3.5.13-universal.jar         \| None                                     \| 	\| UCHIJAAAAAA \| storagedrawers            \| 1.12-5.2.5                      \| StorageDrawers-1.12.1-5.3.2.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| refinedstorage            \| 1.5.18                          \| refinedstorage-1.5.18.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| refinedstorageaddons      \| 0.1.1                           \| refinedstorageaddons-0.1.1.jar                      \| None                                     \| 	\| UCHIJAAAAAA \| resourceloader            \| 1.5.3                           \| ResourceLoader-MC1.12.1-1.5.3.jar                   \| d72e0dd57935b3e9476212aea0c0df352dd76291 \| 	\| UCHIJAAAAAA \| rftoolscontrol            \| 1.6.8                           \| rftoolsctrl-1.12-1.6.8.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| rftoolsdim                \| 5.05                            \| rftoolsdim-1.12-5.05.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| roots                     \| 0.103                           \| roots-2-0.103.jar                                   \| None                                     \| 	\| UCHIJAAAAAA \| rustic                    \| 0.4.2.1                         \| rustic-0.4.3.jar                                    \| None                                     \| 	\| UCHIJAAAAAA \| woodenshears              \| @MAJOR@.@MINOR@.@REVIS@.@BUILD@ \| SBM-WoodenShears-1.12-0.0.1b8.jar                   \| None                                     \| 	\| UCHIJAAAAAA \| shetiphiancore            \| 3.5.2                           \| shetiphiancore-1.12.0-3.5.2.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| simplesponge              \| 3.5                             \| SimpleSponge-1.12-3.5.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| simplytea                 \| 1.4                             \| simplytea-1.4.jar                                   \| None                                     \| 	\| UCHIJAAAAAA \| skyblocks                 \| 0.1.1-alpha-1.12.1              \| Skyblocks-0.1.1-alpha-1.12.1.jar                    \| None                                     \| 	\| UCHIJAAAAAA \| soulshardstow             \| 1.12-2.7.3-52                   \| SoulShards-TOW-1.12-2.7.3-52.jar                    \| None                                     \| 	\| UCHIJAAAAAA \| spiceoflife               \| 1.3.10                          \| SpiceOfLife-mc1.12-1.3.10.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| stevescarts               \| ${version}                      \| StevesCarts-1.12.1-2.4.8.44.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| storagedrawersextra       \| @VERSION@                       \| StorageDrawersExtras-1.12-3.1.0.jar                 \| None                                     \| 	\| UCHIJAAAAAA \| techreborn                \| 2.7.4.243                       \| TechReborn-1.12.2-2.7.4.243-universal.jar           \| 8727a3141c8ec7f173b87aa78b9b9807867c4e6b \| 	\| UCHIJAAAAAA \| terraqueous               \| 1.4.3                           \| terraqueous-1.12.0-1.4.3.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| thermalcultivation        \| 0.1.1                           \| ThermalCultivation-1.12-0.1.1.6-universal.jar       \| None                                     \| 	\| UCHIJAAAAAA \| thermaldynamics           \| 2.3.5                           \| ThermalDynamics-1.12-2.3.5.12-universal.jar         \| None                                     \| 	\| UCHIJAAAAAA \| tinkertoolleveling        \| 1.12-1.0.2b.DEV.1a79301         \| TinkerToolLeveling-1.12-1.0.2b.jar                  \| None                                     \| 	\| UCHIJAAAAAA \| toastcontrol              \| 1.1.1                           \| Toast Control-1.12-1.1.1.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| topaddons                 \| 1.12-0.15.1                     \| topaddons-1.12-0.15.1.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| traverse                  \| 1.3.1                           \| Traverse-1.12.1-1.3.1.jar                           \| None                                     \| 	\| UCHIJAAAAAA \| usefulnullifiers          \| 1.4.1                           \| usefulnullifiers-1.4.1.jar                          \| None                                     \| 	\| UCHIJAAAAAA \| wanionlib                 \| 1.12.1-1.0                      \| WanionLib-1.12.1-1.0.jar                            \| None                                     \| 	\| UCHIJAAAAAA \| waterstrainer             \| 3.2.0                           \| WaterStrainer-1.12-3.2.0.jar                        \| None                                     \| 	\| UCHIJAAAAAA \| waystones                 \| 4.0.15                          \| Waystones_1.12.1-4.0.15.jar                         \| None                                     \| 	\| UCHIJAAAAAA \| worldstripper             \| 1.4.1-1.12.1                    \| World-Stripper-1.4.1-1.12.1.jar                     \| None                                     \| 	\| UCHIJAAAAAA \| xnet                      \| 1.4.0                           \| xnet-1.12-1.4.0.jar                                 \| None                                     \| 	\| UCHIJAAAAAA \| xtones                    \| 1.12-1.0.6-9                    \| Xtones-1.12-1.0.6-9.jar                             \| None                                     \| 	\| UCHIJAAAAAA \| teslacorelib_registries   \| 1.0.9                           \| tesla-core-lib-1.12-1.0.9.jar                       \| None                                     \| 	\| UCHIJAAAAAA \| unidict                   \| 1.12.1-1.0                      \| UniDict-1.12.1-1.0.jar                              \| None                                     \| 	\| UCHIJAAAAAA \| wrapup                    \| 1.12-1.1.1                      \| WrapUp-1.12-1.1.1.jar                               \| None                                     \|
21:23:46 | FML | Server thread | fatal | The ForgeModLoader state engine has become corrupted. Probably, a state was missed by and invalid modification to a base classForgeModLoader depends on. This is a critical error and not recoverable. Investigate any modifications to base classes outside ofForgeModLoader, especially Optifine, to see if there are fixes available.

**Comment by ouroborus** [comment]
All the useful information is missing. Post the entire crash log as a separate file.

**Comment by Boomflex** [comment]
Update to 4.3
