### ISSUE TITLE
Clipboard Bilbliocraft mod

### ISSUE THREAD

**Issue by xxsuperdreamxx** [AllTheMods/ATM-3#207]
Don't put the clipboard on walls because you are going to crash tested by 2 people.
https://gist.github.com/xxsuperdreamxx/2437db9896fd4aa6266246ca8c57c474
https://gist.github.com/xxsuperdreamxx/e8feeec6c7d2acdaa2469ce35d03802d

**Comment by MrNinja93** [comment]
Clipboard in general is just crashing allot, Crashes occasionally if you look at it in JEI crashes being near it, crashes looking at it.... 

Been multiple reports on bibliocraft's github so the dev at-least knows 
https://github.com/Nuchaz/BiblioCraft/issues

**Comment by Boomflex** [comment]
Mod issue.

Has been reported to Dev.
