### ISSUE TITLE
Can't decompress Overloaded Draconium Blocks

### ISSUE THREAD

**Issue by Drakefyre27** [AllTheMods/ATM-3#209]
Draconium blocks can be compressed via Overloaded, but can't be decompressed.
The 1x Compressed Draconium Blocks to 9 Draconium blocks recipe shows up in JEI.
Tried many crafting tables to no avail. Compacting drawer is of no help either.

**Comment by Drakefyre27** [comment]
Update: It seems that all ''Overloaded'' compressed blocks can't be decompressed.
Just tried it with obsidian and didn't work.

**Comment by OrdinatorStouff** [comment]
I just became aware of this a day or two ago myself in a personal playthrough as well. I'm working on manually adding/fixing all of these recipes with crafttweaker scripts

**Comment by Boomflex** [comment]
No longer an issue.

Please update to latest version.
