### ISSUE TITLE
Botania magnet and Immersive engineering crash

### ISSUE THREAD

**Issue by MrNinja93** [AllTheMods/ATM-3#210]
I don't understand who's end is broke but I Imagine someone on here will.

I broke a chest while wearing a botania magnet and crashed to desktop and then soft crashed to multi-player screen after re-load until I tp'd away via console, removing magnet and returning to pick everything up worked fine. 

Only IE item in the chest was the shield like log mentions, was not upgraded at all just the base version.

Running base ATM3 version 4.0

Crash Log:-
https://gist.github.com/MrNinja93/1dde4c294933e08336f2bf0c93dce314

**Comment by Boomflex** [comment]
Please update to latest version of the pack (v4.3)
