### ISSUE TITLE
Magical Crops Watering Cans

### ISSUE THREAD

**Issue by Hatter243** [AllTheMods/ATM-3#213]
Any watering can that has unlimited water can be used to avoid the afk timer. Set up a macro to hold down right click and it will register you as being online because your character is doing something.

**Comment by ouroborus** [comment]
@Hatter243 There are a lot of ways to avoid afk timers. As a server admin, if you wish to avoid this, the best you can feasibly do is announce a rule instituting penalties for afk timer avoidance and then manually enforce it.

**Comment by Boomflex** [comment]
Not a pack problem.
