### ISSUE TITLE
Chisel not possible on some blocks despite having patterns available.

### ISSUE THREAD

**Issue by ouroborus** [AllTheMods/ATM-3#215]
The Chisel mod (not Chisel and Bits) provides chisel patterns for a number of storage blocks but they're not bound to the storage block itself so it's not possible to chisel them.

For example, there are patterns for Block of Aluminum but the chisel doesn't show anything when any of the non-Chisel variants of Block of Aluminum are placed in the tool.

On the other hand, placing a Block of Redstone into the Chisel tool shows a number of patterns.

**Comment by Boomflex** [comment]
Currently not possible with Chisel.

Waiting on Crafttweaker/Modtweaker addition.
