### ISSUE TITLE
[4.1] Actually Additions Farmer only harvests 1 Inferium Essence from tier 6 Inferium crops

### ISSUE THREAD

**Issue by ffgda** [AllTheMods/ATM-3#216]
The tier 6 Inferium crops that are added by Mystical Agradditions are supposed to drop 6 Inferium Essence, which is the case if you harvest/break them manually. If you automate a farm with the Actually additions Farmer, it only grants 1 Essence per harvested crop.

**Comment by Boomflex** [comment]
Please update to latest version of the pack.

Currently v4.3 is latest.
