### ISSUE TITLE
Mining world diamonds and emeralds

### ISSUE THREAD

**Issue by Lescius** [AllTheMods/ATM-3#217]
In aroma1997sdimension_gen.cfg, you have sections for diamond and emerald, but they both specify minecraft:emerald_ore

**Comment by OrdinatorStouff** [comment]
Thanks, that's a silly copy+paste error on my part :/

**Comment by OrdinatorStouff** [comment]
should be fixed in pack ver 5.0+ let us know if anything else seems off

thanks
