### ISSUE TITLE
Please add nuclearcraft ores to void miner.

### ISSUE THREAD

**Issue by Electrofried** [AllTheMods/ATM-3#218]
Currently boron is unobtainable (I have not even found it in newly genned chunks) and the other ore/metals are unobtainable due to the lack of boron and world gen. Please consider adding it to the void miner list and/or editing the actually additions cfg to include extra ores in the mining lens whitelist. (note: have not tested the orchid yet to see if that works to obtain the ore)

**Comment by xenoflot** [comment]
@Boomflex To make your life a little simpler, here what I added the following to the tiers1-6 jsons on our server. Don't forget to add a comma after the erodium_crystal definition (like I did... oops!).  These numbers have Thorium as common as gold, boron as common as Silver and the others a little rarer than Diamond. Mg/Li should probably be as common as Thorium but this was a quick fix.

As a side-note, if you can cut the MagicBooks ores by at least 50% that'd be a Good Thing IMO :D

    {
      "target": "black",
      "weight": 19,
      "id": "OD:oreThorium"
    },
    {
      "target": "white",
      "weight": 12,
      "id": "OD:oreMagnesium"
    },
    {
      "target": "silver",
      "weight": 12,
      "id": "OD:oreLithium"
    },
    {
      "target": "gray",
      "weight": 16,
      "id": "OD:oreBoron"
    }

**Comment by OrdinatorStouff** [comment]
will be taken care of soon: https://github.com/AllTheMods/ATM-3/issues/346
