### ISSUE TITLE
Quantum Tank Placement  - Client crash - ATM3 4.2

### ISSUE THREAD

**Issue by DaePrice** [AllTheMods/ATM-3#219]
When Placing a quantum tank with creosote in it, my client crashes to desktop. Upon re-log, there is an empty tank placed where the creosote filled one should be, and the creosote filled one is in my inventory, effectively duping the container. This is the following crash report. This is on the ATM3 testing server.

https://pastebin.com/80qaC07t

**Comment by DaePrice** [comment]
Ok, more testing. It is not just the creosote tank, it is empty tanks as well. It does not leave a copy every time either. I am placing them on this wall. where the tank is at now, is where I have been trying to place it. It might be the proximity to the RS connector

**Comment by mrdeadlocked** [comment]
I have the same issue. All of my quantum tanks also no longer show their contents.

https://pastebin.com/ck93Y9v0

**Comment by DaePrice** [comment]
Yeah, I after crashing about 9 times to test, I can say it is all Quantum tank placement for me, full, empty, newly crafted, they all crash my client. Also, they do not connect to Refined Storage. The existing tanks do: ones connected before the 4.2 update. new tanks however do not connect to RS. They DO connect to other mods (xnet specifically is a yes) once they are placed.

**Comment by OrdinatorStouff** [comment]
Related:
https://github.com/gigabit101/QuantumStorage/issues/114
https://github.com/gigabit101/QuantumStorage/issues/112
https://github.com/gigabit101/QuantumStorage/issues/110

**Comment by OrdinatorStouff** [comment]
should be fixed in mod updates. open new issue if problems come up in pack ver 5.0+
