### ISSUE TITLE
Visual Bug when opening the Drawer GUI

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#22]
Storage Drawer version: 1.12-5.2.8
Forge version: 2406

When you open the Drawer GUI it doesn't show u the items properly.

![](https://puu.sh/wH2sa/1ca5a83299.jpg)

**Comment by OrdinatorStouff** [comment]
seems to have been fixed already by latest version
![image](https://user-images.githubusercontent.com/6283913/30015655-78227eb6-9106-11e7-9ca1-c116b33bd58d.png)
