### ISSUE TITLE
Yellorium Seeds in mystic ag are not craftable.

### ISSUE THREAD

**Issue by DaePrice** [AllTheMods/ATM-3#220]
Not sure if this is on purpose or not. Yellorium Seeds in mystic ag have no recipe.

**Comment by ffgda** [comment]
You get Yellorium instead of Uranium from Uranium essence.
IC2 Uranium seems to be disabled (not Uranium 238 though). Don't know why they disabled the Yellorium seeds and not the Uranium seeds to make it less confusing, but that's how it is.

**Comment by Boomflex** [comment]
Uranium works in place of Yellorium in all recipes and usage.

This is intended behaviour.
