### ISSUE TITLE
[4.2] Compressed Cobblestone can't be un-compressed

### ISSUE THREAD

**Issue by seattleda** [AllTheMods/ATM-3#222]
In 4.1 was able to compress and decompress cobble.  Now, not so much.  Is this intended?

**Comment by ouroborus** [comment]
https://github.com/AllTheMods/ATM-3/issues/209

**Comment by OrdinatorStouff** [comment]
This should be unrelated to the compressed blocks from Overloaded since ExtraUtil2 should be the only mod with compressed cobblestone -- will need to investigate

**Comment by seattleda** [comment]
Looks like this has been fixed in 4.3 👍

**Comment by Boomflex** [comment]
No longer an issue as of v4.3
