### ISSUE TITLE
Possible Compatibility Issues w/RFTools Shape Builder

### ISSUE THREAD

**Issue by pinkphoenix1990** [AllTheMods/ATM-3#223]
**ISSUE**

The server will crash immediately upon opening the GUI of the 'Shape Tool' for the @RFTools Builder machine.

**DESCRIPTION**

I cleared out a chunk of the landscape with the builder, and I then started playing around with the actual building options of the machine. Using the 'Shape' attachment for the machine, I selected *hollow* and *top dome*. Unfortunately, that was  not quite the design I was looking for... so I continued to cycle through the shape options. The server immediately crashed upon seeing the option 'scan' pop on the selection area. Returning, once the server automatically restarts, I tried to open the Shape Tool's GUI once more and, again, it crashed the server. I tested this on a personal single player world and the results were the same.

**CONSOLE OUTPUT**

`16.10 13:45:36 [Server] Server thread/ERROR [FML]: Index: 16 Listeners:
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 0: NORMAL
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 1: ASM: class vazkii.botania.common.core.handler.CommonTickHandler onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 2: ASM: class flaxbeard.immersivepetroleum.common.EventHandler handleLubricatingMachinesServer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 3: ASM: com.minecolonies.coremod.event.FMLEventHandler@4ab085fc onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 4: ASM: it.zerono.mods.zerocore.internal.common.MultiblockEventHandler@1a13d0d onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 5: ASM: vazkii.quark.automation.feature.PistonsMoveTEs@6a76b9cb onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 6: ASM: ic2.core.TickHandler@7de44777 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 7: ASM: ic2.core.energy.grid.EventHandler@432acafd onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 8: ASM: forestry.greenhouse.multiblock.blocks.ChunkEvents@76bb0428 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 9: ASM: vazkii.botania.common.item.ItemGrassSeeds@6cfd5f37 onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 10: ASM: vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraAxe@3c9a0d9a onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:36 [Server] Server thread/ERROR [FML]: 11: ASM: cofh.cofhworld.init.WorldTickHandler@2d57e6e4 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
16.10 13:45:37 [Multicraft] Skipped 67 lines due to rate limit (30/s)
`

**FURTHER TESTING**
It appears that the combination of 'Hollow' and 'Scan' are the issue here, since it will easily slide past the 'Scan' option if 'Solid' is selected. I am not sure if this is an error of the mod, specifically (*I will be notifying the mod developers as well, if I can find an issue tracker for them*), but the console output did throw a lot of different mod-names out there.

Thank you for your hard work in bringing us these amazing ModPacks!

**Comment by ouroborus** [comment]
@pinkphoenix1990  https://github.com/McJty/RFTools/issues

**Comment by OrdinatorStouff** [comment]
please let us know if this is still a problem at all in pack ver 5.0+
