### ISSUE TITLE
Gendustry: Ease of Life: Genetic Templates and Gene Samples not smeltable in Mek Smelter

### ISSUE THREAD

**Issue by djcosmic2** [AllTheMods/ATM-3#225]
Genetic Templates and Gene Samples are supposed to be smeltable to reuse old unwanted templates/samples - but they wont smelt in a mek smelter. they do work in vanilla furnace. havent tested other furni

**Comment by GolemDragon** [comment]
The Extra Utilities 2 Furnace works however it has a bug in which you have a blank sample in both the input and output after you smelt one... basically giving you duplicate blank gene samples (dupe bug).  when you look at the uses of gene samples you see it is very limited in what can smelt ones... would be nice to see it expanded...

**Comment by OrdinatorStouff** [comment]
going to say this is fine as intended. the forestry squeezer will yield liquid dna even. Might be cool to just have that as an option, but a vanilla furnace being able to reset them (and exu2 is a special snowflake they can do whatever they want) is fine as it is.
