### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by xxsuperdreamxx** [AllTheMods/ATM-3#226]
Hatter234 is not able to log in the server. When she tries to log in she is crashing
https://gist.github.com/xxsuperdreamxx/d120512fb5d0a67a22cafe0f5c78c4c7

**Comment by OrdinatorStouff** [comment]
This ticket is regarding a player issue on out official ATM3 server. It is related to Mekanism/Tinkers crash with hammers and pipes (see: https://github.com/AllTheMods/ATM-3/issues/99). 

I have fixed hatter being able to log in. The crash will happen if you LOOK at a mekanism pipe/cable while holding a Tinker's hammer so I just changed the "active slot" of what item is currently held
