### ISSUE TITLE
IE Steel Rod != Tinkers Steel Rod in Steel Scaffolding Recipe

### ISSUE THREAD

**Issue by LazerusKI** [AllTheMods/ATM-3#229]
Steel Rods are required to build Steel Scaffoldings which are required to build the Metal Press which is required to build the Steel Rods.

While the Recipe shows that you can use Tinkers Steel Rods for the scaffolding instead, this recipe sadly doesnt work.

![s1](https://user-images.githubusercontent.com/1797439/31839791-eb7b266e-b5e2-11e7-8bce-0aa093e2a07f.png)

**Comment by Boomflex** [comment]
Please update to version 4.3

Recipe does work.

![image](https://user-images.githubusercontent.com/22868795/31900443-3f37d1c8-b816-11e7-8da8-7179b98b8bb2.png)
