### ISSUE TITLE
OreDict all ores?

### ISSUE THREAD

**Issue by kolhed** [AllTheMods/ATM-3#23]
Right now we have 7 different copper ore... Not sure all gen in the world, but more then one do...
Same for tin, nickel, silver, lead...

In other packs they have all been able to go in the same barrel/drawer, but now a simple miningtrip will be total chaos :(

Didn't we have some great "make-all-into-one"-mod on ATM2? Is there one such for 1.12?

**Comment by Boomflex** [comment]
This is being worked on now we have the tools to do so.

Will close when update is pushed.

**Comment by kolhed** [comment]
Any idea what will happen?
will all ores magicly turn into the same, or will there be a way to convert them?
specially if I have 15 different drawers with 4 kind of ore in...

**Comment by OrdinatorStouff** [comment]
personal TODO: incorporate `oredict_ores.zs` concept from ATC to ATM3

**Comment by OrdinatorStouff** [comment]
This has been implemented. There's still some small tweaks to be considered (i.e. aluminum oregen and whatnot) but this should be good enough to close

(any oredicted ORE should be able to be crafted into one of a base type by crafting two ores together)
