### ISSUE TITLE
Config Option Request: Refined/Reborn Storage

### ISSUE THREAD

**Issue by Beannsss** [AllTheMods/ATM-3#230]
Hey, Reborn storage adds back the classic AE1 assembler to Refined Storage, however, the blocks take up way too much power to be usable with the current controller. A simple 5x5x5 assembler takes up to around 42k RF/t, and the controller is only able to handle 32k/t. This makes the whole system just flicker on and off even if you do have enough RF production. A full 16x16x16 assembler would use ~ 1.2 million rf/t. Would be nice for the controller (there is a config option) to be able to hold at least that much if not more. The creative controller is able to handle it, but not sure if it's really appropriate to gate use of the machine behind that.

Edit: Of course, I've changed it myself, but would be a healthy change for the pack overall.

Thanks

**Comment by Boomflex** [comment]
Will look in to for future updates.
