### ISSUE TITLE
Crash when extracting starlight from lightwell with Fluiducts using servos.

### ISSUE THREAD

**Issue by Drakefyre27** [AllTheMods/ATM-3#231]
As title says, extracting Astral Sorcery's starlight from a lightwell using a Thermal Dynamic fluiduct with servo crashes the server.

Fluiducts, when attached to a lightwell, do not cause a crash... but adding a servo did.

Crash log:
https://gist.github.com/dmodoomsirius/994e59451304e78be35e6c045fdabc22

**Comment by Doomgull** [comment]
Pack: ATM 4.2
ModVer: AS 1.6.1

**Comment by HellFirePvP** [comment]
Issue got fixed for AS version 1.7 published recently.

**Comment by Boomflex** [comment]
Please update to latest pack version 4.3.
