### ISSUE TITLE
Compressed Dirt

### ISSUE THREAD

**Issue by OuterRealm** [AllTheMods/ATM-3#234]
Dirt only allowed compressing; Decompressing at just compressed dirt doesn't work level 2 does double compressed will decompress to compressed.

**Comment by Boomflex** [comment]
What version of the modpack are you using?

Have you updated to v4.3?

**Comment by Boomflex** [comment]
Works in v4.3

Please update to latest pack.

**Comment by OuterRealm** [comment]
We are on the latest public version.  Also cobble is doing the same thing

**Comment by OrdinatorStouff** [comment]
Did you make sure you updated the scripts folder? Fresh, deleting the old
scripts folder and uploading them from the 4.3 serverfiles zip? If scripts
were skipped or not done correctly this wouldn't be fixed for you yet.

**Comment by OuterRealm** [comment]
I will give it a try

**Comment by OrdinatorStouff** [comment]
We provide a "simplified" packmode that reverts the intended, "normal"
changes to recipes such as extreme reactors. If you change packmode.cfg to
"simplified" and restart the server, any of the balance and flavor and
challenge that we intended for the pack will be reverted to a simplified
basic bland flavorless version of the pack. NOTE: any clients connecting to
the server as well will also need to change their packmode.cfg to match AND
the server and any clients must be fully restarted after saving the config
file (unfortunately it is not possible to "hot swap" recipes anymore like
in ~1.7 minecraft)
