### ISSUE TITLE
Void miner tier 4

### ISSUE THREAD

**Issue by Hatter243** [AllTheMods/ATM-3#238]
I went to place over a stack of structure blocks tier 4 on a tier 4 void miner with the assembly wand and they all disappeared. Relogged and they were just all gone. Real shame. Something to look into?

**Comment by Hatter243** [comment]
It may have actually placed them under bedrock but I cant check. I forgot to move the void miner block into the air

**Comment by Boomflex** [comment]
@Hatter243 Is it your single player save? What version of the mod pack?

**Comment by Hatter243** [comment]
No, this was on the offical server for ATM3. So the current version? This happened last night.

**Comment by Boomflex** [comment]
Non reproducible.

Will keep an eye out for it happening.
