### ISSUE TITLE
Actually Additions worms keep vanishing

### ISSUE THREAD

**Issue by kythorn** [AllTheMods/ATM-3#239]
On a server I personally host, using version 4.3 of the pack, my actually additions worms that I use to maintain my farmland keep vanishing without a trace. 

The area is chunkloaded. This has never happened while I'm online, and I have found nothing in any log output to indicate what's going on.

**Comment by OrdinatorStouff** [comment]
Worms are configured to expire/die after 24 real-world hours. If your base
is chunkloaded and server always-on that would explain it.

This is intended.

For your own server if you'd like to change it you could edit the actually
additions config file and set the worms tick duration back to 0.

**Comment by OrdinatorStouff** [comment]
Self Todo: add JEI tooltip to worms with CraftTweaker saying they are
configured to expire

**Comment by kythorn** [comment]
Thanks, much appreciated!
