### ISSUE TITLE
Moving wand on colossal chests clears inventory

### ISSUE THREAD

**Issue by doritobob269** [AllTheMods/ATM-3#24]
Moving wands delete all contents of colossal chests if any block is picked up with a moving wand. This not only includes the chest core (which holds all the chests contents), but also any other part of the colossal chest once it's been created. There is a config option for the moving wand, so if all the colossal chest blocks could be added, that'd be great!

**Comment by oly2o6** [comment]
This is a known issue with anything like a moving wand, or sack of holding from cyclic, do not use them on colossal chests or RS drive bays as it will wipe its containers, its not really a bug in the mod as they do not expect you to pick it up and move it, but still a major issue that isn't fixed right now unfortunately, maybe check colossal chests GitHub? see if they have a fix for it or know about it? if not report it, much appreciated, thank you

**Comment by OrdinatorStouff** [comment]
Confirmed "issue"

From the pack side, I added colossal chest stuff to moving wand blacklist but not sure if it'll actually prevent, and besides, like @oly2o6 said there are other mods that can move blocks as well and can't all be blacklisted (cyclic sack doesn't seem to have a blacklist option) so this is an interaction that can't quite be truly prevented
