### ISSUE TITLE
Tech Reborn missing recipe for carbon plate

### ISSUE THREAD

**Issue by loginator** [AllTheMods/ATM-3#240]
Hey,
first of all thank you guys for the work on the modpack :)
I think I found an issue:
I'm not able to craft the tech reborn carbon plates since the compressor is missing (There's also no recipe fpor the carbon plate in JEI).
Regards, loginator

**Comment by OrdinatorStouff** [comment]
Ic2 compressed carbon plate things are supposed to work for anything you'd
need the TR ones for. Can you check that? If not let us know what it is you
need TR plate for that ic2 plate isn't working as substitute.

**Comment by loginator** [comment]
IC2 would work it just feels odd to make machines that are using EU to create stuff for the Extreme Reactors mod to create RF ;).
I used crafting tweaks on my server and added new recipes and used carbon plates from Mekanism.
Would be cool if you'd add another recipe too so you're not depending on IC2 only.
Thank you for the fast reply :)
Regards,
loginator

**Comment by Boomflex** [comment]
Works as intended.
