### ISSUE TITLE
Major Stuttering at random

### ISSUE THREAD

**Issue by ThatBenderGuy** [AllTheMods/ATM-3#241]
Occasionally during gameplay I get times where after every 3-5 seconds the game just freezes for 2-3 seconds then repeats this for a while. It randomly comes and goes. Is it something I should allocate more memory to within the launch arguments? I have 16GB of ram so I should be able to configure it higher (It currently uses something like 2.7GB) 

Hardware:
CPU: Intel Core i3 2120 @ 3.30GHz 
GPU: NVIDIA GeForce GTX 650 Ti BOOST (2047MB)

**Comment by Boomflex** [comment]
How much RAM are you actually allocating?

**Comment by ThatBenderGuy** [comment]
It's set to these JVM arguments
-Xmx3072m -Xms256m -XX:PermSize=256m

**Comment by Boomflex** [comment]
I would recommend to use a MINIMUM of 5GB.
