### ISSUE TITLE
Journeymap fullscreen map displaying overworld map in mining dimension

### ISSUE THREAD

**Issue by kythorn** [AllTheMods/ATM-3#242]
Pack Version 4.3

Issue: Journeymap's fullscreen map displays the overworld map in Aroma's mining dimension. The minimap  however displays the right dimension. I can't seem to find a way to get it to toggle.

**Comment by kythorn** [comment]
I updated to version 4.4 of the pack and the issue went away.

**Comment by OrdinatorStouff** [comment]
thanks for the follow up letting us know it's good~
