### ISSUE TITLE
Flux Anodizers Augment and Aluminum Ore don't match.

### ISSUE THREAD

**Issue by Gorden211** [AllTheMods/ATM-3#243]
As stated by the title, when using the Thermal Expansion Flux Anodizers Augment in a Thermal Expansion Redstone Furnace for fast ore doubling the Redstone Furnace does not accept Thermal Foundation Aluminum Ore, maybe because it is not recognized as ore.
Bauxite Ore is also not accepted and Osmium isn't accepted as well.

Not sure if TE issue or pack issue so I posted it here.

**Comment by Boomflex** [comment]
Sounds very much like a Thermal issue, please post there.

3rd party issue.
