### ISSUE TITLE
(ATM3 4.4 Simplified) Certain ingot dusts require Redstone Furnace to smelt.

### ISSUE THREAD

**Issue by Horras64** [AllTheMods/ATM-3#246]
Many dusts require a Redstone Furnace in order to smelt into their ingot. Even after processing with Mekanism since JAOPCA is installed, this is still the case for certain ores. e.g. Pulverized Aluminium, Pulverized Iridium, Lithium Dust (IC2), Magnesium Dust, Pulverized Mana Infused Metal, Crushed Uranium Ore. This is also the case for Steel Blend, I have found even when you make it via Mekanism.

**Comment by xenoflot** [comment]
Adding a little to this one:

I set up a Mekanism 5x ore processing system today and found a few ores that can't make it all the way through.

* Early processing of Yellorium and Uranium ores are turned into JAOPCA materials until they hit the Mek Crusher. The Mek Crusher turns the Yellorium Clumps into IC2 Crushed Uranium Ore which can't be processed by the Enrichment chamber.
* NuclearCraft magnesium becomes Tech Reborn Magnesium Dust in the Enrichment Chamber but can't be smelted by the Energized Smelter
* NuclearCraft Lithium becomes IC2 Lithium dust in the Enrichment Chamber but can't be smelted by the Energized Smelter
* Thermal Foundation Pulv Aluminium can't be smelted by the Energized Smelter
* Thermal Foundation Pulv Mana-Infused can't be smelted by the Energized Smelter

**Comment by OrdinatorStouff** [comment]
possible dupe/overlap with https://github.com/AllTheMods/ATM-3/issues/296 -- forcibly add smelting options to multiple machines. Closing this ticket with the reference there
