### ISSUE TITLE
ATM 3 4.4 crashes with Forge ver  14.23.0.2528 client

### ISSUE THREAD

**Issue by chrisisonwildcode** [AllTheMods/ATM-3#247]
Crashes on client when attempting to start with Forge version  14.23.0.252. Server appears to run fine but due to client crash am unable to connect to confirm that server remains fine.

See Attached:
[fml-client-latest.log](https://github.com/AllTheMods/ATM-3/files/1433824/fml-client-latest.log)
[crash-2017-11-01_11.57.00-client.txt](https://github.com/AllTheMods/ATM-3/files/1433828/crash-2017-11-01_11.57.00-client.txt)

**Comment by Boomflex** [comment]
All the Mods 3 v4.4 is to be ran on Forge v14.23.0.2517.
