### ISSUE TITLE
Excavate Modifier/Enchantment broken on version 4.4

### ISSUE THREAD

**Issue by 123zane321** [AllTheMods/ATM-3#248]
Updated to version 4.4 of ATM3, and the Excavate modifier (I've got it stacked 25x, the maximum) doesn't work for me or anyone else I know anymore. Neither does the Excavate enchantment. I don't even get the message saying that I need a tool with the appropriate modifier/enchantment when I try and excavate a block without the right gear. I can change the area that I should be able to excavate with the appropriate keybind, though.

- I've tested multiple different tools
- I've tested both the TiCon modifier and the enchantment
- I've tested in both singleplayer and on a server
- I've tried changing the keybinds for ore excavating

**Comment by Boomflex** [comment]
Fixed in update v4.5 coming soon.
