### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by GrantK108** [AllTheMods/ATM-3#249]
if you get a immersive engineeing book. dont have it open for too long or it will crash your game'

**Comment by OrdinatorStouff** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2225

The IE book doesn't work with the 3-year old version of Java that Minecraft
launcher ships with by default. If you install latest Java manually and
tell Twitch or whatever launcher you're using to use the new version and
not the bundled version it should no longer crash.

**Comment by Boomflex** [comment]
Update your Java to latest and try again.
