### ISSUE TITLE
Immersive Engineering Insulating Glass bug

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#25]
IE version: 0.12-66
Forge version: 2406

Unable to craft the insulating glass.

![ss 2017-07-11 at 09 23 34](https://user-images.githubusercontent.com/20716525/28086502-8b190eec-667f-11e7-844c-63dbc023b925.png)

**Comment by OrdinatorStouff** [comment]
Seems working now in normal crafting table even with various oredict ingredients
![image](https://user-images.githubusercontent.com/6283913/30033253-1f5b2050-914f-11e7-9669-fe1c533a3052.png)

**Comment by wsadev01** [comment]
Hi, I am really sorry to add this comment, but I am having the same problem!

Minecraft: 1.19.4 
Immersive Engineering version: 1.19.4-9.4.1-168
Forge: 45.2.6

If it is useful for something, I am also using Chisel and bits 1.3.137 & Scena 1.0.100

## Screenshots
![image](https://github.com/AllTheMods/ATM-3/assets/57674086/d77aff0d-5290-4913-9d5a-f0299ba678e4)
![image](https://github.com/AllTheMods/ATM-3/assets/57674086/2a557392-4802-468c-ba27-8305d3749227)
