### ISSUE TITLE
ATM3 v4.4 CRASH

### ISSUE THREAD

**Issue by ConnCraft** [AllTheMods/ATM-3#250]
ATM3 v4.4 suddenly crashes on startup. It crashed the whole computer once and only the launcher twice. 

Win10 BSOD said it attempted to write to read-only memory, but that shouldn't have crashed. Here are the two launcher crash reports. Please get on this soon.

https://pastebin.com/g7N0uHhR

https://pastebin.com/kvJg1R6J

Pastes will expire in 1 month. Hopefully it doesn't take that long to fix.

**Comment by OrdinatorStouff** [comment]
The BSOD is concerning, and likely an indication of something else going on with your PC in general perhaps. Maybe try running a mem test on startup and make sure there's not an obvious hardware problem perhaps.

Both of those crash logs however are pointing at ContentTweaker maybe not liking the config file. Can you try a fresh/new install/profile and see if that will launch for you? It could be that mods/configs didn't update fully

**Comment by Boomflex** [comment]
Update to v4.5
