### ISSUE TITLE
CTD Tesselating block model

### ISSUE THREAD

**Issue by xenoflot** [AllTheMods/ATM-3#251]
I'm running a manually updated 4.4 (Linux and the Technic version of the pack is still at 4.0) which has been working fine thus far. I logged out to take a break and when I tried to come back in, the game explodes with a tesselating block model error. Forge 2517 in case it's different from the official 4.4.

I was able to log in with a 2nd account, destroy the offending block and log back in with my main.

The interesting bit:

Description: Tesselating block model 
java.lang.NullPointerException: Tesselating block model
-- Block model being tesselated -- Details: Block: mekanism:transmitter[tier=elite,type=universal_cable] 
Block location: World: (-455,72,-922), Chunk: (at 9,4,6 in -29,-58; contains blocks -464,0,-928 to -449,255,-913), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)

The full log:

https://zerobin.net/?40ebe0c1b3ab5521#3PFZrucdwIVjMw6ie7CQQUii8ySWzpzkTzuYZq7NASA=

---

Oddly enough I had a similar error, "Tessellating CCL block in world" a couple of days ago and a TE Resonant Duct was the culprit. Perhaps it's just coincidence that the location of the offending TE duct was (-455,71,-921)

**Comment by OrdinatorStouff** [comment]
No idea why this went untouched for so long, I apologize about that. Considering the age however, this is no longer viable to troubleshoot. If you have this problem or something similar still **on the current / recent version of the pack**, feel free to create a new report and log and we'll look more into it.
