### ISSUE TITLE
Crash to desktop when placing Mekanism Solar Generator into Tinker's Construct Crafting Station

### ISSUE THREAD

**Issue by Alphanos** [AllTheMods/ATM-3#253]
Good evening,

I have been doing some testing regarding this bug, and I have isolated the details required to cause it or prevent it.  I have also reported this to Mekanism, but it looks like it may possibly be a Forge bug?  I am hoping one of you will better understand how this should be best addressed.  My report to Mekanism can be found here: [https://github.com/aidancbrady/Mekanism/issues/4798](https://github.com/aidancbrady/Mekanism/issues/4798).

The most relevant info is from my last post of my findings on that issue page, quoted below:

> With some additional testing, I have isolated the cause of the crash to a Forge config file setting that All the Mods 3 edits from the default value. I will list the steps to reproduce below, and then report the issue to All the Mods 3. I do not have sufficient understanding of the implications of this setting to be able to tell whether this should be reported to Forge. If this should be reported as a bug to Forge, hopefully either you or the All the Mods 3 pack maintainer will know how this should be done.
> 
> Steps to replicate the crash:
> 
>     1) Using the Twitch launcher, create a new custom profile with Minecraft 1.12.2 and Forge 2529 (latest at the time of writing).
>     2) Add Tinker's Construct, which will add Mantle as a dependency.
>     3) Since the most recent Mekanism release has not yet been marked for 1.12.2, manually copy in Mekanism-1.12.1-9.4.1.326.jar, MekanismGenerators-1.12.1-9.4.1.326.jar, and MekanismTools-1.12.1-9.4.1.326.jar into the mods folder of your new profile.
>     4) Launch the game and create a new single player creative world.
>     5) Get a Tinker's Construct Crafting Station and some Mekanism Solar Generators.
>     6) Repeatedly place the Solar Generators into the Tinker's Construct Crafting Station and remove them again. You will observe no crash. Exit the game.
>     7) Edit config/forge.cfg. Set value B:alwaysSetupTerrainOffThread to true instead of the default, which is false.
>     8) Restart the game and repeat step 6 in your test world. Within a few attempts of placing and removing the Solar Generators into and out of the crafting grid in the Crafting Station, the game should crash to desktop.
> 
> Workaround: In config/forge.cfg, set value B:alwaysSetupTerrainOffThread to the default setting, which is false.
> 
> The description of the setting involved reads as follows:
> 
> `# Enable forge to queue all chunk updates to the Chunk Update thread. May increase FPS significantly, but may also cause weird rendering lag. Not recommended for computers without a significant number of cores available.
> 
> Thank you!

Although the steps to replicate are written from the perspective of testing in a new clean profile, All the Mods 3 sets this problematic config setting already, so most likely any up to date instance of All the Mods 3 should be able to replicate the crash simply by inserting and removing the Solar Generators into and from the Crafting Station.

I hope this helps!

**Comment by Yoosk** [comment]
As far as i know, anything from mek in crafting station crashes the game.

**Comment by OrdinatorStouff** [comment]
This could possibly be a breakthrough in this long-standing bug that Tinkers and Mek has been having. Tinker's tables "render" items in world and the Mek items often cause this crash. I have heard that both Tinker's and Mek devs have tried finding/fixing this to no luck. The link to alwaysSetupTerrainOffThread could be a new clue.

For NOW, the response we have at a pack level is "Don't craft anything Mek related in Tinker's tables or put them on drying racks/etc" If you are crashing in an existing world you can also edit tinker's construct to disable rendering items in world to at least get back in (and can be done client side only)

As for the `B:alwaysSetupTerrainOffThread=true` I don't want to change that to False since it has been shown to often cause significant FPS boosts and as far as I know this one Tinker's/Mek thing is only a niche collateral bug.

**Comment by lalleman44** [comment]
same problem here :(

**Comment by Boomflex** [comment]
Mod conflict.

Not fixable by modpack.

**Comment by Alphanos** [comment]
> Not fixable by modpack.

To be more precise, this can be fixed on a pack level by reverting to the Forge-default config setting for B:alwaysSetupTerrainOffThread.  However, it sounds like this could cause performance/FPS issues for a larger number of people than those who are experiencing this crash.  Hopefully the developers involved can find and fix the root cause of this crash.

**Comment by Boomflex** [comment]
Causing majo FPS drop for the majority of a user base is not a fix. It’s a very bad bandaid at best.

**Comment by Skar78** [comment]
Ok - issue still alive and well in 5.9.3b :)
