### ISSUE TITLE
[ATM3 4.4] Timing out from server when Astral Sorcery tries to sync

### ISSUE THREAD

**Issue by jarquafelmu** [AllTheMods/ATM-3#255]
This is something that just started happening the last couple of days. I log into the server and I will time out and be kicked off within a few moments of loading the terrain. I know when I am going to be kicked because WAILA doesn't give me information on the block I'm looking at.

I looked at my server's console and it consistently seems to happen when Astral Sorcery tries to synchronize its configuration with me.

I have tried restarting my router, the server and reinstalling my client but nothing has worked. I even tried increasing the Java timeout from 30 seconds to 60 seconds.

I am not 100% certain that it is Astral Sorcery causing the issue, it's just thing that is always the last to output before I get kicked off. Sometimes it doesn't say I was timed out, sometimes it says that my connection was closed by the remote host.

Any thoughts on what I can try next?

**Comment by OrdinatorStouff** [comment]
Did you increase the timeout on both server and client? If you only add the arg to one side and not the other it will have no effect.

I usually go straight for recommending 90 seconds, and I've had people report some success with better initial connection rates with some tweaked client JVM args for tuning GC a little bit. 

I too am not sure if the Astral Sorcery part is anecdotal or possibly related. You could try backing up the world and entire server and re-starting it without Astral Sorcery and observe if it behaves any different (just for testing)

**Comment by jarquafelmu** [comment]
Thank you @OrdinatorStouff for your suggestions. 

I had tried increasing the timeout the server and my client but it wasn't helping. Perhaps my timeout command was incorrect. Could you please send me the command that you use?

I tried wiping my minecraft client as well as the server and reinstalling using the latest version of forge (v.2531). I restored the world file and the server launched without trouble but I am having CTD trying to launch my client now so I have circle back around to see what went wrong.

Restarting the server without astral sorcery is a good idea to test and I will try that if the increased timeout doesn't help.

Thanks again for your help

**Comment by OrdinatorStouff** [comment]
To change the connection timeout window you have to add a JVM launch argument to both the server as well as your client. Clientside is easy enough to change in Twitch (or whatever launcher you use) settings but depending on how your server is hosted you might need to contact support if it's a hosting company if you aren't provided a way to modify/add JVM args through your control panel. 

Timeout JVM arg (setting it to 90 seconds):
**`-Dfml.readTimeout=90`**

An example of many other JVM args that also tweak memory usage and also includes the increased timeout:
`-server -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m   -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3  -Dfml.queryResult=confirm -Dfml.readTimeout=90`

After adding the Dfml.readTimeout JVM arg to both server and client, both would need to be restarted for it to take effect

**Comment by jarquafelmu** [comment]
Thanks again for helping me. Updating to v4.5 and using the read timeout command has allowed me to get back on my server

**Comment by OrdinatorStouff** [comment]
Glad to hear it's good now... cheers!
