### ISSUE TITLE
Unable to move in certain chunks.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#26]
Pack version: 1.5
Forge version: 2406

U sometimes get stuck in random chunks and your minimap disappears.
When u teleport somewhere your game starts to spazz out and still stuck u, a relog fixes it but when u go back to where u originally got stuck it happens again.

**Comment by OrdinatorStouff** [comment]
I've witnessed this as well but have yet to find a consistent cause/reason for it. Going to leave this issue open and hopefully get feedback if anyone is still experiencing this in most recent versions

**Comment by whatthedrunk** [comment]
Going to assume this is fixed now. Please reopen if you have any new information. Thanks!
