### ISSUE TITLE
Can't craft Sound Muffler

### ISSUE THREAD

**Issue by notacompletemoron** [AllTheMods/ATM-3#261]
Server 4.5

Cannot craft sound muffler in at least TC crafting table and player crafting grid.

**Comment by Boomflex** [comment]
Reported to the correct github: https://github.com/rwtema/extrautilities/issues/1747

**Comment by notacompletemoron** [comment]
This is turning out to be a Forge issue.

**Comment by PapiDimmi** [comment]
This is an issue with Forge 14.23.0.2532.

To fix this, downgrade to Forge 14.23.0.2531 (or just update to ATM 3 v. 4.5b).
