### ISSUE TITLE
Tinker's Construct Crafting Blocks missing in JEI

### ISSUE THREAD

**Issue by Gorden211** [AllTheMods/ATM-3#263]
All of Tinker's crafting blocks except for the Tool Forge are missing in JEI search. If you however look at the uses for necessary items you can find the recipe, but not via search in JEI.
See in the screenshots at the example of the Stencil Table.
![2017-11-10_02 23 50](https://user-images.githubusercontent.com/25781557/32638200-74798344-c5be-11e7-9255-795fc7006ea2.png)
![2017-11-10_02 25 26](https://user-images.githubusercontent.com/25781557/32638201-764d0448-c5be-11e7-999d-082cd6b4f84b.png)

**Comment by OrdinatorStouff** [comment]
This is a known thing in JEI hiding items automatically when there's hundreds of "variants" of them.
https://github.com/mezz/JustEnoughItems/issues/923

What I didn't realize until now, is there there is a tinker's config option that we can enable that SHOULD show just "one" of each bench and therefore no longer be hidden by JEI. We will investigate this as possible fix.

**Comment by OrdinatorStouff** [comment]
should be fixed (showing in JEI) as of pack ver 5.0+
