### ISSUE TITLE
Allthemods 3 v.4.5, frozen ocean biome not generating.

### ISSUE THREAD

**Issue by graycatgrayhat** [AllTheMods/ATM-3#265]
Allthemods 3 v.4.5, frozen ocean biome not generating under the following world generation settings.

{"landScheme":"continents",
"tempScheme":"latitude",
"rainScheme":"random",
"biomeSize":"huge",
"amplitude":1.0,
"generateBopOre":true,
"generateBopSoils":true,
"generateBopTrees":true,
"generateBopGrasses":true,
"generateBopFoliage":true,
"generateBopFlowers":true,
"generateBopPlants":true,
"generateBopWaterPlants":true,
"generateBopMushrooms":true,
"generateRockFormations":true,
"generatePoisonIvy":true,
"generateBerryBushes":true,
"generateThorns":true,
"generateQuicksand":true,
"generateLiquidPoison":true,
"generateHotSprings":true,
"generateNetherHives":true,
"generateEndFeatures":true,
"mainNoiseScaleX":80.0,
"mainNoiseScaleY":160.0,
"mainNoiseScaleZ":80.0,
"coordinateScale":684.412,
"heightScale":684.412
,"upperLimitScale":512.0,
"lowerLimitScale":512.0}

Searched in the configs folder, under biomes and did not find any toggle setting.

**Comment by OrdinatorStouff** [comment]
sorry for lack of response earlier, if this is still happening in 5.6+ please let us know in a new ticket
