### ISSUE TITLE
[ATM3 v4.5] Industrialcraft2  and mekanism console spam server

### ISSUE THREAD

**Issue by wenest** [AllTheMods/ATM-3#266]
hello,

ic2 is spamming my console with the following text. I Whas looking throuth the config file`s but i cant find a sollusion.

11.11 09:02:52 [Server] ic2-poolthread-2/WARN [ic2.EnergyNet]: Tile mekanism.generators.common.tile.TileEntityAdvancedSolarGenerator@3383240d (dim 0: -406/67/-731) removal without registration
11.11 09:02:52 [Server] ic2-poolthread-2/WARN [ic2.EnergyNet]: Tile mekanism.generators.common.tile.TileEntityAdvancedSolarGenerator@480c5c42 (dim 0: -406/67/-735) removal without registration
11.11 09:03:29 [Server] ic2-poolthread-2/WARN [ic2.EnergyNet]: Tile mekanism.generators.common.tile.TileEntityAdvancedSolarGenerator@27a345e (dim 0: -406/67/-731) removal without registration
11.11 09:03:29 [Server] ic2-poolthread-2/WARN [ic2.EnergyNet]: Tile mekanism.generators.common.tile.TileEntityAdvancedSolarGenerator@3d668f7b (dim 0: -406/67/-735) removal without registration
11.11 09:03:29 [Server] ic2-poolthread-2/WARN [ic2.EnergyNet]: Tile mekanism.generators.common.tile.TileEntityAdvancedSolarGenerator@27a345e (dim 0: -406/67/-731) removal without registration
11.11 09:03:29 [Server] ic2-poolthread-2/WARN [ic2.EnergyNet]: Tile mekanism.generators.common.tile.TileEntityAdvancedSolarGenerator@3d668f7b (dim 0: -406/67/-735) removal without registration

I'm looking forward to hearing from you

[Config.zip](https://github.com/AllTheMods/ATM-3/files/1463562/Config.zip)

**Comment by Boomflex** [comment]
Always been an issue.

Both Devs are aware.

Nothing a pack author can do.
