### ISSUE TITLE
[atm3 v4.5] Industrialcraft 2 basic machine casing crafting bug?

### ISSUE THREAD

**Issue by wenest** [AllTheMods/ATM-3#267]
when i place for example 1 cobblestone in the crafting grid ill get a machine frame from ic2.
this also happens with dirt or other blocks.  see the printscreen for example.
is use all the default configs that are deliverd by the modpack.
this is on a server if that makes a diverent

http://prntscr.com/h95miq

**Comment by wenest** [comment]
Can this also give problems with "me glass cable -flux" i cant craft them i tryed alot of things. i can see them in a me crafting terminal but cant grab them out of there

**Comment by ouroborus** [comment]
@wenest 4.5b was released to roll back Forge to a slightly earlier version to fix the glass cable issue. Maybe it was also causing your IC2 issue. Update and try again.

**Comment by wenest** [comment]
i downgraded the server to a lower forge build and that fixed it.

**Comment by OrdinatorStouff** [comment]
closing this as we're not making sure to ship the pack with a non-offending forge build in later versions
