### ISSUE TITLE
[ATM 3 4.5] - Unable to craft ME Cable

### ISSUE THREAD

**Issue by eliminat** [AllTheMods/ATM-3#268]
When I follow the recipe to make ME cable, it shows the output, but will not let me grab it or map it on a pattern.
Had another player on the server try as well, same result.
Did not have this issue with 4.4

**Comment by djnifos** [comment]
Same, with covered cable, except I cannot see the output in an ME terminal, it shows it's the recipe, but will not craft.

**Comment by jarquafelmu** [comment]
In addition to this, patterns that use wool, like the covered cable or the fuzzy card are also invalid now.

**Comment by Boomflex** [comment]
Duplicate Bug.

Check other Issues before posting.
