### ISSUE TITLE
Man-portable f* everything in a 15 chunk radius

### ISSUE THREAD

**Issue by ouroborus** [AllTheMods/ATM-3#269]
So it turns out the cardboard box can be used on a chaos crystal.

When a chaos crystal is removed from the world, its blast sequence starts. If the chunk that the crystal is in becomes unloaded, it resets and starts again when the chunk reloads. If you box the crystal and leave the area (cause the chunk to unload), you can place the crystal somewhere else. Breaking the newly placed crystal (or boxing it again) starts a detonation sequence at the new location.

It's important that the original chunk doesn't load in the meantime. If an explosion tied that particular crystal gets to the destruction stage, opening the box just instakills you and, probably, everything in the area.

Fun Fact: The destruction wave ignores things like bedrock being unbreakable and chunk ownership permissions.

**Comment by OrdinatorStouff** [comment]
realistically the cardboard box should have built-in blacklist for that crystal but at a pack level at least add it to the box blacklist.

ALSO we should probably tweak the recipe for the cardboard box and cyclic sack of holding to be similar to the moving wand.

**Comment by ouroborus** [comment]
I would say increase the difficulty of the recipes but either make them a bit easier than the wand or add them to the chest loot lists.

**Comment by ogradyjd** [comment]
First, this sounds AWESOME!   "Hi best buddy!  I have a gift for you!  What's in the cardboard box?   It's a surprise.  Don't open it until you get to your base."

Second, you might want to test this with the Cyclic Back of Holding.  The same issue might apply.

**Comment by OrdinatorStouff** [comment]
looks like DE has already patched this. I was testing tonight to work into the update and it seems YOURE the one that gets the special surprise now.

I'll leave it as it is handled by DE but if anyone can find a workaround to make the explosion happen again somewhere else let me know and we'll see about patching THAT out but for now cardboard box, even admin/creative mode "pick block" and placing it causes it
