### ISSUE TITLE
Cannot craft Metal Press Mold: Wire/Plate/Gear/Rod

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#27]
IE version: 0.12-66
Forge version: 2406

![ss 2017-07-12 at 02 25 33](https://user-images.githubusercontent.com/20716525/28096514-b4fc91c8-66a9-11e7-92b4-9b10da047aac.png)

Cannot craft it with those items, haven't tested other plates.

**Comment by whatthedrunk** [comment]
Working now on version 2.2 that will be out soon.
