### ISSUE TITLE
[ATM3 v4.5] Minecolony Farmers getting extra Mystical Agriculture seeds, even with default configs.

### ISSUE THREAD

**Issue by Schadrach** [AllTheMods/ATM-3#270]
Exactly what the title says -- if you set up a Minecolony farm to grow Mystical Agriculture seeds (for example inferium seeds), the farm produces more seeds with every harvest, despite the default configs for the pack disabling extra seeds for MA crops.

**Comment by OrdinatorStouff** [comment]
Mystical Ag seeds are "special" and need "special" code in any mod that is farming them. If this is still happening "wrong" in 5.6+ please open an issue with Minecolonies devs for specific minecolonies support
