### ISSUE TITLE
[All the Mods 3, 4.5b] Game freezes when exiting the world and entering the world (or another world)

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-3#271]
If I leave the world and re-enter it or enter another world, my client freezes. There’s nothing of significance in the log.

By freezing, I mean that it stops at “Loading world” and stays like that seemingly forever.

**Comment by LC14199** [comment]
When the game hangs like this, it's only ever happened to me when moving from a multiplayer server to an SSP world. Try making the game hang again, then force the process to close in the task manager. Post the errors logged in the Game Output screen of the client. If this is the error I'm thinking of, there should be a reference to a Search Tree function in the Game Output.

**Comment by PapiDimmi** [comment]
Log: https://pastebin.com/raw/VFUVa3q9

**Comment by LC14199** [comment]
This is not the error I was thinking of sadly. Hopefully someone else can shed some light on what's going on.

**Comment by PapiDimmi** [comment]
I assume this is what froze my game:

_[Server thread/FATAL]: The ForgeModLoader state engine has become corrupted. Probably, a state was missed by and invalid modification to a base classForgeModLoader depends on. This is a critical error and not recoverable. Investigate any modifications to base classes outside ofForgeModLoader, especially Optifine, to see if there are fixes available._

I _do_ use OptiFine.

**Comment by PapiDimmi** [comment]
I assume this is what froze my game:

_[Server thread/FATAL]: The ForgeModLoader state engine has become corrupted. Probably, a state was missed by and invalid modification to a base classForgeModLoader depends on. This is a critical error and not recoverable. Investigate any modifications to base classes outside ofForgeModLoader, especially Optifine, to see if there are fixes available._

I do use OptiFine.

**Comment by ouroborus** [comment]
Contrary to PapiDimmi, I don't use optifine and I'll get this error when entering a world after just having left a world.

My impression is that waiting about 15 seconds after leaving a world prevents this from happening but I haven't specifically tested this. (It seemed like there were some messages that show up a few seconds after leaving a world. It seems as though, if these messages haven't come up yet, you'll get this error when trying to enter a world. I wasn't paying close attention so I may be misremembering this part.)

**Comment by OrdinatorStouff** [comment]
I have heard/seen this problem before, even across MC versions so it's something, just hard to pinpoint.

sorry for lack of response earlier, if this is still happening in 5.6+ please let us know in a new ticket
