### ISSUE TITLE
[All the Mods 3, 4.5b] Item frames and XP disappearing and then re-appearing when re-logging

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-3#272]
Sometimes, my item frames or experience disappear, and I have to exit the world and re-enter it for them to appear again. Pretty strange visual bug.

I’ve heard of people having the item frame issue in vanilla, but I’m not sure about the experience issue.

**Comment by OrdinatorStouff** [comment]
sorry for lack of response earlier, if this is still happening in 5.6+ please let us know in a new ticket

might have been related to the "terrain animations" lag that was recently resolved as well
