### ISSUE TITLE
Aluminium/Bauxite missing in oregen of the overworld

### ISSUE THREAD

**Issue by Gorden211** [AllTheMods/ATM-3#275]
I don't know if this is intentional, but I looked through the worldgen and there is no Bauxite or Aluminium in the oregen of the overworld.
You can only find it in the mining dimension or other dimensions, but not in the overworld.

**Comment by Gorden211** [comment]
Nevermind, Bauxite is in the oregen, I looked at the wrong file. But it's quite rare actually in the overworld.

**Comment by OrdinatorStouff** [comment]
Bauxite/Aluminum was specifically tuned and the spawn rate was buffed quite a bit, but it only spawn in higher elevations (similar to copper) so you won't find it if branch mining for diamonds, for example.
