### ISSUE TITLE
[All the Mods 3, 5.0] Beryllium Cell not craftable

### ISSUE THREAD

**Issue by Terminator81** [AllTheMods/ATM-3#276]
i want to craft the Thick Neutron Reflector, so i need the Beryllium Cell!

the recipe say 4 tin ingots, but so i will craft the empty cell...

**Comment by MrFootman** [comment]
Hi,

I think it's a JEI problem with TechReborn cells.

But if you look on another tab, with the electrolyser, you have the recipe :

http://prntscr.com/hflasr

So 16 ender pearl dust in, with 16 empty cells, and you got your Beryllium cell

**Comment by OrdinatorStouff** [comment]
looking now I agree this looks like a bug in how JEI and TechReborn are registering cells as recipes and outputs. Might need follow up with those mod devs for fix

**Comment by Boomflex** [comment]
Going to remove this due to its age.

If it continues to happen, please refer the issue to the relevant Mod Devs.

Thanks.
