### ISSUE TITLE
[All The Mods 3, 5.0] Duplicate ores in overworld from libvulpes

### ISSUE THREAD

**Issue by Elpotatoman** [AllTheMods/ATM-3#277]
There are duplicate ores of copper, tin, etc in the over world in 5.0.

I imagine this is because of the recent addition of advanced rocketry into the pack which requires libvulpes.  Doing a /oredistribution 64 confirmed this.

**Comment by PapiDimmi** [comment]
[Looks like this was fixed in 5.1](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2500794).

**Comment by Elpotatoman** [comment]
Issue solved in 5.1 thank you guys :)
