### ISSUE TITLE
(v 5.0) Recipe conflict

### ISSUE THREAD

**Issue by Porthiir** [AllTheMods/ATM-3#278]
There is a recipe conflict between Chisel's Futura Block & Computercraft's Wired Modem. according to JEI the recipe for the [Futura Block](https://www.dropbox.com/s/4rchnwor2ywktp0/futura%20recipe.png?dl=0) is 8 stone surrounding a piece of redstone dust, but when placing those items into a crafting grid (problem occurs in AE2/RS crafting grid & in vanilla crafting table) the result is instead the [Wired Modem](https://www.dropbox.com/s/5dd96bjfhmz6sb2/recipe%20result.png?dl=0) (links are to screenshots on Dropbox).

**Comment by MrFootman** [comment]
It works. But if you look closer at the recipe, you'll have to chisel the stone. 

Work perfectly fine with chiseled stone :)

**Comment by Porthiir** [comment]
Yes, that's how I was able to make the blocks, but when you use JEI to fill the crafting grid from within either AE2 or RS - it fills the spaces with just regular (unchiseled) stone.

**Comment by OrdinatorStouff** [comment]
should be fixed in pack ver 5.2+ thank you
