### ISSUE TITLE
In multiplayer, players can’t look down

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-3#279]
If a player looks at me and I look down, to him, I automatically look straight up unless he either presses F1 or goes far enough away from me.

ATM 3 version: 5.1

**Comment by OrdinatorStouff** [comment]
I... don't even know where to start with this one. It sounds like it's just a "visual glitch" that your player model appears to be facing a different direction than your actual facing?

Maybe driver/hardware/optifine/graphics settings related? Is this still happening in 5.6+ pack version?

**Comment by Boomflex** [comment]
Non-reproducible.

Closed for now.
