### ISSUE TITLE
Cannot attach IC2 Jetpack to Chestplates

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#28]
IC2 version: 2-2.8.7-ex112
Forge version: 2406

![](https://puu.sh/wHjDV/ae4ea32e11.png)

Cannot attach Electric Jetpack to either Diamond Chestplate or Flux-Infused Chestplate.

**Comment by karolans** [comment]
Same here, doesn't work with any chestplate.

**Comment by OrdinatorStouff** [comment]
Just tested and seems to work for me in a vanilla table so must have been fixed in recent mod updates
![image](https://user-images.githubusercontent.com/6283913/30033362-aa4005b4-914f-11e7-9bf2-b02581288133.png)
