### ISSUE TITLE
[ATM3 v5.1] Recipe conflict for Transformer Upgrade

### ISSUE THREAD

**Issue by Zarkov2** [AllTheMods/ATM-3#280]
The recipe for the IC2 Transformer Upgrade is the same as for the Tech Reborn variant of the item, except the Tech Reborn variant uses Insulated Gold Cable and IC2 uses 2x Ins. Gold Cable.

However, using any combination of either Insulated Gold Cable or 2x Ins. Gold Cable will only craft the Tech Reborn variant, making it impossible to craft the IC2 version. This is in single player, not tested in multiplayer.

**Comment by MrFootman** [comment]
Hi.

Same issue here. On multiplayer this time. 

I  tried the recipe full of IC2 items (because you can use foresty/mekanism too), thought it could be the solution, but it doesn't work.

**Comment by OrdinatorStouff** [comment]
should be fixed in pack version 5.2+
