### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jugulargrunt** [AllTheMods/ATM-3#283]
My friend is crashing on startup with no crash reports.
She can start other modpacks with no problem but atm3 just wont start.
I have send my entire modpack to her (because it worked on another modpack) and still it wont work.
Can you help us please ?

all the mods 3v5.1

**Comment by gabguy** [comment]
+1

**Comment by OrdinatorStouff** [comment]
If you change the setting that says to keep the Minecraft lanucher open
after starting the game the launcher window should show some logging with
more clues.

Off the top of my head I'm thinking there might not be enough RAM
allocated. ATM3 needs at least 5gb or so. Also if you don't have 64bit Java
installed it will crash like that as well if more than 3.5gb is allocated.

Does it start to load, show some bars and blue loading screen or immediate
crash?
