### ISSUE TITLE
[ATM3 V5.1] ExtraCells2 - ME-FluidAssembler crashes on pattern-insertion.

### ISSUE THREAD

**Issue by chaosprin76** [AllTheMods/ATM-3#284]
Hi,
i have milk on a 4k-Fluid-storage disk. I created a pattern for cake, which uses 3 buckets of milk. 

When i shift-click the pattern into the ME-FluidAssembler the game freezes, so i have to kill the process.
When i put the pattern into it, using just the mouse, its in the table, but as soon as i open up my terminal, the game crashes with NullPointerException.

I created a gist from the crash-report:
https://gist.github.com/chaosprin76/de2803223f37c99f0b68053ef563be25

Cant say for sure if this is related: https://github.com/ExtraCells/ExtraCells2/issues/492

**Comment by OrdinatorStouff** [comment]
looks like it was related and should have been updated since then to not be an issue anymore
