### ISSUE TITLE
Server connect timeout

### ISSUE THREAD

**Issue by ShortByte** [AllTheMods/ATM-3#285]
Whenever i try to connect to my server i get a Timeout.

`io.netty.handler.timeout.ReadTimeoutException: null
[22:46:06] [Server thread/INFO]: ShortByte lost connection: Timed out
[22:46:06] [Server thread/INFO]: ShortByte left the game
`

**Comment by JaSpr** [comment]
This one is super common.  A lot of us on our server have to try connecting multiple times before actually getting in.  (usually 2-3 tries)

**Comment by ShortByte** [comment]
No, that does not work.

**Comment by SolarEclipz** [comment]
I had a player on my server have this issue after the v5.5 update. I ended up whitelisting him only and he has had not issues since. 

There was also post in here that said to set the timeout limit up to 90sec from the default 30.

**Comment by OrdinatorStouff** [comment]
`Dfml.readTimeout=90` JVM arg on both server AND client has shown great progress in preventing frequent timeouts.
