### ISSUE TITLE
V5.1 ME Glass Cable - Fluix issue

### ISSUE THREAD

**Issue by carcher7878** [AllTheMods/ATM-3#286]
Crafting recipe doesn't work for the ME glass cable. Tried both normal and pure fluix crystal in both modded and vanilla crafting tables. Used JEI to populate the crafting tables so the recipe is correct, but no items populate in the item slot to retrieve the crafted item. Tried this on both SSP and on a server.

**Comment by carcher7878** [comment]
update - if you eat the personal crafting cookie from whatever mod it is, you can create the cable in the crafting table on the player GUI but not in a crafting table

**Comment by OrdinatorStouff** [comment]
This was resolved in mod updates a while back. Multiple other tickets were opened/closed around that time as well. Closing ticket for cleanup.
