### ISSUE TITLE
Dupe glich

### ISSUE THREAD

**Issue by 91169suraj** [AllTheMods/ATM-3#29]
so using a moving wand on a coke oven (specifically the center piece that you used to construct it) and placing it down you get a duped block that has no texture but you can break to get coke bricks.

**Comment by oly2o6** [comment]
i dont believe this is a dupe, it is basically removing the block making the coke oven multiblock, but not recognising that the coke brick was broken the multiblock stays together, so theoretically you could use 27 bricks to make a coke oven, remove all but 1 block (to interact with the gui), add 1 block and have 2 fully functioning coke ovens, so less of a dupe more of a game breaking dupe, maybe head to bluesunrizes GitHub and report this please bob? much appreciated thank you.

**Comment by OrdinatorStouff** [comment]
Related to #24 

Added immersive bricks to swapping wand blacklist.

The core "problem" would have to be addressed by immersive engineering I'd think
