### ISSUE TITLE
[5.1] Actually Additions Farmer only harvests 1 Inferium Essence from tier 6 Inferium crops

### ISSUE THREAD

**Issue by Schadrach** [AllTheMods/ATM-3#292]
#216 appears to still be a thing.
Harvesting tier 6 inferium crops by hand yields 6 inferium essence, when using an Actually Additions farmer it only yields 1.  The other tiers of inferium crops yield the expected number of essence from the farmer.

**Comment by ouroborus** [comment]
https://github.com/BlakeBr0/MysticalAgradditions/issues/22

**Comment by ouroborus** [comment]
Appears to be fixed in ATM3 5.2

**Comment by OrdinatorStouff** [comment]
Thanks for the follow up @ouroborus 
Closing issue, reopen or make new if still having issues
