### ISSUE TITLE
transfer nodes to framed chest bug

### ISSUE THREAD

**Issue by FluxcapGaming** [AllTheMods/ATM-3#293]
Connecting the Item transfer node (Extra Utilities 2) to a framed chest (Bibliocraft) seems to delete the transfer node when attempting to access the chest to insert items.  This is repeatable and seems to happen every time.

**Comment by OrdinatorStouff** [comment]
Need some testing/confirmation if still happening in 5.6+ pack version. Either way sounds like a mod interaction bug and will need to be reported to those mods accordingly if confirmed.

**Comment by Boomflex** [comment]
Still an issue in 5.7b

**Comment by Boomflex** [comment]
Mod issue that can't be fixed by Modpack.

Please report to Mod Dev.
