### ISSUE TITLE
Bees secondary output // Species unreachable

### ISSUE THREAD

**Issue by MrFootman** [AllTheMods/ATM-3#297]
Hi,

Not sure if it's a bug, or a choice. So i prefer to report it.

**Issue description:**

 1)   Few bees i tried can't produce their secondary output : Gelid bee don't produce cryotheum dust, Yellorium bee don't produce yellorium comb... ...

2)    Some species can't be breed. There is no oblivion hive, and no infernal hive in the nether (tried a lot of spot with a digiminer). So all species from this two are unobtainable.

**Steps to reproduce:**

1)    Works with several bees i tried. Gelid / Yellorium / Nuclear / Unstable...
All the time in a Gendustry apiary, with 8 production upgrades.
I removed the upgrades, just in case, same problem.

Version :

Lastest version of the modpack

**Comment by Yoosk** [comment]
So, theres a lot of infernal hives in nether, at least on official server. Oblivion hives can be found in overworld though.

Ill check cryo and yellorium bees soon too.

**Comment by MrFootman** [comment]
Thank you for answering.

Just checked, the oblivion and infernal hive aren't in JEI. So server config issue ?

**Comment by Yoosk** [comment]
jei likes to hide most of bees for no real reason.

**Comment by Kojikun** [comment]
Secondary output (Specialty) is only made when the bee is in its ideal environment. Add a Hell emulation upgrade for Pyro bees or a Winter Emulation Upgrade for Gelid bees.

**Comment by MrFootman** [comment]
Just tried twice in an industrial apiary, with winter upgrade and Gelid bees.

The bees disapeared, just like the upgrade... Never saw that. (lastest version ATM 5.2)

**Comment by OrdinatorStouff** [comment]
From the discussion here it looks like non-issues. Hives are spwaning and secodary is biome-dependent. The disappearing bees is already tracked in the other mentioned issue.
