### ISSUE TITLE
Chestplates

### ISSUE THREAD

**Issue by xdiacanthusx** [AllTheMods/ATM-3#3]
The NoMansLib armor pieces are associated incorrectly. Like the recipe for the platinum armor is made with bronze ingots, and the nickel armor is made with platinum ingots.

**Comment by TheCodedOne** [comment]
will fix

**Comment by Boomflex** [comment]
This has been fixed in a newer build by TheCodedOne who is Dev on NoMansLib.

Thanks for your report!
