### ISSUE TITLE
Recipe conflict crop stakes from rustic

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-3#30]
To build the stakes (in wiki called crop stakes, ingame only stakes: https://github.com/the-realest-stu/Rustic/wiki/Crop-Stakes) you should put 3 plankes vertikally in the 3 x 3 grid. These stakes are needed to grow the seeds from rustic (Tomatoes and others) which do not grow without them. You get another item, not the stakes. A workaround is to chisel the planks and use them after that, then you get the stakes.

**Comment by whatthedrunk** [comment]
Looks to be fixed now.
