### ISSUE TITLE
Crossing dimentions deletes items

### ISSUE THREAD

**Issue by xxsuperdreamxx** [AllTheMods/ATM-3#300]
When I crossed The end and Overworld with the Rf-Tools Transmitter my Extra Inventory items were gone plus some Environmental Tech Soral pannels and 1 Solar array tier 2 with 7 modifiers and Tinkers items

**Comment by OrdinatorStouff** [comment]
When you say "extra inventory" what do you mean? Just items in your player inventory not on hotbar or a backpack or what?

**Comment by xxsuperdreamxx** [comment]
The inventory cake one I wish I was able to give you more information about the mod but I have problem with the electricity and I can't run my desktop

**Comment by xxsuperdreamxx** [comment]
And that  happens only when I use the RF tools dialing device

**Comment by xxsuperdreamxx** [comment]
Its from Cyclic mod

**Comment by OrdinatorStouff** [comment]
I think this could have been a temporary/visual/networking issue. I've sometimes had the extra inventory appear empty but be "restored" when looking again a few minutes later. 

Any issues with in-game problems on the official server (such as lost item reimbursement) is not done on this issue tracker but in the server's discord channel.
