### ISSUE TITLE
[AllTheMods3 v5.2] Amped bee (magicbees.allele.spawnblitz) causes Industrial Apiary to reset

### ISSUE THREAD

**Issue by Kojikun** [AllTheMods/ATM-3#301]
I've been grinding towards the Amped bee (TE Aerotheum Producing bee) since it is one of the only species that has the "Blinding" speed modifier (aptly named magicbees.allele.Blinding). When an Amped Queen is placed within an Industrial Apiary from Gendustry, the block will freak out, the GUI closes, and the contents of the apiary are reset to it's empty state, deleting anything that was previously inside (including the upgrades and queen). It's probably a fail-safe by Gendustry to prevent the entire server from crashing. 

I have found out that the Effect trait *magicbees.allele.spawnblitz* will cause this block bug. Removing the trait will allow you to use the Amped bee. I would warn against people going for the Blinding speed modifier until this bug gets fixed, unless the blitz spawning trait is removed from the Amped bee. 

This bug exists in the most recent version (v5.2) and all previous versions.

**Comment by DietmarKrause** [comment]
perhaps related: after the latest update my material chest (i believe from gendustry)  with the bees / drones / queens in it was empty. before that it  was almost full with material, esp. extracted genes from gendustry.

**Comment by MrFootman** [comment]
Perhaps related : Last update on issue #297 

I still have my drones/princess and extracted genes. But i stored all of them in vanilla chest.

**Comment by OrdinatorStouff** [comment]
Need to get some testing/confirmation if this still a problem in 5.6+ pack ver

**Comment by Boomflex** [comment]
Please update to latest pack version v5.8
