### ISSUE TITLE
Pack out-of-date on Technic Launcher

### ISSUE THREAD

**Issue by balla2185** [AllTheMods/ATM-3#304]
using technic launcher which has version 4.0 server i want to play on is using 5.2 i have been at this for 3 hours now i am not able to update the version HOW do you??

**Comment by OrdinatorStouff** [comment]
Technic updates are no longer officially being done. We recommend using something like the dev branch of MultiMC that supports curse modpack downloading (or the Twitch client if an option).

To manually update the profile you have on Technic, first delete (or backup/move) the mods, scripts and config folders from the profile files. Then Download the "server files" from curseforge for the latest version you'd like to plan and extract all files into the Technic profile folder. Lastly, update the forge version of the technic profile to match the forge version of the update you chose.

If that doesn't work or you continue to have difficulties please consider another launcher or pack download method that supports fetching the files from Curse directly.

**Comment by Boomflex** [comment]
Technic no longer supported.

Use Twitch App or the new MultiMC version.
