### ISSUE TITLE
ATM-3  5.2 Mekanism configurator bug

### ISSUE THREAD

**Issue by Hythragon** [AllTheMods/ATM-3#305]
When I use shift + right click or even just right click on a logistical transporter, the game disconnect me from my server.

**Comment by OrdinatorStouff** [comment]
This has been[ fixed in Mekanism code](https://github.com/aidancbrady/Mekanism/issues/4835#issuecomment-348544943) so it should be better once the modpack can update to a mekanism release that has this fix

**Comment by OrdinatorStouff** [comment]
This has been fixed as of pack version 5.6
