### ISSUE TITLE
Being removed from your own team

### ISSUE THREAD

**Issue by englishmuffins10** [AllTheMods/ATM-3#306]
Me and several other people on a server I have been running have been coming across an issue where we are removed from the teams we have made. This has happened to 3 different people and to me at least 3 times. This has caused a fairly major problem as all chunks need to be reclaimed and anyone who is not an admin suddenly find that they are unable to interact with their own base. Seeing as that there is no way to delete a team (as far as I know) this has forced me to make several new teams with different names and is rather annoying.
Here are some pictures of the teams shown.

![2017-12-02_11 03 54](https://user-images.githubusercontent.com/6701138/33518296-21f3a87e-d758-11e7-8cc8-9b6be3b20f50.png)

![2017-12-02_11 03 51](https://user-images.githubusercontent.com/6701138/33518297-220dddca-d758-11e7-8297-4a02cfdd324c.png)

![2017-12-02_11 58 26](https://user-images.githubusercontent.com/6701138/33518309-4d0f30a0-d758-11e7-8f66-2de3708a7aaa.png)

**Comment by JustaRandom** [comment]
Hey, 
This is an issue with the FTB mods, the dev is aware of it. This modpack is running on the 4.2.3 of FTButilities. A new version is available 4.2.4 but I do not know if the issue will be fixed.

I play myself on a SP and have to "everytime" I load the game, I have to chunk load everything.

So maybe update and see if it fix your pb?

Peace

**Comment by OrdinatorStouff** [comment]
Are you running with ANY changes to the ATM3 pack? Sponge? Added/removed mods? Different version of Forge etc?

**Comment by JustaRandom** [comment]
I did not change anything on the modlist that you uploaded 5.2, you are doing an update more or less every week, so it is a bit redundant.

Will try to update the FTBU and lib to see if it is fixed, will get back to you tomorrow "EU time".

Peace

**Comment by JustaRandom** [comment]
Been updating the mod FTBUtilities to 4.2.4 and FTBLib to 4.2.5 and the problem still persist.

Note that I do that on a SP map. 5.2 version.

To see if problem might be fixed please refer to 
https://github.com/LatvianModder/FTBUtilities/issues/565

Peace

**Comment by englishmuffins10** [comment]
I have a unedited version of 5.2 for this modpack as I have yet to update it to 5.3 but i am running a multiplayer server so it seems to be an issue with the mod itself.

**Comment by Boomflex** [comment]
No longer seems to be an issue as of v5.7
