### ISSUE TITLE
Advanced Generators & Advanced rocketry recipes does not show ın JEI

### ISSUE THREAD

**Issue by rokolix** [AllTheMods/ATM-3#309]
I cant see some mods recıpes ın JEI.For example , Advanced generators & Advanced rocketry.Is that bug or you dıdnt ımplent yet ?

**Comment by OrdinatorStouff** [comment]
I see you closed the issue was this resolved / figured out? Are you good now?

**Comment by rokolix** [comment]
Yes.I turn off the jei and turn on again.It solve the my problem.

4 Ara 2017 23:15 tarihinde "OrdinatorStouff" <notifications@github.com>
yazdı:
