### ISSUE TITLE
Immersive Engineering manual book crash

### ISSUE THREAD

**Issue by rokolix** [AllTheMods/ATM-3#311]
When ı open the IE manual book,after few seconds game crashes.Sometimes it take 1-2 min but it definitely crashes while looking at the heavy machinery or other topics. I added the log
[latest.log](https://github.com/AllTheMods/ATM-3/files/1540735/latest.log)

**Comment by OrdinatorStouff** [comment]
this is an old/known issue. it's all over the IE github [many times and repeatedly](https://github.com/BluSunrize/ImmersiveEngineering/issues?utf8=%E2%9C%93&q=is%3Aissue+manual+java+version).

Minecraft by default ships with very old Java version

Twitch (and maybe other) Launchers let Minecraft use it's own "internal" version

Immersive Engineering manual WILL crash in this 2-3+ year old Java version

You need to first install/update latest Java 1.8 on your computer

Then tell your launcher to specifically use that newer version (NOT 1.8.0_25)
