### ISSUE TITLE
Akashic Tome made from a block of dirt, contains all books.

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-3#313]
Seen this in earlier packs, but I can make [the Akashic Tome from dirt.](https://imgur.com/a/q0MCU) Should probably fix that.

**Comment by OrdinatorStouff** [comment]
This is intentional. We manually created this recipe that includes many of the mod's manual's and made it "free" for player convenience.

Is there a reason I might not be thinking of why this is bad?

**Comment by TheKrister2** [comment]
It might be for convenience, but I just think it feels cheap. That and there are small problems with the Akashic Tome right now. I can't remember which one, but a manual actually causes a client crash if you stay in the book through the Tome for to long, which shouldn't happen. Either way though, I think this is less "convenience" and more just cheaty, as you're getting an item, containing lots of other items, from _one block of dirt._ To each their own though.

**Comment by OrdinatorStouff** [comment]
the "from one block of dirt" is a replacement-recipe, it's our intention that new players actually start in a new world with the book in-hand. Half of these included books are ones that by mod defaults would be given to the player on new world join anyway, and most of the others are extremely basic/simple recipes as well. Even the empty akashic tome is simple as well. There are maybe one or two manuals that require something slightly more than 'early game' to get but even then I'm not sure what's "cheaty" about having easy access to mod manuals without inventory clutter.  
  
The only crash that I have remotely heard of that kind of matches your description is the immersive engineering known bug where if in the IE manual and using the old 1.8.0.25 java that minecraft launcher ships with it will crash. That crash is independent of akashic tome, however. 

If there is another that I don't know about please open a new issue with more details so we can look into fixing it or removing that manual from this default tome.
