### ISSUE TITLE
Tinkers issue with Server version 5.3 of ATM3

### ISSUE THREAD

**Issue by Possemaster** [AllTheMods/ATM-3#315]
Please check video for clear reproduce.

We experienced the issue on our server. 
Sand will smelt but not display correct and crash the game if you select another liquid in the smeltery.
So I checked if this issue could be reproduced in a singleplayer session, no issues. (see video 1) [ [https://youtu.be/qZ_mE2x-UhQ](https://youtu.be/qZ_mE2x-UhQ) ])
I started a localhost server with new server files and experianced the same issue with tinkers as I have on the public server. (see video 2 [ [https://youtu.be/9lr8-5_47lk](https://youtu.be/9lr8-5_47lk) ])

If you check the fml-junk-earlystartup.log you will see that the server is outputting Exceptions from line 21686 concerning Tinkers.
And on line 30861 you see below and after that the exception keep on coming:
`[00:32:00] [Server thread/ERROR] [tconstruct-TinkerSmeltery]: Error trying to save fluids inside smeltery! Invalid Liquid found! Smeltery contents:
[00:32:00] [Server thread/ERROR] [tconstruct-TinkerSmeltery]:   fluid.tconstruct.stone/4320mb
[00:32:00] [Server thread/ERROR] [tconstruct-TinkerSmeltery]:   fluid.tconstruct.glass/31000mb
[00:32:05] [Netty Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel tconstruct`

[fml-junk-earlystartup.log](https://github.com/AllTheMods/ATM-3/files/1544144/fml-junk-earlystartup.log)
[fml-server-1.log](https://github.com/AllTheMods/ATM-3/files/1544145/fml-server-1.log)
[fml-server-latest.log](https://github.com/AllTheMods/ATM-3/files/1544146/fml-server-latest.log)
[latest.log](https://github.com/AllTheMods/ATM-3/files/1544147/latest.log)

**Comment by OrdinatorStouff** [comment]
I have read recently some discussion about Forge packet/networking code changing slightly and messing up some other mods in an unexpected way. We did a forge version rollback in 5.6 to fix some other bugs, maybe this was one that also caused by that? 

Need to test for reproduceability in 5.6+ and troubleshoot further if confirmed.

**Comment by Boomflex** [comment]
Please update to latest pack version.

Issue closed due to being non-reproducible.
