### ISSUE TITLE
All the mods 3 ver 5.3 memory leak

### ISSUE THREAD

**Issue by Rubijox** [AllTheMods/ATM-3#318]
i have 6400MB of ram allocated to the modpack, but over time while playing memory usage in task manager jumps up to 10-14gb and keeps going up until my computer locks up entirely

**Comment by OrdinatorStouff** [comment]
Is this still happening in 5.4?

What version of Java do you have installed and what launcher do you use to launch the pack?

Do you use any additional JVM arguments?

**Comment by OrdinatorStouff** [comment]
We're about to update agains soon probably within the next few days to ATM3 5.6, if this is still a problem that's been going  on and still happening in 5.6 please re-open this issue
