### ISSUE TITLE
Ender Dragon Dimlet not craftable

### ISSUE THREAD

**Issue by Kaffee81** [AllTheMods/ATM-3#319]
I tried to create an ender dragon mob dimlet, but the dimlet is not craftable. I tried the given rarity 5 and also 6, none of them worked.

Using version atm 3 v5.3, playing on my server.

![enderdragon_dimlet](https://user-images.githubusercontent.com/12095307/33807002-9d0fa43a-ddd0-11e7-9bff-5f5ab998ea57.png)

**Comment by OrdinatorStouff** [comment]
we've known about this for a while and I don't think we (ATM team) changed it intentionally -- we've assumed it was a change in defaults from RFTools dimensions.

Thinking about it now though, I might add a custom recipe for this outside of rftools dimlet workbench anyway.

**Comment by OrdinatorStouff** [comment]
we disabled the syringe on the dragon since it could be abuse in the rft spawner for griefing in other dimensions by spawning a dragon there

starting in 5.7, there will be a crafting recipe to craft a dragon dimlet outright to be used in RFT dimensions

**Comment by josephcsible** [comment]
Uh, you know you can disable spawning ender dragons in the spawner without messing with the syringe, right? The way you did it is unnecessarily confusing a lot of players: McJty/RFToolsDimensions#133

**Comment by SpeedSlider** [comment]
The ender dragon dimlet specifically states it is not craftable in the 5.8 version in JEI. I think that is an RF Tools thing not an ATM custom configuration. The implications is that you may only be able to find it by searching dim loot rooms.

**Comment by josephcsible** [comment]
I just checked in a clean instance with just RFTools (the same version). It's not an RFTools thing.

**Comment by SpeedSlider** [comment]
Well then based upon the comment it is a specific pack configuration and is intentional.

**Comment by josephcsible** [comment]
My point is that you can accomplish the stated goal (keeping people from using the Spawner to spawn ender dragons) without breaking other uses of the syringe.

**Comment by josephcsible** [comment]
Actually, it's not just ender dragons. ALL mob dimlets are broken. I'll open a new issue about this.
