### ISSUE TITLE
client crash unknown cause 

### ISSUE THREAD

**Issue by Willy347** [AllTheMods/ATM-3#32]
i was hovering using the quantum armor and sneaked to go down looking at a garden cloche and i crashed.
don't know how or why
here is the report
[crash-2017-07-12_17.16.58-client.txt](https://github.com/AllTheMods/ATM-3/files/1142486/crash-2017-07-12_17.16.58-client.txt)

**Comment by OrdinatorStouff** [comment]
I tried reproducing but couldn't get it to crash BUT I do know that covers has been working on the CCL rendering stuff (i.e. issues with Pam's Market block) and unfortunately this stack trace is not helpful, the thing that ACTUALLY crashed is seen in the "latest.log" just before the crash.

Thank you for taking the time to report, normally the logs are more helpful. In this case I'm going to close and assume/hope it's been addressed already in recent mod updates. Obviously if it happens again we'll try to be more diligent about tracking it down.
