### ISSUE TITLE
Bug-fixing update to NuclearCraft

### ISSUE THREAD

**Issue by turbodiesel4598** [AllTheMods/ATM-3#320]
Should probably let you know that [the mod has been updated to v2.7](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) and mainly fixes a lot of bugs that people playing your pack, among others, had reported over the last couple of months, including crash bugs.

**Comment by OrdinatorStouff** [comment]
I think we got this update and even still sounds like there's another big one that did or will soon come out again.

We update the modpack regularly and update every mod we can each time. In general there shouldn't be more than a few days to a week before a mod update is picked up and included in the pack
