### ISSUE TITLE
Please add some chunkloaders for the next update

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-3#321]
There are some chunkloaders already in the pack, but they can't be crafted, at least four can't, as far as I know. As far as I know, there isn't a way to chunkload a dimension properly without making everything overly annoying. Something like [Chicken Chunks's chunkloader and spotloader.](https://minecraft.curseforge.com/projects/chicken-chunks-1-8) Or something like [Persistent Bits.](https://minecraft.curseforge.com/projects/persistent-bits) The pack might be rather young, but it has a crippling lack of any useful chunkloaders at the moment, it is of course possible to claim chunks with ftb's utility, however, it doesn't keep the dimension loaded. And the moment no one is inside the dimension for a little while, it is unloaded. Hopefully this can be addressed by the next update.

**Comment by Kaffee81** [comment]
Check the FTP Claim chunk again. Did you claim the chunk or did you claim+chunkload the chunk via ftb? It requires a second click with shift pressed, to activate chunk loading for your claimed chunks. It should also display it at the bottom right "Claimed Chunks 1/1000 and Loaded Chunks 1/64" if you did it correctly.

**Comment by TheKrister2** [comment]
I know how to claim and chunkload chunks with ftbutilities. That is _why_ I mentioned it. As an example for a chunkloader. However, it doesn't keep the dimension loaded. Once the player is absent from a dimension for a period of time, it is unloaded again, any chunks that are meant to be loaded are not, when the dimension isn't.

**Comment by Yoosk** [comment]
Use ic2 chunk loader.

**Comment by OrdinatorStouff** [comment]
I'll be tweaking a few chunkloader-related settings/recipes. We have no intention at this time of adding new mods for the sole purpose of chunkloaders.

Also as an official statement, chunkloaders in this pack are supposed to be difficult/rare (but not necessarily nonexistent)

**Comment by phrostbit** [comment]
Make a team, even if you're by yourself, and you will be able to claim chunks.

- Phrostbit
