### ISSUE TITLE
Iron rod recipes

### ISSUE THREAD

**Issue by DJDrWright** [AllTheMods/ATM-3#323]
iron rod recipes are not working in ATM3, immersive engineering recipe, they make a raw handle from Steve's Carts. In a 3x3 the only output is the raw handle, If I choose move items from JEI, same thing
receipe by UniDict, if that helps. Plus there are two recipes, two iron bars make four rods, which doesn't work, makes two iron plates and three iron bars makes Steve's raw handle.

**Comment by OrdinatorStouff** [comment]
I'll look into this but off the top of my head it sounds like either a packmode mismatch or a profile/server that doesn't have all of the scripts from the modpack. 
  
Is this on a server or single player?
Has packmode been changed? If so is it "simplified" or "normal" mode?

**Comment by DJDrWright** [comment]
This is on a server and I will have to ask the server owner

**Comment by DJDrWright** [comment]
It is on a server Normal

**Comment by OrdinatorStouff** [comment]
Thanks for the follow-up, does this affect everyone on the server the same or just you? I assume everyone I just want to make sure

**Comment by DJDrWright** [comment]
I cannot get a hold of anyone on the server at the moment but one other person reported it in single player also

**Comment by DJDrWright** [comment]
other server users reported the same issue

**Comment by OrdinatorStouff** [comment]
you should be able to make them in an immersive engineering press multiblock, or use a forestry workbench to cycle between recipe options

these are temporary suggestions until we fix it officially

**Comment by OrdinatorStouff** [comment]
coming in 5.7 added more stuff to Iron Rod (stickIron) oredict -- the recipes that need the iron rod mostly seem to be oredict compatable too
