### ISSUE TITLE
Experience pylon bug

### ISSUE THREAD

**Issue by TheKrister2** [AllTheMods/ATM-3#325]
Not sure how it happened, but when I came back after doing a lot of stuff one day, I found the pylon in negative thirtyish thousand experience. I first just thought it was a gui bug, so I tried updating it by extracting a little. I'm at around two thousand levels now. That _probably_ shouldn't happen. Not sure if it is a problem with the mod itself, or some configuration on the pack. It did not log an error to the console when it happened. It is reproducible as well, considering I managed to get it to do that more or less every time I try to extract with the +500 button or whatever it's called. When I press the insert all button, it would normally fill up with twenty thousand experience if I remember correctly, but now it goes _way_ over it's limit, going into negative, then positive, then negative. It held about 400 levels when I was level 2000 or so. If you drain it into another container, like an extrautils barrel, then it continues until the tank is empty. It is basically filled 4+ times, so the tank itself shows as full until you reach the normal amount.

Not sure if this will help or not.

**Comment by OrdinatorStouff** [comment]
appears to be fixed in the mod already: https://github.com/PrinceOfAmber/Cyclic/issues/632 which means it already should be fixed in the pack or will be soon
