### ISSUE TITLE
Recipe addition: Certus quartz Crystal and Fluix Crystal

### ISSUE THREAD

**Issue by Nayashi** [AllTheMods/ATM-3#326]
IGN: Fowah
Add the recipe 
![recipe additions](https://user-images.githubusercontent.com/26238942/34052738-76ba1418-e178-11e7-944f-808dda45ee3b.png)
to Mekanism Crusher / Crushing Factory

**Comment by Nayashi** [comment]
mods.mekanism.Crusher.addRecipe(<appliedenergistics2:material:0>, <appliedenergistics2:material:2>); 
mods.mekanism.Crusher.addRecipe(<appliedenergistics2:material:7>, <appliedenergistics2:material:8>); 
added to ModTweaker would add the recipes

**Comment by Boomflex** [comment]
Great idea.

Recipes added in next update.
