### ISSUE TITLE
Digital Miner not mining some ores

### ISSUE THREAD

**Issue by Yoosk** [AllTheMods/ATM-3#327]
So far found 2 ores, oreUranium and oreLapis, digital miner with proper oredictionary filters can see amount of ore he should mine, but on start it goes down to 0 and shuts down, as you can see on [video](https://a.doko.moe/llkfxd.webm).

Place had to claims whatsoever, away from anything that could interact.

**Comment by OrdinatorStouff** [comment]
[fixed in mek dev](https://github.com/aidancbrady/Mekanism/issues/4841)
should be updated when modpack next updates
