### ISSUE TITLE
Bronze blocks Thermal expansion not converting to ingots

### ISSUE THREAD

**Issue by thaimichael** [AllTheMods/ATM-3#328]
If you alloy blocks of bronze in a smeltery they come out as bronze blocks thermal expansion.  Put block crafting grid unable to break down into ingots.  
Take 9 thermal expansion ingots in grid become 1 block bronze tech reborn.
1 ingot bronze in grid becomes 9 nuggets mekanism 
9 mekanism nuggets 1 mekanism ingot
Tech reborn bronze block does not appear to have an ore dictionary entry.
I can use the Industrial Foregoing ore dictionary converter to change most blocks and unify ore dictionary names but the bronze block is problematic and it may related to the missing ore dictionary entry from tech reborn (from my looking about)

**Comment by OrdinatorStouff** [comment]
Bronze should behave better now in 5.7
