### ISSUE TITLE
Recipe Conflict IC2 Carbon Fiber

### ISSUE THREAD

**Issue by chooven** [AllTheMods/ATM-3#33]
Version 1.5

Carbon fiber for the IC2 nano Suit: 
When you combine coal dust you get the Tech reborn Carbon Fiber and when that is combined you get the Tech Reborn CombineCarbonFiber that will not go into the IC2 Compressor to make the Carbon Plate and the Tech Reborn Carbon plate doesn't work in the Nano Suit recipes.

**Comment by jeffwcollins** [comment]
Try the forestry crafting table.  It lets you switch between conflicting recipes.

**Comment by chooven** [comment]
Awesome, thanks that works

**Comment by OrdinatorStouff** [comment]
This looks like's it's already been fixed with the TechReborn "compatibility recipe" config option
