### ISSUE TITLE
can't open oak chests

### ISSUE THREAD

**Issue by meson11** [AllTheMods/ATM-3#330]
after updation on v5.5 i can't open oak chests anymore. other chests are working.

**Comment by Trollmen** [comment]
I can confirm this. Oak chest do not open.

**Comment by GTD-Carthage** [comment]
Also have this problem occurring.

**Comment by OrdinatorStouff** [comment]
I confirmed this in a single player world but it does not seem to be affecting server / SMP worlds.

**Comment by whatthedrunk** [comment]
5.6 will be out tonight with this fixed. Update your forge if you need the fix now.
