### ISSUE TITLE
IC2 Solar Panel not craftable

### ISSUE THREAD

**Issue by thejims** [AllTheMods/ATM-3#331]
With the addition of TR Solar Panels, IC2 Solar Panels are no longer craftable.   The IC2 recipe yields the TR version.  The IC2 Solar Panels are needed for Compact Solar Arrays solar panels, so none of the Compact Solar Array items are currently craftable.

**Comment by OrdinatorStouff** [comment]
This has been fixed natively in TechReborn code per this commit (https://github.com/TechReborn/TechReborn/commit/9fafbf1ed4794055531eff09b4bcf9060e5ae355)

If there isn't a release public on Curse before next pack update we'll make a temporary change in recipes but hopefully it'll be available soon
