### ISSUE TITLE
[AllTheMods 3 v5.6] Crash on creating world.

### ISSUE THREAD

**Issue by NoPain9** [AllTheMods/ATM-3#339]
Trying to create a Biomes of Plenty world, with only a few things set to No, like Thorns, poisen pools and quicksand.

Have not added anything, not changed anything in configs and I get an error which I haven't seen before, probably because it's one of my first 1.12.2 packs.

https://pastebin.com/nAu5YVeh

That is the crashlog that I get! Thanks in advance!

**Comment by OrdinatorStouff** [comment]
dim 6 is supposed to be the "nether mining dimension" added by JED. the JED config wasn't changed in this or any recent update even and how it used to work would be that it created the dimension if it didn't exist. Your error log says that it couldn't find the dimension though. Will need to look into this some more.

```json
{
    "dimensions": [
        {
            "dim": 6,
            "override": false,
			"dimensiontype":
            {
                "id": 6,
                "name": "Nether Mining Dimension",
                "suffix": "_dim6",
                "keeploaded": false,
                "worldprovider": "WorldProviderHellJED"
            }
        },
        {
            "dim": 1,
			"worldinfo": {
				"BorderCenterX": 0,
				"BorderCenterZ": 0,
				"BorderSize": 320000
            }
        }
    ]
}
```

**Comment by OrdinatorStouff** [comment]
@NoPain9 if you don't mind can you try a few troubleshooting steps for me, please:

First, re-download the pack fresh all over again. Maybe a file or config was corrupt in the existng instance
Then, try to create a new world strictly "vanilla"
If that works, exit and try to create a new world as BoP 'defaults'
If that works, exit and try created a new world with the same BoP tweaks you did before, noting specifically which ones you're toggling.

If it fails at any point along the way please update the issue with the details and crashlog again if applicable.

**Comment by NoPain9** [comment]
@OrdinatorStouff Hmm I tried those things, redownloaded it, created a new world.

Strictly vanilla: Worked !
BoP Default (After Vanilla): Worked !
BoP Tweaked (After Vanilla & BoP Default): Worked !

Not entirely sure what changed, maybe when I made Vanilla world the configs knew what the Nether was? Not sure here but it seems to be working now, gonna keep watching the logs every now and then to see if anything changes but so far it seems to work. Atleast I am in my world so. That's good news.

Thanks though!

**Comment by OrdinatorStouff** [comment]
We still don't know exactly what caused it to fail but at least it's working now. Let us know if anything else comes up or crashes or whatever but we'll just close this as resolved then. Thanks for the prompt follow-ups as well.

**Comment by twoworlds** [comment]
Just wanted to say, that I got this error, too.

I wanted to try ATM3 and did a fresh install in MultiMC. I started and selected BoP to generate a new world (no custom settings, standard BoP). 

Here is my crashlog:
https://pastebin.com/iwTbNbXm

No further mods included, just plain ATM 3 Version 5.6

**Comment by twoworlds** [comment]
Just a follow-up, I can't create a standard world either, it gives me the same crash

**Comment by twoworlds** [comment]
Maybe a conflict with JED and Aromas 1997 Dimensional World? I saw, that both use ID 6 for their dimension ID.

**Comment by KufrA** [comment]
Silimar error for me also. New to ATM3, just downloaded everything via twitch launcher.
Started new world using Realistic worldgen and mine also fails to load the world and crash at Dimension ID 6.
Playing singleplayer.

logfile:
[crash-2018-01-05_19.28.45-server.txt](https://github.com/AllTheMods/ATM-3/files/1607536/crash-2018-01-05_19.28.45-server.txt)

Will try now to see if creating strictly vanilla will solve it.
