### ISSUE TITLE
Dragon kill bugged?

### ISSUE THREAD

**Issue by Zetharion** [AllTheMods/ATM-3#34]
Have you had any reports of the dragon being unkillable in the last version (1.5) of the ATM3 pack?  The health bar never goes down, but you can still damage it.  When you do kill it, it goes through the whole animation of dying, but the portal doesn't light and it doesn't drop an egg.  After a bit a second dragon appears out of no where.

**Comment by infina** [comment]
This appears to be a bug with Astral Sorcery 1.5.8. Updating Astral Sorcery to 1.6.0 resolves the issue.

**Comment by Zetharion** [comment]
Was just about to note that.

**Comment by whatthedrunk** [comment]
v2.1 will be up on curse with this fixed. Thanks.
