### ISSUE TITLE
For some ores, Crafting 9 ingots together makes a Mekanism block - not a Thermal Foundation block

### ISSUE THREAD

**Issue by ogradyjd** [AllTheMods/ATM-3#342]
Crafting 9 copper ingots together in a crafting table or Extra Utilities mechanical crafter results in a Mekanism copper block,  It should result in a Thermal Foundation copper block.  Tin is the same.  
**Update:** This goes for converting ingots to nuggets as well!

As I figure them out:
1. copper
1. tin
1. bronze
1. charcoal - turns into a chisel (raw) charcoal block which does not burn.  should be a Forestry or Mekanism charcoal block.  This sucks because there's a lot of automation with tree farm -> charcoal blocks
    - This seems to only happen with the Extra Utils 2 mechanical and analog crafters.  Crafting table results in a Mekanism block, which is okay.  
    - Cyclic Auto Crafter properly converts charcoal to a Mekanism charcoal block, so you can tell players to use that instead of the Extra Utils 2 machines. Downside: the auto crafter needs power, whereas the EU2 machines don't.

**Edit:** Took out osmium - it is mekanism only, so there is no Thermal variant of the ore.  

**Update (180112):** I've tried a lot of other ores and the list above is, so far, the only ones I've found with the block crafting problem.

**Comment by OrdinatorStouff** [comment]
This might be resolved by a new crafttweaker script I'm working on to help forcibly unify blocks <-> ingots <-> nuggets

This is a very useful report as it gives me specific targets to check for compliance, thank you!

**Comment by OrdinatorStouff** [comment]
Bronze has been addressed specifically for 5.7 but this is an ongoing area of improvement I'm still working on

**Comment by Sakata-MC** [comment]
Copper still doing this as of 5.9.3b
