### ISSUE TITLE
A fatal error has occurred - this connection is terminated

### ISSUE THREAD

**Issue by Zer0Yield** [AllTheMods/ATM-3#344]
Running a small server for myself and friends and am getting the above issue when trying to connect. No crash on either client or server side. It seems odd as nothing has changed in the world since we were last able to log in, but the last week it has been running. I loaded the earliest backup with no luck. Any ideas?

I see that there are some references to recipes not loading - I do recall I had pumpkin pie from magic bean drops. Is there a resolution to this?

[latest.log](https://github.com/AllTheMods/ATM-3/files/1588084/latest.log)

**Comment by OrdinatorStouff** [comment]
The recipe/advancements part at the top is not relevant. This log doesn't list what's happening or why. Could you please procure a full set of logs for us to review:

restart server
fully exit and restart client
attempt to connect
as soon as connect fails, get a copy of ANY file ending in .log on both your client AND the server and attach them all here.

It's a bit much, I know but this way we can find which log and which side is having the issue and go from there.


Also, is this all the time or only intermittent? Every player on the server or only some?

**Comment by Zer0Yield** [comment]
Here are all logs from both client and server... I had temporarily salvaged this by downloading fresh server files and moving the 'world' to the new set. It all worked until tonight where I again got the same error. I have restarted both sides numerous times. Here are all the logs from the most recent failure, first one being the client and all the rest are server:

[latest.log](https://github.com/AllTheMods/ATM-3/files/1590202/latest.log)
[fml-server-latest.log](https://github.com/AllTheMods/ATM-3/files/1590203/fml-server-latest.log)
[fml-server-1.log](https://github.com/AllTheMods/ATM-3/files/1590204/fml-server-1.log)
[fml-junk-earlystartup.log](https://github.com/AllTheMods/ATM-3/files/1590205/fml-junk-earlystartup.log)
[latest.log](https://github.com/AllTheMods/ATM-3/files/1590206/latest.log)

Thank you for the help!!

**Comment by OrdinatorStouff** [comment]
Try deleting `/world/advRocketry/planetDefs.xml` and restart the server.

**Comment by stardustrider** [comment]
I was having an almost identical issue. Tried the above, but that didn't work. I deleted the advRocketry folder for the server world, and that worked for me, but no-one else could connect, with them being gated with "Fatally missing registery entries". So... I'm just disabling the mods completely for now.

**Comment by OrdinatorStouff** [comment]
if these same issues are happening in latest pack version please open a new issue
