### ISSUE TITLE
Can't create new world (JED / "Invalid dimension id 6")

### ISSUE THREAD

**Issue by patyak** [AllTheMods/ATM-3#345]
i been trying to play allthemods and it won't work, i have tried both server and single on single i create world it says building world but never builds i let it try for 3 hours once and nothing and when i try to log into a server it says loging in but then goes back to main menu

**Comment by OrdinatorStouff** [comment]
We'll need to see logs to get more details but also try fully re-downloading the pack as a fresh profile. Check to make sure you're allocating at least 4gb of RAM as well.

Can you give details of your computer spcs (CPU/RAM/OS) and find the latest.log from the modpack directory and upload it here for us to take a look at

**Comment by patyak** [comment]
![specs](https://user-images.githubusercontent.com/34876968/34399180-e7b937e6-eb52-11e7-9cda-fd2501d8381d.PNG)

**Comment by patyak** [comment]
there is no crash report thats the problem because it doesn't crash it just won't let me load into a world

**Comment by patyak** [comment]
[latest.log](https://github.com/AllTheMods/ATM-3/files/1590362/latest.log)

**Comment by OrdinatorStouff** [comment]
First of all, 6gb total RAM is going to make it difficult. Not impossible but difficult to load a large pack like ATM3, itself needing 4-6gb of RAM to run smooth.

That being said, I've seen this error more and more comingup lately:
```java
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Dimensions (justenoughdimensions)

Caused by: java.lang.IllegalArgumentException: Invalid dimension id 6
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77) ~[ayn.class:?]
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:113) ~[DimensionManager.class:?]
	at fi.dy.masa.justenoughdimensions.config.DimensionConfig.registerDimension(DimensionConfig.java:309) ~[DimensionConfig.class:?]
	at fi.dy.masa.justenoughdimensions.config.DimensionConfig.registerNonOverrideDimensions(DimensionConfig.java:273) ~[DimensionConfig.class:?]
	at fi.dy.masa.justenoughdimensions.JustEnoughDimensions.serverStarted(JustEnoughDimensions.java:87) ~[JustEnoughDimensions.class:?]
```

And I've spoken with the mod dev of JED and the cause is shrouded in some mystery of vanilla issues or something. I have seen this "fixed" by simply re-downloading the modpack as a fresh instance and trying again. If you haven't tried that yet, please do and let me know.

**Comment by patyak** [comment]
yes i tried i even deleted the mod and downloaded from curse and would not load in yet if i remove and load the pack i can log in

**Comment by patyak** [comment]
i updated to the version released yesterday and it works thankyou for your time

**Comment by OrdinatorStouff** [comment]
@patyak do you mean you manually updated JED to the new version from curse?

**Comment by OrdinatorStouff** [comment]
@twoworlds can you try manually updating JustEnoughDimensions to the latest version (the alpha from Dec 28 or later) and see if that fixes the problem for you?

**Comment by twoworlds** [comment]
Here is my crashlog:

https://pastebin.com/iwTbNbXm

I have updated JustEnoughDimensions to the latest version and now I can create a world without a problem!

**Comment by patyak** [comment]
yes i manually updated jed

**Comment by OrdinatorStouff** [comment]
@patyak that's unrelated to the dimension crash but it means that you don't have enough RAM allocated to the pack and Minecraft/Forge has to constantly fight itself for more RAM while loading. If you don't have a lot of total system RAM it can be hard finding the number that works just right overall but you probably want to shoot for at least ~4.5gb allocated. 5-6gb if you can spare it.

**Comment by patyak** [comment]
ok thank you very much for everything
