### ISSUE TITLE
Can't start ATM, getting error on creating world

### ISSUE THREAD

**Issue by twoworlds** [AllTheMods/ATM-3#348]
I get the same error as mentioned here:

https://github.com/AllTheMods/ATM-3/issues/339

I can't create a standard world nor a BoP world. 

Crash-Log: https://pastebin.com/iwTbNbXm

Maybe a conflict betweed JED and Aromas 1997 Dimensional World?

**Comment by OrdinatorStouff** [comment]
We've had a few issues opened for this same problem. Currently the "Main" one still open is https://github.com/AllTheMods/ATM-3/issues/345
can you please post your crash log in that issue for better visibility? Just trying to keep it all in one place
