### ISSUE TITLE
My helmet appears in my torso/Character visual glitch.

### ISSUE THREAD

**Issue by VenoMexe17** [AllTheMods/ATM-3#349]
When ever i wear a helmet in game it shows on my head and also on my torso. I think this is due to miniaturization fluid but I dont know how to reset it. If anyone has any ideas i'm up to hear them, thank you. 

You can see what i mean in [this gif](https://gyazo.com/3d40d09ad33e998cba260c850f6d09b1)

**Comment by Boomflex** [comment]
Please update to latest pack version.

Issue closed due to being non-reproducible.
