### ISSUE TITLE
EXUtils Lasso not craftable.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#35]
ExUtils version: 1.12-1.5
Forge version: 2407

Unable to craft the regular Lasso from ExUtils2 everything else works like Dark Lasso and Angel Ring the lassos have wrong names as well.
![ss 2017-07-13 at 01 40 25](https://user-images.githubusercontent.com/20716525/28164694-d64bd618-67d0-11e7-918a-f262a3e9b65d.png)
Tried the old recipe as well seemed to work.

**Comment by Darkere** [comment]
https://github.com/rwtema/extrautilities/issues/1587

**Comment by OrdinatorStouff** [comment]
Looks already fixed in latest mod versions
