### ISSUE TITLE
[1.12.2 forge-14.23.2568 (server) ATM3 v 5.6] Player goes into Spectator mode after death

### ISSUE THREAD

**Issue by VallenFrostweaver** [AllTheMods/ATM-3#350]
Using the command (/back) again does nothing and the player is stuck in gamemode 3 (spectator mode). Is this a mod that allows this or a bug? I used commands to restore them to Survival mode but it would be nice to know if this is as intended.

UPDATE: When a player dies they go into spectator mode. The back command was miscommunicated as the issue.

UPDATE UPDATE: I'm a moron. I left Hardcore mode on instead of Hard mode. Just... just shoot me.

**Comment by OrdinatorStouff** [comment]
Thanks for the detailed report regardless. I'm glad you got it sorted out. :) 👍
