### ISSUE TITLE
Crafting Recipes

### ISSUE THREAD

**Issue by Gerni-real** [AllTheMods/ATM-3#351]
Hey I found a Crafting Recipe that exist two times:

If you want to craft an Industrialcraft Solar Panel you will get a Basic Solar Panel from Tech reborn!

**Comment by OrdinatorStouff** [comment]
Thank you for taking the time to report this, but we already have an open issue here: https://github.com/AllTheMods/ATM-3/issues/331 for this exact same thing.

It's **should** be addressed in the next update
