### ISSUE TITLE
End Lapis Ore (Cyclic) causes a Game/Server Crash

### ISSUE THREAD

**Issue by Henri979** [AllTheMods/ATM-3#353]
Hello there,
our Server crashed twice (5 min inbetween) after mining End Lapis Ore (from Cyclic). He used an Tinker Pickaxe (Cobalt Head/Cobalt Binding/Titan Handle/[following upgrades: Unbreakable, Luck 3, Excavate Level 25, Hastester]).
We guess its caused by Cyclic and the Excavate Modifier from OreExcavation Integration.

We don't have access to the files yet. If I get access to the crash log I will post it.

If you need anything else (I guess you do since I only have very less data) ask.

Version: allthemods 3 v.5.6
MC-Version: 1.12.2 (with mods) forge-14.23.1.2568

**Comment by OrdinatorStouff** [comment]
I will try to reproduce when I can but yes we very much do need the crash log to see what the root cause is and how to fix it (or which mod author to report it to)

**Comment by OrdinatorStouff** [comment]
We duplicated this setup exactly on the ATM3 official server (also 5.6) including the exact tinker's pick parts and modifiers. We were able to excavate a vein of cyclic end lapis ore multiple times and not encounter a crash. 

That means without being able to reproduce on our end we can't do any more troubleshooting until we can see your relevant server crashlogs.

**Comment by OrdinatorStouff** [comment]
It's been a while with no response and we just released pack version 5.7

If you're still having issues on 5.7+ please open a new issue with crash logs (since we couldn't reproduce it on our server)
