### ISSUE TITLE
Infinite "Building Terrain" when generating new world

### ISSUE THREAD

**Issue by BenjaminZimbal** [AllTheMods/ATM-3#354]
When I was creating a new world in all different world types and all different game modes I cannot get past the text "Building terrain". Forcing the game to shut down and bringing it back up it shows the newly generated world with the correct game mode and world type. 

After loading the newly generated world and being ingame there are no issues whatsoever - terrain is ok and everything else seems to be alright. I simply cannot get into the world when I am generating a new one and have to restart the game before playing on a new map.

Some more info:
I am on the most recent version of the modpack.
There were no mods or ressourcepacks added to the game.
The modpack has got 8GB of RAM which it can use (but never did yet).

**Comment by Ravalli03** [comment]
I'm having the same issue, downloaded the modpack today from twitch and can't get past the loading screen. I have made 0 changes to the pack. I have a gaming computer with plenty of RAM.

**Comment by BenjaminZimbal** [comment]
@Ravalli03 Remember that the world will still be generated and you just have to force-close minecraft and start it again; after that you can join your world and play with it. If you run into terrain issues or anything of that kind please leave another comment~

**Comment by OrdinatorStouff** [comment]
I'm certain this is related to the JustEnoughDimensions fix where the latest version of JED allows the world to be created without issue. (JED isn't the problem, the just get "stuck" with it)

Either exit and reload and see if the created world is there and loads fine, OR if not, update JED manually to the latest version on curse and try to create a new world.

JED will be updated in latest pack version update that is coming soon in a couple days, as well.

**Comment by Ravalli03** [comment]
The world loaded just fine after restarting. Thanks

**Comment by BenjaminZimbal** [comment]
Thanks @OrdinatorStouff for your help. I guess it will be fine after the modpacks update. Have a nice day!
