### ISSUE TITLE
ATM3 server

### ISSUE THREAD

**Issue by Sosig11** [AllTheMods/ATM-3#355]
https://pastebin.com/0dKXF0vs

pc crashed while server running, fatal error, connection terminated

**Comment by OrdinatorStouff** [comment]
There's nothing terribly obvious in that log. Is that from the server or the client?

You say "PC Crashed" do you mean like a blue-screen or reboot or did you instead mean that the game client or server crashed?

Are you using the ATM3 serverfiles download and the included serverstart batch file?

Also that log says it's Forge 2570 but the most recent version of the modpack (5.6) currently is using 2568, is this a server for 5.5 pack version then and if so have you tried updating to 5.6 and see if the same problem happens?

**Comment by Boomflex** [comment]
Please update to latest pack version.

Issue closed due to being non-reproducible.
