### ISSUE TITLE
Nether stars duplication with Industrial Foregoing mob crusher

### ISSUE THREAD

**Issue by balkongo** [AllTheMods/ATM-3#356]
I placed down four mob crushers and connected them with TE signalum-plated itemducts and resonant servos and each of the four crushers often got a star, from ten witherbosses I got atleast 20 stars. Only when servos was set to high redstone signal.

**Comment by Boomflex** [comment]
Hey @balkongo are you able to test this in 5.9.2 for me?

Buuz, the Dev added specific checks in IF v1.8.5 that hopefully should stop this.

Let me know!

**Comment by balkongo** [comment]
Hi @Boomflex! I tried to recreate it with about 30 wither bosses and there was no star duplication. 30 wither bosses resulted in exactly 30 stars.
