### ISSUE TITLE
Scrapbox Loot Table Issue

### ISSUE THREAD

**Issue by NNikia** [AllTheMods/ATM-3#357]
The Scrapbox's current loot table is just wooden farming hoes and dirt.

**Comment by OrdinatorStouff** [comment]
Members of IC2 dev team confirmed via discord that the Hoe percentage is not currently configurable. The other items listed on the ic2 wiki for scrapbox output are still technically in the loot table but there's a 99.5% chance that output will be wooden hoe.

![image](https://user-images.githubusercontent.com/6283913/34853602-e1aa1ff0-f6f1-11e7-86bc-8071f2279e87.png)

If and when we get the ability to modify the scrapbox loot table, we will but for now there's nothing that can be done about **IC2** scrapboxes loot table at this time.
