### ISSUE TITLE
Advanced Rocketry 

### ISSUE THREAD

**Issue by RedChaos56** [AllTheMods/ATM-3#360]
no destination selected in red writing wont go away
![2018-01-09_16 48 25](https://user-images.githubusercontent.com/35255979/34713298-ca13702c-f560-11e7-83a5-563a7962de03.png)

**Comment by OrdinatorStouff** [comment]
Does this persist even after exiting to the menu (or exiting whole game) and going back in? Have you done anything with any AR machines in this world? Does it show up in new worlds too?

**Comment by OrdinatorStouff** [comment]
closing for no reply
