### ISSUE TITLE
Quantum Quarry / Actuator disabled. How to enable?

### ISSUE THREAD

**Issue by Kilajan** [AllTheMods/ATM-3#361]
Hello. I see that the Quantum Quarry and Actuators are disabled in the mod (<extrautils2:quarry>: Disabled due to lag/performance impact)

I would like to be able enable the recepie again. How can I do that? Can't find where too. Find it annoying, because it's only me playing, and I don't want to "cheat" with creative mode. Please help. :]

**Comment by OrdinatorStouff** [comment]
In the next update that should be out in a couple days we're going to "test the waters" and actually re-enable the ExU2 quarry again. If you're in no rush then just try it in pack version 5.7.

If you want to get into it sooner, though you can edit [packmodes_balance.zs around line 160](https://github.com/AllTheMods/ATM-3/blob/master/overrides/scripts/packmodes_balance.zs#L160) where the recipes are disabled and just delete those few lines from the script file. If you're playing on a dedicated server, you'd have to make the change in the server files script as well.
