### ISSUE TITLE
Dimension ID problem

### ISSUE THREAD

**Issue by garrett-may** [AllTheMods/ATM-3#362]
Apologies in advance if this is a duplicate. https://github.com/AllTheMods/ATM-3/issues/291 mentions something similar, but I believe it refers to v5.2 of the modpack.

When playing with the All The Mods 3 v5.6 modpack, building a rocket and then going to the Moon actually caused me to go to another dimension, the Dark Realm. Is this a bug to be fixed on Advanced Rocketry's side, or on All The Mods 3's side, or something a server should configure involving dimension IDs?

Note: this did not occur in a previous version of the modpack, but All The Mods 3 v5.4 has the bug involving the Chemical Reactor crash.

Reproduction:
 - Build a valid rocket, with a seat and rocket fuel
 - Travel to the Moon (Luna)
 - Note that the rocket does not land on the Moon

**Comment by OrdinatorStouff** [comment]
Any Advanced Rocketry dimension mix-ups should be resolved in any NEW worlds created. However if you have an existing world with these kinds of problems, deleting the `planetDefs.xml` file from the save/world data files should resolve it. Can you try deleting that file and restarting and let me know if it's still an issue or not?

(Also pack version 5.7 just came out that might be worth updating to or looking into as well)

**Comment by garrett-may** [comment]
Hi there, I have attempted the following:

- Create a new world, build a rocket, fly to Luna
- Play an existing world, delete the `planetDefs.xml` file, build a rocket, fly to Luna
- Play an existing world, build a rocket, fly to Luna, delete the `planetDefs.xml` file

In all cases I am not taken to Luna, but the Dark Realm, and deleting the `planetDefs.xml` file does not change this. This occurs on both v5.6 and v5.7b of the modpack.

**Comment by Yoosk** [comment]
Seems to be working fine in 5.9.5, after generating new world, Luna looks like normal moon is supposed to.

**Comment by Boomflex** [comment]
Older version of pack.

Please try newer version in New World.
