### ISSUE TITLE
Crash on SP caused by keyboard input

### ISSUE THREAD

**Issue by DKnightADRI** [AllTheMods/ATM-3#364]
When changing a certain control to the '<' button on my keyboard, it caused the [following crash](https://pastebin.com/gtMzYzan).

**Comment by OrdinatorStouff** [comment]
Looks like it might be caused by InvTweaks. Can you tell me which keybind it was that you were trying to change, by chance? Is it repeatable (i.e. can you cause the crash again at any time by changing that same keybind to `<` again?

**Comment by DKnightADRI** [comment]
Good question. I wish I was able to check. I do not remember which control I changed it into but there should be a way to check this through files right? If it's repeatable? Yes. I think. I mean, I haven't been able to get on SP because of this.

**Comment by DKnightADRI** [comment]
Seemed to be the sorting keybind of InvTweaks.
-----options.txt-----
`key_invtweaks.key.sort:316` (crash)
changed this too
`key_invtweaks.key.sort:0` (no crash)

Maybe this is because java doesn't 'know' this key? I have a[ german keyboard ](https://i.imgur.com/5sBnzWM.jpg)which may be a little bit different? Couldn't find what button 316 is linked to on the internet either.

**Comment by Boomflex** [comment]
Non-reproducible.
