### ISSUE TITLE
Tinker's Construct Problems

### ISSUE THREAD

**Issue by maestro3000** [AllTheMods/ATM-3#366]
There's a lot of missing stuff for tinker's construct. The flamestring is impossible to get because the spider mob doesn't spawn, and the current bowstring options are identical in stats. There's also a lack of fletchings, and very few possible bolt cores.

**Comment by OrdinatorStouff** [comment]
Most of what you're referring to is very subjective (i.e. you **feel** like there is a lack) when I'm not sure if there's anything "missing" versus what the mod has to offer. The heatscar spider string I can look into but in general the stats/options are provided by Tinker's directly and there's not a ton of customization we can even do at a modpack level.

We'll try to look into it still though and make sure nothing's amiss.

**Comment by RyanP1991** [comment]
The flamestring is impossible to get due to the heatscar spider comes from Natura, not tinker's construct. Looking at the Natura configs it says:

"    B:"Enable Heatscar Spiders"=false  "

**Comment by Boomflex** [comment]
Working as currently intended.

Closed.
