### ISSUE TITLE
UU-Matter Uses

### ISSUE THREAD

**Issue by maestro3000** [AllTheMods/ATM-3#367]
There are no end-game uses for UU-matter except for one

**Comment by OrdinatorStouff** [comment]
UU-Matter (liquid) should be usable in the IC2 Mass Fabricator to "duplicate" just about any vanilla item or IC2 item. 

If you're referring to the solid "item" form from Tech Reborn, that is not intended to have recipes/uses except for the endgame ATM Star recipe stuff. 

Mass Fab recipes aren't shown in in JEI though so you'd have to reference an IC2 guide for how that works and what you can get

**Comment by Boomflex** [comment]
Working as intended.
