### ISSUE TITLE
Tweak configs for OpenBlocks elevators

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-3#368]
Things like searchDistance and maxPassThrough

**Comment by Boomflex** [comment]
Made the Elevators a little more "balanced" and also changed the spawning on each platform centre to stop potential suffocating and health loss in Commit:https://github.com/AllTheMods/ATM-3/commit/05d6428e93a96e919656c9dc98eede85594ad433

**Comment by Seegras** [comment]
With max Distance 8, it's now too low for my Baroque Chateau (which I built before this change) which would need 10, with 3 thick ceilings. I think 8 is way too low for a lot of detailed builds, and it now mostly favours low ceilinged-buildings. Please reconsider.

**Comment by Yoosk** [comment]
Or you can use travel anchors.
