### ISSUE TITLE
16/15 people on the server.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#37]
Pack version: 2.0

If one person disconnects at 15/15 and 2 people are fast enough to join they both can.

**Comment by OrdinatorStouff** [comment]
Thanks for the heads up but I'm not really concerned about this. I only bumped the max players down slightly to help combat lag at peak times anyway, the same problem would be possible with 21/20 players theoretically, or 501/500, etc. Lowering to 15 from 20 was just to try to "take a little edge off" with lag issues.

I should bump it back up to 20 for now that it's been reset, though...
