### ISSUE TITLE
Portalgun and Chemical Thrower not working?

### ISSUE THREAD

**Issue by xorinzor** [AllTheMods/ATM-3#374]
I think it was version 5.3 or 5.4 when we tested the modpack and the Portal Gun was working, havent used it since, until a player used it again a few days ago.

Now the Portal Gun didn't seem to work in 5.6, but the Chemical Thrower did.

Now after the update to 5.7 both the portal gun and Chemical Thrower don't seem to work.
Despite the Chemical thrower making the sound, and the tank contents to lower while using it (just no effects seem to be made).

I was wondering whether if this issue is something specific for my server, or happens on other servers too (ie: modpack related).

**Comment by Boomflex** [comment]
Please update to version 5.7c and re try.

Thanks.
