### ISSUE TITLE
Cartographer map recipes missing

### ISSUE THREAD

**Issue by xorinzor** [AllTheMods/ATM-3#375]
The recipes for the OpenBlock Cartographer maps seem to be missing.

Only the 1:1 scale works, the 1:2 shows in JEI, but doesnt work, and 1:4 and 1:8 don't have a recipe at all.

**Comment by Boomflex** [comment]
This is an issue with the Mod, not the modpack.

I have raised it with OpenBlocks.

https://github.com/OpenMods/OpenBlocks/issues/881
