### ISSUE TITLE
Quantum Storage Disk does not return Schwarzschild's Sphere

### ISSUE THREAD

**Issue by ouroborus** [AllTheMods/ATM-3#376]
@OrdinatorStouff [let me know](https://www.reddit.com/r/allthemods/comments/7qidaw/atm_star_and_overloaded_spoilers_atm3/dsqa1xh/) that the Schwarzschild's Sphere should be returned when crafting a Quantum Storage Disk. Currently (5.5 and probably up through 5.7), it is not returned.

**Comment by Boomflex** [comment]
Recipe has now changed.

Please update to latest pack version.
