### ISSUE TITLE
Ticking baubles causes internal server error

### ISSUE THREAD

**Issue by OsirisKalev** [AllTheMods/ATM-3#377]
Hi there.

After updating to ATM3 5.7, I've come across an issue where I was immediately kicked from my current world with an internal server error. Checking the server logs pointed to baubles behaving incorrectly. I edited my player file and deleted my baubles, then reconnected and re-added the baubles (specifically, Ring Of Aura, Ring of Mana and Soujourner's Sash). As soon as I added the sash, I was disconnected. I then did the same again, except without the sash. As I am wearing Botania armour, upon taking damage and having some mana drained from the Ring of Mana, I was disconnected again.

I did some tests on a clean server and a clean singleplayer world and was able to replicate this issue (in the case of the singleplayer world, it just outright crashes the client).

I was able to fix this problem by downgrading Baubles from version 1.12-1.5.2 to 1.12-1.5.1.

**Comment by ogradyjd** [comment]
Looks like I'm hitting this too.

[crashlog.txt](https://github.com/AllTheMods/ATM-3/files/1636192/crashlog.txt)

**Comment by ogradyjd** [comment]
This might help.  Looks like you might have to downgrade baubles to fix until baubles fixes something?  I'm at work and don't have time to grok the whole thread....
https://github.com/Vazkii/Botania/issues/2517

**Comment by OsirisKalev** [comment]
Yeah, I figured out the downgrading worked (as written at the bottom of the comment), but it's good to see that there's a report on Botania's issue page as well.

**Comment by Boomflex** [comment]
Please update to v5.7c of the pack.

This is now fixed.
