### ISSUE TITLE
Can't disable waypoints in JourneyMap

### ISSUE THREAD

**Issue by Gravecat** [AllTheMods/ATM-3#378]
As of version 5.7 of ATM3, with the new beta version of JourneyMap, it's impossible to disable waypoints, they're active and visible at all times and the button to turn them off does not work. This issue is still present in ATM3 5.7b, and is a known issue in JourneyMap 1.12.1-5.6.0b1: https://github.com/TeamJM/journeymap/issues/15

Edit: Apparently there's a "workaround" of disabling ALL waypoints at once, but there's no way to disable individual waypoints while leaving others active.

**Comment by Boomflex** [comment]
Mod issue. 

Will update when update is released from Dev.
