### ISSUE TITLE
Cyclic crashing game

### ISSUE THREAD

**Issue by Mukkod** [AllTheMods/ATM-3#379]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Cyclic (cyclicmagic)

thats all i have as far as crash report. it doesnt seem to have given me a crash log of any kind.

**Comment by Boomflex** [comment]
If it is crashing the game it will give you a crash log. 

What pack version are you using?

**Comment by Mukkod** [comment]
clicking view crash log does nothing, and im running 5.7

**Comment by Boomflex** [comment]
Can you update to the latest version of the pack 5.7b and let us know if it persists.

**Comment by Mukkod** [comment]
i did and it did, i tried reinstalling the pack but it wouldnt let me install. im currently trying reinstalling twitch and then the pack

**Comment by SpeedSlider** [comment]
Were you able to resolve this issue? If not using pastebin to post the crash report will help us.

**Comment by Boomflex** [comment]
Twitch App issue.

Reinstall latest version.
