### ISSUE TITLE
Journey map only has map function

### ISSUE THREAD

**Issue by Kinluki** [AllTheMods/ATM-3#380]
Version 5.7b

With the latest update there seem to be a lot of issues with Journey map. 

- Info like fps, time etc are not displaying at all at the minimap. 
- Waypoint can't be used for teleporting
- Waypoint can't be turn of individual. 

Maybe going back to the release version instead of the beta one?

**Comment by Boomflex** [comment]
Mod issue. 

Will update to hotfix when they release the fix. 

Will not hotfix with a downgrade.
