### ISSUE TITLE
Flugel Tiara Crash

### ISSUE THREAD

**Issue by maestro3000** [AllTheMods/ATM-3#381]
When you equip and try to use the Flugel Tiara, it instantly kicks you from servers with an IOException error or internal server error

**Comment by Boomflex** [comment]
What pack version?

**Comment by maestro3000** [comment]
Second to newest

**Comment by Boomflex** [comment]
Please update to newest and let us know if it carries on.

**Comment by Boomflex** [comment]
This was an issue with Baubles.

Fixed in v5.7
