### ISSUE TITLE
Cannot create a world

### ISSUE THREAD

**Issue by xYnizzle** [AllTheMods/ATM-3#384]
Hello everyone. Just been having some issues creating a world. Im using the twitch launcher, everything is up to date and for the past couple hours been trying to create a world for me and some friends. Shouldnt be any hardware limitations or speed issues, wondering if anyone has any suggestions. I have a 7700hq, 1060, 1tb ssd, 16 gb ram etc...
Thanks for your help :)

**Comment by DKnightADRI** [comment]
Sounds like a issue where you haven't allocated enough RAM. I recommend 6gb without texture pack. Would you mind getting a log because based on this information, I may even be entirely wrong of what the actual problem is.

**Comment by Boomflex** [comment]
Please confirm what pack version and your allocated RAM?

**Comment by Ravalli03** [comment]
When you mean having issues, are you talking about getting stuck on the loading screen? If so, restart minecraft and a saved world should be there. It's an issue for everybody but not sure if the new update has fixed it.

**Comment by xYnizzle** [comment]
Just would like to say that yeah, it was an issue with ram. We hadn't played minecraft in years so forgot all about that. It defaulted to like 2 gigs so I gave it 8 and it works perfectly. Thanks for suggestions :)

**Comment by SpeedSlider** [comment]
Glad this issue is resolved sounds like it is ready to be closed.

**Comment by Boomflex** [comment]
Resolved.
