### ISSUE TITLE
Baubles 1.5.2 bugged

### ISSUE THREAD

**Issue by Retzudo** [AllTheMods/ATM-3#385]
ATM v.5.7b ships with Baubles 1.5.2 which causes some issues in conjunction with Botania:

1. Having a equipped Soujourner's Sash as a Baubles caused my world to crash on load
2. Dropping an item with `Q` while having a Ring of Magnetization equipped causes the item to be deleted.

Downgrading Baubles to 1.5.1 resolved the issue for me.

https://github.com/Azanor/Baubles/issues/241
https://github.com/Azanor/Baubles/issues/243

**Comment by ogradyjd** [comment]
This is most probably the same issue as reported in #377

**Comment by Boomflex** [comment]
Please update to pack version v5.7c as we downgraded Baubles.
