### ISSUE TITLE
[ATM3 5.7b] Minecraft hangs upon opening Gendustry compartment

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-3#388]
I have an older Gendustry compartment https://binnie.mods.wiki/wiki/Compartment which workes in 5.6. When i open it now, the system hangs (like a never ending lag) no crash and diplyes no content. i have to force Mincraft to end. It is reproducable.

**Comment by Boomflex** [comment]
Please update to the latest version of the pack v5.7c.

Thanks.

**Comment by DietmarKrause** [comment]
still an issue in latest version of the pack, 5.7c. Just updated. GUI opens but do not show any contents and Minecraft hangs without responding to anything.

**Comment by Boomflex** [comment]
Please report to Gendustry Github.
