### ISSUE TITLE
ExtraUtils AutoCrafter wont let u put items in it.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#39]
ExUtils version: 1.12-1.5
Forge version: 2407

When u try to put items into the Crafter it kicks u out of the GUI.

**Comment by Electrofried** [comment]
To add to this, if you put items in the crafting window by using NEI you will crash the game when trying to click on them. Probably an Extra utilities bug. will report on there.

**Comment by OrdinatorStouff** [comment]
https://github.com/rwtema/extrautilities/issues/1652
https://github.com/rwtema/extrautilities/issues/1675
[...and many more](https://github.com/rwtema/extrautilities/issues?utf8=%E2%9C%93&q=is%3Aissue%20crafter)

The analog crafter seems to work okay but the mechanical crafter is still messy. Will disable recipe

**Comment by Boomflex** [comment]
No longer an issue in latest versions.
