### ISSUE TITLE
crafting reactor casing

### ISSUE THREAD

**Issue by Sosig11** [AllTheMods/ATM-3#391]
cannot craft reactor casing. 

using atm3, version 5.5. 
recipe needs 4 carbon plates, 2 steel blocks, one advanced alloy and pressure vessels,
i used ic2 carbon plates and thermal expansion steel, techreborn advalloy.
recipe only shows output in drac chest.

**Comment by Yoosk** [comment]
That's an old version of pack, have you tried to update?

**Comment by Boomflex** [comment]
Currently working as intended.

Please update to latest version of the pack and ensure that the Scripts folder is updated too.
