### ISSUE TITLE
Compact Machines Lag

### ISSUE THREAD

**Issue by Ravalli03** [AllTheMods/ATM-3#393]
When entering anytime in any size compact machine (empty or not), there it's really bad spike lag that last for the first 30 seconds or so then goes away. According to author, it's not coming from his end. 

Playing on newest pack version: v5.7c

**Comment by scotty9090** [comment]
Same here, noticeably more laggy than the same mod used in the DW20 pack.

**Comment by Boomflex** [comment]
Please update to latest pack version v5.8
