### ISSUE TITLE
[Suggestion] Tweak the opinium core recipes to include modded metals

### ISSUE THREAD

**Issue by ManMan36** [AllTheMods/ATM-3#395]
Right now, the ATM star requires thousands of iron and gold ingots but very little of any other metals. I would like to see other metals such as bronze incorporated. This could be done by changing the tier 2 opinium core's iron blocks to bronze blocks. The same could be done with the other repeated vanilla metals. It would make the recipes a little more interesting.

**Comment by ogradyjd** [comment]
Are you insane?!?  Don't give the dev ideas!  He'll make it so we have to kill Herobrine himself to create the opinium cores!  Wait... did I just say that?  Crapbaskets....

**Comment by Boomflex** [comment]
For now, the recipes are what they are.

However, it is a great idea and one we will look in to in upcoming packs.
