### ISSUE TITLE
'Starting greenhouse thread' stalling server install

### ISSUE THREAD

**Issue by makmammalattack** [AllTheMods/ATM-3#396]
When using the server batch file, it stalls on "[Forestry Greenhouse/INFO] [forestry]: Starting greenhouse thread"

I've tried uninstalling, reinstalling, restarting, etc. etc. but cannot get it to move past this point no matter how long I leave it up. I have server properties set to allow 13 GB of RAM so that shouldn't be the issue. Removing the forestry mod made it get caught in a crash loop about 10 seconds into the attempted install. 

Running the server jar gets stalled in this same spot and gives the classic "something's taking too long" error. Haven's had any luck waiting on that either. Please, please give me a solution.

**Comment by OrdinatorStouff** [comment]
"Starting greenhouse thread" is *usually* the last thing you'd see after the server is done starting up and ready to accept players and "just work"

Did you try connecting to the server or running a command like `/list` in the console and see if it responds?

**Comment by Boomflex** [comment]
No further information and non-reproducible.
