### ISSUE TITLE
Cyclic/Advanced Generator recipe conflict

### ISSUE THREAD

**Issue by metnavman** [AllTheMods/ATM-3#397]
There's already a script written for this within the atm_recipeconflicts_misc.zs file:

//(Redstone Clock) <cyclicmagic:clock:0> * 1 conflicts with [Shaped] (Control Circuit) <advgenerators:controller:0> * 1
	recipes.remove(<cyclicmagic:clock:0>);
	recipes.addShaped(<cyclicmagic:clock:0>, [
		[<ore:ingotIron>,            <minecraft:redstone_torch>, <ore:ingotIron>],
		[<minecraft:redstone_torch>, <ore:gemQuartz>,            <minecraft:redstone_torch>],
		[<ore:ingotIron>,            <minecraft:redstone_torch>, <ore:ingotIron>]
		]);

The issue I'm having is that this script does not appear to be working properly. The cyclic clock recipe is still defaulting to the same recipe as the adv generator controller chip and overwriting it, making it impossible to craft the chip. Is this script written incorrectly, or is there something else going on? Thanks for the assist!

**Comment by Boomflex** [comment]
Recipe works in v5.7c as intended

![image](https://user-images.githubusercontent.com/22868795/35781436-0fe0e752-09e2-11e8-8e53-b9e8bbddb283.png)

Please update to latest pack and ensure that the Scripts folder is also updated.
