### ISSUE TITLE
[Mod Sugestions] Attractor and SpatialCompat

### ISSUE THREAD

**Issue by MrDj200** [AllTheMods/ATM-3#398]
Hey there,
Love the pack, thanks for the Hard work maintaining it!

I got 2 Suggestions for mods to add:

1. [Attractor](https://minecraft.curseforge.com/projects/attractor)
2. [SpatialCompat](https://minecraft.curseforge.com/projects/spatialcompat)

### Attractor:
Adds 1 Block

A block to attract mobs.
Can be reversed with Redstone.
Range Configurable.
Possibillity to make a different mob farm than usual.

### SpatialCompat
Adds no Blocks

Adds all Modblocks to the AE2 Spatial Storage Whitelist.
Is able to be installed as Server-only mod.

## ---------------

Thanks for reading, and maybe considering, my suggestions.
Have a nice day!

-Dj

**Comment by ogradyjd** [comment]
There's an issue for mod suggestions - you might want to move this there: #1

**Comment by MrDj200** [comment]
Oh, sorry my bad. 
Thanks for the Heads up!
