### ISSUE TITLE
Random red-ish tint

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#40]
Pack Version: 2.0

People randomly get a red tint in the game, disappears after an unknown amount of time.

![](https://cdn.discordapp.com/attachments/192287258362118145/335181861410045962/2017-07-13_18.12.50.png)

**Comment by DietmarKrause** [comment]
i habe noticed some sort of Eclipse during some days. As if the moon darkendes the sun. During this period mobs spawn even during the day. Can be related. perhaps the light is red-ish during this period. But i dont know what mod is causing that.

**Comment by TheElectricCake** [comment]
Unsure if this is eclipse-related. Sometimes it affects some people online but not others. An eclipse should theoretically affect everyone on dim0 at the same time.

**Comment by OrdinatorStouff** [comment]
Could this be the worldborder warning hue for being too close to worldborder?

**Comment by whatthedrunk** [comment]
Closing more old issues that I haven't noticed. Feel free to open back up if you notice on ATM3 4.0+ Thanks :D
