### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by Phixaen** [AllTheMods/ATM-3#401]
I've run across a few recipes that I can't make - even if I look them up and put all the correct items on the crafting table like the atomic reconstructor, charcoal block, emerald chestplate, iron casing (actually additions), garden trowel (water strainer) and wind mill, fluid router, current transformer, hv & normal transformer lv & hv, mv wire connector/relay the lv & mv capacitors, copper coil block, charging station (immersive engineering).  Is there a specific file I can delete to get these all back?
edit : adding missing recipes

**Comment by Phixaen** [comment]
Integrated Dynamics : squeezer is also missing

**Comment by OrdinatorStouff** [comment]
This sounds like an issue where the scripts folder was altered or not updated properly. We've seen this a lot with servers using CreeperHost. 

1) Is this a server or strictly single player?
2) If server, what host?
3) If Single Player what client?
4) Are you playing in simplified packmode or normal?
5) have you added or removed ANY mods at all?

**Comment by Phixaen** [comment]
Server, theminecrafthost, switched to simplified thinking it would fix it and yes but after I noticed missing recipes - added nomorerecipeconflict hoping it would help

**Comment by Phixaen** [comment]
I'm so sorry for bothering you, I think I wasted your time.  Took the time to backup my world, delete everything on the server and re-upload the pack and it all works fine now.

**Comment by OrdinatorStouff** [comment]
Not a waste, I'm just glad you were able to figure out a solution. Just an FYI if you change packmode on the server, your client (and any other clients that use the server) also have to change it and reboot as well.

Please feel free at any time to ask questions or give feedback, it's always welcome.
