### ISSUE TITLE
Refined Storage / Inventory Tweaks Conflict

### ISSUE THREAD

**Issue by scotty9090** [AllTheMods/ATM-3#404]
Trying to grab a single item out of RS using middle click causes Inventory Tweaks to try to sort the inventory, making it difficult to try to do this multiple times in succession.  

This is a reported bug for Inventory Tweaks but since both are in this pack and I didn't find another issue related to it, I'm wondering if there's a way around this - or suggestions short of swapping out Inventory Tweaks for Inventory Sorter (which doesn't have this problem)?

**Comment by Ravalli03** [comment]
You can reassign the keybinding to something esle

**Comment by scotty9090** [comment]
I've tried that but I guess it's going to need to be a key that I never press when using RS otherwise the same thing happens.  E.g. I reassigned it to 'R' and whenever I type anything with 'R' in the RS search box it tries to sort.  I'll give this another shot with an unused key.

**Comment by scotty9090** [comment]
For reference, here is the issue on the Inventory Tweaks repo (it's been there for a while now so not sure a fix is happening any time soon.)

https://github.com/Inventory-Tweaks/inventory-tweaks/issues/518

**Comment by Boomflex** [comment]
Mod issues. 

Not fixable by pack.
