### ISSUE TITLE
tohohealth damageindicators

### ISSUE THREAD

**Issue by Wirquarian** [AllTheMods/ATM-3#405]
ATM3 pack lacks damage info , tested torohealth damageindicators mod , works perfectly.
displays useful damage numbers and is tiny in size , only 64.8KB
its client side mod , also i suggest in config display time should be 800+ , the default is 400

**Comment by Boomflex** [comment]
Please put this as a Mod Suggestion: https://github.com/AllTheMods/ATM-3/issues/1
