### ISSUE TITLE
(Server) Stuck on "downloading forge 1 of 2 steps"

### ISSUE THREAD

**Issue by Chiggahim** [AllTheMods/ATM-3#406]
I'm trying to setup a server and I first have to start the serverstart.bat file. However it remains stuck on the downloading forge screen for 10 minutes. I've tried allocating 8 gb of ram and still no dice. Help appreciated!

**Comment by RhyxMormarteno** [comment]
Solution download forge installer put it into server files catalog where you got your serverStart/bat/ssh with version you yot in cfg file and it will work from there

**Comment by Boomflex** [comment]
Currently not reproducible.

Please try to download the correct files direct from Forge and put in to the same folder as the serverstart.bat

**Comment by jamesxsc** [comment]
This was reproducible when running from a network mapped drive for me.
