### ISSUE TITLE
Refined Storag Thermal Foundation won't craft Electrum

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#41]
RS Version: 1.5.9
Thermal Foundation: 1.12-2.3.2.8

Whenever u try to craft electrum using an Induction Smelter it won't craft and shows this instead:

![](https://puu.sh/wIZH4/2cd7702022.png)

**Comment by DietmarKrause** [comment]
help me if i am wrong...... electrum is Gold + silver (not invar) or am i wrong?

**Comment by gefailter71** [comment]
It is indeed and said ingots are in the recipe for the Induction smelter but invar and gold will show up :)

**Comment by Boomflex** [comment]
Can't reproduce.

Maybe the pattern was incorrect?
