### ISSUE TITLE
AbyssalCraft / BOP - AbyssalCraft mobs spawning where they shouldn't

### ISSUE THREAD

**Issue by scotty9090** [AllTheMods/ATM-3#413]
I'm getting AbyssalCraft mob spawns in my lovely White Beach biome from BoP - which wouldn't be such a big deal except for the black ooze everywhere.

I'm guessing this is a biome ID conflict?  I can't see a way to change (or even find) the AbyssalCraft biome IDs and I'm not sure what the ramifications are of changing a BoP biome ID in an existing game.  Advice?

**Comment by Boomflex** [comment]
Non-reproducible in the worlds I started.

Will keep an eye on it.

Thanks for report!
