### ISSUE TITLE
Slate compression

### ISSUE THREAD

**Issue by FlutterAi** [AllTheMods/ATM-3#414]
Most common overworld resources have an a recipe added into Overloaded to compress them 9:1, up to 4 times compression. Slate, which is about as common as marble, does not. This is simply a suggestion to include it in the list of Overloaded recipes.

**Comment by SpeedSlider** [comment]
This issue should be tagged as suggestion to be considered for future update. It may not make the current working update as we are trying to get journeymap issues addressed as quickly as we can.

**Comment by OrdinatorStouff** [comment]
should be added in 5.9
