### ISSUE TITLE
Server crash using version 5.8 (Code: "Settings.cfg_Error:MAX_RAM")

### ISSUE THREAD

**Issue by Mekanofreak** [AllTheMods/ATM-3#417]
I update my server to the new 5.8 release and When runnig the ServerStart file I get this error :

```
FIND: /I: No such file or directory
FIND: MAX_RAM=: No such file or directory

**** ERROR ****
There was an Error, Code: "Settings.cfg_Error:MAX_RAM"
```
Went back to 5.7c and it runs fine.

**Comment by Boomflex** [comment]
I have redownloaded the Server Files from CurseForge and ran them to no issue 3 times in a row.

I would advise that you redownload the files and try again fresh,

Non-reproducible.

**Comment by SpeedSlider** [comment]
@Mekanofreak I know the ATM official server just upgraded and didn't have any issues. You may want to try our discord #help-desk and pinned messages. Perhaps there is a step we do differently that may fix your problem.

**Comment by Mekanofreak** [comment]
Redownloaded the files and tried again, still get the same error, any log I can send you to help find the cause ?

**Comment by SpeedSlider** [comment]
The only recommendation I have is to work with the #help-desk channel in our discord https://discord.gg/FdFDVWb. One other thing. I noticed in the readme.md file in the main folder of the server files that the default max ram setting is 5 Gb so if you are using less that may be the cause of your error.

**Comment by Mekanofreak** [comment]
I uploaded the update on my server (was testing it on my home computer running windows 10 before uploading ), and it works, the server is a dedicated server running ubuntu. so maybe something to do with my home computer, tough it can run 5.7c just fine. So not mutch of a problem. Just to add more info, the machine I was testing it on got 32g of ram, so its not the problem, the setting file was also not changed from default so it still use 5g.
