### ISSUE TITLE
Keeps crashing during minecraft startup 

### ISSUE THREAD

**Issue by 1-Like-Pi** [AllTheMods/ATM-3#419]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Comment by SpeedSlider** [comment]
How much ram do you have allocated? This issue might be better resolved using our discord #help-desk channel. https://discordapp.com/invite/FdFDVWb

**Comment by Boomflex** [comment]
I would recommend making sure you had 6GB of RAM allocated and download a fresh instance.

Sounds like an issue while downloading.
