### ISSUE TITLE
Morphing Tool doesn't work.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#42]
Morph-o-Tool version: 1.12-15#
Forge version: 2407

Whenever u try to use the wrench it won't change to the wrench u need and just doesn't work.

**Comment by Darkere** [comment]
Fixed

**Comment by OrdinatorStouff** [comment]
Confirmed working BUT just in case anyone doesn't know how it works, it switches tools based on the block you're looking at:

https://gfycat.com/gifs/detail/BrightPartialCentipede
