### ISSUE TITLE
IE Crusher Problem

### ISSUE THREAD

**Issue by RhononDex** [AllTheMods/ATM-3#420]
Der Crusher von Immersive Engineering verarbeitet keine Erze (nimmt sie nicht auf).
Cobblestone z.B. wird verarbeitet.

Bitte um Hilfe

Danke im vorraus
LG RhononDex

**Comment by Boomflex** [comment]
The Crusher from Immersive Engineering does not process any ores (does not absorb them).
Cobblestone e.g. is being processed.

Please help

Thanks in advance
LG RhononDex

**Comment by Boomflex** [comment]
This issue is not occurring on the v5.8 of the pack.

Please update if not on that version.

Non-reproducible.
