### ISSUE TITLE
[Woot] Factory_config.json errors

### ISSUE THREAD

**Issue by Ipsis** [AllTheMods/ATM-3#424]
Part 1: factory_config.json syntax error

There are errors in the factory_config.json file.
[13:40:16] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 15 column 8 path $.mobconfigs[0].configs[2]
This is due to extra "," being present at the end of the "configs" section which is invalid strict JSON.

lines 14, 31, 53, 177, 194, 211, 224

This will cause the file to stop loading at the first error. This basically knocks out all your custom configuration in this file.

Part 2: Use of whitelist

By using the "entitywhitelist" this will prevent any mob from being captured that isn't in the whitelist.
It is there for mobpacks which only want a limited set of mobs to be farmed using Woot.

Going from your other configuration you want an empty "entitywhitelist".

The only reason that this isn't currently causing issues is that due to Part 1 of this issue, this part of the file is not processed.

**Comment by OrdinatorStouff** [comment]
@Ipsis I could have sworn I ran those configs through a JSON validator at least twice each before sending them to the pack but I must have still missed that, thanks for the heads up... 

As for the whitelist I did not know that implied exclusivity -- thank you for that clarification. We're already discussing the chaos guardian in #418 which was the only reason I tied using that config in the first place.

**Comment by Ipsis** [comment]
The only other error I saw was in custom_drops.json

Woot: getItemStack: missing data for item draconicevolution:chaos_shard
Chaos Shard's have subtypes, so you need to specify which one you want to use.

**Comment by OrdinatorStouff** [comment]
Should be fixed in 5.9
(Thanks again, Ipsis <3)
