### ISSUE TITLE
Update is breaking my world..

### ISSUE THREAD

**Issue by alcheya** [AllTheMods/ATM-3#425]
https://i.imgur.com/WMlWLC0.jpg

It's regenerating untouched land and now these cliffs are all around my house and  spread throughout where I've been. Is there any way to stop this?

**Comment by alcheya** [comment]
https://i.imgur.com/ugHlwlc.jpg

Hrm.. I restarted it.. and everything is back.. Not sure what's happening..

**Comment by Boomflex** [comment]
Non-reproducible.
