### ISSUE TITLE
Woot guide manual requires Guide-API to be installed

### ISSUE THREAD

**Issue by ogradyjd** [AllTheMods/ATM-3#426]
Upgraded to latest (5.8).  Woot guide wasn't in the akashik tome, so I tried to craft one.  NEI says you need the guild-api mod installed to access the manual.

https://minecraft.curseforge.com/projects/guide-api/files

**Comment by notacompletemoron** [comment]
Seconding.

**Comment by FallenEagle1** [comment]
While this is true, if you type in jei guide, you will see that there is another book called woot guide made with a book and zombie flesh. guide-api is in the pack already, its just woot adds that uncraftable item to tell you where to look.

**Comment by Boomflex** [comment]
Guide-api is already in the pack.

As @FallenEagle1 correctly states "woot guide made with a book and zombie flesh."
