### ISSUE TITLE
Draconium ore texture is broken from the Void Miners

### ISSUE THREAD

**Issue by notacompletemoron** [AllTheMods/ATM-3#427]
Only 5.8 affected thus far.

https://imgur.com/NgpRDvk

It places in the world, and breaks, just fine.

**Comment by FallenEagle1** [comment]
To add to this, draconium ore from draconic has the metadata of 0, 1, or 2. This is overworld, nether, and end variants of the ore. The ore that the void ore miner is producing has the metadata of 32767.

**Comment by notacompletemoron** [comment]
So, is this an ET or DE bug?

**Comment by FallenEagle1** [comment]
A little bit of both it looks like. There is a issue opened up about it on the environmental tech github page and it is being taken care of there.

**Comment by Boomflex** [comment]
Mod issue.

https://github.com/ValkyrieofNight/EnvironmentalTech/issues/103

Will update when fixed.
