### ISSUE TITLE
Paper and Cardboard Box Recipes conflicting via 2x2 Sawdust

### ISSUE THREAD

**Issue by prezpaul** [AllTheMods/ATM-3#428]
The actual recipe that works for sawdust is, in a 3x3, three dust on top row and one in the middle of the 3x3.

JEI recipe shows both cardboard box and paper being the results of 2x2 of sawdust.

**Comment by OrdinatorStouff** [comment]
This is a result of my attempt to apply some correction when it was first brought up back on https://github.com/AllTheMods/ATM-3/issues/187 

My intention was to actually make the cardboard box a little more challenging than just 4 sawdust which is probably how this will be addressed.

**Comment by OrdinatorStouff** [comment]
should be fixed in 5.9
