### ISSUE TITLE
Just some Issues.

### ISSUE THREAD

**Issue by guppy488** [AllTheMods/ATM-3#429]
Issue between Mekanism and Wizardry
-
Crafting a Mana booster with any item other than a bucket of mana will consume the item entirely.

example:
Using Fluid Tank from Mekanism filled to the maximum amount possible and putting an empty syringe will cause your Fluid tank to disappear upon crafting.

- Will update more issues i see as time goes by i guess?

**Comment by Boomflex** [comment]
Please report mod bugs to the correct Mod Devs.

This is not a pack issue.
