### ISSUE TITLE
ExtraUtils2 Solar GP gen not working.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#43]
ExUtils version: 1.12-1.5
Forge verison: 2407

The Extra Utils Solars don't generate GP even when in sunlight

![](https://puu.sh/wJ0GK/10f54327ed.jpg)

**Comment by WoWaster** [comment]
Read the 2nd line, it means that now you not using any power, but all your panels generate 96 GP that can be used when needed

**Comment by gefailter71** [comment]
I tried them when I was making stoneburnt still didn't work.

**Comment by Tejasminer** [comment]
This is still an issue. Not sure how your display shows you have power. It does not show the same on mine. I tried to pickup all the parts and replace and so far no good.

**Comment by Darkere** [comment]
Already fixed.

**Comment by OrdinatorStouff** [comment]
Seems fine in my testing as well
