### ISSUE TITLE
Missing receipts from like Filter Transfer Pipe and bees.

### ISSUE THREAD

**Issue by mylace** [AllTheMods/ATM-3#430]
Missing receipts from like bees. Only got 300 receipts.

**Comment by Boomflex** [comment]
You mean recipes?

JEI hides anything with a massive amount of versions of the same item.

To change this, go to the JEI config and change the below line from 300 to a higher number

`    # Items with more than this many subtypes will not be displayed in JEI.
    I:maxSubtypes=300`
