### ISSUE TITLE
Re-enabling Steve's Carts 2 Chunkloader

### ISSUE THREAD

**Issue by turret001** [AllTheMods/ATM-3#432]
This item can't be crafted, and does not show up on JEI. 
https://ftbwiki.org/Chunk_Loader_(Steve%27s_Carts_2)

**Comment by SpeedSlider** [comment]
you should be able to use ftb claims and chunkloading feature. I am not sure if this was intentional or not as many mod chunkload feature are buggy for server play.

**Comment by Boomflex** [comment]
Intended.

Removed by Pack Makers.
