### ISSUE TITLE
paper/builder recipe not working

### ISSUE THREAD

**Issue by Mugatoo** [AllTheMods/ATM-3#434]
Along with Builder not being craftable, neither is paper. Im wondering if may have a settings that needs to be changed to allow me to use certain recipes.  Very frustrated right now. It seems ALOT of the recipes in this mod will not work.

**Comment by SpeedSlider** [comment]
Paper is craftable with rice and the use of sugarcane may have been overlooked and is a known issue that will or will not be addressed in the next update.

**Comment by Boomflex** [comment]
in v5.8 the Builder from RFTools is craftable

![image](https://user-images.githubusercontent.com/22868795/36631394-f9f80550-196e-11e8-9db9-2405953522d7.png)

Paper is currently craftable via rice in v5.8 (will have usual method added back next update).

It sounds as if your Scripts folder hasn't transferred across from previous update. Please reinstall the latest version.
