### ISSUE TITLE
Mystical Agriculture Block to ingot

### ISSUE THREAD

**Issue by Tillysaur** [AllTheMods/ATM-3#435]
The supremium block to supremium ingots do not work, it instead converts to superium ingots (when crafted in any crafting grid)

**Comment by Boomflex** [comment]
Please can you send a screenshot of this being the case?

![image](https://user-images.githubusercontent.com/22868795/36631606-238d50ce-1973-11e8-8bc5-686a9af92d31.png)

There is no such thing as a Supremium block of ingots, only essence?

**Comment by Tillysaur** [comment]
You can pour it through the tinkers smeltery I will provide screenshots asap

**Comment by Tillysaur** [comment]
EDIT: Server restart seemed to solve the issue?
