### ISSUE TITLE
Issue with EXUtils Speed Upgrades.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#44]
ExUtils2 version: 1.12-1.5
Forge version: 2407

"I'm having an issue where the upgrades from exu2, as soon as the "penalty" text is updated, won't stack."
![ss 2017-07-14 at 10 55 52](https://user-images.githubusercontent.com/20716525/28230539-b5514dfe-68e7-11e7-9412-631ae44e4b60.jpg)
![ss 2017-07-14 at 10 55 55](https://user-images.githubusercontent.com/20716525/28230542-b723939e-68e7-11e7-8529-43f7063cec1b.jpg)

**Comment by jeffwcollins** [comment]
They are actually two different Item nbt tags/id's , so it's doing what it's supposed to do.  The mod updated to have two different tiers.

**Comment by Darkere** [comment]
not a bug exu2 speed upgrade only stack to 4.

**Comment by OrdinatorStouff** [comment]
yeah speed upgrades slightly different, multiple tiers, don't stack the same, etc
