### ISSUE TITLE
The morphing tool should use ore dictionary to craft

### ISSUE THREAD

**Issue by Trinsdar** [AllTheMods/ATM-3#441]
Simple. the recipe for the morphing tool needs to be changed so that any dye of the required color can be used, not just vanilla dye. Ord approved this, by the way.

**Comment by SpeedSlider** [comment]
I can confirm that Ord_ approved this change in the ATM3 server chat :P

**Comment by OrdinatorStouff** [comment]
should be fixed in 5.9+
