### ISSUE TITLE
[ATM3 V5.8] Mekanism Logistal Transporters no longer connect to Tech Reborn Machines

### ISSUE THREAD

**Issue by DieselDuk** [AllTheMods/ATM-3#442]
All four (Basic/Advanced/Elite/Ultimate) Logistal Transporters in Mekanism have stopped interfacing with Tech Reborn Machines (certainly with the Centrifuge, Grinder and Sawmill). 
It worked fine in V5.6, I skipped V5.7, and now no longer works. I haven't seen any other connectivity issues with the Transporters or the Tech Reborn Machines.

**Comment by OrdinatorStouff** [comment]
are you able to force the transporter mode with the configurator (i.e. configure the pipe to pull) -- also a possibility could be if TechReborn has some new sidedness that might need to be configured in the TR GUI or with an upgrade?

**Comment by DieselDuk** [comment]
My bad, didn't spot the new Configure Slots button.
