### ISSUE TITLE
Error loading all the mods 3

### ISSUE THREAD

**Issue by azvisio** [AllTheMods/ATM-3#443]
this is the error it's displaying is anyone else having same issue?

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Comment by SpeedSlider** [comment]
Are you using the Twitch client? How much RAM did you allot. The ideal amount of RAM is 6Gb. Also, you should be using the Jar Launcher option in Twitch instead of the Native Launcher. If none of this helps then you issue may be more quickly resolved using our discord https://discord.gg/QV3B76.

**Comment by azvisio** [comment]
thank you I didn't realize it required 6 gb allocation. it works now thank you
