### ISSUE TITLE
No heads/skulls dropping

### ISSUE THREAD

**Issue by Grygon** [AllTheMods/ATM-3#444]
Hopefully this isn't intended...
Wanted to try out woot now that it's been added, but to do that I need non-wither skulls/zombie heads. First time I've needed them in a semi-long playthrough, so I hadn't noticed until now, but I found that despite killing tons of mobs I have yet to receive a single drop! JEI says they don't drop naturally.

![image](https://user-images.githubusercontent.com/647846/36878582-9ed73be6-1d8d-11e8-9970-d16f02d1c015.png)

I tried finding a relevant config file to enable them, but couldn't, so I'd guess this is unintended. 

Playing on ATM 5.8, but I believe this game may be going back to 5.6--not entirely sure.

**Comment by SpeedSlider** [comment]
You can get heads using the Tinkers Construct Cleaver. It starts standard with beheading II, I believe, and then you can add additional beheading modifiers by using obsidian and ender pearls. It is entirely possible this is intended as the pack is heavily customized for balance purposes and to help force players to explore all the mods.

**Comment by FallenEagle1** [comment]
Just checked, beheading on cleavers still gives a chance for heads. First cleaver kill I had in a test world gave a zombie head. I think the calculation is 10% chance of a head, not 10% more of base.

**Comment by SpeedSlider** [comment]
I use it to get wither skelly heads and have beheading 9 and as a result it feels like I get a head with every skelly I kill so yeah 90% is about right. Already have about 50 heads and I don't use any farm other than spawner changer on a vanilla spawner and just go and kill some when I want them.

**Comment by Grygon** [comment]
Looks like you're right, just tried it out and got skulls--also, woot drops them without it being on the drop table, which was my other concern.
Also, wither skellys have skulls in their normal drop table, which is part of why I was confused--it was more regarding normal skeleton/zombie/creeper etc heads.
Still don't like this change, but I guess it's not a bug and so probably doesn't deserve an issue.
