### ISSUE TITLE
[v5.8] Extreme Reactor recipe from Fission Reactor no longer valid

### ISSUE THREAD

**Issue by kerzenhans** [AllTheMods/ATM-3#445]
Since updating NuclearCraft to 2.9c the Fission Reactor (Old) is no longer craftable. Hence the recipe for the Extreme Reactor Controller using the Fission one is not attainable.

**Comment by Boomflex** [comment]
The current NuclearCraft version in the latest ATM3 pack update is 2.9d

Please update the pack to the latest version.

**Comment by Boomflex** [comment]
Will be fixed in new update.
