### ISSUE TITLE
Add Improvable Skills

### ISSUE THREAD

**Issue by kkjdroid** [AllTheMods/ATM-3#448]
Actually Additions makes mobs drop Solidified Experience. Looting weapons make them drop *tons* of Solidified Experience. There isn't a ton of stuff to enchant, and after that, what do you do with your 5,000 (I'm not exaggerating, that's how much I had) SE? I propose that we use [Improvable Skills](https://minecraft.curseforge.com/projects/improvable-skills/files/2534980). It gives you a button in your inventory to do things like make your jump higher, increase your maximum health, and increase your armor at the cost of XP, sometimes a whole lot. I used the whole 5,000 and only maxed out the base skills; about half of them (including the armor and HP boosts) must first be found in dungeon chests.

**Comment by SpeedSlider** [comment]
mod suggestions need to be added by comment to https://github.com/AllTheMods/ATM-3/issues/1

**Comment by kkjdroid** [comment]
My bad, moved the request to the appropriate place.
