### ISSUE TITLE
Add The Lost Souls

### ISSUE THREAD

**Issue by kkjdroid** [AllTheMods/ATM-3#449]
McJty, the author of The Lost Cities, recently released a companion mod to scale the challenge of Lost Cities to the gear available in large modpacks (better armor and swords than diamond, easier enchantments, and so on). It's called [The Lost Souls](https://minecraft.curseforge.com/projects/lost-souls).

**Comment by Yoosk** [comment]
That should go into https://github.com/AllTheMods/ATM-3/issues/1

**Comment by kkjdroid** [comment]
My bad, moved the request to the appropriate place.
