### ISSUE TITLE
Freezing after a short time playing in-world

### ISSUE THREAD

**Issue by FuzzyFoxe** [AllTheMods/ATM-3#450]
I've double checked with vanilla. 1.12.2 Minecraft does not seem to do this by itself, only when I use this modpack.

Nothing I do seems to prevent this Freeze/Crash either. I'm either doing some random thing, or hell, I could be in a menu, or even just afk for a moment, and the game just freezes up and never recovers. I've already checked the log when this happens, but no luck at all, the log doesn't even record the issue since it doesn't trigger a crash itself, just freezes.

I've even tried just letting it sit for a couple hours to no avail. This is with the latest version of this modpack (v.5.8).
I'm running this via the Twitch client, no modifications to the pack. I've tried giving it more ram (started at 6GB and worked my way up to 12GB) still with no luck. When I'm playing, the game runs smooth, I've got decent hardware, and as I said, vanilla runs with no issues. (run through the same program: Twitch)

And most specifically, it doesn't freeze up until I've loaded a world and played in it for some random amount of time. I could even hold still long enough and do absolutely nothing, and it still freezes.

I've made sure Java is updated, (Though I'm pretty sure minecraft usually uses its own built-in version; correct me if I'm wrong please) I've made sure my video card drivers are up to date, I've even searched -ALL OVER- to find anyone having the same issue, and found no one else reporting this issue. (Only issues I find are related to stuttering, not actual freezing, and it was due to the person not limiting their fps to their monitor's refresh rate, which is not the case for me.)

Specs:
Windows 10 Pro
i5 6600k (Stock clock)
16gb RAM
Nvidia GeForce GTX 1070 (8gb vram)

Please someone help me, I want to enjoy this modpack, but it doesn't even stay unfrozen in single-player either.

If there's a way to get a log of the freeze other than "Curse\Minecraft\Instances\All the Mods 3\logs" Or something else I can do to help track this down, that would be great.

As it is, (obviously) this issue makes the modpack nearly 100% unplayable.

**Comment by FuzzyFoxe** [comment]
Okay, took me some time, but I got it to freeze again. The log ended up being too long for pastebin's free account limit of 512kb (which is 100% ridiculous) had to use a different site: https://paste.ee/p/7XWF6
I also used this page's suggestion on getting more info: https://www.minecraftforum.net/forums/support/unmodified-minecraft-client/tutorials-and-faqs/2134680-tut-advanced-debugging-minecraft

Which again, I can't seem to figure out what I'm doing wrong when these freezes happen, because again, it does not end with an error because it does -not- cause a crash.

**Comment by xAtlasx** [comment]
Same here, after playing about 30min i get frezzes for about 5sec every 5-10min

**Comment by FuzzyFoxe** [comment]
Make sure your frame rate is set to your monitor's refresh rate. Kinda sounds like the issue you have there. My issue isn't occasional freezing here and there, it's full blown frozen/crash/won't do anything/hanging/unresponsive/dead; But since it doesn't actually cause the game to crash on its own, it does not record any errors in the log file, it just sits there frozen until I manually kill the process.

**Comment by xAtlasx** [comment]
I dont think that monitor refresh rate is problem for me. Other mods like direwolf20 or infinity and vanilla minecraft works fine.

**Comment by FuzzyFoxe** [comment]
Hmm, perhaps your issue might be related to ram allotment? This is a very large modpack, and it's recommended 6gb of ram or higher allocated to it.

**Comment by xAtlasx** [comment]
For mod i have 8gb ram (max16gb) so ram is not a problem.

**Comment by FuzzyFoxe** [comment]
Well shoot, that exhausts my knowledge of fixes. :(

**Comment by pgudge** [comment]
I also have had this on the latest ATM3, I believe I also has this on the original ATM. On 6GB and lower after the client being open for over a few hours, the Mem: counter goes from about 66% and increases all the way to 99% then the game freezes for about 4/5 seconds, the Mem then drops back to ~66% and immediately grows to 99% again in the space of 1/2 minutes. Restarting client fixes temporarily.

I've since gave the client 8GB RAM and it's not done it once yet. It however does still increase to ~89% then drops back to ~54%.

I also have OptiFine added, and Sphax pack, other than that nothing different.

HTH

**Comment by FuzzyFoxe** [comment]
Again, the issue I'm having is not a -temporary- freeze. It locks up indefinitely. I've let it sit for an hour or more before to no avail.
I also recently tested single player, and found it seems to not happen there like I swore it did. Only happens on multiplayer. (The being able to idle for a while and have it freeze regardless of what I do)

**Comment by Boomflex** [comment]
Will investigate further.

Thanks for bringing it to our attention.

**Comment by TolgaKerem07** [comment]
Mine is freezing every 3-4 seconds too. İt is unplayable. I gave 6 gb of ram but it keeps freezing (maybe unresponsive)

**Comment by FuzzyFoxe** [comment]
Wow, had to search for this. Anyway, I just got a new motherboard and the modpack seems to work fine. Seems my old motherboard was dying. Sorry for the frustration. This can be completely closed and/or deleted if you wish.
