### ISSUE TITLE
Tier 6 Seeds from Mystical Aggradations can't be placed in Immersive Engineering's Garden Cloche. Modpack All the Mods 3 version 5.8.

### ISSUE THREAD

**Issue by Noobwiki** [AllTheMods/ATM-3#453]
Modpack All the Mods 3 version 5.8.

**Comment by Yoosk** [comment]
Not a bug.

**Comment by OrdinatorStouff** [comment]
This is working as intended -- the T6 seeds are "op" and the need for the crux under them is kind of a way toi "balance" their production somewhat.
