### ISSUE TITLE
Compaction Drawer and Compressed Cobble.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#46]
Storage Drawer verison: 1.12-5.2.8
Forge version: 2413

There's regular cobble in the chest and as soon as the item-duct tries to input the cobble into the drawer it locks onto those compressed cobble types and won't accept any regular cobble.
![ss 2017-07-15 at 03 36 11](https://user-images.githubusercontent.com/20716525/28239762-7ffcf838-6973-11e7-886f-98865ab25cfa.png)
![ss 2017-07-15 at 03 31 27](https://user-images.githubusercontent.com/20716525/28239763-81e7fbac-6973-11e7-88a9-6292d6e28541.jpg)

**Comment by BloodWorkXGaming** [comment]
The smallest compression level you have in there is double compressed, not
normal cobble stone, so it can't go on in there

gefailter71 <notifications@github.com> schrieb am Sa., 15. Juli 2017, 15:37:

**Comment by gefailter71** [comment]
Yeah Blood I know that is the problem double compressed shouldn't be the lowest compression level since I didn't do anything to the drawer beforehand it just does that when I try to input normal cobble via an itemduct.

**Comment by BloodWorkXGaming** [comment]
Maybe click the bottom right slot with a normal cobble and then lock it? I
think I had that issue before as well.

gefailter71 <notifications@github.com> schrieb am Sa., 15. Juli 2017, 17:35:

**Comment by jeffwcollins** [comment]
It doesn't matter which slot it's inserted in, it still only presents or accepts double compressed as soon as one cobble is inserted.

**Comment by jeffwcollins** [comment]
Looks like it was already filed as a bug in the storage drawer mod.

https://github.com/jaquadro/StorageDrawers/issues/539

**Comment by jaquadro** [comment]
Should be fixed with the next pack update

**Comment by whatthedrunk** [comment]
Should be good in 2.2 which will be out soon.
