### ISSUE TITLE
Some 64x9 ingot crafting to blocks causes lag

### ISSUE THREAD

**Issue by pgudge** [AllTheMods/ATM-3#460]
When crafting 64x9 Iron Ingots, shift click, it takes a few seconds for the 64 Blocks to enter your inventory. Gold seems quick too. However other ores like Coal, Lead, Silver, Alu etc all take about 10 seconds to craft and cause lag on the server. Server also outputs the skipping ticks warnings in the server logs. All players notice rubber banding lag, like running away the jumping back, and chests not opening during the ~10 seconds block crafting.

Some logs from server below.

Iron/Gold Ingot - Minecraft (1 sec)
No error message

Nickel Ingot - Thermal Foundation (10 secs)
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 13622ms behind, skipping 272 tick(s)

Lead Ingot - Thermal Foundation (11 secs)
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 13655ms behind, skipping 273 tick(s)

Draconium Ingot - Draconic Evolution (13 secs)
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 13397ms behind, skipping 267 tick(s)

Osmium Ingot - Mekanism (4 secs)
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2185ms behind, skipping 43 tick(s)

Boron Ingot - NuclearCraft (10 secs)
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 10091ms behind, skipping 201 tick(s)

All the Mods 3 v 5.8

**Comment by OrdinatorStouff** [comment]
This is entirely dependent on which crafting grid you're doing this in. Is it in a vanilla workbench? Refined Storage Grid? Tinker's workbench? Every one of them handles recipe caching differently in their own code.

**Comment by pgudge** [comment]
I have the Tinkers' Construct Crafting Stations all over the place. I've also just tried it with the vanilla Crafting Table and same for the Nickel and Silver.

**Comment by Boomflex** [comment]
Added FastWorkBench which will sort that out.

Other than that, this is well out of Modpack control.
