### ISSUE TITLE
Can`t connect to my own Server

### ISSUE THREAD

**Issue by Bond0712** [AllTheMods/ATM-3#462]
Me and my friends started a new playthrough of ATM3 a few days ago and today i updated the server and we all updated our packs. Now we tried to join on it again and we can`t join. We all just get a disconnect and the only thing i can see in the Server log is "lost connection: Handshake complete review log file for details." Anything that could help would be appreciated.
[latest.log](https://github.com/AllTheMods/ATM-3/files/1830419/latest.log)

**Comment by OrdinatorStouff** [comment]
theres an error in the JVM args that include a part that makes no connections possible
```
-Dfml.debugNetworkHandshake=true 
```
If you remove that part from settings.cfg and re-launch server it should work like normal after that -- the next serverfiles to go out will have this removed from the settingscfg as well
