### ISSUE TITLE
Paper Recipe using Rice

### ISSUE THREAD

**Issue by snoopydude48** [AllTheMods/ATM-3#464]
Using version 5.9 of the pack.
 The recipe with 3 rice diagonally from top left to bottom right yields 2 rice dough, not 3 paper.

![2018-03-21_11 38 34](https://user-images.githubusercontent.com/8415887/37719865-6efdb494-2cfc-11e8-8b0c-37425d344908.png)
![2018-03-21_11 39 38](https://user-images.githubusercontent.com/8415887/37719930-969d9780-2cfc-11e8-919c-123db1be868f.png)

**Comment by Boomflex** [comment]
Please use the Sugar Cane recipe for paper for now.

Thanks.

**Comment by OrdinatorStouff** [comment]
fixed in 5.9.1
