### ISSUE TITLE
Ic2 Re Battery ae2 autocraft issue

### ISSUE THREAD

**Issue by Mugatoo** [AllTheMods/ATM-3#465]
When auto crafting generators. Ae2 will always request an re battery from ic2 with no damage value. 

Those batteries only craft with a 0/10k value causing a hang which can't be fixed. 

I have tried manually entering recipe to include a 0/10k value battery and also tried changing the me interface priorities to craft the battery first.

**Comment by ouroborus** [comment]
A work around is to treat the batteries as though they weren't a basic crafting recipe. Use the AE2 interface to pump the ingredients into a non-ae2 autocrafter and then have that autocrafter pump the results back into the interface.

**Comment by Yoosk** [comment]
You want to use tech reborn battery and it just works fine.

**Comment by OrdinatorStouff** [comment]
Not much of a modpack issue, if the autocrafting system can't ignore damage/metadata then alternative means are needed such as recomended by Yoosk and ouroborus already.
