### ISSUE TITLE
Charcoal to pulverized Coal = easy Diamonds

### ISSUE THREAD

**Issue by MarvTekko** [AllTheMods/ATM-3#467]
You can use the Mechanical Squeezer to turn Charcoal into pulverized Coal.
It is therefore very easy to craft diamonds from it. Is that how it should be?
However, I have not tested it in the latest version.

Modpackversion: v.5.8

**Comment by SpeedSlider** [comment]
IMO diamonds are not hard to get in modded and the steps and machines required to get diamonds doesn't seem that different from using miners.

**Comment by Boomflex** [comment]
Intended behaviour with currently no plans to change this.

Thanks for the heads up.
