### ISSUE TITLE
Cyclic Sprinklers Crash - ATM 5.9.1

### ISSUE THREAD

**Issue by JayWood** [AllTheMods/ATM-3#469]
See the log:
* https://gist.github.com/JayWood/30f806da6fa59ed7e351f7de64726de0

Stacktrace:
```
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at com.lothrazar.cyclicmagic.component.sprinkler.SprinklerTESR.renderAnimation(SprinklerTESR.java:75)
	at com.lothrazar.cyclicmagic.component.sprinkler.SprinklerTESR.render(SprinklerTESR.java:48)
	at com.lothrazar.cyclicmagic.component.sprinkler.SprinklerTESR.func_192841_a(SprinklerTESR.java:37)
```

There are 3 sprinklers in the middle of a 3x3 area, every time my character sees them ( for rendering ) I crash, and the client closes... I then have to wait ages to get going again. The only solution I've had was to remove the mod, but upon re-adding it, I crash again, despite me loading the chunks afterwards.

**Comment by JayWood** [comment]
As a side note, the fix that worked for my server was to place blocks where the sprinklers were and then re-enable cyclic.

**Comment by OrdinatorStouff** [comment]
I experienced this as well with a player on the official server but while it crashed him 100% upon entering the chunk, it did NOT crash me. The only explanation I can think of is some graphical setting on the client that conflicts. That player tried it with and without optifine as well with no change. 

Since this is intermittent and also need the client to be re-launched every time, it'd be difficult to track down the precise cause...

**Comment by JayWood** [comment]
@OrdinatorStouff I wasn't aware it was client only :( a friend on the server was able to re-place them no problem, so maybe it was old block/NBT/meta data? I'll do further testing to see if this is even an issue going forward.

**Comment by JayWood** [comment]
At this point it seems to be far-reaching, I can't even login today. Still working to resolve locally, in the meantime I've opened a ticket with Cyclic.

**Comment by JayWood** [comment]
Reinstalling the pack seems to solve the problem, though a bit overkill. Looks like the previous stable version we were using was 1.12.1 and a huge jump to 1.14.5 in the latest modpack release, wow, that's a lot of versions.

Cyclic dev has flagged the item as a crash, so hopefully they look into it.

**Comment by Boomflex** [comment]
Not a pack issue.

Dev is aware of this problem.
