### ISSUE TITLE
Tesselating Block Model Game Crash

### ISSUE THREAD

**Issue by DaanHolleman** [AllTheMods/ATM-3#470]
My client will crash when I try to break any block, giving me a NullPointerException.
On a side note, Immersive engineering tells me my Java version is 1.8.0_25 when I have no other version installed than 1.8.0_165 (the latest verison).

First crash:
[crash-2018-03-29_18.56.16-client.txt](https://github.com/AllTheMods/ATM-3/files/1861669/crash-2018-03-29_18.56.16-client.txt)

[crash-2018-03-29_18.56.17-server.txt](https://github.com/AllTheMods/ATM-3/files/1861670/crash-2018-03-29_18.56.17-server.txt)

Second crash:
[crash-2018-03-29_21.44.02-client.txt](https://github.com/AllTheMods/ATM-3/files/1861724/crash-2018-03-29_21.44.02-client.txt)

[crash-2018-03-29_21.44.04-server.txt](https://github.com/AllTheMods/ATM-3/files/1861725/crash-2018-03-29_21.44.04-server.txt)

**Comment by DaanHolleman** [comment]
Thanks for the tips, it seems the temporary fix works and I can play again <3

**Comment by Boomflex** [comment]
Duplicate.
