### ISSUE TITLE
OpenBlocks Elevators values were reversed.

### ISSUE THREAD

**Issue by nullKomplex** [AllTheMods/ATM-3#471]
This occurred in 5.8. I confirmed with Boomflex that this was indeed not intended. As this was not corrected in 5.9.1 I have decided to post an issue.

#### Relevant commits:

Nerf: https://github.com/AllTheMods/ATM-3/commit/05d6428e93a96e919656c9dc98eede85594ad433#diff-4473d6639a060d1f9f9cd707826b2f0cL148
Wrong value increased after nerf: https://github.com/AllTheMods/ATM-3/commit/2da42dcf03afb7a850afbee6bfd448094d4b608a#diff-4473d6639a060d1f9f9cd707826b2f0c

#### Relevant lines (for convenience):

https://github.com/AllTheMods/ATM-3/blob/master/overrides/config/openblocks.cfg#L150
https://github.com/AllTheMods/ATM-3/blob/master/overrides/config/openblocks.cfg#L157

#### For clarification:

`maxPassThrough` is the amount of solid blocks it's allowed to work through. This number is independent of the maximum amount of distance traveled, and only affects blocks inbetween elevators.

`searchDistance` is how far apart you can place elevators.

#### As a side-note/opinion/suggestion (not at all relevant to the issue):

Personally I think 20 was small, but 16 is fairly short. We run 32 on our server.

**Comment by Boomflex** [comment]
Intended.

I confirmed it was supposed to be 8 and 8, not the other way round.

Closed.

**Comment by Boomflex** [comment]
This is before I realised what I had actually done. 

As I stated, it is to be 8 and 8.

Thanks.

**Comment by nullKomplex** [comment]
My apologies, I attempted to use reddit markdown so the first line that stated you _had_ actually realized what you had done did not show up in the email you replied to. I don't really mind changing this setting to a more realistic setting every update, but I'd appreciate it if you didn't falsify details.
