### ISSUE TITLE
Refined Storage Item storage

### ISSUE THREAD

**Issue by lalleman44** [AllTheMods/ATM-3#472]
When i'm using refined storage to fill disc's with stuff, once a 64k disc is full, the items are stored somewere but not on a disk. Using Quantum disc's also show this issue. 

Reproduce:
add at leased 2 discs in the drivebay
add items untill one drive is full, then add more items, disc 2 remains empty but items are stored in the system.

P.s trying to extract items with a empty disc using the manipulator drive does also not work, disc ejects right away.

![refined 1](https://user-images.githubusercontent.com/33482692/38136494-03754618-341f-11e8-9e1b-063c01835d62.jpg)
![refined 2](https://user-images.githubusercontent.com/33482692/38136495-038b143e-341f-11e8-9df2-19216fc94411.jpg)

**Comment by Boomflex** [comment]
Tried replicating this numerous times to no avail.

Will put it down as non-reproducible, but if it happens again after latest update, then please report it directly to the Mod Github.
