### ISSUE TITLE
[ATM3 5.8+] Cannot craft TR cables

### ISSUE THREAD

**Issue by notacompletemoron** [AllTheMods/ATM-3#473]
I can't craft TR LED Lamps because they require TR tin cables, and TR tin cables do not have a recipe.

IC2 tin cables do not work as substitutes.

First noticed this issue in 5.8, and has carried over to 5.9.1.

**Comment by Boomflex** [comment]
Created recipe to allow IC2 cables.

Will be available in next update.

Thanks for pointing it out!

**Comment by SpeedSlider** [comment]
Confirmed the LED lamp is craftable with IC tin cables in 5.9.3.
