### ISSUE TITLE
Creative Computer Case cannot be used in non-Creative modes.

### ISSUE THREAD

**Issue by nullKomplex** [AllTheMods/ATM-3#474]
Title. It can be placed but cannot be broken or right clicked. I can't seem to find an option to enable its use in non-Creative.

This is not something you can address directly if there's no config to change it, but it is a recipe added by ATM3 for a use of an ATM Star.

It's not a huge problem since it doesn't consume any part of the Star, but still.

**Comment by Boomflex** [comment]
Will remove recipe in next update.

**Comment by SpeedSlider** [comment]
Confirmed that recipe to craft is removed in 5.9.3. Also, if in creative item is available and can be placed and loaded with RAM, hardrives, EEPROM, and graphic card.
