### ISSUE TITLE
Creative Watering Can has no water.

### ISSUE THREAD

**Issue by nullKomplex** [AllTheMods/ATM-3#475]
Despite clearly stating "Infinite" the NBT data of the can created through the recipe contains no water and cannot be used. It also cannot be filled. The intended value of the NBT Tag water is 60000.

**Comment by Boomflex** [comment]
Recipe updated in next update.

**Comment by SpeedSlider** [comment]
Confirmed the creative watering can, when crafting with empty watering can, is full and capable of watering without need to fill in 5.9.3.
