### ISSUE TITLE
Cannot place Buckets in Coke Oven to extract Creosote

### ISSUE THREAD

**Issue by Drecondius** [AllTheMods/ATM-3#476]
ATM 3 v 5.9.1
I have built a coke oven on multiple worlds. I cannot place a bucket into the oven to extract creosote. When it is piped out however it is TE creosote.

**Comment by Boomflex** [comment]
Mod issue with Immersive Engineering that has already been fixed by the Dev.

Will be fixed in a future update.

**Comment by SpeedSlider** [comment]
Confirmed that an empty bucket can be placed in the coke oven and extracts creosote oil; oredict to Thermal Foundation in 5.9.3.
