### ISSUE TITLE
Advanced rocketry ores are not mineable by the void ore miner.

### ISSUE THREAD

**Issue by Trinsdar** [AllTheMods/ATM-3#477]
I don't know if that is intentional, but ores from advanced rocketry, specifically rutile and dilithium, are not mineable by the void ore miner.

Perhaps you could add at least rutile to the void ore miner list?

I'm currently using 5.9.1 as of making this issue, but will be updating to 5.9.2 soon.

Edit: I'm now using 1.9.2.

**Comment by Trinsdar** [comment]
Either that, or perhaps add an titanium enriched asteriod to the asteroid config.

**Comment by Boomflex** [comment]
Intentional behaviour.

We are encouraging actually mining for these at exploration is the name of the space game.
