### ISSUE TITLE
Invar, Iridium don't have TiC Smeltery ingot/block recipes.

### ISSUE THREAD

**Issue by Deagroth** [AllTheMods/ATM-3#478]
After alloying invar in the smeltery or melting down iridium ore you can not pour either into ingot casts or casting basins for ingots/blocks due to there not being recipes for them.

**Comment by OrdinatorStouff** [comment]
I would like to add these in manually if not a simple config change

**Comment by Boomflex** [comment]
Fixed in upcoming update.

Thanks KJ.
