### ISSUE TITLE
Unable to craft Forestry Fertilizer

### ISSUE THREAD

**Issue by scotty9090** [AllTheMods/ATM-3#479]
Version v5.8

I made a Forestry multifarm and am trying to craft fertilizer for it.  The recipe requires "concentrated compound" from MagicBees in place of the usual Apatite.  JEI doesn't show how the concentrated compound is obtained.  I'm assuming I'm not forced to go through bees in order to setup a farm so wondering if this is unintentional?  I can't find any other way to craft the forestry fertilizer in JEI.

**Comment by KevinLinders1904** [comment]
if you go to page 2 you see multiple other recipies

![image](https://user-images.githubusercontent.com/2630343/38263073-54d8e034-376f-11e8-9216-7a46fba89706.png)

**Comment by scotty9090** [comment]
Good grief - I can't believe I missed that.  I'm going to go ahead and blame this on the late hour, being tired, and trying to rush this before I went to bed.  Thank you for the help - closing this now.
