### ISSUE TITLE
60 rubies from one ruby block

### ISSUE THREAD

**Issue by Kaperios** [AllTheMods/ATM-3#48]
This process let you make 60 rubies from one ruby block (same for sapphire and peridot) from Tech Reborn:
-----------------
![image](https://user-images.githubusercontent.com/17909958/28240668-09272612-6986-11e7-9cd9-db4cc50b9d79.png)
![image](https://user-images.githubusercontent.com/17909958/28240671-12ceb5a4-6986-11e7-9bf5-87559134dff6.png)
![image](https://user-images.githubusercontent.com/17909958/28240679-2fa59256-6986-11e7-9485-e20b38db5259.png)

**Comment by OrdinatorStouff** [comment]
confirmed on latest versions this is fixed. 2 blocks of rubies gave me a total of 12 rubies, 2 leftover ruby dust and 48 dark ashes.
