### ISSUE TITLE
Destoying a coke oven or blast furnace gives weird item

### ISSUE THREAD

**Issue by KevinLinders1904** [AllTheMods/ATM-3#481]
When destroying a blast furnace or coke oven multiblock structure (immersive engineering)

it gives out an item called crude blast furnace and coke oven

![image](https://user-images.githubusercontent.com/2630343/38262887-c9d5432e-376e-11e8-80af-4937da355e0b.png)

**Comment by Boomflex** [comment]
Known issue with IE.

Fixed in 5.9.3

**Comment by SpeedSlider** [comment]
Confirmed that when destroyed using a pick axe or hammer from tinkers that you just get the blocks back for each.
