### ISSUE TITLE
ChunkLoading Problem with Mekanism 5x ore processing setup

### ISSUE THREAD

**Issue by Trostan** [AllTheMods/ATM-3#482]
So i'm playing All the Mods 3 v5.9.1 on a server and built a 5x ore processing setup with mekanism. The Problem is it doesn't work when i'm not online even tho it's chunkloaded. I have it chunkloaded with FTB Utilities and even tried the chunk loading ward from extra utilities 2, but it just doesn't work. Everything else like Void Miners, Garden Cloches, Tree Farm, AE2 Autocrafting and Stuff works just fine when i'm offline.

**Comment by Trostan** [comment]
I will look into this and report back

**Comment by Boomflex** [comment]
There was issues with FTBUtilities in a previous version.

Update to latest (5.9.3b)
