### ISSUE TITLE
Enderman head crafting

### ISSUE THREAD

**Issue by balkongo** [AllTheMods/ATM-3#484]
Enderman heads are introduced with Ender IO. It would be nice to be able to craft them like the other skulls with Mystical Agriculture essences. They are made with a blank skull and 8 mob essence all around.

**Comment by Boomflex** [comment]
Not a bad idea, will have a look in to this.

**Comment by Boomflex** [comment]
Recipe created: 

![image](https://user-images.githubusercontent.com/22868795/38439344-2f482524-39d5-11e8-9578-06b760fa1564.png)

Will be in v5.9.3
