### ISSUE TITLE
Please Downgrade JourneyMap!

### ISSUE THREAD

**Issue by alpal01** [AllTheMods/ATM-3#489]
Please downgrade JourneyMap to  journeymap-1.12.2-5.5.1 due to: https://github.com/TeamJM/journeymap/issues/13
It is a bug where the map isn't usable on new worlds made for MC 1.12.2 
Please downgrade it.
Thanks

**Comment by Boomflex** [comment]
What version of the modpack are you playing on?

**Comment by alpal01** [comment]
5.9.2 
JM Version:5.5.2

**Comment by Boomflex** [comment]
I looked in to the issue you linked and it is all fine.

I created a new world, entered a cave, it switched to cave mode, left and it went back?

https://gyazo.com/ea2abf5cdfb9077e41f9c0551de48289

**Comment by Boomflex** [comment]
Created 3 brand new worlds. Map worked fine each time.
Checked both Official Public server and Official Patreon server an no isse?
Are you adding anything to the pack yourself?

**Comment by alpal01** [comment]
nope will load pack back up

**Comment by Boomflex** [comment]
I will close this for now as I've tried reproducing 5 times excluding 2 separate servers with 20-30 people on not having the issue.

Will keep an eye out for any further mention though, so thanks for bringing it to our attention.

**Comment by alpal01** [comment]
![2018-04-08_13 29 54](https://user-images.githubusercontent.com/5721147/38470445-1148bcd4-3b31-11e8-91af-36c9d7e68562.png)
![2018-04-08_13 30 00](https://user-images.githubusercontent.com/5721147/38470446-115905d0-3b31-11e8-9619-b3f49d359893.png)

**Comment by alpal01** [comment]
But when I installed journeymap 5.5.1 on other packs I never encountered this issue
