### ISSUE TITLE
Capturing Wand, Not Enough Wands; doesn't capture when fully charged.

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM-3#491]
The capturing wand gives the error not enough energy when trying to capture mobs even when fully charged. Additionally, the moving wand must be fully charged to move a single item and once a single item is moved it must be recharged.

**Comment by Boomflex** [comment]
Capturing Wand is definitely funky.

Moving wand works fine for me?

Will look in to the config for Capturing, something definitely weird.

**Comment by StrommKral** [comment]
in my experience, the capturing wand will not work on hostile mobs, or villagers, just vanilla peaceful mobs/animals.

**Comment by SpeedSlider** [comment]
Yeah, I have used the capturing wand successfully in past, I could not find a situation where it worked. I suspect it is related to the same tweaking on the moving wand. The moving wand only works if fully charged and will only move one block even through a significant charge remains on it. So you have to fully recharge it after each use.

**Comment by Danimineiro** [comment]
I can't use it too even on horses or pigs.

**Comment by Yoosk** [comment]
fixed it in dev
