### ISSUE TITLE
Issue with Astal sorcery - Items / power disapearing - Caused by Ritual ?

### ISSUE THREAD

**Issue by xini88** [AllTheMods/ATM-3#494]
I got some issue with Astral Sorcery, the Rituals goes off once u go to the Nether (most likely other realms too), and all machine in the AOE of the buff lose thair power, items, and augments.
its in ATM3 1.12.2 playing by twitch app latest version.

The ritual i use is Mineralis, (im use it for ore gen Quarry) with a ritual anchor
RF Tools Build - any quarry card

Singel Player mode - Survival

I can recreate the bugg all the time, i prevent it by turning my builders off- then i can go to other realm,
in order to start my builders w/o loseing the card items etc, i need reboot minecraft, then i can quarry.

if need more info il keep my eye on this post. so i can update missing info

![quarry](https://user-images.githubusercontent.com/38265910/38587410-a53c71e6-3d21-11e8-9a3c-e5556321277d.jpg)

![qaurry 2](https://user-images.githubusercontent.com/38265910/38587430-b3a56c88-3d21-11e8-882e-d31c9f843abc.jpg)

**Comment by Boomflex** [comment]
This is not something we can fix as a Modpack, please report this to the Mod Dev.

Thanks for bringing it to our attention.
