### ISSUE TITLE
ATM 3 v5.9.2

### ISSUE THREAD

**Issue by nastro1995** [AllTheMods/ATM-3#496]
Hi i was playing on my sp world when the game crashed as i was about to walk out my base's door ( i doubt its the oak door lol ) ,   no idea what could of caused it.

Extra Information:
Launcher: MultiMC5 (If it is multimc5 related i can make a post on there)
OS: Windows 10 Pro 64-bit
Optifine is manually installed

Client crash log:
[crash-2018-04-11_11.08.58-client.txt](https://github.com/AllTheMods/ATM-3/files/1898144/crash-2018-04-11_11.08.58-client.txt)

**Comment by SpeedSlider** [comment]
The issue appears to be related to rendering a screen, did you perhaps recently replace one? It also could be a combination of what is on the screen and Optifine so if you need to log in without crashing to resolve the issue then try logging in without Optifine.

This issue may be better resolved by going to our discord help channel.
https://discord.gg/JnZ55Bn

**Comment by SpeedSlider** [comment]
The removal of Optifine is/was only to facilitate troubleshooting. I use Optifine and betterfps in order to run modded with texture packs.

**Comment by Boomflex** [comment]
Please update to 5.9.3
