### ISSUE TITLE
[Bug #dupe] Elytra + Multiple dragon scales

### ISSUE THREAD

**Issue by thejims** [AllTheMods/ATM-3#497]
Using ATM3 v5.9.2
For n greater than one, craft Elytra + n dragon scales in a stack.  This consumes 1 dragon scale, does not consume the original Elytra, and gives the Dyed Black Elytra plus (n - 1) * 2 additional dragon scales.
So for example:
Elytra + 2 dragon scales = (2 - 1)*2 = 2 dragon scales
Elytra + 6 dragon scales = (6 - 1)*2 = 10 dragon scales

**Comment by Boomflex** [comment]
The recipe isn't supposed to consume the original Elytra.

However the duplication is a Crafting Table bug that is unfixable by the pack itself.

I will show this to the Quark Dev who adds this recipe to see if there is anything we can do to stop.

Thanks for the report.
