### ISSUE TITLE
ExUtils 2 can't craft mid-lowtier barrel.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#50]
ExUtil version: 1.12-1.5
Forge version: 2413

Tried the old recipe since the new one isn't existent.

![](https://puu.sh/wKvcP/286fbe23d8.png)

![](https://puu.sh/wKvn9/2dd547de69.png)

**Comment by Darkere** [comment]
https://github.com/rwtema/extrautilities/issues/1574

**Comment by Darkere** [comment]
fixed loong time ago
