### ISSUE TITLE
Biblio craft tesselation issue 

### ISSUE THREAD

**Issue by AthlonS2K** [AllTheMods/ATM-3#500]
Game crashes, server is fine.  Bibliocraft tesselation issue for those who wished to review it.  Someone was kind enough to help me find a method to share it.  I have since disabled biblio craft for my world.  I never used it besides to make a checklist, ill use real world stickies.

https://gist.github.com/AthlonS2K/bff99a4567ae77cafa589f1a4fbd8eb2

**Comment by Boomflex** [comment]
Duplication of: https://github.com/AllTheMods/ATM-3/issues/407

The Dev is aware of the issue.

**Comment by AthlonS2K** [comment]
but mine was never placed in the world, its on my bar, but if you say they are the same. ill accept that.

**Comment by Yoosk** [comment]
If it's in your bar just remove your player.dat and carry on.

**Comment by AthlonS2K** [comment]
As I said, I dont use biblio now, I have disabled the addon. I never used it before, I dont feel I will be missing much.  

Ender IO is why im back, I have wanted to play with their new version and was eagerly awaiting its release.  My world is solely built on and around Ender IO.  Dark Steel armor, weapons, tools. the new machines are fun. I cannot wait to see some modpack creator make a skyworld hard mode like FTB did but using this new EnderIO.   I will gladly accept that challenge.
