### ISSUE TITLE
Chaos Guardian not working properly in woot factory

### ISSUE THREAD

**Issue by mthp1999** [AllTheMods/ATM-3#502]
Chaos Guardian woot farm is not generating or taking items

## Expected Behavior

The farm should take in growth crystals, awakened cores 4000mb of resonant ender and 1000mb of blazing pyrotheum and generating chaos guardian drops. 

## Current Behavior

The farm will run through its timer once, not take or generate items and then won't run anymore either. 

## Possible Solution

I am guessing that the reason for this bug is with woot and blazing pyrotheum detection as the ender dragon and wither controllers were tested and worked. Ender dragon requires items and resonant ender and the wither requires items. leading me to believe that its the pyrotheum because it is the outlying variable.

## Steps to Reproduce

1.Make tier 4 woot factory using chaos guardian controller
2.
3.
4.

**Comment by FallenEagle1** [comment]
This is being looked at by the dev and there should be a new version of the mod in a couple days according to them.

**Comment by Boomflex** [comment]
Issue with Woot itself handling our increased numbers.

Dev is aware and will be fixed in an upcoming release.
