### ISSUE TITLE
Mechanical user not working with petal apothecary

### ISSUE THREAD

**Issue by henrikhakan** [AllTheMods/ATM-3#504]
The Extra Utilities 2 block Mechanical user is no longer properly interacting with the Petal apothecary from Botania. 

## Expected Behavior

![fig1](https://user-images.githubusercontent.com/30940744/38729321-e8e91208-3f12-11e8-983d-9df3ac567d0f.png)
Mechanical user should fill up Petal apothecary with water, from water buckets provided. 

![fig2](https://user-images.githubusercontent.com/30940744/38729932-ef9957fa-3f14-11e8-9d1b-a2ea5003a50e.png)
In order for this to work one needs to configure the mechanical user to "Activate block with item".

## Current Behavior

When the option "activate block item" is selected in the mechanical user, and it has a bucket of water in its inventory, on the first attempt to fill the apothecary with said water bucket the GUI closes and standard settings are reset, the waterbucket then places the block of water on top of the petal apothecary. This setup worked with no noted issues prior to the recent 5.9.3 update.

## Possible Solution

Perform code magic until problem goes away pls =)

## Steps to Reproduce

1. Place mechanical user facing upwards underneath petal apothecary.
2. Place bucket of water in mechanical user
3. Set mechanical user to "Activate block with item"
4. Tip: Use Redstone signal as an on/off switch

## Log

N/A

## Detailed Description

This is a bug. A function that was working prior to 5.9.3 has broken since the recent upgrade and this is a request to restore above described functionality =)

**Comment by StrommKral** [comment]
i ran into this today, couldn't get the mechanical user to use fertilizer on a rose, not could i get it to use a how on earth, it just ate the items. However, they mechanical user will work fine in SP AND unclaimed chunks on the server

**Comment by Boomflex** [comment]
This was caused by an issue with FTBUtilities/Mech User.

Please break your Mech User and try it again on the latest version of the modpack (5.9.3b)
