### ISSUE TITLE
Multiple copper dusts

### ISSUE THREAD

**Issue by GloriousYellow** [AllTheMods/ATM-3#506]
## Expected Behavior
Only 1 copper dust exists

## Current Behavior
Multiple copper dusts are shown in JEI and recipes (Pulverized Copper, and Copper Powder)

## Steps to Reproduce

1. Open inventory
2. Search "copper dust" in JEI
3. Both Pulverized Copper and Copper Powder are shown

**Comment by Boomflex** [comment]
Everything will automatically go to the Thermal variant.

Will look at removing the EIO via hiding.
