### ISSUE TITLE
Mystical Agriculture armor not in OpenBlocks grave after death

### ISSUE THREAD

**Issue by pgudge** [AllTheMods/ATM-3#507]
## Expected Behavior
On death, OpenBlocks grave is created with all inventory and armor/baubles.

## Current Behavior
All inventory appeared in grave but no armor.

## Steps to Reproduce
1. Equipt Mystical Agriculture armor, Supremium in this case
2. Cause death
3. Break grave
4. Full inventory minus armor

## Log
Only OpenMods log of storing post-mortem inventory was logs, no errors.

## Detailed Description
I had the full Supremium armor, Supremium helmet, chestplate, leggings and boots. Boots had fire protection upgrade, and chestplate had Resistance upgrade. Used the Tuberous Exchanger I accuired from Magic Beans and died with the message "pgudge tried to operate a potato exchanger", grave spawned. After breaking the grave all inventor appeared excluding the armor and a charm but forget what that even was.

**Comment by Boomflex** [comment]
Tried to replicate numerous times but 100% of the time the armour was in the Inventory.
