### ISSUE TITLE
can not make chests from spruce wood

### ISSUE THREAD

**Issue by philip5203** [AllTheMods/ATM-3#508]
## Expected Behavior

craft chest

## Current Behavior

does not craft chest

## Steps to Reproduce

1.craft a chest with spruce planks
2.
3.
4.

**Comment by Yoosk** [comment]
https://i.imgur.com/fNXfU0T.png 
Works fine in 5.9.2, What version are you on?

**Comment by philip5203** [comment]
5.9.3

**Comment by philip5203** [comment]
https://i.imgur.com/YkvHj8f.png

**Comment by Yoosk** [comment]
We are investigating that.

**Comment by philip5203** [comment]
k

**Comment by philip5203** [comment]
just to let you guys know i have not changed any mod settings.

**Comment by Boomflex** [comment]
Not entirely sure why this doesn't work so I have added an oredict recipe in for the next version.
