### ISSUE TITLE
Gelid Queen Not Producing It's Specialty Product

### ISSUE THREAD

**Issue by TheLegendaryFoxFire** [AllTheMods/ATM-3#510]
## Expected Behavior

The Queen should be producing Ctyotheum Dust

## Current Behavior

The Queen is only producing Frozen Comb

**Comment by Boomflex** [comment]
In v5.9.3 I got it to produce Cryotheum Dust on its first cycle.

![image](https://user-images.githubusercontent.com/22868795/38815868-caa83716-418c-11e8-8c42-19e60afbed76.png)

You may just be unlucky as it is a 9% drop chance.

**Comment by FallenEagle1** [comment]
Just because the tolerance is +-3, doesn't mean the range that the bee is "happy" changes. Specialty items that are produced need to be in the range that the bee works best in, so try putting the cooling upgrade in the industrial apiary to get the temp down to cold.

**Comment by TheLegendaryFoxFire** [comment]
Well, I waited after installing the cooling upgrade for about 30 minutes and I've still yet to get Cyrotheum Dust.

**Comment by TheLegendaryFoxFire** [comment]
Yeah, I've done just what you said and I haven't been able to get a single dust.
