### ISSUE TITLE
Game Difficulty is Being Automatically Changed After Attempting to Set it to Something Other Than Normal

### ISSUE THREAD

**Issue by xScruffers** [AllTheMods/ATM-3#511]
ATM 3 - v5.9.3

Whenever the /difficulty command, or options menu is used to change the game difficulty the change initially goes through. If set to peaceful mobs despawn and hunger stops being an issue. However after roughly 2 seconds the difficulty is automatically set back to normal mode. Mobs spawn again, hunger takes effect. This difficulty change also occurs if I attempt to set the difficulty to easy or hard as well. Even if I use the vanilla MC option to lock the world difficulty it won't stay. 2 seconds after exiting that menu it is changed back to normal. The locked option will now display normal difficulty instead of what I attempted to lock it to.

I assume a mod or configuration setting somewhere is causing this but for the life of me I cannot figure out which one.

Thank you for your time.

**Comment by Boomflex** [comment]
Have you added any mods to the pack at all?

Is this SMP or SSP?

**Comment by xScruffers** [comment]
No mods have been added, no configuration files have been altered. SSP.

**Comment by Boomflex** [comment]
The way I found it to work, is if you press the LOCK button first, then using the /difficulty command it locks it.

I have tried 5/6 times and it worked that way as a workaround.

I will look in to why, but that works what I just described.

**Comment by Skar78** [comment]
I experienced this today after update to 5.3.9b and another guy also mentioned this in discord.

**Comment by Boomflex** [comment]
This is an age old Vanilla issue that has been around since 1.7.10

I have spoken with multi Pack Devs (Darkosto/Snowshock/Sherdian) and they have all had it reported but there is no fix other than restarting the profile and even then, it isn't a guaranteed fix.

Closing this as there is no fix we can do ourselves.
