### ISSUE TITLE
Void Ore Miner config typo

### ISSUE THREAD

**Issue by Spreezeh** [AllTheMods/ATM-3#512]
There is a typo in the config files for Environmental Tech Void Ore Miners. The entry for Thorium from Nuclearcraft is incorrectly spelt 'OD:oreThroium' which prevents the miners from mining thorium. The typo is in the config files for all of the tiers of void ore miner.

Thanks for the great pack and excellent updating and maintenance of it.

**Comment by Boomflex** [comment]
Please update to v5.9.3

Fixed this in the latest update.
