### ISSUE TITLE
Fluid Transporter not filling bucket?

### ISSUE THREAD

**Issue by RacerDelux** [AllTheMods/ATM-3#513]
Member on my server found this bug. He is trying to fill a bucket with redstone. Pics below show exactly the issue.
## Expected Behavior
![Expected](https://cdn.discordapp.com/attachments/350788803381952512/435543102284103686/unknown.png)
## Current Behavior
![Actual](https://cdn.discordapp.com/attachments/350788803381952512/435543043974627338/unknown.png)

**Comment by akihikotv** [comment]
Hi, i just found the same bug ;) - and i found this post 👍

**Comment by Buuz135** [comment]
This is an incompatibility with EnderIO adding fluids for its tinkers construct compat with the same name as TE fluids

**Comment by OrdinatorStouff** [comment]
I'm not sure about long-term fix but one user on discord has confirmed that resetting the fluid registry from level.dat has fixed the problem.  

THIS ALSO SUGGESTS that it is only a problem in existing worlds upgrading up and should not affect new worlds.  
  
![image](https://user-images.githubusercontent.com/6283913/38846424-1d620c74-41b1-11e8-8355-c192039e8fa2.png)

**Comment by Boomflex** [comment]
Fixed for New Worlds.

Will look in to it in more detail.

Thanks for the report.

**Comment by Boomflex** [comment]
Fixed in 5.9.3b

![image](https://user-images.githubusercontent.com/22868795/38903529-30afa2d6-429d-11e8-8748-be3500c3ece8.png)
