### ISSUE TITLE
Broken Textures/Something Not Right

### ISSUE THREAD

**Issue by engdev8** [AllTheMods/ATM-3#514]
I just installed the pack from twitch added Optifine and loaded it up. Once I got into a world everything was fine but nothing had the normal texture.

## Expected Behaviour
Textures should be normal

## Current Behavior
Textures not there/not right

## Possible Solution
I looked through configs of mods but it might be Optifine but I can't play modpacks without it.

## Steps to Reproduce
![2018-04-16_18 54 07](https://user-images.githubusercontent.com/24496657/38841056-261fea60-41a8-11e8-815c-cc3f0d260de3.png)

1. Install Optifine
2. Create world

**Comment by Boomflex** [comment]
Remove Optifine and try again. 

If it persists after removing Optifine then reinstall pack.

**Comment by engdev8** [comment]
I removed Optifine and loaded it up, problem persisted reinstalling pack now.

**Comment by engdev8** [comment]
I reinstalled pack from Twitch and the problem still there.

**Comment by engdev8** [comment]
Thanks ghatus, works now. Don't know why I didn't think of that!

**Comment by Boomflex** [comment]
Issue resolved.
