### ISSUE TITLE
Block and tile entity stop updating in a ported world from 5.9.1 to 5.9.3/5.9.3b

### ISSUE THREAD

**Issue by Flextt** [AllTheMods/ATM-3#520]
The 5.9.3b reduces world load times for me by 9 minutes from 10 minutes down to 1. This is a huge bonus for me because world load times despite a fairly good machine and the instances on the SSD have been 10-15 minutes. Unfortunately a few minutes into my ported 5.9.1 world (fresh configs, only journeymaps waypoint legacy) tile entities seem to bug out.

## Expected Behavior
As no significant changes have occured I expect to gain the performance gain while maintaining functionality of my current builds.

## Current Behavior
A few minutes into the ported world tile entities seem to break down. RFTools Storages cannot be opened. RFTools Builder loses its Quarry card. Elevators break down. Redstone functionality of RFTools screens breaks. Thermal Expansion machines no longer have animated GUIs but still work. Dropped items can be picked up but their model entity persists until I change the dimension and return.

## Possible Solution
Not applicable.

## Steps to Reproduce
1. Port world from 5.9.1 to 5.9.2 and if it works / persists, to 5.9.3 or 5.9.3b. Alternatively port directly from 5.9.1 to to 5.9.3b. I tested both, no difference.
2. Check different builds. Check different tile entities. Open up Thermal Expansion machines.
3. Tile entities bug out. Blocks and tile entities can no longer be broken. Dropped items e.g. from the inventory persist on the ground until I change dimensions e.g. with my RFTools Charged Porter.

## Log
[debug.log and latest.log](https://gist.github.com/Flextt/0c59ff033c420a9365df7678464b424a) of the test run

## Detailed Description
Not applicable.

**Comment by FallenEagle1** [comment]
First thing I would do is restart the pack, and see if it loads with a more realistic time (that 10ish minutes) if that still doesn't happen, redownload the pack. For some reason, starting a fresh pack sometimes doesn't load properly, especially when launched from twitch I've noticed. It is most likely this issue, the pack didn't initialize or download correctly, so this is why the world looks all messed up.

**Comment by Boomflex** [comment]
Just upgraded from 5.9.1 to 5.9.3b and had no issues in an existing world.

Will keep an eye on this but it sounds like a dodgy pack install.

**Comment by Flextt** [comment]
FallenEagle1, I dont get it. Whats your proposed solution? I cannot avoid using the Twitch App to get the installation files, can I?

**Comment by Boomflex** [comment]
You can use MultiMC and use the link from CurseForge: https://minecraft.curseforge.com/projects/all-the-mods-3/files/2553021/download

Install from ZIP.

That is how I play the pack.

**Comment by Flextt** [comment]
Cheers, I missed the ./download part.

**Comment by Flextt** [comment]
I tried the dev build and adding MultiMC in the Windows Firewall. Sadly it still gives "failure to resolved mod id" errors. It doesnt seem to work but I read that at times curseforge acts out. I will keep an eye on this and it isnt a pressing matter since the short world load seems to be abnormal and unintended. So thanks for taking the time anyway.

**Comment by Flextt** [comment]
Sorry for necroing. Fresh world, fresh config in 5.9.4b, did a few starting builds, updated to 5.9.5. Block updates again cease after dimension change or a few minutes. Tried with both a MultiMC instance and a Twitch Launcher instance.
