### ISSUE TITLE
Can't make Mana Orb 100% from Wizardry

### ISSUE THREAD

**Issue by Crasben** [AllTheMods/ATM-3#522]
## Expected Behavior
Give Mana Orb 100%

## Current Behavior
Does nothing

## Possible Solution
I don't know

## Steps to Reproduce
1. Throw an orb at the mana pool of Wyzardry

## Detailed Description
When you throw an orb in the mana pool of Wyzardry it does not give you after a while a Mana Orb 100%

**Comment by Boomflex** [comment]
Duplication.

Please check Closed Issues before repostins.

https://github.com/AllTheMods/ATM-3/issues/516

**Comment by FallenEagle1** [comment]
This is a known problem. Should be fixed, but in the mean time, in the config file there is a folder labelled wizardry. Delete the folders inside of it and restart minecraft and that should fix it.
