### ISSUE TITLE
craftingtweak/astral sorcery integration issue

### ISSUE THREAD

**Issue by andyoc1986** [AllTheMods/ATM-3#523]
## Expected Behavior
Placing a crafting table in an astral sorcery altar should allow you to craft the resonating wand and the luminous crafting table (to progress in the mod both steps need to be done). 

## Current Behavior
when i place the recipe in the crafting table it is not detecting it and/or crafting both items because craftingtweaks is changing the crafting table somehow. 

## Possible Solution
remove crafting tweaks is how i removed the bug.

## Steps to Reproduce
1.Go to a astral sorcery altar and place the crafting table.(making sure the star light connects)
2.Attempt to craft a Resonating wand or Luminous crafting table.

**Comment by FallenEagle1** [comment]
There is also a known bug where after changing minecraft worlds that the crafting is glitched sometimes. A restart of minecraft fixes this, so this may be related to that. The dev I believe is aware of it, but I'll check.

**Comment by kjmaster1** [comment]
Blay09 claims this is not an issue related to Crafting Tweaks - https://github.com/blay09/CraftingTweaks/issues/115
Hellfire is aware of the crafting glitch - https://github.com/HellFirePvP/AstralSorcery/issues/535
There is nothing that can be done on a pack level.
