### ISSUE TITLE
Forestry backpacks taking in wrong item types

### ISSUE THREAD

**Issue by Sakata-MC** [AllTheMods/ATM-3#524]
Several items seem to end up in the Miner's pack that shouldn't. Bat wings are one, a few plants end up in the backpack as well.

Many of the flowers, some bushes, and tree items are not recognised and pulled into the forester's backpack. (Botania ones shouldn't though, there is a special bag for them).

Thank you for your hard work on the pack. If I had time these days I'd offer to assist.

**Comment by Blueletric** [comment]
This is a mod bug and should be reported to the mod author. Nothing the ATM team can do on their side unfortunately.

**Comment by Boomflex** [comment]
Please post here: https://github.com/ForestryMC/ForestryMC/issues

Not a pack issue.
