### ISSUE TITLE
Tesselating Block Model Crash

### ISSUE THREAD

**Issue by NoMoreStars** [AllTheMods/ATM-3#526]
The program crashes whenever one of two things are done. A: I look towards the Applied Energistics 2 Hand Crank block, which causes a crash, or B: I attempt to break any block in the world, which also results in a crash.

Attempted to update deleting Java, updating Java, allocating a reasonable amount of ram (6GB), uninstalling ATM3, reinstalling ATM3, giving Java administrator permissions, updating video drivers, and nothing works. For reference, i'm running ATM3 through the Twitch launcher on Windows 10 with a total of 8GB or ram installed.

## Steps to Reproduce
1. Launch ATM3
2. Launch Any World.
3. Do One of the following:
     a. break a block
          -. crash
     b. look in the general direction of the applied energistics hand crank
          -. crash

EDIT: https://gist.github.com/Boomflex/4eae2ff603627433f5a65b4743f219f6

**Comment by FallenEagle1** [comment]
Please put that log somewhere like gist.github or hastebin and link it here. Its hard to scroll through all that on a github post. That being said, first thing you could try is to remove those blocks with commands (if singleplayer, can open to lan to temporarily turn cheats on). If that doesnt fix it, you could try changing foamfix from anarchy to lawful, or add in optifine. I would try removing them first though.

**Comment by Chubblezap** [comment]
Getting the same thing here. Seems to be something with FoamFix, turning off the coremod in the config fixed the crashing but made it unbearably laggy. Wasn't able to determine which part of the coremod is actually causing it, assuming that's the case.

**Comment by Chubblezap** [comment]
@FallenEagle1 It isn't an issue with any specific block, it happens whenever you try to break something. I'm guessing it's something to do with the "crack" texture. I tried to do a fresh install but Twitch isn't letting me download the pack anymore, so I can't do more testing at the moment.

**Comment by NoMoreStars** [comment]
@Chubblezap Yep I can attest to disabling FoamFix fixing the crash at the cost of unbearable lag. I would not recommend trying it for yourself. So something with FoamFix seems to be causing the issue. As for the technical side, I'm clueless on this front.

**Comment by Boomflex** [comment]
There is a FoamFix update in the next pack update which should minimise this issue.

Please report back after the next update if it persists.
