### ISSUE TITLE
RFtools builder 

### ISSUE THREAD

**Issue by lalleman44** [AllTheMods/ATM-3#528]
restarting the game results in loss of quarry card in rftools builder.

## Expected Behavior
builder should keep the card and move on

## Current Behavior
builder remains only to be idle with no more card inserted.

## Possible Solution
???

## Steps to Reproduce

1.set builder and insert a quarry card 
2.let the quarry run
3.leave the game
4.after restarting the game, the builder remains with no card inside the builder.

Please advice

**Comment by Yoosk** [comment]
version of t he game?

**Comment by lalleman44** [comment]
version 5.3.9b

tested more and card goes away even without restarting the game.
Planted different cards in the builder , card poof gone when exiting and entering the builder.
It's in the mining dimension.

**Comment by jasondm** [comment]
This wouldn't happen to be in any chunks claimed/chunkloaded with ftbutilities, would it?

**Comment by FallenEagle1** [comment]
Any changes to the pack? (Ex. spongeforge, added mods, etc)

**Comment by lalleman44** [comment]
ah there could be the problem,yes i used ftb chunkloading.

Nope, nothing changed in the pack, just the standard pack that i'm using.

**Comment by FallenEagle1** [comment]
There are a couple other chunkloaders in the pack, such as ic2 chunkloader, chunk ward from Exu2, and maybe another I'm forgetting. Also, pnuematiccraft has a protection system in it. Have you tried deleting the current builder and replacing it?

**Comment by jasondm** [comment]
Yeah, just claiming chunks with it can cause issues, so player presence doesn't matter.

**Comment by lalleman44** [comment]
haven't tried other chunkloaders from the pack (not a big fan) 
yes, even made a new one to test out :(
will be testing the chickenchunks loader tomorrow 

Thanks for the feedback so far you guys :)

**Comment by lalleman44** [comment]
first tested it with no chunkloading and it worked,later  chickenchunks chunkloader and still works,so seems like ftb chunkloading does not like something. (had trouble with ftb chunkloading environment tech too)

**Comment by jasondm** [comment]
If it isn't one thing, it's another, eh?  I think the rftool issue is solved; the mining dimension issue might be related to an issue I had in a past as well. 

Basically, dimensions without players present, even chunkloaded, seemed to get unloaded or "paused" or something. I "fixed" it by restarting the server and it seemed to work fine after that.  It might be related to a forge chunkloading option, the unloader mod, some other mod, or just a vanilla problem. I never found a decent solution to it, but it only happened twice (once in single player, once on another server) so I never pursued it further.

**Comment by lalleman44** [comment]
hmm. maybe i will set my code cap on :) yeah . i haven't had much problems with most packs and mods, only this modpack gives me a headache.
Anyways, thanks for the input , hopefully me or somebody will find a sollution for this problem.

**Comment by Boomflex** [comment]
I have just tried this 3 times on 5.9.3c and the card has stayed in the machine every single time...

Not reproducible on our end.
