### ISSUE TITLE
Cannot install from Twitch app because DiscordSuite removed from Curseforge

### ISSUE THREAD

**Issue by givepiesachance** [AllTheMods/ATM-3#529]
I attempted to make a fresh install of version 5.9.3b with the Twitch app.  The install fails with an error stating "Cannot find child addon: 282743."  It appears that Curseforge project 282743 is DiscordSuite, and their Curseforge page has been taken down.

You may need to remove this mod to allow fresh downloads.

**Comment by Boomflex** [comment]
Unfortunately, a mod in our modpack has been removed from CurseForge due to issues out of our control which is causing the issue you are having. The mod DiscordSuite is causing the pack to fail to install. We have a Hotfix uploaded to CurseForge but we are awaiting Approval
