### ISSUE TITLE
Nutrient Distillation cannot be brewed using Nether Wart

### ISSUE THREAD

**Issue by Dhs92** [AllTheMods/ATM-3#532]
## Expected Behavior

Netherwart should be accepted by The Vat to brew Nutrient Distillation from EnderIO.

## Current Behavior

The recipe does not exist because of a typo in the main config (gets reset whenever you restart the client)

## Possible Solution

Update EnderIO to a nightly build if possible.

**Comment by FallenEagle1** [comment]
Which typo are you seeing that you think is resetting it? I just looked through the vat.xml and netherwart is still showing up even after restarts.

The other thing, I just tested this in a test pack with just ender io in it and it does not work, so this is not an issue with the modpack, rather an issue with the mod itself.

**Comment by Dhs92** [comment]
The issue was fixed in one of the nightlies. The issue is that minecraft:nether_wart refers to the block version of the item. In the more recent versions they have changed it to item:minecraft:nether_wart, which fixed the recipe.

**Comment by Boomflex** [comment]
If the fixed version isn’t on CurseForge then it will stay like that till it is. 

They’ve obviously fixed it in Dev so will close this.
