### ISSUE TITLE
Configuration file compatibility

### ISSUE THREAD

**Issue by Sakata-MC** [AllTheMods/ATM-3#533]
There are a few config files that get recreated on linux server systems. This is likely due to some mods not using the same case in different places, like looking for "Waystones.cfg" and not seeing that "waystones.cfg" is there and the desired file.

If this isn't the mod's fault, it is possible that the pack may need to have config files' names generated while on a linux system so the case is correct, then editing/including from there.

If not, I have submitted bug reports to some of the ones I noticed, but perhaps incorrectly before I thought about it.

**Comment by Boomflex** [comment]
This is a mod by mod issue.

Please report it to the relevant devs.
