### ISSUE TITLE
ATM 3 Does not load, Staff unhelpful to resolve the issue, Will never touch ATM again or support it

### ISSUE THREAD

**Issue by Solverbolt** [AllTheMods/ATM-3#534]
## Expected Behavior

Actually work to resolve the issue, instead of giving only partial answers that have no real information. 

## Current Behavior

I asked for assistance because All The Mods 3 would not load, at first it was a crash error due to DiscordSuite, but even after removal of that mod, the modpack would hang at full loading until ram crash. 
When mentioned to staff, they gave me the answer that i needed to make changes to my java settings, but provided no links or other information to actually know what changes needed to be made. 

One helper refused to even log back on to his computer.

## Possible Solution

Fire every single helper and general staff, as they are unwilling to actually do their task with any effort.

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

If the current staff of helpers are kept, then I will not only stop supporting in anyway this project, but will go out of my way to warn all my viewers and fellow minecraft mod friends to stay as far away from this project.

**Comment by FallenEagle1** [comment]
I've been on the whole time, just doing multiple things. Along with that, I mentioned that the answer was in the pinned messages of that help desk. It is a common question so the answer is pinned there to be looked at.

**Comment by whatthedrunk** [comment]
Have fun with that one.
