### ISSUE TITLE
Nature's Compass causes intermittent crashes/server shutdowns

### ISSUE THREAD

**Issue by shiney103** [AllTheMods/ATM-3#535]
During gameplay, attempting to search for biomes with the nature's compass will sometimes cause the user to be disconnected, and sometimes crash the server itself. This is with the newest 5.9.4 release,

## Expected Behavior
The compass should search for a nearby biome, and display the information on it, or display that it was not found.

## Current Behavior
Sometimes when clicking on a biome to search for (Happened with canyon, and vanilla desert) has crashed the server twice, and searching for the Alps biome has disconnected the user. Other times, it seems to function normally.

## Steps to Reproduce
Suggested, might not work. Unable to test further as admin is disabling NC until a fix is found.
1. Add a nature's compass, or craft one.
2. Scroll through the list of biomes, and find different ones to select.
3. Click "Search" and wait anywhere from instant, to several seconds for a disconnect or crash. (Only happens some of the time, others the biome is found without issue.)

## Log
Asked admin for log, will add it if I receive it.

**Comment by Boomflex** [comment]
Use the Compass for 20 mins selected MULTIPLE biomes with 0 issues.

Non-reproducible.

Please get logs if possible.
