### ISSUE TITLE
Thaumcraft doesnt allow progress past Aspect smelting in thaumonon

### ISSUE THREAD

**Issue by bwser20** [AllTheMods/ATM-3#536]
Does not finish research after picking up 6 different vis crystals.

## Expected Behavior
It should unlock then next stage of Essentia smelting 

## Current Behavior
does not unlock next stage

## Possible Solution
Fix code

## Steps to Reproduce

1. Get upto essential smelting
2. Get required resources
3. Research isn't unlocked
4.

**Comment by Boomflex** [comment]
Known issue with Thaumcraft.

This will be fixed in future update.
