### ISSUE TITLE
Environmental Tech - Solar Arrays no longer working in The End

### ISSUE THREAD

**Issue by stardustrider** [AllTheMods/ATM-3#538]
In previous version of ATM3, Solar Arrays worked in The End, whereas the latest (v5.9.4b, with the previous used being v5.9.3b) they don't.

ET hasn't been updated since March, so maybe this is a Forge issue/change?

**Comment by Boomflex** [comment]
Well the End is night... so it shouldn't actually work.

So, maybe Forge fixed this.
