### ISSUE TITLE
Trying to mine a block with a pickaxe resets your progress of mining

### ISSUE THREAD

**Issue by Danimineiro** [AllTheMods/ATM-3#539]
## Expected Behavior
Normal mining of a block.

## Current Behavior
Sporadically, the progress resets while mining.

## Steps to Reproduce
[https://youtu.be/GhP8fpIQcfw?t=39s](url)
In the video above you can sporadically see the progress resetting.

**Comment by Boomflex** [comment]
Video doesn't work.

What version of the pack?

What have you added?

What RAM?

What Java?

If you enter no information, how do you actually expect to get a response?

D- Try harder.

**Comment by Danimineiro** [comment]
The video dos work, just clicking on the link doesn't seem to.

This is on the newest Version, 5.9.4b, though the Server is on 5.9.4.

I didn't add nothing.

My Pc has 16 GB of Ram, I allocated 12 on Twitch, the Server I'm running this on has 6 GB of RAM to run the Modpack.

My Java is on build 1.8.0_171-b11, the Server is running on build 1.8.0_121-b13.
