### ISSUE TITLE
DarkUtils Sneaky blocks crash u.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#54]
DarkUtils version: 1.6.162
Forge version: 2413

When u place a "Sneaky Block" in the world it crashes u and nobody can enter the area.
My crash log just in case: https://pastebin.com/TR2Q4hYE
Maybe it's useful somehow.

**Comment by Boomflex** [comment]
Already reported to Dev. 

Fixed in latest build.
