### ISSUE TITLE
Redstone Furnace not accepting wood to turn into charcoal

### ISSUE THREAD

**Issue by 9-30am** [AllTheMods/ATM-3#541]

**Comment by Boomflex** [comment]
https://streamable.com/sn4rp

**Comment by 9-30am** [comment]
![redstone-furnace](https://user-images.githubusercontent.com/23363817/39410413-6b9ab8c6-4bbd-11e8-928c-0b1237bcfa6b.PNG)

**Comment by 9-30am** [comment]
Then what am I doing wrong? In the JEI, it says I can use wood in the redstone furnace to turn into charcoal.

**Comment by fractaltheory** [comment]
I'm getting this problem as well - JEI is showing the recipe and I can insert into the machine, but it won't smelt.
