### ISSUE TITLE
Regenerate Config Files...

### ISSUE THREAD

**Issue by OscarXcore** [AllTheMods/ATM-3#543]
This is more of a TODO type thing.

I just noticed that FoamFix was pretty much useless because its config file was from ages ago and had nothing from recent versions that makes it useful.

I don't know how many configs this may effect, but I am thinking a good majority.

## Expected Behavior
Foamfix config should have useful options such as the ability to enable multithreading when deduplicating models.

## Current Behavior
That option didnt exist, along with many others.

## Possible Solution
1) Make a copy of the current config folder somewhere else on your PC.
2) Delete the config folder in the instance folder.
3) Load the pack fully to generate all new stuff.
4) Close the modpack.
5) **Manually** (Yes, manually, or with a python script if you are a cool kid) restore the new config values to match the old ones as well as keep an eye out for new entries in the config files and change them accordingly
6) Push the update

## Steps to Reproduce
Download the modpack...

## Log
No logs for you.

## Detailed Description
It can't get anymore detailed than whats in the Possible Solution section.

**Comment by OscarXcore** [comment]
I could even the config regeneration and restoration for you as well as make a list of new entries so you know what is new and what may or may not need changing.

**Comment by Blueletric** [comment]
Multithreading in minecraft is one of the hardest things to do at this point because it was made to run on one core. If you come up with a multithreading mod that works, I'm sure that foamfix would love to implement it.

**Comment by OscarXcore** [comment]
You what?

Did you just skim the whole thing and get stuck on multithreading?

If the foamfix config what new and up to date. This would be an option.

**
# Threaded, parallel model baking. [default: false]
    B:parallelModelBaking=false
**

Under Experimental

**Comment by Blueletric** [comment]
Yes, I do know about that and no I did not just skim the entire thing, I read it. They don't have that enabled for a reason because it can cause crashes in some instances.

**Comment by OscarXcore** [comment]
Ok fair point. They also cant have it enabled in the current version of the pack, if it doesnt exist because the config is out of date. Back to the issue at hand. Can I look forward to the modpack having up to date configs? or am I gonna have to do it myself?

**Comment by Blueletric** [comment]
They will update the configs if they get the chance, I will mention it to boom and wtd.

**Comment by OscarXcore** [comment]
Ok cool. May I speed it up if I do it myself anyways?

**Comment by Blueletric** [comment]
If you do it yourself, it will only be locally so yes.

**Comment by OscarXcore** [comment]
Of course. Not what I meant.

Let me repost what I offered.

```
I could even do the config regeneration and restoration for you as well as make a list of new entries so you know what is new and what may or may not need changing.
```

**Comment by OscarXcore** [comment]
I would just end up zipping the folder and sending it to one of you guys.

**Comment by Blueletric** [comment]
Sorry, its 1 am here I'm just busting these things out. The ATM core team handles everything for the packs.

**Comment by OscarXcore** [comment]
No worries. If I do it, I may just make a NodeJS thing that will do it all for me.
Search the Old configs folder for a .cfg file, find a matching one in the New configs folder.
Parse out both, evaluate all config entries and sort them, one pile is entries that are common between both configs, and the other is entries that are not common.

Common entries get their values copied from Old to New.
Uncommon entries get stuffed into a JS Object with other info for differentiation, which will then be either kept and logged into a text file with which config file its from, and what line/entry name, if its from a New config; otherwise its put into a comment block at the bottom of the New config file at reconstruction.

Rinse and repeat.

**Comment by OscarXcore** [comment]
tbh, this might be really useful in the future. So whether you arent ok with it or not, I am probably gonna still make it and base it off of the ATM 3 config folder since its the only testing subject I have that will have drastic changes between old and new configs.

**Comment by Boomflex** [comment]
Thanks for the heads up.
