### ISSUE TITLE
Thermal Foundation Iridium converts to Tech Reborn Nuggets

### ISSUE THREAD

**Issue by ozhound** [AllTheMods/ATM-3#544]
## Expected Behavior
Should convert into TF Nuggets not Tech Reborn Nuggets

## Steps to Reproduce
1. In Self Crafting grid, TF ingot converts to TR Nugget
2. If you try and convert 9 TR Nuggets to TF it converts it to TR Nuggets

**Comment by OrdinatorStouff** [comment]
Can be addressed manually just like bronze is [here](https://github.com/AllTheMods/ATM-3/blob/dev/overrides/scripts/atm_oredict_unify_metals.zs#L198)

**Comment by Boomflex** [comment]
Fixed in 5.9.5

Thanks KJ
