### ISSUE TITLE
Industrial Foregoing Plant Interactor duplicates Mystical Agriculture seeds

### ISSUE THREAD

**Issue by Sovereignty89** [AllTheMods/ATM-3#545]
## Expected Behavior

No seeds should be duplicated/gathered by the Plant Interactor.

## Current Behavior

The Plant Interactor gathers both the crop and seeds and duplicates the seeds 1:1 ratio.

## Steps to Reproduce

1. https://gfycat.com/SparseAntiqueBoa

## Detailed Description

Wasn't a hundred percent sure where to create this issue. Here? Industrial Foregoing or Integration Foregoing?

**Comment by Buuz135** [comment]
Already fixed in the latest public version 😎

**Comment by Sovereignty89** [comment]
Thank you very much good sir! I shall close this issue and alert my server admins about this.

**Comment by Buuz135** [comment]
Of Industrial Foregoing*

**Comment by Sovereignty89** [comment]
Apologies I misunderstood. I just noticed that the latest version of your mod Industrial Foregoing isn't in the latest version of ATM3 (which we aren't running yet). I assumed that we only had to update to the latest version of ATM3. We shall have to be patient and wait a bit and hope that our players don't go too crazy on the crops! Again, thank you.
