### ISSUE TITLE
Server kicked players with "fly is not avilable" when they flying

### ISSUE THREAD

**Issue by GordonHollow** [AllTheMods/ATM-3#547]
On ATM-3 server i set allow-flight=true, but sometimes i was kicked with reason "fly is not available for this server"

Is this modpack have some mods that override server settings for disable fly?

**Comment by ghatus0** [comment]
Check to make sure that there isn't a space after true, I've heard that's a thing.

**Comment by GordonHollow** [comment]
Yes, it is.
