### ISSUE TITLE
Pig to Demon Pig, Cows to Demon Cows

### ISSUE THREAD

**Issue by Streuld** [AllTheMods/ATM-3#548]
## Expected Behavior

When I kill pigs and cows in the overworld, they should normally die.

## Current Behavior

Pigs and cows in the overworld are aggressive, attack me as soon as I get near them. It also displays their mod name as AbyssalCraft in The One Probe. When I kill those pigs and cows in the overworld (seems to happen only on beaches, though I don't know if that affects it or if that's just coincidence), they make ghast noises as I'm hitting them, and when they die they turn into Demon Pigs and Demon Cows. 

https://imgur.com/a/nE6J1fq
https://imgur.com/a/zEMFjZQ

## Steps to Reproduce

1.Find a cow or a pig in the overworld
2.Kill it
3.they turn into demons

**Comment by Boomflex** [comment]
Intended behaviour.

Part of AbyssaCraft.
