### ISSUE TITLE
Tungsten dust no longer smelts in a redstone furnace

### ISSUE THREAD

**Issue by Trinsdar** [AllTheMods/ATM-3#552]
Simple: tungsten dust no longer will smelt into ingots in the redstone furnace from TE. it will only smelt in a vanilla furnace and exu2 furnace and any other furnace that uses the vanilla  furnace recipes.

I am using version 5.9.4

**Comment by Boomflex** [comment]
Recipe has moved to the Induction Smelter

![image](https://user-images.githubusercontent.com/22868795/39667127-3d3e8f2c-50a7-11e8-9177-32d6e00c46cb.png)
