### ISSUE TITLE
After teleporting too much, unable to do anything

### ISSUE THREAD

**Issue by Streuld** [AllTheMods/ATM-3#553]
## Expected Behavior
After teleporting via /spawn and /home a few times, everything should work as usual.

## Current Behavior
After teleporting via /spawn and /home a couple of times due to me forgetting stuff, I became unable to teleport with any command anymore, and I couldn't break any blocks. Doing /spawn or /home would just output "Teleported to spawn/home" in chat, it wouldn't transport my character anywhere. (This happened as I was moving through portals, e.g. teleported with /home while in the Nether or End, so that might have something to do with it.)

**Comment by Boomflex** [comment]
Changing Dimensions has been an issue since Modded Minecraft.

Maybe report this to FTBUtilities.

Nothing can be done on a pack level.
