### ISSUE TITLE
Tessalating Block error When Breaking Blocks

### ISSUE THREAD

**Issue by Kuraikhaos** [AllTheMods/ATM-3#555]
## Expected Behavior
Should be able to break blocks.

## Current Behavior
Crashes when I try to break anything.

## Log[
https://gist.github.com/Kuraikhaos/adc7e0e15f71f898835a3ad89b05b70e#file-crash-2018-05-05_20-46-00-client-txt

## Detailed Description
I load into a world and every thing is fine until i try to break anything.
Also I'm using v5.9.3
Trying to play on a friends server

**Comment by Boomflex** [comment]
Update to latest version of the pack.
