### ISSUE TITLE
Certain Thermal Expansion recipes not showing crafting recipe in JEI (Item is still craft-able)

### ISSUE THREAD

**Issue by Shaggy01** [AllTheMods/ATM-3#557]
## Expected Behavior

When the item is clicked on inside of JEI, it should show how the item is made.

## Current Behavior

When the item(s) is clicked on inside of JEI, nothing happens. It dos not show the item's crafting recipe.

## Steps to Reproduce

1.Open JEI
2.Search for: "Portable Tank", "Energy Cell", "Cache",  "Strongbox",  and/or "Reinforced Cell Frame"
3.Click on  "Portable Tank", "Energy Cell", "Cache",  "Strongbox",  and/or "Reinforced Cell Frame"
4.Nothing happens.

**Comment by Boomflex** [comment]
As of v5.9.4b the recipes above do work and show correctly.

You may need to reinstall the instance or upgrade to the latest version if not on it.

![image](https://user-images.githubusercontent.com/22868795/39715607-c4767534-5225-11e8-8fc8-71582f07acd1.png)
![image](https://user-images.githubusercontent.com/22868795/39715623-d092da60-5225-11e8-8f5b-9d31d02d8771.png)
![image](https://user-images.githubusercontent.com/22868795/39715628-d659fa3c-5225-11e8-88ba-80f889ffba14.png)
