### ISSUE TITLE
[5.9.5] Base game crashing at startup

### ISSUE THREAD

**Issue by xhatz** [AllTheMods/ATM-3#561]
Hello! Since the latest version, once I start my game, it crashes during the main loading (before showing the menus) and shows me an error message. I believe that it worked once, but I haven't touched to anything since then, and it keeps crashing...

## Expected Behavior
The game should just load...

## Current Behavior
Just before the game finishes loading after being started, it crashes and gives me this error:
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)`

## Steps to Reproduce
1. Install ATM3 5.9.5 on a fresh instance and start it
2. Wait :/

## Log
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)`

**Comment by Boomflex** [comment]
You need to allocate more RAM. 

In th Twitch App allocate it 6GB. This will fix it.

**Comment by xhatz** [comment]
Ohh it used to always work from above 4GB! Thank you for your reply though :P!

**Comment by Boomflex** [comment]
ATM3 hasn’t worked with 4GB of RAM for about 6 months... You been away?

Pleased it’s sorted.
