### ISSUE TITLE
Quark chests

### ISSUE THREAD

**Issue by vrork** [AllTheMods/ATM-3#567]
Are the chests added by quark made from other wood types disabled? If yes, how i can enable them again?

**Comment by Blueletric** [comment]
I PRed a fix for this last night, if @Boomflex merges it they will work

**Comment by vrork** [comment]
Was that a quark issue or a modpack issue? I been seeing quark having some problems.

(Btw, you guys having problems with the gears? Something seems to be weird between AE2 and EnderIO)

**Comment by Boomflex** [comment]
Will work in new update.
