### ISSUE TITLE
Block tessellation crash

### ISSUE THREAD

**Issue by rhystuck** [AllTheMods/ATM-3#568]
I keep getting crashes that seem to be due to block tessellation. I also had this happen in Enigmatica 2, so might not be due to the modpack, but I didn't know where else to go to get help for this. Here's some crash logs:

Server: https://pastebin.com/GHU8vq7H
Client: https://pastebin.com/iVt2Rv2n

**Comment by Boomflex** [comment]
Not a modpack Issue. 

Try installing Optifine.
