### ISSUE TITLE
Server loading issue with Thaumcraft Aura generation

### ISSUE THREAD

**Issue by theduke0001** [AllTheMods/ATM-3#569]
When the server is finished loading the world it tries loading auras and says it is taking too long, here is an example of what the log says:
AURAS TAKING 2234 ms LONGER THAN NORMAL IN DIM 0
The time can range from 1000ms to 50000ms
There is also something else taking too long to load and that is Greenhouse, the log for that is as follows:
GREENHOUSE TAKING 13273 ms LONGER THAN NORMAL
I'm not sure why this is occurring because I don't have a problem in single player loading All the Mods version 5.9.5

**Comment by Boomflex** [comment]
Please report this to the Thaumcraft Dev, not a pack issue.

Thanks.
