### ISSUE TITLE
crash when trying to chisel marble blocks from astral sorcery

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-3#57]
Don`t have a crashlog in this moment but can provide it if necassary. 
EDIT : here is the crash report: https://pastebin.com/wY2j0yx6

**Comment by DietmarKrause** [comment]
https://github.com/Chisel-Team/Chisel/issues/492

**Comment by DietmarKrause** [comment]
https://github.com/Chisel-Team/Chisel/issues/496

**Comment by Boomflex** [comment]
Outdated Chisel.
