### ISSUE TITLE
ATM3 Crash - Possibly related to Dismantler or one of ValkyrieofNight's mods

### ISSUE THREAD

**Issue by NightsBladeofTruth** [AllTheMods/ATM-3#573]
During loading, MC crashed to desktop with [THIS ERROR.](https://pastebin.com/WUcXrK9C)

Disabling Dismantler fixed the crash. The only modification made to the pack was adding VanillaFix.

**Comment by Boomflex** [comment]
We do not recommend adding VanillaFix to our packs.

**Comment by Yoosk** [comment]
You,ve allocated 4GB of ram, that's likely to crash.
