### ISSUE TITLE
Twilight Forest - Acid Rain issue (not sure if I did it wrong, or it is a bug)

### ISSUE THREAD

**Issue by Thunder-Nova** [AllTheMods/ATM-3#576]
## Modpack Version

V5.9.5

## Expected Behavior

Acid Rain to dissipate as soon as I kill the Ur-Ghast, Ice Queen, and Hydra

## Current Behavior

Acid Rain did not dissipate as soon as I kill the Ur-Ghast, Ice Queen, and Hydra (Even in my achievements it says I killed them)

## Steps to Reproduce

Pretty much self explanatory
<a href="https://ibb.co/bWYD6J"><img src="https://preview.ibb.co/jz54Dy/Acid_Rain.png" alt="Acid_Rain" border="0"></a>

**Comment by Boomflex** [comment]
Fixed in latest update.
