### ISSUE TITLE
Lag opening Simple Stirling Generator from EnderIO

### ISSUE THREAD

**Issue by DiamondGallery** [AllTheMods/ATM-3#577]
## Expected Behavior

Computer/Game-stalling lag when opening simple stirling generator each time.

## Current Behavior

3-4 second lag upon each attempt to open Simple Stirling Generator. Seems like game is going to crash but has always recovered so far.

## Possible Solution

Tried tweaking a huge number of settings including RAM and in-game/mod settings.

## Steps to Reproduce

1. Download all the mods 3 via twitch launcher. Run everything latest version, increase RAM slightly at first.
2. Once atm3 loaded, create default new survival SP world. 
3. Acquire enough resources to build Simple Stirling Generator from EnderIO. 
4. Place it down, everytime its opened computer/game waits 3-4 seconds before responding.

**Comment by Boomflex** [comment]
This is an Ender IO issue, not something we can do on a pack level.

Please report it to the appropriate Github: https://github.com/SleepyTrousers/EnderIO/issues
