### ISSUE TITLE
Yeta Wrench Causing CTD on Enderio Machines

### ISSUE THREAD

**Issue by ozhound** [AllTheMods/ATM-3#578]
## Expected Behavior
Machine should break as per normal

## Current Behavior
Using the Yeta Wrench, Sneak Right Click to Break a Machine (SLice and Dice and Tank tested) Causes the game to Crash to Desktop

## Possible Solution
Using Normal Pickaxe as a work around

## Log
https://paste.ubuntu.com/p/6MMQsBJskT/

**Comment by Yoosk** [comment]
https://github.com/AllTheMods/ATM-3/issues/565
