### ISSUE TITLE
Won't load with Discord mod in Linux

### ISSUE THREAD

**Issue by oodgaard** [AllTheMods/ATM-3#580]
v5.9.5 wont load in Linux with the Discord mod enabled.

## Expected Behavior
Should load with Discord mod enabled in generic x86-64 Linux.

## Current Behavior
Crashes not long after starting.

## Steps to Reproduce
1. Use MultiMC to install the mod pack on Linux - in my case Solus Linux.
2. Adjust max memory for java to >= 4096MB
3. Launch mod pack.

## Log
https://pastebin.com/cBCYHs1m

## Detailed Description
Perhaps the author of the discord mod can fix it for Linux ? Perhaps test on more than just Ubuntu ?

**Comment by Daktyl198** [comment]
This crash also happens in macOS. I had to disable the Discord mod for a friend because she couldn't even get past stage 1/7.

Both Twitch and MultiMC launchers.

**Comment by Yoosk** [comment]
I would suggest to make issue on his github: https://github.com/AstroInteractive/DiscordSuite/issues

**Comment by oodgaard** [comment]
Found an existing issue: https://github.com/AstroInteractive/DiscordSuite/issues/37

**Comment by Boomflex** [comment]
Known issue.

Both Linux and Mac already fixed in update.

v5.9.6 will fix this.
