### ISSUE TITLE
Server Not Working Properly

### ISSUE THREAD

**Issue by VolkBanda** [AllTheMods/ATM-3#581]
I just installed the ATM3 server pack and put it into a seperate folder like your supposed to.  When I click the serverstart bat file, it goes through the steps but then stops and says "There was an Error, Code : "ForgeDownloadURLNotFound".  I've looked everywhere, but could not find the solution, please help.

**Comment by FallenEagle1** [comment]
Double check the version needed in the settings.cfg file, but you can manually download the forge files. The forge universal file and the forge installer file (not forge installer-win) are needed.

**Comment by VolkBanda** [comment]
Unfortunatly, im not sure what you mean by this.
