### ISSUE TITLE
Iridium Shard can only be found in dungeon/fortress loot making Jetpack Attachment Plate difficult to craft

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM-3#582]
## Expected Behavior
The expected behavior would be to craft the jetpack attachment plate by mining iridium ore and converting it to ingots and/or nuggets.

## Current Behavior
you can only find iridium shards through dungeon/fortress loot.

## Possible Solution
oredict iridium shards and nuggets.

## Steps to Reproduce
N/A

## Log
N/A

## Detailed Description
In order to craft the jetpack attachment plate you need four iridium shards from Industrial Craft 2 (IC2). There are three forms of iridium ore that can be found/mined but form ingots and nuggets. According to JEI 9 shards make an ore (ball shape). for the minable iridium ore 9 nuggets form an ingot and you get one ingot from an ore. Currently there is no reliable way to craft the jetpack without exploring multiple dungeon/fortress. I have already explored two nether fortresses and an end city and did not get iridium shards. After 5 minutes of mining in the mining dim I was able to find iridium ore.

**Comment by OrdinatorStouff** [comment]
I want to expand cross-mod compatability but I also want to be careful to not trivialize iridium in the context of IC2 where it is an extremely rare/valuable material. Otherwise I agree and am on-board.

**Comment by Yoosk** [comment]
You are aware that you can duplicate iridium shards using some ic2 machines? That's the way you should aim for.

**Comment by SpeedSlider** [comment]
closing issue as originator.
