### ISSUE TITLE
Can't Make Pigiron from Tinker's Construct

### ISSUE THREAD

**Issue by LastXsile** [AllTheMods/ATM-3#583]
Over 3 blocks of molten Iron, 3000mb of Blood, 4 blocks of clay, lava is in the tank and its well over the require temperature.
## Expected Behavior

Molten Materials should alloy into pigiron.

## Current Behavior

Molten Materials don't combine and stay seperated.

## Steps to Reproduce

1.Add materials in smeltery
2.Materials smelt into molten
3.
4.

**Comment by FallenEagle1** [comment]
Try putting more blood into it. That seems like a low amount for it

**Comment by LastXsile** [comment]
Sorry 3000mb Ill edit the post

**Comment by kjmaster1** [comment]
Not sure what went wrong for LastXsile but Pigiron can be made just fine - https://streamable.com/ilt9m

**Comment by Boomflex** [comment]
Working as intended.

**Comment by LastXsile** [comment]
This seems to have fixed itself, im not sure what was causing it, but i think it had something to do with the type of blood being used to make the pigiron. Ethier way it resolved now thanks for your time.

**Comment by kohlth** [comment]
seem to be having the same issue for some reason, i also can seem to be able to create blood in the smeltery with mobs and myself (they lose health but no pig iron is made)
