### ISSUE TITLE
all the mods 3 difficulty bug

### ISSUE THREAD

**Issue by nynedog** [AllTheMods/ATM-3#584]
i have played hundreds of mod packs over the years and this is a first for me i was playing all the mods 3 after updating it. today i came across a bug where i am unable to change the difficulty from normal. i can change it but it changes right back no matter what i do. this has never happen to me in this mod pack before or any other mod pack anyone know how to fix this

**Comment by Boomflex** [comment]
Known issue from Vanilla.

Not fixable from a pack level.

**Comment by ZombieHDGaming** [comment]
If we can get more info about this bug, either via issue on our tracker or other means, we can have VanillaFix fix this issue, if ATM would like to take advantage of VF at a later date.

For now, we'd still like to provide a fix for this in VanillaFix, but some more info about this would be helpful, if you can provide it please.

**Comment by Boomflex** [comment]
VanillaFix, at this stage (and for the foreseeable) isn't something we would look to add to the pack, but by all means try to fix this issue.

**Comment by ZombieHDGaming** [comment]
We will definitely look into fixing this for other players, but just out of curiousity, is there any particular reason you wouldn't want to use it in ATM @Boomflex? While I can understand that we are still very much in a beta phase and have stuff we need to work on and fix (trust me, we work hard to fix any and all issues that arise pretty quick), but there are some very helpful features that I think could be handy for a large modpack, such as yours.
