### ISSUE TITLE
Crafting Lag

### ISSUE THREAD

**Issue by ProStashio** [AllTheMods/ATM-3#588]
Crafting Lag/Server Timeout when crafting items in bulk such as Iron Blocks. Works well ina Forestry Workbench but not a Vanilla/Tinkers. (Maybe more, but this is what we have found.)

## Expected Behavior
Should craft with no lag

## Current Behavior
Lags & times out the server

## Steps to Reproduce
https://www.youtube.com/watch?v=u-IBMWxsbnI&feature=youtu.be

## Log
https://gist.github.com/ProStashio/114e4d3641dee4b25f9302658d3e1270

**Comment by Boomflex** [comment]
Not fixable on a pack level.

**Comment by Rikudouu** [comment]
Did you end up finding out any workaround? Anytime someone crafts a stack, the server lags out and kicks everyone. Half of us crash completely as well due to RAM issues.

**Comment by martmists** [comment]
This is a vanilla issue since the 1.10 crafting update. Unless you want to try patching Minecraft internals, I doubt there will be a solution to this.

**Comment by Rikudouu** [comment]
Actually, it looks like the server lag is caused by Spongeforge. I removed Spongeforge, and the server lag disappeared, but the client side lag was still there. The client side lag is tolerable, but not the server lag. 

In case anyone else has this issue, try removing Spongeforge.
