### ISSUE TITLE
Nether Quartz Duplication

### ISSUE THREAD

**Issue by ckhawks** [AllTheMods/ATM-3#591]
There is a way to generate infinite amounts of Nether Quarts due to incorrect ratios.

## Expected Behavior

The Factorizer from Thermal Expansion should turn a Quartz block into 4 Nether quartz.

## Current Behavior

The Factorizer from Thermal Expansion should turn a Quartz block into 9 Nether quartz, allowing users to turn the extra quartz into more blocks to repeat the process.

## Possible Solution

Correct ratios in config, I would think?

## Steps to Reproduce

1. Create nether quartz block
2. Put Factorizer on Split mode
3. Put nether quartz block into Factorizer
4. You receive 9 quartz instead of 4

## Log

N/A

## Detailed Description

I feel there is no necessary information but let me know if you need anything else!

**Comment by kjmaster1** [comment]
When thermal expansion is updated in the next pack update this bug will be fixed - https://github.com/CoFH/Feedback/issues/1071

**Comment by Boomflex** [comment]
Fixed in newer version.

**Comment by SpeedSlider** [comment]
Confirmed
