### ISSUE TITLE
Thaumcraft 6 - Amber Block issue

### ISSUE THREAD

**Issue by Luxhide** [AllTheMods/ATM-3#593]
Crafting an amber block in a 3x3 crafting grid with TC amber gives a JAOPCA block instead of a TC one.
This is then unusable in TC recipes (namely: Arcane Lamp).

## Expected Behavior
9 TC amber should make a Thaumcraft "Amber Block" usable in crafting TC's recipes.

## Current Behavior
9 TC Amber makes a JAOPCA "Block of Amber" that is not usable in TC recipes.

## Possible Solution
n/a

## Steps to Reproduce
1. Craft 9 Thaumcraft Amber in a 3x3 grid
2. Result will be a JAOPCA "Block of Amber"

## Detailed Description
See above.

Correct as of v5.9.5

**Comment by Alaric323** [comment]
Can these be oredictionaried together so it can be used in Thaumcraft recipes?

**Comment by Yoosk** [comment]
was pretty sure its in ore dictionary

**Comment by kjmaster1** [comment]
#607 Fixes this issue

**Comment by Boomflex** [comment]
Fixed in new update.
