### ISSUE TITLE
Thaumcraft Thaumometer Extreme Lag when holding (Using 5.9.6)

### ISSUE THREAD

**Issue by KCtops100** [AllTheMods/ATM-3#598]
## Expected Behavior

Thaumcraft Thaumometer is working fine but shouldn't lag

## Current Behavior

Thaumcraft's Thaumometer gives extreme lag when holding

## Steps to Reproduce

1. Simply hold the Thaumcraft's thaumometer in hand.
2.
3.
4.

## Log

No crash

## Detailed Description

To somehow make the Thaumcraft's thaumometer not lag

**Comment by Boomflex** [comment]
Known Thaumcraft issue.

**Comment by KCtops100** [comment]
Thank you.
