### ISSUE TITLE
unknown error whilst trying to join atm3 server

### ISSUE THREAD

**Issue by oly2o6** [AllTheMods/ATM-3#6]
https://gyazo.com/299bd23cf8bf8d0e5452e190c23045f8 

there are no logs as not a crash and others are getting this, cant join the server, thank you in advance

**Comment by oly2o6** [comment]
Khrenan gave me his logs https://pastebin.com/bHD0FgHu

**Comment by OrdinatorStouff** [comment]
Almost guaranteed to be duplicate/related to: https://github.com/raoulvdberge/refinedstorage/issues/1345

**Comment by whatthedrunk** [comment]
This has been fixed in the newest update. Let me know if you see anything similar.
