### ISSUE TITLE
Responsive Scaffolding - Cyclic.

### ISSUE THREAD

**Issue by gefailter71** [AllTheMods/ATM-3#60]
Cyclic version: 1.12-1.6.0
Forge version: 2413

When placing the scaffolding in a 9x9 or 1x9 and u break one of the lowest/the lowest block the other disappear and only the block u actually mined drops.

**Comment by OrdinatorStouff** [comment]
Confirmed still exibiting buggy behavior. Can you please report to [cyclic issue tracker](https://github.com/PrinceOfAmber/Cyclic/issues)?

**Comment by Boomflex** [comment]
Mod bug, not pack related.
