### ISSUE TITLE
Steve's Carts with entity crashes game

### ISSUE THREAD

**Issue by TheSamFisher** [AllTheMods/ATM-3#600]
When putting an entity into the cage of the Steve's Carts mod, the game crashes

## Expected Behavior
The Mob should be trapped in the cage and not crash the game

## Current Behavior
The mob becomes trapped inside the cage then the game crashes and whenever you try to reconnect the game crashed as soon as its loaded.

## Possible Solution
¯\_(ツ)_/¯

## Steps to Reproduce
1. Create a cart from the steves cart mod (The one I used was reinforced hull, with an advanced tank, internal tank, cage and a solar engine).
2. Place a mob near the cage.
3.Activate the pickup 
4.Crash.

## Log
https://gist.github.com/TheSamFisher/675168e7727f94394472a98900ad1c06

## Detailed Description
¯\_(ツ)_/¯

**Comment by Boomflex** [comment]
Please report to Mod Dev Github.

Not a pack issue.

Thanks.
