### ISSUE TITLE
Draconic Armor can void baubles

### ISSUE THREAD

**Issue by martmists** [AllTheMods/ATM-3#601]
Taking critical damage while wearing Draconic Armor voids all items in the baubles slots.

Steps to reproduce:
- Get fully charged draconium armor
- Put a bauble in any bauble slot
- Take critical damage (easily reproduced by fighting a chaos guardian)
- Your baubles will now be void.

**Comment by Boomflex** [comment]
Please report to DE or Baubles devs.

Not something than can be fixed on a pack level.

**Comment by ogradyjd** [comment]
Not resurrecting this, but just for information:
https://github.com/brandon3055/Draconic-Evolution/issues/1111
