### ISSUE TITLE
Question:  Draconic Evolution Recipe Tweaks ... where are they?

### ISSUE THREAD

**Issue by scotty9090** [AllTheMods/ATM-3#603]
I'd like to roll-back a few of the modifications made to DE recipes (I think it's the pack making them since I don't see them in other packs) but for the life of me, other than the Wyvern Chestplate, I can't see where any of the DE recipes are being changed.  

I would expect these would be in packmode_balance.zs but I don't see them.  I searched through the other CraftTweaker scripts as well to no avail.  What am I missing?  Specifically I'm interested in the Wyvern Core recipe ... things are getting a bit grindy waiting for massive amounts of those to craft.

**Comment by FallenEagle1** [comment]
The wyvern core recipe is part of the draconic evolution config itself. there is a line that reads out as
 `    # When true everything is just a little harder. (Currently only effects recipes but that will probably change in the future)
    B:hardMode=true`
setting this to false will change some of the recipes that havent been modified by the atm devs

**Comment by scotty9090** [comment]
Thank you so much!  I didn't even think to check that.  I'll go ahead and close.
