### ISSUE TITLE
Can't activate ender shard with ender dragon

### ISSUE THREAD

**Issue by tomm2000** [AllTheMods/ATM-3#608]
I want to build a woot dragon farm but I cannot activate the ender shard when I got the dragon. It should work because on the woot manual there are infos about the ingredients to spawn a dragon. I play on a server with the latest atm3 version.

**Comment by Yoosk** [comment]
Did you smack dragon with shard, then killed it?

**Comment by tomm2000** [comment]
Yes

**Comment by Boomflex** [comment]
You have to HIT the Dragon with the shard first as this programmes it.

You then KILL the Dragon for it to register.

Just done it myself on 5.9.6b

https://i.imgur.com/q4DRzUS.png
