### ISSUE TITLE
Wrong draconium ore ID from Enviromental Tech Void Miner

### ISSUE THREAD

**Issue by rgbgamingcarpet** [AllTheMods/ATM-3#611]
## Current Behavior
Void Ore Miner generates draconium_ore (4332:32766), when it should generate either draconium_ore (4332:0), (4332:1) or (4332:2). The current ore that it drops results in an untextured pink block that when placed turns into regular overworld draconium ore.

![javaw_2018-06-02_02-57-40](https://user-images.githubusercontent.com/39846175/40869352-8bfc5b2e-6611-11e8-8dfb-68f6f6c4640b.png)

## Solution
Change item ID in config\environmentaltech\multiblocks\void_miner\ore\tier1,2,3,4,5,6_.json

##
It's not really an issue but it's really ugly lol

**Comment by FallenEagle1** [comment]
Known about and fixed in dev already.
