### ISSUE TITLE
Can't activate ender shard with ender dragon

### ISSUE THREAD

**Issue by tomm2000** [AllTheMods/ATM-3#612]
## Expected Behavior
Hitting the ender dragon with an ender shard should start the programming of the shard itself

## Current Behavior
I punch the dragon with the shard and nothing happens

## Possible Solution
Idk

## Steps to Reproduce
1.be on an atm3 sponge server
2.go to the end
3.punch the ender dragon with a woot ender shard
4.discover that nothing happens

## Detailed Description
I suggest to either fix this or add another way to farm elytra and hearts (it should work because in the woot book there are the items and fluids needed to spawn the dragon)

##other
Please tell me why u closed the last issue I sent on the same topic as this.

**Comment by martmists** [comment]
Does this also happen on non-sponge servers?

**Comment by Boomflex** [comment]
Sponge issue.

Works on non-sponge.

Sponge GREATLY affects Woot.
