### ISSUE TITLE
Ender IO Dimensional Transceiver is forgetting Networks.

### ISSUE THREAD

**Issue by ProStashio** [AllTheMods/ATM-3#615]
Ender IO Dimensional Transceiver is forgetting Networks.

Expected Behavior
Should not forget

Current Behavior
Forgets

Possible Solution
Steps to Reproduce
Set a channel & wait for it to forget

Log
Hard to say when it happens, its random.

**Comment by kjmaster1** [comment]
This issue has been reported on the Ender IO Github -https://github.com/SleepyTrousers/EnderIO/issues/4546 - not fixable on a pack level.

**Comment by OrdinatorStouff** [comment]
Hopefully fixed in next update, otherwise it's a known reported mod issue and can't be corrected at a pack level as kj mentioned.
