### ISSUE TITLE
Breaking Conduits also gives Charcoal

### ISSUE THREAD

**Issue by FallenEagle1** [AllTheMods/ATM-3#617]
## Issue
When using a tinkers pickaxe that has both autosmelt on it and luck, and you use it on a conduit from enderio, you will get the conduit in item form like expected, but also will get a piece of charcoal as well. Tested this with just the required mods themselves, and nothing, so it is something with the modpack.

Wondering if this has anything to do with the recipe a while back that said you could get charcoal from the stonework factory? Basically there was a recipe that you could get charcoal from nothing? 

## Steps to Reproduce
1. Grab a tinkers pickaxe with autosmelt on it (fiery pickaxe is one example)
2. Add lapis to it to get luck
3. Grab enderio conduits, any type and place down
4. Break with pick and get the item and charcoal back

**Comment by OrdinatorStouff** [comment]
Likely an issue of mod conflict or bugs. Will need to review in next pack update to see if still present and report to mod devs if so

**Comment by FallenEagle1** [comment]
That was the plan, just getting down on paper to start with. Was going to look into the scripts/mod interaction when I had time to test

**Comment by jimmysmith1** [comment]
Yea I just got this same issue. Also happens if you using a normal pickaxe with the "Smelting" enchantment. The EnderIO discord already know about the issue.

**Comment by Sakata-MC** [comment]
Mekanism glowstone block does same

**Comment by HenryLoenwind** [comment]
FYI: Root cause is that some mod registers a vanilla smelting recipe "ItemStack.EMPTY -> Charcoal"

**Comment by Yoosk** [comment]
So far narrowed it down for JAOPCA messing up
