### ISSUE TITLE
Please update FTBUtilities to 5.1.0.27

### ISSUE THREAD

**Issue by Possemaster** [AllTheMods/ATM-3#620]
As I pregenerated all dimensions my world folder size is 20+GB.
The current version in the pack of FTBU is 5.1.0.24 and has a bug that causes the server to freeze on performing a backup. A workaround was implemented in 5.1.0.26 and the issue was fixed in 5.1.0.27. So please update your pack with FTBU version 5.1.0.27 as we are having issues now that we do not have a safe backup method without causing server issues for 8 minutes during backups that run every hour.

Dependant mod is of course new version of FTBLib 5.1.0.22

Thanks

**Comment by OrdinatorStouff** [comment]
All mods are updated to their latest or otherwise most-appropriate versions every pack update. This will be addressed autoamtically as soon as the next pack update is released provided the FTBU mod has been corrected in it's latest version at the time of pack update.
