### ISSUE TITLE
mekanism/betweenlands crashing

### ISSUE THREAD

**Issue by Maditox** [AllTheMods/ATM-3#622]
## Expected Behavior

crafting lol

## Current Behavior

basicly i found when i was trying to craft a robit that when you place a personal chest on a weedwood crafting table it causes crashes, like no one can load that chunk anymore and the server had to be rolled back to a backup kinda crashing.

## Possible Solution

not sure if there is anything that can be done about it, just making you aware of it

## Steps to Reproduce

1. all you gotta do is place a personal chest on a weedwood crafting table and it should crashout, unless our game was just weird.
2.
3.
4.

## Log

https://gist.github.com/Maditox/2f5d1f7338be593dbe86a06dd8a5d403

**Comment by Yoosk** [comment]
Got exact same crash when tried that out, its not fixable on pack end, mekanism/betweenlands dev should take care of that. It would be great if you could make github issues there.
https://github.com/Angry-Pixel/The-Betweenlands/issues
https://github.com/aidancbrady/Mekanism/issues
