### ISSUE TITLE
Tech Reborn Ores being Generated

### ISSUE THREAD

**Issue by FallenEagle1** [AllTheMods/ATM-3#623]
Version: ATM3 5.9.7b

## Description

As the title states, in the world the tech reborn variants of the ores are being generated along with the thermal expansion versions. So back to two versions of silver ore, copper ore, etc being generated.

**Comment by Yoosk** [comment]
Will take a look and fix

**Comment by bogger33** [comment]
not just tech reborn, there's also immersive engineering ores spawning. lots of doubling up

**Comment by Yoosk** [comment]
checked some of those, most is fixed in https://github.com/AllTheMods/ATM-3/commit/d2061e660777d4a073d163ed5cb08f0036d15b40
