### ISSUE TITLE
Client crash when using Yeta to break machines

### ISSUE THREAD

**Issue by wesker1213** [AllTheMods/ATM-3#624]
## Expected Behavior

In theory, machines should come back to me unharmed, and unmolested when I break them.

## Current Behavior

Client crashes every time.

## Possible Solution

Not sure as to what causes it, but I read on another thread with same issue that it could be linked to ftb utilities claiming chunks, but not are claimed/loaded in my area in question.

## Steps to Reproduce

1. Place Machine
2. Hold Wrench in hand
3. Attempt to dismantle
4. Crash

## Log

https://pastebin.com/dNJKGgfi

## Detailed Description

Version 5.0.24

I hate have to rely on my axe all the time to avoid crashing. Not sure where the problem lies, but it is bothersome.

**Comment by Yoosk** [comment]
Looks like bug with ftbu, have you tried to update pack to latest version with 5.0.26 version of mod?

**Comment by Yoosk** [comment]
yeah, its working in 5.9.7b
