### ISSUE TITLE
Fresh computer, fresh server files, crash on startup. I edited nothing

### ISSUE THREAD

**Issue by TolgaKerem07** [AllTheMods/ATM-3#625]
## Expected Behavior

Just open the server

## Current Behavior

Crash

## Steps to Reproduce

1.
2.
3.
4.

## Log

https://gist.github.com/TolgaKerem07/5054121da3f210f3d59852a59b9eea02

## Detailed Description

Version v5.9.7b

**Comment by Yoosk** [comment]
Downloaded last server pack, launched it and works just fine. It has to be something on your end, you would have to provide latest.log for us to check more. And it looks like you don't launch with default arguments, i would suggest to begin with that.

**Comment by sonvar** [comment]
I get the same issue. I am reverting to previous version to see if the new version is broken.

**Comment by Yoosk** [comment]
I would like to know if those [serverfiles](https://dl.dropboxusercontent.com/s/8emzp04pbc1jzpe/allthemods3_v5.9.7b_serverstarter.zip) would do any better for you. There will be available soon on curseforge too.

**Comment by sonvar** [comment]
It seems after a fiddling with java versions and a computer restart, the game launches on version 5.9.7b just fine.

**Comment by TolgaKerem07** [comment]
ı am sorry ı cant find information about how to use server files
