### ISSUE TITLE
Environmental tech/Draconic ore Tile block

### ISSUE THREAD

**Issue by Goofyschooler** [AllTheMods/ATM-3#627]
Environmental tech Ore miner with light grey lens is giving Tile blocks from Draconic Ore. (see image)

## Expected Behavior
Should be giving a normal Draconic Ore

## Current Behavior
![image](https://user-images.githubusercontent.com/17286580/41502326-2c16a384-7153-11e8-9e01-408029e97579.png)

## Steps to Reproduce
https://www.youtube.com/embed/Np9wI1rRVuI" 

## Detailed Description
Haven't found a fix yet.

**Comment by FallenEagle1** [comment]
Fix is in the works from what I understand.

**Comment by Goofyschooler** [comment]
Oh okay, thank you @FallenEagle1

**Comment by Yoosk** [comment]
shouldve been already fixed https://github.com/AllTheMods/ATM-3/commit/cdecc9d94945bf4ac5c1df202939410a692bafac

**Comment by SpeedSlider** [comment]
With limited run time using light gray lens I got regular draconic ores, confirmed fixed.
