### ISSUE TITLE
[Suggestion] Growth Essence Tweak

### ISSUE THREAD

**Issue by JheregJAB** [AllTheMods/ATM-3#628]
I was chatting on discord with FallenEagle16 and later Ordinator as well.

JheregJAB - Today at 11:38 AM

> Does anyone know if there is a way to increase the speed of the actually additions empowerer?
> or is my only option going to be to build multiple and stick them in parallel?

FallenEagle16 - Today at 11:38 AM

> make more of them unfortunately

JheregJAB - Today at 11:39 AM

> damn
> That makes the manufacture of growth essence rather annoying.
> guess I'll be making a tower of empowerers to be able to get it with any decent speed.
> I found the exercise of getting to growth essence to be actually a lot of fun. Going partially through the tech trees of multiple mods and figuring out how to automate them all was something I enjoyed. A lot of work for someone who didn't know them all to begin with, but enjoyable. Kind of a let down for the final product to be so slow to produce after all that build-up work.

Ordinator - Today at 11:44 AM

> Hm, I agree that once you've unlocked a thing it should then afterwards be easier to make. I've been meaning to revise the custom items/recipes for a while now since there's so many new mods since when I first made them and that's something I can try to work in when I do

JheregJAB - Today at 11:45 AM

> I know I would appreciate it. I would suggest maybe making the recipe work with the draconic infusion crafting if possible. Then you could do actually additions for earlier, and if / when you get the resources for draconic you could do it that way. Maybe have the draconic version require more power but the actual crafting step be quicker.
> idk if its easy to modify draconic recipes or not though.

After this conversation I asked if it would be worthwhile to submit here, and Ordinator indicated that I should.

**Comment by Blueletric** [comment]
The only thing with having it switch over to say a draconic infusion recipe is that we cant make it cost more power from my understanding. The good thing about having it at the AA stage is you can start it somewhat earlier than draconic.

**Comment by JheregJAB** [comment]
I wouldn't actually suggest getting rid of the AA recipe, just add an additional one with draconic.

My thought was that with both options, you could make a few with the AA stuff earlier. Then when you get to draconic you could ramp up production to a faster rate without having to build multiples of the AA stuff.

My suggestion for having the draconic version use more power was as an additional balance mechanic. If its not possible to alter the power used, or for that matter the crafting time, then if any changes were to be made they'd make more sense to be in a direction other than draconic, probably. I had gravitated to draconic first just because the mechanic is already so similar.

In an ideal world, and given the above, I'd like to see the power requirement be very large, several ten million or hundred million rf in draconic, but the actual crafting speed be very quick, maybe just a second or two. So you'd need a good power infrastructure before it is more attractive than going the AA route.

and hey, I've never tried to balance a modpack or anything, so maybe that's unrealistic to begin with. ;)

**Comment by Iolause** [comment]
Please put Jurassicraft in the pack. I would love having a space zoo.

**Comment by martmists** [comment]
@lolause see #1

**Comment by Iolause** [comment]
@martmists Oh, I comment my suggestions there? Thanks

**Comment by Yoosk** [comment]
Issue is, you cant really set the speed of crafting in fusion table. Came up with that:
![image](https://i.imgur.com/CWjhfkL.png)
Takes from 10-16 seconds depending on how you apply power into injectors (mekanism cable does ignore input rate in machines, means you can pump whole 5m rf instantly if you have enough of cables)

**Comment by JheregJAB** [comment]
Idk exactly how much power it pulled, but the actually additions version of the recipe took about a full minute. 10-16 seconds seems like a pretty good improvement.

**Comment by martmists** [comment]
I would recommend setting the recipe for Draconic Infusers to include Growth Essence, otherwise it's too easy to do without setting up any actually additions machines at all.

**Comment by Yoosk** [comment]
![](https://i.imgur.com/Pt8Xgmp.png)
That will do i think.

**Comment by SpeedSlider** [comment]
Confirmed.
