### ISSUE TITLE
Watering Can Thermal Cultivation Dupe

### ISSUE THREAD

**Issue by Goofyschooler** [AllTheMods/ATM-3#629]
Literatly dupes the item.

## Expected Behavior
Should fill the can with water

## Current Behavior
Dupes the item

## Steps to Reproduce
https://youtu.be/uaQBgLSJFLA

**Comment by Yoosk** [comment]
According to what i found out, its mod issue, https://github.com/CoFH/Feedback/issues/1077, would be nice if you could open another issue on their github.
