### ISSUE TITLE
Mystical Aggriditions Insanium ingots recipe broken

### ISSUE THREAD

**Issue by oly2o6** [AllTheMods/ATM-3#63]
-AlltheMods 3 version 2.2 
-Mystical agradditions version 1.2.0 
the recipe for insanium ingots is completely broken, showing the recipe for supremium ingots instead, even though it will not make insanium as it (fortunatly) prioritises the Mystical agriculture ones, also reported on the mystical agraditions github.

**Comment by Boomflex** [comment]
![image](https://user-images.githubusercontent.com/22868795/28385938-d8089720-6cc1-11e7-942a-87d18a36b326.png)

Fixed in newer version.
