### ISSUE TITLE
hardened Signalum Glass is uncraftable with Fused Quartz

### ISSUE THREAD

**Issue by Goofyschooler** [AllTheMods/ATM-3#630]
Induction smelter won't accept Fused Quartz

## Expected Behavior
One Signalum and One Fused quarts in indcuction smelter crafts one Hardened signalum glass

## Current Behavior
Fused quartz won't go into the indcution smelter

## Possible Solution
Add a script to get rid of the recipe to deter confuision

## Steps to Reproduce
https://youtu.be/GcPV7P6ut48

**Comment by SpeedSlider** [comment]
I am still unable to use fused quartz to craft signalum hardened glass in the induction smelter.

**Comment by Aranak** [comment]
I am unable to put fused Quartz in the Induction smelter.
Version 1.57
