### ISSUE TITLE
Cyclic Powered Diamond Anvil internal buffer empty

### ISSUE THREAD

**Issue by iopredman** [AllTheMods/ATM-3#631]
## Expected Behavior
Powered Diamond Anvil internal GUI should show that power is stored. Energy should drain from the anvil normally when a repairable item is placed in the GUI.

## Current Behavior
Powered Diamond Anvil internal GUI shows that no energy is stored, but the HUD when observing the powered diamond anvil block shows that the anvil is RF full. This also seems to cause the items placed into the diamond anvil to repair more slowly than expected.

## Possible Solution
I can't tell from the behavior if this is a pack or mod related issue.

## Steps to Reproduce

1. Create Diamond Anvil
2. Place on redstone energy fluxduct powered by whatever
3. Drain the initial buffer down to 0
4. Place another item into the powered diamond anvil
5. Item will charge slowly and internal GUI should show no power in the anvil

**Comment by FallenEagle1** [comment]
The rf not showing is a cyclic bug, but it is just a visual glitch. Nothing as far as I'm aware has changed the speed of the processing, so I'm thinking it's the right speed and the visual glitch is just showing up

**Comment by Yoosk** [comment]
It would be great if you could make issue about it on https://github.com/PrinceOfAmber/Cyclic/issues
