### ISSUE TITLE
[5.9.7b]No recipe for graphite essence

### ISSUE THREAD

**Issue by galfalek** [AllTheMods/ATM-3#632]
## Expected Behavior

Be able to use graphite essence to craft graphite bar

## Current Behavior

No recipe

## Possible Solution

Add a recipe

## Steps to Reproduce

1. Open JEI
2. Search graphite essence

**Comment by Yoosk** [comment]
Its packmode change so you cant obtain it from seeds, however i'm not sure if someone just forgot to re-add that later on.

**Comment by Yoosk** [comment]
[](https://i.imgur.com/gSet7WL.png)

**Comment by SpeedSlider** [comment]
Confirmed fixed in 5.9.8a (in testing phase)
