### ISSUE TITLE
Game Crash when placing Colossal Chests core in ATM3

### ISSUE THREAD

**Issue by Pontiac76** [AllTheMods/ATM-3#633]
#### Issue type:

- :bug: Bug

Cross-Posted/Reported here as well: https://github.com/CyclopsMC/ColossalChests/issues/109
____

#### Short description:

Game crashes hard when placing at least the wooden core (Playing in survival).  Playing local in single player.

#### Steps to reproduce the problem:

1. Place down 7 of the 8 required block to make a 2x2 chest
2. Place down the core, watch the core not be placed, game proceeds to crash
3. Reload and wait another 5 minutes.
4. After starting up, see that the chest is invisible.

#### Expected behavior:

Chest forms, can access, client doesn't crash.

____

#### Versions:

- This mod: 1.12.2-1.6.11 and 1.12.2-1.6.10
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Log file:

https://pastebin.com/raw/w1ZzwZTp

#### Additional notes

As per the 109 issue, I did a LITTLE bit more digging.

- I went and created a new world with just CC and JEI and I did not crash when placing any chest cores.
- I cheated in a copper core, placed it solo, and the game crashed hard.
- Dupe bugs started to occur, but I don't remember how that happened at this time.  I'll see how I can reproduce and YouTube it, but, I do know its after a game load.  Not sure if this is worth anything as the game IMO is in a perilous state because of the crashes.
- On the invisible chest, breaking a chest wall, then placing it seems to form the chest and I can start using it as its designed.

My computer is not a slouch by any means.  Plenty of memory (32gig available, 6gig I think allocated to ATM -- Whatever is defined as default).  I've not added or removed any mods (yet).  This pack was installed several weeks ago so I don't remember the exact build.

**Comment by Pontiac76** [comment]
If I get the chance, I'll look into this tonight after work.  Thanks.

**Comment by Yoosk** [comment]
That's how it looks for me: [video](https://dl.dropboxusercontent.com/s/t813y919rtsneba/2018-06-20%2016-39-20.mp4)

**Comment by Pontiac76** [comment]
Video received.  I place the blocks down in the same order you did.  Going with what happened last night, I get the first 7 blocks down, but the 8th knocks my games teeth out when using ATM3.  When I get back into the game, the 2x2 chest is invisible.   WAILA shows me the appropriate blocks (Core & Wall) despite their being invisible.  If I remove one of the walls (Not the core) the other walls and the core reappear. When I place down the wall again, everything works as expected.  If I remove the core block, the chest breaks, as expected, but when I place the core down again, the game goes down hard.

I'll grab the newest release of ATM3 tonight, plus apply all the Java stuff as suggested.  I wasn't aware of all those changes you could make within the Twitch client.  I've not looked at it as I received this while at work, but will try and do in about 6 hours from now.

**Comment by Pontiac76** [comment]
Looks to have been the Java thing. I set Twitch to use the most recent version of Java, launched, and I'm able to place everything.  Thanks.
