### ISSUE TITLE
Early game machines (EnderIO)

### ISSUE THREAD

**Issue by madkingdiamond** [AllTheMods/ATM-3#635]
The early game Machines for EnderIO are bugged in your latest patch. I try to open the UI and it doesn't open. Instead it bugs my inventory and i have to relog. 

## Expected Behavior
UI opens to access the machines.

## Current Behavior
UI doesn't open. Works in previous patcehs of ATM3 but not the recent one.

## Possible Solution
No idea. 

## Steps to Reproduce

1. https://i.gyazo.com/thumb/1200/3937a93ca956289b6a3e98a5662fb2af-png.jpg <-- Picture of player UI after trying to access machines.
2. https://i.gyazo.com/thumb/1200/34db2ee3109e73b8197d94447a0c9df5-png.jpg<--- Picture of machines that dont open.
3. Everybody on the server has this issue
4.

## Detailed Description

Figure out what mod is conflicting with it to cause this? I have no idea.

**Comment by Yoosk** [comment]
According to my test, its working fine on our side, video made on official server:
https://dl.dropboxusercontent.com/s/bye3ql25i4ci1rv/2018-06-21%2021-38-13.mp4
We are on 5.9.7b, default packmode.
You sure you don't have any additional mods, or missing files?

**Comment by HenryLoenwind** [comment]
FYI: We're getting plenty of reports for this. ATM3 and other modpacks that recently updated.

**Comment by Blueletric** [comment]
@HenryLoenwind this is most likely a clientside glitch and nothing we can do pack side. Therefore just have them relog and it will fix the issue

**Comment by DatenThielt** [comment]
Please see the enderIO git,  It completely renders EnderIO Useless as the UI for all machines does not appear, it could be to do with Some Server side mods being disabled aka Refined Storage (we are testing), we are running tests with the Debug command arg to find out. also  it also appears if the users is in creative it actually duplicates on the server too.

**Comment by DatenThielt** [comment]
So This is kind of resolved, I'm not sure if it needs looking at here, or probbaly refined storage's git, But we re-enabled refined storage, and EnderIO started working great again!

Its odd that disabling a mod would prevent EnderIO's GUI from coming up though? Will let you decide what needs to happen here :) Thanks everyone

**Comment by HenryLoenwind** [comment]
as it was only disabled on the server and still running on the client, about anything could have happened...
