### ISSUE TITLE
Iron Rod from Immersive Engineering not craftable

### ISSUE THREAD

**Issue by Syer10** [AllTheMods/ATM-3#636]
Using the recipes for the iron rod give different items

## Expected Behavior
Iron rod comes out of the crafting table

## Current Behavior
1 recipe gives me 2 iron plates from AbyssalCraft 
The other gives a raw handel from Steve's Carts 2.

## Possible Solution
Add a recipe that does not conflict

## Steps to Reproduce
1. Get 3 iron
2. Place them in the crafting table in the way JEI tells you to.
3. It produces different items

## Detailed Description
The recipes do not work but I would like to be able to craft them. Adding a different way to craft them is my suggestion.

**Comment by SpeedSlider** [comment]
There are two crafting recipes for this item and the first one crafts a raw handle for steve's carts. This may still confuse some players.
