### ISSUE TITLE
Growth Essence Broken in Simplified Mode

### ISSUE THREAD

**Issue by TheLargeCactus** [AllTheMods/ATM-3#639]
## Expected Behavior

Growth Essence should be craftable in simplified mode in some way

## Current Behavior

Growth Essence not craftable in simplified mode in any way

## Possible Solution

ModTweaker script change to provide recipe for growth essence in simplified mode

## Steps to Reproduce

1. Change to simplified mode
2. Look for crafting recipe in JEI
3. None exists

## Detailed Description

A possible oversight or deletion of script recipe has made it such that crafting the growth essence item by any means in simplified mode is impossible, or at least unstated in JEI.

ATM3 version: v5.9.6b

**Comment by Yoosk** [comment]
Afaik that should not be craftable in simple mode, as it was created only for use to balanced mode.

**Comment by OrdinatorStouff** [comment]
Someone pointed out that growth essence is needed for wither spawning, even in simplified mode. Since we can't switch the woot config based on packmode, we should either add a recipe for it or do as I had already intended to do and remove the growth essence requirement from Wither woot farms. There are plenty of wither farming methods that can be automated that the need for a growth essence per wither is excessive and unnecessary.  
  
The dragons might need it as well, in which case we should review and make Woot configs packmode agnostic.

**Comment by StrommKral** [comment]
IMO, if your using Woot to spawn a wither, you doing way more work than you need too. there are far easier ways to farm a wither safely.  Using Woot for anything other than the Chaos Guardian is a total waste of resources and time.  IF you want/need guidance on any of these methods just ping me on ATM discord. IMO, making a change so extensive and intrusive is not worth the time. That time can be spent on other problems not so easily avoided.

**Comment by TheLargeCactus** [comment]
But the point of a pack containing 'All the Mods' isn't to play it necessarily the most optimal way. If the option can be given, let the player come up with how they want to play. Giving them that option should be the goal.

**Comment by OrdinatorStouff** [comment]
@StrommKral I'm not sure if you misread but I was saying that I want to remove the need for the growth essence from the wither woot, not add it. My reason being I agree that it should not be so complex.  
  
As for preference, one reason Woot can be preferable is the lack of lag from spawned-in entities and maybe a power-sink for people that have too much RF and don't know what to do with it.

**Comment by FallenEagle1** [comment]
Growth essence has been changed some, and should work now for simplified in 6.0.
