### ISSUE TITLE
accessing RFTools storage tablet crashes client

### ISSUE THREAD

**Issue by StrommKral** [AllTheMods/ATM-3#640]
whenever i try to access the items in my rftools storage tablet it crashes the client

## Expected Behavior

[crash-2018-06-24_21.11.18-client.txt](https://github.com/AllTheMods/ATM-3/files/2131391/crash-2018-06-24_21.11.18-client.txt)
[crash-2018-06-24_21.11.18-client.txt](https://github.com/AllTheMods/ATM-3/files/2131392/crash-2018-06-24_21.11.18-client.txt)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yoosk** [comment]
https://github.com/McJtyMods/RFTools/issues/1789 Seems to be fixed in next version.
