### ISSUE TITLE
[Chisels and Bits] Breaking a bit on some blocks causes them to act like water

### ISSUE THREAD

**Issue by Rikudouu** [AllTheMods/ATM-3#641]
I tested this one on a completely fresh download from the twitch client, and in singleplayer. This issue originally occurred on my spongeforge server, which also has a few extra mods, but I was able to reproduce the bug again on a fresh, unmodified, singleplayer install of ATM 3 v5.9.7b

## Expected Behavior

You chisel the solid block, and it breaks off a bit, or as many bits as you chiseled, and adjusts collision accordingly, like it does with most other blocks. 

## Current Behavior

Basically, if you take certain blocks (I don't know all of them, only a few, and I haven't noticed any pattern to them), and chisels them, they will act like water. You can go through them, and if you hold space, you'll start swimming to the top, as you would in water. You also see the splashes and the bubbles of the water when you enter the block.

So far, I've noticed this happen on white lamp (on), a red flat colored block, and murray pine wood planks.

## Steps to Reproduce

1. Have a c&b diamond chisel in your inventory
2. Place down a murray pine wood plank
3. Break a bit off
4. Walk through it

**Comment by Yoosk** [comment]
Not something we can fix on pack level, make an github issue on [chisel and bits](https://github.com/AlgorithmX2/Chisels-and-Bits) git.
