### ISSUE TITLE
Induction matrix

### ISSUE THREAD

**Issue by MythixDino** [AllTheMods/ATM-3#642]
This can be made with any lithium dust, which breaks balance. What about making it so you can only use the lithium from mekanism (so you have to build a solar tower - etc).

**Comment by Sleeeper** [comment]
Or just make draconic orb. I would keep it as is, not much people doing the matrix anyway, and the change will just make it useless. Tried to make it once, takes  a lot of gold to craft ultimate cells.

**Comment by MythixDino** [comment]
The point is a draconic orb requires awakened draconium which is way more expensive.

**Comment by DKnightADRI** [comment]
@Sleeeper if you have something useful to say then say it. Do not add opinion based mess here that doesn't add anything to the suggestion.

Now how I think of it: Mekanism is mekanism. Meaning that making the components of an induction matrix should require something more than just a digital miner (that's all you need right now really). The lithium is (not right now - now it's the easiest part) the only hard part of making the thing.

**Comment by OrdinatorStouff** [comment]
A core value of All The Mods flagship packs are to showcase the interoperability of all the mods. The ability to use Nuclearcraft lithium ore or even IC2 lithium dust is not a bug, it's a **feature**. 
  
One ultimate induction cell costs

4 stacks of lithium dust
34 stacks of redstone dust
9+ stacks of iron ingots
22+ stacks of gold ingots


That's not considering

1 stack osmium
4 stacks steel 
4 stacks glass
16 reinforced alloy
4 atomic alloy

just for the energy cubes.  
  
The hard part about mek Lithium is just time. It's a slow grind that the only way around is by spamming dozens of 200-ticking-block multiblock towers.  
  
For one ultimate cell you'd need to mine a minimum of ~1400+ ores and even that number is assuming 5x ore processing which is not really "nothing more than a digital miner" but even that that's 25 minutes of constant mining by a fully-upgraded digiminer but you're not going to find all 1400 ores you need in one 32-block radius but several, rather which makes teardown and re-setup quite time consuming as well. Shooting from the hip I think it'd take the most determined farmer at least a couple hours of micro-managing a digiminer or two, even.

**Comment by OrdinatorStouff** [comment]
@Sleeeper thank you for adding your opinion/input. Additional viewpoints are always welcome.
