### ISSUE TITLE
Graphite Essence @Mystical Agriculture

### ISSUE THREAD

**Issue by Dovahaak** [AllTheMods/ATM-3#645]
Graphite Essence has no further recipe making is useless.

## Expected Behavior
Graphite Essence should be craftable into Graphite Bars/Dust of Extreme Reactors.

## Current Behavior
they lay in my inventory

## Possible Solution
Add a Recipe with 8 Graphite Essences with nothing in the middle.
Output should be between 2 and 4 Bars.

## Steps to Reproduce

1. Rightclick Graphite Essence of Mystical Agriculture
2. See that there is nothing

**Comment by FallenEagle1** [comment]
Update to 5.9.8a. This is already fixed, as this was brought up in issue #632 and a recipe was added.
