### ISSUE TITLE
Crash with immersive engineering handbook

### ISSUE THREAD

**Issue by xxnovosxx** [AllTheMods/ATM-3#646]
Version All the Mods 3 5.9.8a
## Expected Behavior
When i open the handbook and go to power, wires, generators and then to power Generation it sould open the page

## Current Behavior
when i open teh immersive engineering handbook an go to power, wires, generators then power Generation the game will freez and then after some time crash 

## Steps to Reproduce
1.Open immersive engineering Handbook go to power, wires, generators then to
power Generation and it will crash

## Log
https://gist.github.com/xxnovosxx/71cae96b64f7d27645916d9524f9b9d5

Sry for my bad englisch....

**Comment by ghatus0** [comment]
If you are using the Twitch launcher you will have to make sure your java is up to date and go to twitch>file>settings>minecraft> and under launch method select jar launcher. This should fix your crash.

**Comment by xxnovosxx** [comment]
it also happens when i cheat the projector for the immersive tech steam engine

**Comment by Yoosk** [comment]
That's fixed in lastest pack versions.
