### ISSUE TITLE
OutOfMemory exception/freezing while loading modpack

### ISSUE THREAD

**Issue by HeroOfFire45** [AllTheMods/ATM-3#648]
## Expected Behavior

Mod pack should load correctly

## Current Behavior

Game crashes due to outOfMemory exception or freezes, the latter being more common (it froze for me 3 times while only crashing once)

## Possible Solution

Figure out a way to reduce mod-pack's memory usage

## Steps to Reproduce

Doesn't take much to reproduce since it occurs during startup

## Log

https://gist.github.com/HeroOfFire45/afe26805f549bf472844643077b5e4b5
Doesn't produce a crash log when it freezes

## Detailed Description

Critical fix of memory issue that is preventing modpack from being playable, as it occurs during startup and mod loading.

**Comment by Yoosk** [comment]
One question, did you read changelog of latest version and set RAM allocation to proper amount as stated there? Because allocating 3GB or RAM you you did, is far from enough to launch this pack.

**Comment by HeroOfFire45** [comment]
Never could figure out how to allocate more memory.

**Comment by hammurabi1337** [comment]
It depends on your launcher, but generally there's an option built in for that. If not it can be defined by the parameter -Xmx8192m where the number the amount of RAM allocated in MB. I have 8192 MB (or 8.192GB) allocated and the pack loads fine for me.
