### ISSUE TITLE
Can't craft bookshelf with planks other than oak

### ISSUE THREAD

**Issue by beanaboston** [AllTheMods/ATM-3#649]
## Expected Behavior

Craft bookshelves with any type of planks.

## Current Behavior

Can't craft unless using oak planks. Even with all the same planks.
Crafting recipes shows that it can be crafted with any planks, (from quark). There is another recipe with just oak planks.

## Steps to Reproduce

1. Attempt to craft bookshelf with birch planks and books
2. Doesn't work??
3. Craft with oak planks instead
4.

## Log

I don't think a log is relevant to this but I can definitely provide one.

**Comment by FallenEagle1** [comment]
What pack version?

**Comment by beanaboston** [comment]
5.9.8c
Should have put in the main post. I'm a bit tired right now so I forget.

**Comment by FallenEagle1** [comment]
No worries, just need to know to look into it.

**Comment by Yoosk** [comment]
Fixed in dev [!image](https://i.imgur.com/xaeq9Ji.png)
https://github.com/AllTheMods/ATM-3/commit/aa96c7cf1452777f20af4a2ffd86a932c45d010f
