### ISSUE TITLE
silicon essence dosent make silicon

### ISSUE THREAD

**Issue by oly2o6** [AllTheMods/ATM-3#65]
AlltheMods3 version 2.2
Silicon essence does not have any usages and cant make silicon, seems to not be a big issue but a weird one as it knows how to craft the seeds with the silicon but not craft the essence from it

**Comment by Boomflex** [comment]
![image](https://user-images.githubusercontent.com/22868795/28385650-cf00bed8-6cc0-11e7-99bc-59a83015db0d.png)

Can you state which Myst Agri version when making a report please.

This helps us narrow it down.

**Comment by Boomflex** [comment]
Fixed.

**Comment by oly2o6** [comment]
sorry i forgot. jsut wanted you to know it was a thing in the current pack version
