### ISSUE TITLE
I can't start ATM 3 server,it gives an error named IllegalArgumentException and ExceptionInInitializerError

### ISSUE THREAD

**Issue by Friqhers** [AllTheMods/ATM-3#650]
## Expected Behavior

It should start without any errors

## Current Behavior

It gives java.lang.ExceptionInInitializerError and java.lang.IllegalArgumentException.

## Possible Solution

I think it caused by the toLowerCase function but I'm not sure.

## Steps to Reproduce

1.
2.
3.
4.

## Log

server crash report:
https://gist.github.com/Friqhers/4a875a78621e17ddeca29a57a106e30b
latest log:
https://gist.github.com/Friqhers/74130d82abd6cb1bbfbd56f7bb3d6761

## Detailed Description

Actually I can't start an forged server of any modpack it gives the same error.I tried to chang my windows language to english from turkish but I couldn't because my windows version is single language.

**Comment by Yoosk** [comment]
I would suggest to update server to latest version and allocate more than ~3596mb of ram. Default 5GB should be enough.

**Comment by Friqhers** [comment]
I tried with the latest version and again the same errors but from different mods
crash report: 
https://gist.github.com/Friqhers/69949c13afe4fd52b33adec009aa16a0
latest log:
https://gist.github.com/Friqhers/999eab2fda4b0a04171abc8dbdf7813b

**Comment by Yoosk** [comment]
That is not the latest version as that one does not have AE alpha. You are using our serverpacks?

**Comment by Friqhers** [comment]
I downloaded from this link: https://minecraft.curseforge.com/projects/all-the-mods-3/files/2577935

**Comment by Yoosk** [comment]
Theres one new: [5.9.8c](https://minecraft.curseforge.com/projects/all-the-mods-3/files/2578419).

**Comment by Friqhers** [comment]
Again same errors.
crash report:
https://gist.github.com/Friqhers/8d0f2921c72ac334a2a3247b13fe986f
latest log:
https://gist.github.com/Friqhers/06201870682e2120b94336ff6a792022
