### ISSUE TITLE
ATM3 crashing upon startup

### ISSUE THREAD

**Issue by sonvar** [AllTheMods/ATM-3#651]
Version 5.9.8c

## Expected Behavior
game start up.

## Current Behavior
 Game crashes upon completion of loading.

## Possible Solution
 unkown

## Steps to Reproduce

1. start game
2.
3.
4.

## Log

https://github.com/sonvar/crash-report/blob/master/crash%207-4-18

## Detailed Description
 I do not know how to read crash files. I hope this is helpful to someone.

**Comment by Yoosk** [comment]
I would suggest to try clean, fresh instance without any additional mods.
