### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by AlexJurju8** [AllTheMods/ATM-3#652]
Every time i try to run the pack it crashes.

## Expected Behavior
The game should start

## Current Behavior
When i try to run the pack it crashes.I think it crashes when minecraft tries to initialize the mods but im not sure.I am using java 171 64bit

## Steps to Reproduce

1.Press play
2.
3.
4.

## Log
https://gist.github.com/AlexJurju8/db967b1e74b3adc1936f10eee1d6842a

**Comment by FallenEagle1** [comment]
Not enough memory is allocated to minecraft. If you are using twitch, you need to go into settings there and change the amount of ram minecraft uses. At least 5.5 GB minimum is recommended. That might not completely fix it, but at least change that so minecraft isn't running out of memory.
