### ISSUE TITLE
Agricraft

### ISSUE THREAD

**Issue by zelflame33** [AllTheMods/ATM-3#653]
Hello, can you add agricraft to the modpack ?
https://minecraft.curseforge.com/projects/agricraft

**Comment by FallenEagle1** [comment]
For suggestions, there is an issue open for putting suggestions on. It's #1 (same as the hats suggestion)

**Comment by zelflame33** [comment]
I write this to the wrong place. Sorry

**Comment by zelflame33** [comment]
I write this to the wrong place. Sorry
