### ISSUE TITLE
RAM usage slowly increasing over time, resulting in regular client freezes.

### ISSUE THREAD

**Issue by Apocryphai** [AllTheMods/ATM-3#656]
## Expected Behavior
RAM usage should remain stable.

## Current Behavior
After playing for ~1 hour the RAM usage (as shown in-game) starts going up from 70% to 95-100% at which point the client completely freezes for a short while. This starts as 1-2 seconds but if I persist in playing then it starts to freeze for over 10 seconds at a time. The server is fine and game time continues whilst the client is frozen.

I am launching ATM3 via MultiMC, with min. memory allocation 512 MB, max. 8 Gb, on a 16 GB system. Several other people have described similar problems here: https://www.reddit.com/r/allthemods/comments/8v9y28/ram_usage_is_about_70_goes_to_100_slowly_and_game/ 

I am using no JVM arguments. I have tried with and without UseG1GC and it makes no difference.

## Possible Solution
I'm just guessing here, but it feels like one or more mods has a memory leak.

## Steps to Reproduce

1. For me, simply playing ATM3 for an hour or more.

**Comment by MiunaOshino** [comment]
This seems to happen on chunk loading. I'm usually fine until I explore / load new chunks ("new" as in not in memory, it doesn't matter if they are pregenerated by the server or not).

Relogging seems to fix it, but it's still pretty annoying.

**Comment by Apocryphai** [comment]
Yup, I just tested it by logging onto my server and staying just in my base, an area that covers about 5x5 chunks. Started happening after about 15 mins.

**Comment by Yoosk** [comment]
Temporarily i would suggest to manually update [ctm](https://www.curseforge.com/minecraft/mc-mods/ctm) if you are playing in singleplayer and check if that helps.
