### ISSUE TITLE
The plant sower doesnt take the seed from the mystical agriculture

### ISSUE THREAD

**Issue by monsterminer34** [AllTheMods/ATM-3#658]
The plant sower doesnt take the seed from the mystical agriculture

I connected the plant sower to the plant gatherer with the transfer pipe from the extra utilities 2, to make the seed  from the mystical agricolture (inferium seed) go in the sower,but the sower wont take the seed.

**Comment by Blueletric** [comment]
Not a pack problem, report to mods github please :)

**Comment by FallenEagle1** [comment]
It is working for me (just tested). Make sure that you don't have the inventory locked
