### ISSUE TITLE
Growth Essence Simplified Draconic EVo Injectors

### ISSUE THREAD

**Issue by carcher7878** [AllTheMods/ATM-3#659]
"Simplified version - to make growth essence, you need to make a Draconic  Tier Wyvern. But to make a Draconic Tier Wyvern, you need Growth Essence. Cant make one without the other. Looked in Simplified script, says to use Actually additions. 

## Expected Behavior

Should be able to make the Growth Essnece

## Current Behavior

Can not make it

## Possible Solution

Change growth essence to a Tier 1 or delete the recipe in BrandonCore config

## Steps to Reproduce

1.Just look in JEI - ensure you're in Simplified mode
2.
3.
4.

## Log

no crash

## Detailed Description

ATM3 V. 5.9.8b  (server)

**Comment by Yoosk** [comment]
https://github.com/AllTheMods/ATM-3/issues/639
