### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by Garlaen** [AllTheMods/ATM-3#66]
whenever i try to join the server (even though it works sometimes), i get a fatal error, and the connection terminates. I'll post the crashlog to pastebin and link it here in a subsequent post. any help is appreciated!
thanks in advance

**Comment by Garlaen** [comment]
https://pastebin.com/wr41Yvr1

**Comment by jeffwcollins** [comment]
Before working through any troubleshooting, update your java.  You have 1.8.0_25, and current release is 1.8.0_141, so suffice it to say, you are a tad behind.

**Comment by Garlaen** [comment]
didn't fix it, but i did update java

twitch was using a native java to run MC, and not the newer version i had installed.

**Comment by TheElectricCake** [comment]
Garlaen, I've had a similar problem (I just opened a ticket now that it seems to be happening to someone other than me!) but with slightly different effects (I think). I can fix my problem so that I can log back in by reinstalling ATM3 from scratch, but then I lose all of my save data including my journeymap bookmarks. :6 Have a look at https://github.com/AllTheMods/ATM-3/issues/67 and see if it looks similar?

**Comment by TheElectricCake** [comment]
I'm still having this problem.

**Comment by whatthedrunk** [comment]
Still having this problem after the new updates?

**Comment by HallowWolf93** [comment]
i have recently updated the modpack to the latest version as of this message and me and a few of my mates are also getting the "a fatal error, and the connection terminates." we started to get errors when using /home or /back so im starting to think that its FTB Utils causing the issue.

**Comment by OrdinatorStouff** [comment]
logs reference ic2 and reborncore a few times around the point of disconnecting. This is very hard to pinpoint however since it's nearly impossible to reproduce consistently.

are these disconnects/cant-connect still happening in pack version 3.1+?

**Comment by OrdinatorStouff** [comment]
related to #75 as well

**Comment by Boomflex** [comment]
Legacy error - no longer relevant.
