### ISSUE TITLE
Some items missing Thaumcraft aspects

### ISSUE THREAD

**Issue by Naphrym** [AllTheMods/ATM-3#665]
## Expected Behavior

Items such as coal should have aspects like Ignis and Potentia like previous versions. There are many more items that should have aspects according to standalone Thaumcraft 6, but don't in this pack.

## Current Behavior

The aspects simply don't exist on the items.

## Possible Solution

I've done a very small amount of research and it seems like mods that play with NBT tags for items might be the cause of the issue. I no nothing about making mods, though, so I'm not sure how reliable that info is.

## Steps to Reproduce

1. Obtain coal/snowballs
2. Hold Shift
3. ???
4. ...No profit

**Comment by Blueletric** [comment]
Mod issue, report to Thaumcraft github tracker please :D

**Comment by Naphrym** [comment]
![thaumcraft 6 standalone](https://user-images.githubusercontent.com/32911024/42728204-0250e000-8783-11e8-8033-5844530e04de.png)
![thaumcraft 6 atm3](https://user-images.githubusercontent.com/32911024/42728205-090b5218-8783-11e8-82b5-d5251227cb32.png)
First image is standalone Thaumcraft 6 Beta16. Second image is from ATM3 with Nutrition removed
