### ISSUE TITLE
white cubes (in a grid) all over my base.

### ISSUE THREAD

**Issue by markarig** [AllTheMods/ATM-3#666]
On our current version server v5.9.8d there is a grid of small white cubes covering our entire base whenever we look in specific directions.  It's only around the base, I don't know if we activated one of the mods or not.  Hopefully I'm including screen shots properly.  

![2018-07-14_18 47 12](https://user-images.githubusercontent.com/37724693/42729138-4b754b18-879c-11e8-952a-899bb898d7a2.png)
![2018-07-14_18 47 15](https://user-images.githubusercontent.com/37724693/42729139-4b80a152-879c-11e8-87cd-cbb351793fd1.png)

One screenshot shows the cube, and the second one shows if you look a little to the left where they are all gone. 

## Expected Behavior

There should not be cubes.  

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ogradyjd** [comment]
Your base is haunted because this issue is number 666

**Comment by Yoosk** [comment]
Looks like some kind of overlay but i have no idea how did you enable it. Any clues what is that from?

**Comment by FallenEagle1** [comment]
It almost reminds me of the building guide, but that one does full blocks. What I would do is have a couple people look from different locations and see what direction you have to look so you could potentially find what is causing it. Then you can get closer to it using the directions you found, and you might be able to find out what it is.

**Comment by zombiemad11** [comment]
its the digital miners visual toggle that causes it. or if not that then probably something else from mekanism.

**Comment by FallenEagle1** [comment]
Did some digging, the squares look exactly like the digital miners visual toggle. To remove them, find the outline of the box in the x and z direction, then go to the middle of that then look along that y axis. Max radius of the machine is 32 and is centered on it. Once you find it, can open it up and the visual toggle button is on the upper left hand side of the gui.
