### ISSUE TITLE
Digital Miner (Mekanism) vanishing or not breakable.

### ISSUE THREAD

**Issue by markarig** [AllTheMods/ATM-3#667]
Our server is currently running v5.9.8d
I'm on our 5th Digital Miner, because it has vanished 3 times.  (One of them went with me when I fell out of the world in unicorn cloud land and was lost.)  We know were we put it, and when we go back the miner is not there.  

Now, I went to break our miner and it refuses to break.  (screenshot included) It still works properly,
![2018-07-14_19 46 36](https://user-images.githubusercontent.com/37724693/42729269-2be82bcc-87a0-11e8-8e14-0efaa4dfa3c4.png)

## Expected Behavior

When I hit it with a pick, it should break so I can pick it up.

## Current Behavior

It just makes a sound of "breaking many blocks" but won't break.  We have tried restarting the server.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yoosk** [comment]
Usually relogging helps in my case, but that is mod issue and not something we can fix one our side, post it on mekanism github.
