### ISSUE TITLE
Crash/Freeze when opening inventory

### ISSUE THREAD

**Issue by PiggyWhiskey** [AllTheMods/ATM-3#668]
https://paste.ee/p/1AyyZ

Brand new  v5.9.8d world using "Great Wall" Type.

It didn't generate properly, so I created a mini bedrock platform and spawned a Mining Dimension portal and some basic gear to start (Refined Storage Controller/Disk Drive/Crafting Grid/64k disk, Basic solar panel) which is sitting in my inventory.

It looks like it's trying to crash, but freezes while trying to save the world.

Crash starts at line 12300 of the log

Edit: Attempted to create a new world.
1. Changed to Creative
2. Teleport to 0,0,0
3. Create Bedrock platform at y=60
4. Attempted to filter JEI "@X" (Was trying for "@Xnet")
5. Freeze/Crash

**Comment by PiggyWhiskey** [comment]
https://github.com/McJtyMods/XNet/issues/285

**Comment by PiggyWhiskey** [comment]
Should I be expecting an update soon, or should I manually update XNet?

**Comment by Blueletric** [comment]
XNet will update when v6 comes out, until then manually update
