### ISSUE TITLE
Since update to latest release Celestial Gateway stopped working.  

### ISSUE THREAD

**Issue by markarig** [AllTheMods/ATM-3#670]
I have 3 celestial gateways set up, and since the update to v5.9.8d they are no longer full of stars.  Or at least the right stars.  The golden stars for teleporting are gone.  I've picked them up and put them back down and broken the base and rebuilt it, but still see no golden stars from any of the 3 I have set up.

## Expected Behavior

I should see 2 golden stars for my other two locations and when I right click at them I should see some particle affects and be teleported to another gateway.

## Current Behavior

There are no golden stars, during the night or day.  So I cannot teleport.

## Steps to Reproduce

1.  Build new pad
2.  build celestial gateway
3.  stand on gateway
4.  see no golden stars.

**Comment by kifujin** [comment]
The version of Astral Sorcery after the version in the current modpack release fixes this.
