### ISSUE TITLE
Refined Storage Destructor + EnderIO item conduit crashes server

### ISSUE THREAD

**Issue by iopredman** [AllTheMods/ATM-3#671]
## Expected Behavior

Placing a refined storage destructor connected to a network, facing an EnderIO item conduit currently crashes the server, and in addition, makes the server unloadable, forcing a backup to be loaded.

## Current Behavior

This action should preferably not cause the crash

## Steps to Reproduce

1. Start new world
2. Place item conduit from Ender IO
3. Place storage controller, disk drive, and disk in disk drive
4. Place destructor attached to controller facing the item conduit
5. Java should crash about 2 seconds later

## Log

https://gist.github.com/iopredman/a27f37049380edbb49e8d7c2286eba9c

**Comment by iopredman** [comment]
I recognize that this is a fairly benign issue as far as likelihood of happening, but the fact that anyone on a public server can do this to corrupt worlds is an issue.

**Comment by Yoosk** [comment]
Again, mod issue and not something we can fix on our side. Make an issue on enderio github.
