### ISSUE TITLE
Dupe bug when placing ExtraCells stuff with Cyclic's sack of holding

### ISSUE THREAD

**Issue by Sleeeper** [AllTheMods/ATM-3#672]
## Expected Behavior

Sack should be emptied when placing it's content.

## Current Behavior

Sack stays filled when placing back Extracells stuff, so you can dupe it infinitely (extracell drives, buses etc.)

## Possible Solution

Add Extracells stuff to sack's blacklist at S:SackHoldingBlacklist in cyclicmagic.cfg

## Steps to Reproduce

1. place stuff from extracells (obsidian drive, fluid pattern thing etc.)
2. take it with sack of holding
3. place back
4. place more...

https://github.com/ExtraCells/ExtraCells2/issues/577
https://github.com/PrinceOfAmber/Cyclic/issues/877

**Comment by Sleeeper** [comment]
I'm using this Sack of Holding a lot and with other mods it works as intended.

**Comment by Yoosk** [comment]
It's working fine for me in my dev versions, maybe its already fixed.

**Comment by Yoosk** [comment]
Found its not all blocks, narrowed down to 3. Will add them to blacklist and hope that one of mod devs will fix rest
