### ISSUE TITLE
Thaumcraft warp without any Thaumcraft?

### ISSUE THREAD

**Issue by ogradyjd** [AllTheMods/ATM-3#673]
This is weird.  I've been through a lot of the mods so far in my world, but I have not touched Thaumcraft at all.  I don't think I've even opened the book.  I've never even tried the mod - not just in this modpack, but ever.   And then one day the mind spiders attacked while the world when fuzzy and Eldritch Guardians swarmed me and my hunger bar died.

## Expected Behavior
I should still be wondering what Thaumcraft does.

## Current Behavior
I somehow have major warp effects

## Possible Solution
No idea.  To remove the warp, I had to run the cheaty commands
```
/tc warp <player> set 0 TEMP
/tc warp <player> set 0 
/tc warp <player> set 0 PERM
```

## Steps to Reproduce
Just played the game.  If you want my world to take a look-see, let me know.

## Log
There was no crash. Just in-game warp effects.

**Comment by OrdinatorStouff** [comment]
Was this in Single-player or a server? 

I know some things can cause warp without even really expecting it to, like eating zombie brains for food is one example that comes to mind.

**Comment by martmists** [comment]
Happened to me on SMP too, got attacked by a demon sheep and suddenly got warp.

**Comment by ogradyjd** [comment]
Sorry, I should have added that information.  This is a single player world.

**Comment by ogradyjd** [comment]
So after some research, I'm thinking there's some kind of integration with Thaumcraft and Abyssalcraft where being in the Abyssalcraft dimensions can give you Thaumcraft warp.  I have tentatively confirmed this when collecting essence in the first Abyssal dimension, I get a message saying I've gained temporary warp.  If anyone can confirm this (because documentation on these mods sucks and I've only found passing references to this), you can close this issue.

**Comment by martmists** [comment]
It seems [Abyssalcraft-Integration](https://github.com/Shinoow/AbyssalCraft-Integration/commit/27328f4b5d1905bfcfc3a152f9e1fbc34aa9a88c) causes this.

**Comment by martmists** [comment]
@ogradyjd It seems this can be disabled in the Abyssalcraft-Integration config.
