### ISSUE TITLE
Mob Totems is a total cheat when fighting the Gaia Guardian

### ISSUE THREAD

**Issue by ogradyjd** [AllTheMods/ATM-3#675]
Yet another thing I don't know that you can do anything about.  Back in the day we had Magnum Torches that prevented mob spawning in a 64x64 area, but they didn't interfere with cursed land, spawners, soul vials, etc.   The mob totems (in a creeper, ocelot, ocelot totem) seem to interfere with everything.  I couldn't place a mob in a soul vial, and ever ~better~ worse, the Gaia Guardian can't spawn mobs at halftime.

Now, while I am going to take shameless and heinous advantage of this while it lasts, it does feel pretty cheaty and is probably not what you want in a challenging pack like this.  Pic is included below.

(Two Battles Later)
One really funny side-effect of this is that it seems the Mob Totems gets confused when the mob that's spawning is a baby zombie riding a chicken due to the chicken not being a hostile mob, so it will spawn the chicken with an invisible baby zombie on it.  When you kill the chicken, the zombie de-spawns.  I'm going to assume that this won't happen with spider-riding skeletons because those are both hostile mobs.

## Expected Behavior
Gaia Guardian (I and II) spawn mobs when they get to that point in the fight.

## Current Behavior
Blissful silence and time to reload.  Specifically, the Gaia Guardian floats up, hangs for a while like Jordan, then continues the fight.

## Possible Solution
No idea.  I'm not a mod-pack developer.  Perhaps the Mob Totems config?

## Steps to Reproduce
Put a mob totem (creeper flavor) next to your Botania Guardian fighting area, fire up the totem and start the fight.

![2018-07-19_12 31 05](https://user-images.githubusercontent.com/4014049/42957378-7ea95922-8b50-11e8-9818-ded933812ac9.png)

**Comment by Sleeeper** [comment]
Without Mob Totems, you can put some mob crushers under the arena or other mob killing area stuff, and have same fight without mobs interrupting you.
