### ISSUE TITLE
Game crashes when I try to load the mods

### ISSUE THREAD

**Issue by BraidedVeins** [AllTheMods/ATM-3#676]
I had just opened minecraft, loading up the modpack for the first time. It was able to load phase 1 but had crashed during the beginning of phase 2. It was just starting to load the mods into the game using forge. If my problem is not loading them through them through the twitch app, i tried to add my minecraft application but it kept saying there it was not a valid directory. 

https://gist.github.com/BraidedVeins/0000049663db206a5e6f7181beeb1846#file-crash-report

**Comment by Yoosk** [comment]
Your main issue is allocating only 1GB of ram, allocate at least 6gb and try again.

**Comment by BraidedVeins** [comment]
I allocated 9G of ram but it still crashed. 
https://gist.github.com/BraidedVeins/7847ec51d051373a7e2d7f0820d00d20#file-crash-report-2

**Comment by Yoosk** [comment]
How much RAM you have total and what launcher are you using?
