### ISSUE TITLE
Ender IO Farming Station disappearing Capacitor and Hoe

### ISSUE THREAD

**Issue by Minethulhu** [AllTheMods/ATM-3#677]
Ender IO Farming Station disappearing Capacitor and Hoe

## Expected Behavior
Ender IO Farming Station should not have installed Capacitor nor nearly fresh Hoe disappear.

## Current Behavior
When certain plants are MANUALLY planted within a plot that is being managed by an Ender IO Farming Station, on next cycle through the managed plots (and presumably when hitting the non-standard plant), both the current Capacitor and the current Hoe disappear from the Farming Station.

The only plant I have seen this issue with is Chamomile from Rustic, but assume there are others since I've only otherwise used standard Minecraft plants or those from Mystic Agriculture...

NOTE: I also have 1 worm per 3x3 plot of farm land from Actually Additions (except the center 3x3 section) keeping the land in question "hydrated".  Unsure if this is a contributing factor (nor if there is much benefit combining the two mods).

NOTE: It is worth mentioning that if the Chamomile "seed" in question is put into the Farming Station for it to manage, it simply never plants it and thus no issue is seen.  The Chamomile "seed" actually looks like little flowers, but otherwise seems to behave like a seed.

## Possible Solution
It would likely be sufficient to have the Farming Station simply ignore this plant.  It doesn't appear in my limited interaction with Chamomile that you can harvest it other than taking the entire plant.

## Steps to Reproduce
1. Setup an Ender IO Farming station on top of a flat area of dirt.
2. Provide a capacitor and a hoe to the Farming Station.
3. Provide power to the Farming Station (in my case using a Dimensional Transceiver)
4. Manually plant Chamomile "seed" from Rustic (Alchemy) onto section of dirt that is managed by the Farming Station

**Comment by Yoosk** [comment]
Thats a mod issue and should go to ender io github.
