### ISSUE TITLE
Server Crash after 100+ hours?

### ISSUE THREAD

**Issue by UniQcorN** [AllTheMods/ATM-3#679]
## Expected Behavior

 I wanted to reset Mining dimension, and therefor I closed down the server - I then moved the DIM-6 folder away, and startet the server again, like I had done for so many times before. but now the server crashes just before its done

## Current Behavior

The server crashes and askes me to either restart or exit

## Possible Solution

 Im afraid its something with my Mekanism Reactor or something, but I really don't know 

## Steps to Reproduce

1. Start server as normal
2. Server Crash

## Log

[crash-2018-07-07_03.23.14-server.txt](https://github.com/AllTheMods/ATM-3/files/2217299/crash-2018-07-07_03.23.14-server.txt)
[serverstart.log](https://github.com/AllTheMods/ATM-3/files/2217300/serverstart.log)
[latest.log](https://github.com/AllTheMods/ATM-3/files/2217301/latest.log)

## Detailed Description

The server version is 5.9.8c
The client version is 5.9.8d

Both has been restarted many times over.

I have attached 3 log files, hopefully the right one. 
Please tell me if other files are needed.
Please help me fix it again

**Comment by Yoosk** [comment]
Can you remove `\world\advRocketry\planetDefs.xml` and try to boot?

**Comment by UniQcorN** [comment]
Thank you Yoosk - it worked perfectly - is it because of my RF-tools dimension builder?

**Comment by Yoosk** [comment]
Looks like it corrupted for some reason, maybe bad shutdown or one of those multiple restarts.
