### ISSUE TITLE
[Embers] Can't create Dawnstone

### ISSUE THREAD

**Issue by titantwoshot** [AllTheMods/ATM-3#68]
The bug is description in http://imgur.com/a/KcClC (testing in ATM3 server)
After that i decide to test it in SP and it work fine

**Comment by TheElectricCake** [comment]
Better title would be: 
Embers Mixer does not create Dawnstone
Remember that people skim these titles sometimes to look for things to avoid doing in game. A good title is very helpful.

**Comment by Darkere** [comment]
Works now.

**Comment by OrdinatorStouff** [comment]
Confirmed working in pack 3.1+ could make dawnstone
