### ISSUE TITLE
Server pack file for version  5.9.8d is named serverfiles.zip

### ISSUE THREAD

**Issue by DDzwiedziu** [AllTheMods/ATM-3#680]
Please see attached image why this is annoying (and this is after cleaning pre-1.12 packs)

![screenshot_20180722_212416](https://user-images.githubusercontent.com/3499420/43049322-c3d54de2-8df5-11e8-8879-72c30936e564.png)

**Comment by DDzwiedziu** [comment]
Also this is not the first time this happens. It's just the moment I wanted to say "enough".

**Comment by Yoosk** [comment]
Renaming those by yourself should fix that issue.
