### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by EncryptedFreedom** [AllTheMods/ATM-3#684]
I installed All The Mods V3 using the Twitch installer (or w/e it is). I allocated 12 GB of Ram to the profile. I launched the game and now the game crashes at a particular point on startup for no apparent reason (to my knowledge).

## Expected Behavior
I expect the game the load properly as I haven't fiddled with any settings and/or files in the mod directory.

## Current Behavior
However, at the same spot at Start-up the game fails to launch and crashes.

The first bar on the loading screen reads: Loading - Initializing Minecraft Engine (3/7)
The Second bar on the loading screen reads: Loading Resource - ModelManager (1/1)
The Third bar on the loading screen reads: ModelLoader: baking (parallel) - please wait (1/1)

This is the exact point where it crashes every single time.

## Possible Solution
I attempted updating Java. This actually got it to go a bit further but, didn't fix the issue.
I allocated more Ram, originally I allocated the recommended 8 of 16 GB of Ram I have. I upped to 12 GB to see if it would have any effect. I didn't notice any. 

## Log
https://gist.github.com/EncryptedFreedom/f4fb93e2c8f52e02d508c1f0e5492817

**Comment by Yoosk** [comment]
1. You are using old java, [update it.](https://gist.github.com/darkhax/2d82494a88327327cec6d5172b1db239)
2. You have allocated only 3gb somehow, [do it properly.](https://i.imgur.com/7VPfxIM.png)

**Comment by EncryptedFreedom** [comment]
Thanks! Should've realized the Ram cap wasn't going through when it capped at 2900MB.
