### ISSUE TITLE
Reinforced Glass Recipe TechReborn->IC2 Not Working

### ISSUE THREAD

**Issue by Gpauxe** [AllTheMods/ATM-3#687]
## Expected Behavior
The recipe converting Tech Reborn Reinforced Glass (TRGlass) to IC2 Reinforced Glass (IC2Glass) is shown in the NEI but doesn't work in any crafting menu, (side note: same thing occurs for the scrap -> scrapbox recipe in IC2).
## Possible Solution
Could be a recipe tweak in the config or could be a conflict between tech reborn and IC2.

## Steps to Reproduce

1. craft or obtain reinforced glass (tech reborn glass will be made if using crafting recipe by default)
2. put glass into crafting grid to try to convert glass to IC2 Reinforced glass

## Detailed Description
Recipe tweak the IC2 mod for Reinforced Glass

**Comment by martmists** [comment]
Works on ATM3 5.9.8d when putting it in the center of a 3x3 in AE2 crafting grid

**Comment by Yoosk** [comment]
It is both oredicted and working already.

**Comment by M0N0X** [comment]
The release on the twitch app (all the mods v5.9.9d) still has the problems written above: any crafting recipe requiring IC2 reinforced glass cant be made w TechReborn reinforced glass & TechReborn reinforced glass cant be changed into IC2 reinforced glass. i've tried this on a vanilla crafting table and I've also tried to use the Forge lexicon (by Thermal Foundation), but nor was it in there or could be changed into the other glass. If there is anything I can help with, please let me know.
