### ISSUE TITLE
Update Minecolonies to newest Beta

### ISSUE THREAD

**Issue by Raycoms** [AllTheMods/ATM-3#690]
Hi, I am one of the main Minecolonies devs and quite some users of ATM3 are reporting issues to us which have been resolved for quite a while already but Atm3 is lacking behind a bit.

Could you update the used version to the newest Minecolonies beta?

https://minecraft.curseforge.com/projects/minecolonies/files/2592806

**Comment by Yoosk** [comment]
It will be removed with new update.
