### ISSUE TITLE
Request to update Refined Storage to v1.6 for ATM3 v6

### ISSUE THREAD

**Issue by derrickmehaffy** [AllTheMods/ATM-3#691]
## Detailed Description

RF v1.6 fixes quite a few issues related to autocrafting, requesting it be added to the update list for ATM3 v6

Link to file: https://minecraft.curseforge.com/projects/refined-storage/files/2587374

Related manifest location: https://github.com/AllTheMods/ATM-3/blob/a7fbca5f00ba8bbb921a58959f6d839d6486f4e1/manifest.json#L858-L862

A note from the the Refined Storage team on their changelog:

> NOTE: Worlds that used Refined Storage 1.5.x are fully compatible with Refined Storage 1.6.x and are getting converted upon loading the world. It is however not possible to revert back to Refined Storage 1.5.x when a world has already been converted to Refined Storage 1.6.x.

**Comment by Yoosk** [comment]
That's tested and done in dev branch.
