### ISSUE TITLE
using chisel and bits with murray pine planks from 'PLANTS'

### ISSUE THREAD

**Issue by 12lewisFTW** [AllTheMods/ATM-3#693]
## Steps to Reproduce

1. get chisel from chisel and bits
2. chisel the wood plank
3.walk up to the wood plank you should clip through like its a liquid
4.

**Comment by FallenEagle1** [comment]
Do you have a pic of the block being chiselled? Trying to test this now and cannot replicate the issue. Also, are there any mods added, is this a server, if it is a server, is it running sponge?

**Comment by 12lewisFTW** [comment]
i tested it on the official ATM3 server whilst building

**Comment by FallenEagle1** [comment]
Apparently an known issue. Shadows-of-Fire/Plants#88

**Comment by FallenEagle1** [comment]
Apparently there is more to this than just the Plants mod. It looks like flat colored blocks has this issue with certain colors of blocks. The one brought up was pink ones when made with botania pink floral essence and cobblestone.

More looking is required.

**Comment by AlgorithmX2** [comment]
This should be fixed in the latest build of C&B 14.22
