### ISSUE TITLE
making chisel and bits bag bigger

### ISSUE THREAD

**Issue by 12lewisFTW** [AllTheMods/ATM-3#694]
## Steps to Reproduce

1.chisel and couple of blocks
2.bag gets full
3.chisel another block when bag is full
4.player drop 4k entities onto the floor
5. server commits seppuku trying to load 4k entities

**Comment by FallenEagle1** [comment]
I can see this issue whether the chisel bag is made bigger or stays the same. As it is, it can hold just about 8 blocks worth in it already. If it's that big of an issue, make another bit bag or two, they're cheap. I don't see making the bag bigger as a way to fix the issue, I just see it as a way to prolong when it happens.

**Comment by Blueletric** [comment]
Anyways we cant do this modpack side, only the mod creator can do this

**Comment by 12lewisFTW** [comment]
its in the config right at the top of 'Chisel and Bits' it said 'stack size'

**Comment by FallenEagle1** [comment]
Been discussed already. It was mentioned to Blue already

**Comment by 12lewisFTW** [comment]
just test changing the stack size i played it with 4k stack size in 'Foolcraft' and its alot more flexible as you realise quicker that the bag is filling up

**Comment by FallenEagle1** [comment]
Already talked about. It's been discussed in chat. Some changes are in the making.
