### ISSUE TITLE
Disappearing swords and can't make sticks

### ISSUE THREAD

**Issue by jazzadellic** [AllTheMods/ATM-3#7]
Hi, I just had the strangest bugs happening in ATM-3. My swords kept vanishing. For all I know other things were vanishing too, but the thing I noticed vanishing was my sword since naturally that is one of the main things in my hand. The exact moment of vanishing I couldn't see because I was occupied with other stuff. The first iron sword to vanish I almost thought it broke, but I knew something fishy was up because I had just made that sword and hardly used it. Then I made another iron sword, and 2 minutes later when I went to equip it, it was gone. I was tripping out. For a moment I thought maybe after I crafted it in the crafting table I had accidentally dropped it on the ground. But it was like 200m away where I made it so I couldn't remember where the spot I crafted it was....I then made a third sword to kill some skeletons, and after killing 2 skeletons that sword disappeared...This time I was sure I wasn't imagining things or had dropped it. It just vanished in to thin air. I then went to make a 4th sword and lo and behold, I can no longer make sticks. Tried it in multiple crafting tables and none worked. After quitting and reloading the game the stick recipe did come back, but none of the missing swords came back. I wasn't doing anything unusual when these glitches happened --- just traveling around killing the occasional zombie and looting chests from villages. I have no idea what triggered it in the first place or how to reproduce it, just wanted to make you aware there is something weird going on.

**Comment by OrdinatorStouff** [comment]
Bruh. Sounds trippy af. First I've heard of it though like sure you don't have "drop item" remapped or something? No idea. I'll leave open in case anyone else has more input or sees similar stuff buuuuuut kinda hard to try and track down, too.

**Comment by whatthedrunk** [comment]
Going to assume this is fixed now. Please reopen if you have any new information. Thanks!
