### ISSUE TITLE
Craft Tweaker 2 Crash

### ISSUE THREAD

**Issue by funman300** [AllTheMods/ATM-3#70]
https://pastebin.com/raw/3civ5spg I updated the pack from v2.1b to v2.3 and get this error when I start the pack.

**Comment by OrdinatorStouff** [comment]
Is this server or client? If client are you using twitch or some other launcher?

If server, did you make sure to replace the "scripts" folder as well as other folders when updating?

**Comment by funman300** [comment]
That was from client side.

**Comment by BloodWorkXGaming** [comment]
Please send your scripts and crafttweaker logs

funman300 <notifications@github.com> schrieb am Sa., 22. Juli 2017, 20:07:

**Comment by funman300** [comment]
ok well I figured out the problem myself. It was because I removed Quark. Is there a way to remove that mod without getting that crash?

**Comment by BloodWorkXGaming** [comment]
Yes, changing the scripts, anything that has a reference to quark has to be
deleted

funman300 <notifications@github.com> schrieb am Sa., 22. Juli 2017, 20:21:

**Comment by funman300** [comment]
Thanks. I assume this can be closed now.
