### ISSUE TITLE
[Full][5.9.8d] Wizardry cape not working in current version

### ISSUE THREAD

**Issue by JRoffel** [AllTheMods/ATM-3#701]
## Expected Behavior

The cape from wizardry properly applies the mana discount when casting spells

## Current Behavior

Spells still take full mana even when the cape is at 100% reduction

## Possible Solution

Update Wizardry to it's latest version, as mentioned here [Wizardry Issue](https://github.com/TeamWizardry/Wizardry/issues/159)

## Steps to Reproduce

1. Craft and cast a spell to get a base mana usage without discount
2. Craft and wear a cape for like 8 hours to charge it up to the max
3. Cast the spell again wearing the fully charged cape
4. Observe no change in the used mana

**Comment by FallenEagle1** [comment]
The mod has been updated and tested in the 6.0 branch. It is working now, so just waiting on the pack release.
