### ISSUE TITLE
My world stops loading at 0%?

### ISSUE THREAD

**Issue by Raffuky** [AllTheMods/ATM-3#704]
When I try to load into my world it stops at 0% even after 1h it will not load in. I tried a new world and everything is fine. 
What do I need to do to fix this ?

**Comment by Raffuky** [comment]
Yes, my ram is at 8GB and java is up to date.

**Comment by FallenEagle1** [comment]
Does the computer have more than 8 in it? What happens if you close minecraft and reopen, does the world show up then in the world selection? 
Just for reference as well, what version of the atm3 modpack is it?

**Comment by Raffuky** [comment]
Yes, I can set the ram higher but  I played on this world with the same ram. When I close Minecraft and open it again the world will show up on top. I just reinstalled ATM3 yesterday.

**Comment by FallenEagle1** [comment]
What version of atm3 is it?

**Comment by Raffuky** [comment]
ATM3 v5.9.8d

**Comment by FallenEagle1** [comment]
I would look at the logs, I'm wondering if thaumcraft was going through its aura checks, those seem to hang things up, although I hadn't heard of it stopping a world from loading like that. If you try loading into the world now, same thing happens?

**Comment by Raffuky** [comment]
I really don't know what to look for at the logs. No, when I create a new world everything is fine.
