### ISSUE TITLE
6.0 beta bugs

### ISSUE THREAD

**Issue by Chocopuffs** [AllTheMods/ATM-3#707]
When I pressed "U" to see the uses of cobblestone my whole client crashed. This also happened to someone else.

## Expected Behavior

The game shouldn't crash.

## Current Behavior

It crashes due to the enormous amount of recipes it has to load.

## Possible Solution

Unknown.

## Steps to Reproduce

1. open JEI
2. Press "U" while hovering over cobblestone

**Likely JEI Mod issue, not fixable on pack level, but mods may exist to work around this issue**

Enderio downgraded to stop this in 6.0 branch -Fallen

**Comment by Sleeeper** [comment]
tried "U" on the capacitor bank, crashed too
log:
https://hastebin.com/biriyuyese.rb

**Comment by Sleeeper** [comment]
Conductive iron Jetpack is uncraftable because thrusters recipes requires enderio wooden gears without oredict, and only craftable wooden gears are from Tesla Core
![default](https://user-images.githubusercontent.com/2624211/43941047-2fe486cc-9c7b-11e8-9021-4a2c4c636481.png)
Solution: add oredict "gearWood" to conductive iron thruster recipe.

**Comment by Darkere** [comment]
Reborn Storage currently crashes placing down any blocks. New fixed Versions are already available.

**Comment by Darkere** [comment]
EnderIO broken spawners are not dropping ( at least not from mineshaft spider spawners).

**Comment by Chocopuffs** [comment]
It's all the spawners Darkere. =(

Server seems to have real struggles with the Tinker's crafting table, causes server lag.

RFtools Dimensions still urks me. You have disabled dimlets which include sky color (which is purely aesthetic) but allow Always day dimlet. I'm not sure how much time you guys have put into RFtools but you're really only allowing us to use the OP aspects and not enjoy the fun aspects.

I'm not sure if this is server plug in side, but /back does not work. and our beds don't actually trigger as our new spawns.

**Comment by martmists** [comment]
`I'm not sure if this is server plug in side, but /back does not work. and our beds don't actually trigger as our new spawns.` That's a server issue. I'm looking into /back, but this is the first report of beds not working as they work fine for me.

**Comment by Chocopuffs** [comment]
Removal of Quantum tanks as they are overpowered.
Yet Black Hole Tanks from Industrial Foregoing still exist at the cost of 3 plastic, 2 Eye of Enders, 2 buckets, redstone coil and a machine frame.... pretty broken.

**Comment by martmists** [comment]
Quantum Storage got removed for causing lag and being instable as far as I'm aware.

**Comment by OrdinatorStouff** [comment]
> Quantum Storage got removed for causing lag and being instable as far as I'm aware.  

And redundant.   
  
> Removal of Quantum tanks as they are overpowered.  

The only thing that was considered OP about quantum storage was the RS Quantum disk but even that wasn't the main candidate for removal, the redundancy and history (albeit not much lately) of instability was more like 90% of it.

**Comment by Darkere** [comment]
Dupe Bug when making minecarts in a rolling machine and then smelting it in a smeltery.

**Comment by Sleeeper** [comment]
not bug but mods interaction, same with golden pressure plates

**Comment by FallenEagle1** [comment]
Got looking into the spawner issue, Im thinking that might be a sponge issue. I set up a server and tested it and was working as expected for me.

**Comment by FallenEagle1** [comment]
binnies liquids not going into fluid transposer.
wax cast in glass maker

**Comment by Darkere** [comment]
Any reasons Bad wither no cookie is missing in the pack?

**Comment by Lartza** [comment]
@Darkere Bad wither no cookie is a 1.10 mod

**Comment by Darkere** [comment]
oh good to know. Then we just need someone to commit this:

config/randomtweaks/randomtweaks.cfg
  B:disableEnderDragonDeathSound=true
  B:disableWitherSpawnSound=true

**Comment by Darkere** [comment]
Akashic Tome not 1 dirt recipe not working.

**Comment by OrdinatorStouff** [comment]
items being stuck in AE can happen from time to time, I'm not sure why though. One solution is to use a filtered/fuzzy exporter to export the item out of the system @Chocopuffs

**Comment by FallenEagle1** [comment]
@Darkere I would test on a non-sponge server. Im able to still make the tome from dirt in the test I just did.

**Comment by OrdinatorStouff** [comment]
@Sleeeper checking the recipe now in my dev instance the conductive iron thruster takes the TeslaCoreLib wood gear which is what I can craft

**Comment by FallenEagle1** [comment]
@OrdinatorStouff I edited their comment, the last line. It was one of the fixes in my last PR

**Comment by OrdinatorStouff** [comment]
oh nice 👍 thanks @FallenEagle1

**Comment by Darkere** [comment]
1.11.2 Compatlayer is in the pack?

**Comment by FallenEagle1** [comment]
@Darkere is that on the sponge server? Just tested in a singleplayer world and was getting 5 bars of armor from it

**Comment by Chocopuffs** [comment]
I have mentioned this in 5.9, but no real change in 6.0. I'm wondering if it's hard to change or balance RFtools dimensions.

You currently can't choose the colour of your clouds (there is no crafting pattern) this could easily just be Coloured wool as the 6th ingredient. it is PURELY aesthetic, no reason this couldn't be implemented.

You can't choose the sky colour, again COMPLETELY aesthetic, you could have the 6th ingredient be dye.

You cant choose the sky features, like fog, suns, planets and moons. - not sure what the 6th ingredient could be.

Weather dimlets aren't craftable, i can understand that creating infinite thunder may be an issue, but you cant even choose "default weather" it's craftable but "Disabled"

All the Liquids require Rarity 5, which is stupid, like apple juice and molten draconium are an equal on rarity... this can be something you fix much later on though....

All mobs are Rarity 5, and HIGH power. this should be much lower power, as it's just saying you want a certain mob to spawn, that's not as op as Liquid uu matter oceans.

The effects aren't craftable but i dont mind that.

You can currently make an always day dimension, i'm not sure if that was intended, i enjoy always day.

I really want to make a dimension soon (in the next 24 hours) i'll donate $10 to get this update in the next 24 hours.... hahaha

Specifically the Aesthetic changes. the rest can be changed later.

**Comment by Darkere** [comment]
JEI Clicking the recipe for anything that has saplings in it into rs pattern grid. Causes a "payload may not be larger than xx" error. Disconnecting you from the server. 

(tested on marts server, sponge is always a possibility)

**Comment by Lartza** [comment]
@Darkere On 5.9.8d I think my client doesn't just disconnect but crashes trying to insert the greenhouse glass recipe to the crafting grid, so probably not Sponge related since I play on a regular forge server. Forgot/Never had time to investigate myself

**Comment by gabeux** [comment]
@Darkere Thanks for noticing it, trying to use JEI to craft a Biome Marker on RS Grid causes a timeout for me too.
