### ISSUE TITLE
Crash Within Load

### ISSUE THREAD

**Issue by disgruntledgrunt** [AllTheMods/ATM-3#708]
![image](https://user-images.githubusercontent.com/26822366/43981502-b8b8177a-9cb7-11e8-9f1a-0222e965fa34.png)

My game crashes right here, and I have no clue how to fix it. Any tips?

## Expected Behavior

The loader should continue past this point and load Minecraft.

## Current Behavior

I stop loading at the point of the above pitcure

## Possible Solution

Possibly increase memory used?

## Steps to Reproduce

1. Load up Minecraft.
2. There's your bug

## Log
Don't know how to provide a Log

**Comment by FallenEagle1** [comment]
That is an issue of not enough ram being allocated to minecraft. For this pack, it is recommended to use at least 5.5-6 Gb, and it looks like you are set at twitch's default values. https://cdn.discordapp.com/attachments/254533502698127370/474949292545802241/E3lRksp.png I would go through this picture and make the changes it suggests, that will help with a couple of different issues.
