### ISSUE TITLE
Balance Grid in Tinkers Crafting Table

### ISSUE THREAD

**Issue by mdinnocenzo** [AllTheMods/ATM-3#71]
When trying to spread the grid in the tinkers crafting table game crashed out.

[crash-2017-07-22_17.58.32-client.txt](https://github.com/AllTheMods/ATM-3/files/1167746/crash-2017-07-22_17.58.32-client.txt)

[latest.log.txt](https://github.com/AllTheMods/ATM-3/files/1167747/latest.log.txt)

**Comment by gefailter71** [comment]
Reported to TiC github :)

**Comment by Darkere** [comment]
Fixed

**Comment by OrdinatorStouff** [comment]
I think this was actually because the recipe book button was overlapping and getting accidentally pressed and causing the crash. Looks to be working fine now (and no recipe book seen on tinkers table ui at all)
