### ISSUE TITLE
[Woot] - Possible config change for rf needs

### ISSUE THREAD

**Issue by Stians92** [AllTheMods/ATM-3#711]
## Expected Behavior
A tier 1 Woot factory should spawn mobs at a reasonable RF cost.

## Current Behavior
A tier 1 Woot factory requires 2.4 million RF to spawn a single skeleton and uses 4.8k RF/tick.

## Possible Solution
Config file should be rewritten.

## Detailed Description
Setting up a Woot factory requires way more work than any other ways to automate mob spawning, but it currently requires ridiculous amount of RF even to spawn the most basic mobs.
Also, the Factory Heart is reporting the use of 4.8k RF/tick, but a Basic Power Cell can only transfer 4k, so you will not be able to run the factory at maximum capacity using the current config file.

https://imgur.com/wYnXgir

**Comment by Yamza** [comment]
Truly wish this could be made reasonable to eliminate the need for tps hogging mob farms, but this was adjusted to balance out being able to farm chaos drops.

**Comment by Stians92** [comment]
But the config can be overridden for specific mobs, so why make the default so ridiculous?

The file factory_config.json can be used to balance out mobs like the wither, ender dragon and the chaos guardian. I would expect woot.cfg to have more reasonable default values for non-boss mobs.

**Comment by FallenEagle1** [comment]
When the changes were done, it was done just a blanket config, just across the board. It can and probably will be fine tuned, its been discussed some with the packdevs.

**Comment by OrdinatorStouff** [comment]
Suggested configs c/o @Yamza for review/integration into 6.0
[woot.zip](https://github.com/AllTheMods/ATM-3/files/2303221/woot.zip)

**Comment by FallenEagle1** [comment]
Woot changes are in a PR right now, will see where that puts us once they start getting used.
