### ISSUE TITLE
Pneumaticcraft 1.12.2 has been released

### ISSUE THREAD

**Issue by Seaniau** [AllTheMods/ATM-3#714]
## Expected Behavior

A patch for Pneumaticcraft has been released addressing some severe bugs in the Mod. Such as the inability to craft some times as well as stability and performance of some mod items.
Please release a patch to ATM3?

## Current Behavior

Unable to craft Machine Gun Ammo - At all.

## Possible Solution

Please release a patch to ATM3?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
Already updated in the test pack for 6.0. Some other bugs are being fixed before 6.0 is released. Shouldn't be too long for that though.
