### ISSUE TITLE
Minecraft window "not responding"

### ISSUE THREAD

**Issue by Creosodde** [AllTheMods/ATM-3#716]
*I've no experience modding, fixing mods, i don't know what i'm doing*
i play single-player. Game stops responding about every 5 minutes. window temporarily fixes itself after 10 minutes wait. no FPS drops in the golden 5 minutes. i see the window go grey (not responding)

I've reinstalled the pack, but neither the old or any newly created worlds run properly. they all now run in the manner described above. before reinstalling, i played less than 20 hours (similar problem existed, but was far more rare 1/30min). restarting MC, Twitch or computer has no impact.

previously i've allocated 4GB RAM (bad), and 7GB RAM (bit better) my PC can only take 8GB ram.
every other setting was left on default.
tried on newest Twitch and pack versions.
ive not added or removed any mods.

where should i start looking for a solution? is this a known problem thats being worked on, or (i dont know what i'm doing) did i screw something up horribly?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yamza** [comment]
If you only have 8GB, you're probably not going to run this _well_. See this guide for adjusting your settings. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
You'll want to use either 5.5 or 6GB of ram, the other settings may help make it playable.

**Comment by Creosodde** [comment]
Operating System: Windows 10 Home 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
            
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: B85M-DS3H
                     BIOS: BIOS Date: 06/19/14 23:00:41 Ver: 04.06.05 (type: BIOS)
                Processor: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 CPUs), ~3.6GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8080MB RAM

**Comment by Creosodde** [comment]
i've done some testing:
when i allocate ~6000MB in twitch, my F3 shows ~4000MB allocated, at about *98% utilisation*. This is probably why the window freezes. i use 'd64' java argument which is supposed to pre-allocate 4000MB - (reason for the lower displayed memory?)

editing the RAM allocation is definitely helpful, so it has something to do with the problem as you noted (thank you)

Since i can't easily expand my PC RAM beyond 8 gig, is there a way to lighten a load  of A.T.M.3?
any mods to be removed? (single player) (i'll look into this on my own)

The suggested method (RAM issues) caused my world to run slower and i couldn't move: i'd be teleported to infinity and back (with some visual glitches), so i reinstalled MC again. no issues with FPS - i would crash in cinema-quality visuals. 21 FPS easy.

all in all, thanks for your help, i now have a pinpoint from where to start.
