### ISSUE TITLE
No way to get applied energestics 2 "quantum entangled singularity"

### ISSUE THREAD

**Issue by huang-junwei** [AllTheMods/ATM-3#717]
## Expected Behavior

putting an ender dust from AE2 and a singularity together on the ground near an explosion should yield 2 quantum entangled singularity

## Current Behavior

none of the available ender dust in the pack gives a quantum entangled singularity when putting them and a singularity together on the ground near an explosion

## Possible Solution

AE2 seems to only check their own ender dust when attempting to create the quantum entangled singularity. However, the AE2 ender dust seems to be disabled in this pack and I think allowing some way to craft AE2 ender dust will be able to help

**Comment by huang-junwei** [comment]
Weird...It doesn't work for me... It still stays as a normal singularity

**Comment by huang-junwei** [comment]
I have no idea how to reopen a thread...... :(

**Comment by huang-junwei** [comment]
Anyways, like I said, terraqueous ender dust also doesn't work in making a quantum entangled singularity... unless there is something I missed...
Tho I am pretty sure I did everything correctly by dropping the ender dust and a singularly together on the ground, followed by a TNT explosion near it.

**Comment by FallenEagle1** [comment]
@huang-junwei Reopened this for you since it seemed like you were not able to. Just did some testing with this while it was back open and was able to make singularities. Ender pearl dust from techreborn and portal gun both work in my testing. Make sure that it is one of these two, and that you are not standing too close as to accidentally pick one or both of the items up before the tnt explodes.

**Comment by huang-junwei** [comment]
I must be missing something then, is there anything I did wrong in this video?
`https://youtu.be/ZCIuFReOhy8`

**Comment by huang-junwei** [comment]
nope, doesn't work, tried unclaiming the chunk, nothing, tried going to a chunk that have never been claimed before, also nothing.

**Comment by FallenEagle1** [comment]
Is that a server where explosions and such are disabled? Also, when you did it in an unclaimed chunk, did the ender pearl dust disappear/the land get exploded?

**Comment by huang-junwei** [comment]
It is singleplayer and mob griefing is disabled, but tnt still does block damage. No, the ender pearl dust did not disappear. Chunk is claimed using FTB utilities for chunk loading.

**Comment by huang-junwei** [comment]
So, I decided to make a new world to test it and somehow it worked in the new world. It seems like something about my current world is broken, no idea what tho....

**Comment by JFMillerUSA** [comment]
any fix found, I'm having same issue
