### ISSUE TITLE
Gendustry causing crash on startup

### ISSUE THREAD

**Issue by Naphrym** [AllTheMods/ATM-3#719]
## Expected Behavior

Minecraft should load properly

## Current Behavior

Minecraft crashes to the launcher during loading

## Steps to Reproduce

1. Load minecraft
2. Wait for it to crash
3.
4.

## Log

https://gist.github.com/Naphrym/448904984547579363d11ef048c0d31b

**Comment by mlody1123** [comment]
I have the same problem..

**Comment by Yamza** [comment]
Reported the issue here: https://github.com/bdew/gendustry/issues/277

**Comment by MCampos** [comment]
Yep me too.

**Comment by DLCIncluded** [comment]
Have someone who has the issue too, they get the same error, but if you remove Gendustry it fails at ExUtils... so not 100% sure its Gendustry's fault. 

Already tried updating java, fresh install of pack, allocating more RAM, using a different launcher, etc and still occurs. Just wanted to throw this out there.

**Comment by Yamza** [comment]
See here for info: https://www.reddit.com/r/allthemods/comments/97t8zn/bug_gendustry_crashing_on_startup/

Only solution right now is Twitch with Jar launcher on current Java (_181 64-bit)

**Comment by phrit** [comment]
same crash here

**Comment by FinnTheNarwhal** [comment]
same here

**Comment by martmists** [comment]
Temporarily locked conversation as we're aware of the issue and looking into it, saying "same here" is not useful feedback.
