### ISSUE TITLE
Extra Utilities 2 now crashes at startup

### ISSUE THREAD

**Issue by SamPhoenix91** [AllTheMods/ATM-3#721]
## Expected Behavior

The game should load as usual

## Current Behavior

The game crashes to the launcher with the error net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
#719 Same thing, its a known issue being worked on.
