### ISSUE TITLE
OpenComputers not able to craft Tier 1 Drone case

### ISSUE THREAD

**Issue by bayleywrayYT** [AllTheMods/ATM-3#722]
## Expected Behavior

I should have crafted a tier one drone case in a regular crafting table but I'm unable to

## Current Behavior

doesn't let me / all it shows is nothing can be crafted from the recipe 

## Steps to Reproduce

1. put the recipes in the crafting table as show from NEI/JEI
2. and it doesn't show anything can be  crafted from it
3.
4.

## Detailed Description

make it so it works? please, and thank you.

**Comment by FallenEagle1** [comment]
What exactly were you using for trying to craft it? Also, what was JEI showing (same thing)? I just tested this in a singleplayer world and it is craftable. This was in the 6.0 test update, but I don't think open computers had an update and nothing changed for it.
