### ISSUE TITLE
Ender Pearl Powder has 3 conflicting recipes 

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM-3#725]
https://i.imgur.com/KPWhUeF.png

Confirmed to be an issue on 6.0 ptr2

**Comment by FallenEagle1** [comment]
Looked into this a little, should be easy enough to fix, by removing the recipe to get ender pearl dust from tech reborn (techreborn:dust:20) and removing the recipe to get ender pearl dust from portal gun (portalgun:item_dust_ender_pearl). Both have alternative recipes for getting them, be it pulverizer or furnace, so they still will be craftable

**Comment by FallenEagle1** [comment]
A fix is in now.
