### ISSUE TITLE
[6.0ptr2] Soulbound enchant not working

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM-3#727]
Items are not bound properly, they go in the grave upon death.

Edit: Tested both EnderIO and the CoFH III versions.

**Comment by Yamza** [comment]
https://github.com/M4thG33k/TombManyGraves/issues/58
https://github.com/SleepyTrousers/EnderIO/issues/4709

TombManyGraves-1.12-4.1.0
tombmanygraves2api-1.12.2-1.0.0
tombmanypluginsbackpacks-1.0.0
tombmanypluginscosmeticarmorreworked-1.0.0
tombmanypluginsthebetweenlands-1.0.0

EnderIO-1.12.2-5.0.30
EnderCore-1.12.2-0.5.37

Not sure which part of this actually pertains to the Soulbound enchant.
CoFHCore-1.12.2-4.5.3.20-universal
CoFHWorld-1.12.2-1.2.0.5-universal

**Comment by HenryLoenwind** [comment]
TombManyGraves prevents all other death processing from working by disabling the Forge API that's there for that purpose.

**Comment by Yamza** [comment]
Replace with Corail Toumbstone: https://minecraft.curseforge.com/projects/corail-tombstone
Disable EnderIO Soulbound(incompatable). Potentially also disable CoFH or Corail Soulbound(redundant).
