### ISSUE TITLE
Conflict between Tinkers and Embers

### ISSUE THREAD

**Issue by jeffwcollins** [AllTheMods/ATM-3#73]
Seems to be a conflict with alloys showing in the TC Smeltery when Embers is installed due to Forge not registering the different fluids.

https://github.com/SlimeKnights/TinkersConstruct/issues/3037

**Comment by whatthedrunk** [comment]
Like it says there you can edit the level.dat file. Not the best solution but it's what we had to do on our server too. Thanks for the report.

**Comment by DietmarKrause** [comment]
@whattthedrunk: what exactly and how has the level.dat to be edited? I would rather like to have a different solution perhaps some config changes somehow

**Comment by OrdinatorStouff** [comment]
Backup level.dat, open with NBTExplorer: 
![unknown 1](https://user-images.githubusercontent.com/6283913/28973754-08fb4e3a-78e9-11e7-9a15-2737ba954fc4.png)
