### ISSUE TITLE
Growth Essence Uncraftable in Privately Hosted Simplified Server

### ISSUE THREAD

**Issue by MasterMilitia** [AllTheMods/ATM-3#730]
## Expected Behavior
The draconic infusion crafting should be used to craft the growth essence.

## Current Behavior
The growth essence can not be crafted due to requiring draconic tier infusion altar parts, which require the growth essence to craft.

## Possible Solution
Empowerer crafting recipe for growth essence. Supposedly there is a recipe but it does not show up in this version, even when manually added to the server and clients royal jelly will not be accepted by empowerer, however it works fine in singleplayer with this fix.

## Detailed Description
Add empowerer recipe to simplified files or make draconic altar infusion recipe require wyvern tier altar parts. Empowerer recipe can be added to client files and recipe will work in singleplayer worlds, when added to server it does not apply correctly however, disallowing players from placing royal jelly in empowerer.

**Comment by Yamza** [comment]
Can you type `@pam` in JEI and see if any items show up?

**Comment by FallenEagle1** [comment]
This is an issue, I was wondering about it but never had a chance to test it. Its not the pams issue

**Comment by FallenEagle1** [comment]
This has been fixed in 6.0
