### ISSUE TITLE
[6.0ptr2] Zinc Ore 

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM-3#733]
Zinc Ore block only comes from Void Miner
Zinc Dust can be made from Sphalerite Ore Block (which would need to be acquired with Silk Touch) at 10% chance.
Zinc Dust can be obtained from Lens of the Miner (rough rate https://i.imgur.com/XcRvOPH.png)
Edit: Forgot Zinc Bees

Should it be this hard to obtain?
Suggestion: Low % Overworld spawn rate?

**Comment by FallenEagle1** [comment]
If this is for getting brass, it doesnt show in jei, but there is a way to get brass without needing zinc. 5 instrumentum and one copper ingot gets you alchemical brass, which functions the exact same as regular brass. But for some reason it doesnt show in recipes even though it can be used. It might be worth putting a tooltip on regular brass to indicate this.

**Comment by FallenEagle1** [comment]
Just got looking, the item doesnt even show up in jei. This can probably be fixed in the oredict scripts.

**Comment by FallenEagle1** [comment]
Zinc ore hasn't been changed, as that is believed to be mod authors intent, but alchemical brass should now show up to make tech reborn brass, so there is now another visible recipe for making brass.
