### ISSUE TITLE
Abyssalcraft zombies

### ISSUE THREAD

**Issue by osiplaygames** [AllTheMods/ATM-3#735]
abyssalCraft zombies spawn 2 often and 2 much

## Expected Behavior
normal zombie spawn smthing like 3-5

## Current Behavior
there is fockin 200 per 1 chunk, it's only two of 3-4 cologne of them yestarday i broke my 1526 durability sword to kill them all (it was fully reapaired). The problem is not that they're annoying but that mount of mobs is lagging server and slowing down minecraft ;..; 

![image](https://user-images.githubusercontent.com/42618976/44480740-49be5f00-a644-11e8-8a37-ec99ba4a00e3.png)
![image](https://user-images.githubusercontent.com/42618976/44481546-5e9bf200-a646-11e8-8fd9-c634511338cc.png)

## Possible Solution
change spawning ratio of abyssalcraft zombies

## Steps to Reproduce

1.
2.
3.
4.

**Comment by martmists** [comment]
Abyssalcraft has been removed in 6.0
