### ISSUE TITLE
Plant Interactor: Industrial Foregoing/SimpleHarvest interaction for vanilla crops harvest

### ISSUE THREAD

**Issue by userjjb** [AllTheMods/ATM-3#740]
- For almost all crops the Plant Interactor from Industrial Foregoing will right click to soft harvest and then store the harvested crops internal to the block's inventory.
- In vanilla Minecraft right clicking crops does nothing, you need to hard harvest and replant.
- SimpleHarvest looks like it mods this slightly by allowing soft harvesting with right clicks, but the crops drop to the ground, they are not stashed in player inventory.

In ATM3 when you try to harvest vanilla crops (e.g. carrots) with a Plant Interactor it will break the carrots and they will drop to the ground.

## Expected Behavior
Harvesting vanilla crops with a Plant Interactor should properly put them in the block's inventory, as is consistent with all other crops that aren't modded by SimpleHarvest.

Note that in other modpacks the Plant Interactor correctly harvests and collects vanilla crops (e.g. Project Ozone, Forever Stranded Lost Souls, etc.). These don't have SimpleHarvest, I'm not sure what they are using to mod vanilla drop harvests.

## Current Behavior
Vanilla crops harvested with the Plant Interactor drop to the ground.

## Possible Solution
Submit upstream suggestion/issue to SimpleHarvest to have modded crops be placed into player inventory? It seems based on the Industrial Foregoing dev's comments an additional event might alternatively be thrown? ( [https://github.com/Buuz135/Industrial-Foregoing/issues/351](https://github.com/Buuz135/Industrial-Foregoing/issues/351)) Given that SimpleHarvest hasn't been updated in a year, maybe an alternate workaround might be needed.

## Steps to Reproduce
1 Plant carrots.
2 Harvest with Plant Interactor.
3 Carrots fall to the ground, rather than being picked up by Plant Interactor.
(Note I have tested this in an otherwise vanilla test pack of the same forge/MC vintage that just includes IF and SimpleHarvest and the issue persists, so unlikely to be interaction from any other mods.)

**Comment by Yoosk** [comment]
With removal of simple harvest, everything works smoothly.
