### ISSUE TITLE
unable to craft supremium ingots

### ISSUE THREAD

**Issue by phrit** [AllTheMods/ATM-3#741]
## Expected Behavior

should be able to craft supremium ingots with 8 supremium essence and a superium ingot.

## Current Behavior

crafting table does not make the supremium ingot.  doesn't even show the picture for it.

## Possible Solution

fix crafting recipe?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
In a test world I am able to make it, so it might be something with the instance you have. It is showing up in jei for me, and is craftable with 8 supremium essence around one superium ingot. What version of the modpack, did you change the packmode, and have you changed anything in the pack?

**Comment by phrit** [comment]
Thanks for the quick response.  am playing on a home server (mine) so my wife and i can play together.  we're using version 5.9.8d both clients and server.  the only change i've made is to make the elevator go 32 blocks instead of 8, which shouldn't interfere (but who knows, i've seen weirder things  lol).

**Comment by FallenEagle1** [comment]
That shouldn't interfere. There are some weird interactions, but that shouldn't be one of them. I'm assuming that you are seeing this issue when you are on the server. If you try to replicate this in a single player world, does the same thing occur?

**Comment by FallenEagle1** [comment]
Also, looking through the scripts, it looks like this is a recipe that gets changed, so if you are not seeing this recipe in game, this indicates that there is a script mismatch. Just for checking, when you are on the server, if you type `@pam` into jei, does anything show up?

**Comment by phrit** [comment]
maybe i got the beta and release version of the server mixed up.  i'll mess around with it and let you know.

**Comment by FallenEagle1** [comment]
Alright, that is a known issue that came up with the serverstarter, as pam's harvestcraft had a change in the mod name to include a ' and it broke it some. Manually download the correct version of pam's harvestcraft and put it in the server's mods folder. Probably could just copy and paste the .jar file from the clients mod's folder and put that into the server's mods folder.

**Comment by phrit** [comment]
we've had a few other recipe problems as well, so i'm just gonna change over to the correct version of the server in an hour or so.  would do it now but the wife won't log out till it's time to make dinner   lol

**Comment by FallenEagle1** [comment]
No worries. Having that mod missing from the server basically breaks all of the scripts so it does mess with a number of the recipes. Adding that should fix all of those. It's supposed to be in, but we missed the name change and it broke things.

**Comment by phrit** [comment]
all fixed. it was pams.  thanks for your help!

**Comment by FallenEagle1** [comment]
Glad it works now!
