### ISSUE TITLE
6.0ptr3 Lost Cities worldgen generating bedrock

### ISSUE THREAD

**Issue by skipgamer** [AllTheMods/ATM-3#749]
## Expected Behavior
Generating a city with Lost Cities should generate a working world

## Current Behavior
The worldgen is simply not there https://i.imgur.com/UHvl2Nt.png

## Possible Solution
? no idea

## Steps to Reproduce
1. Create world using Lost Cities worldgen, doesn't matter what settings or with BoP
2. Hopefully you see the same thing and it's not just a me thing :x

**Comment by Yamza** [comment]
Confirmed to be an issue. PTR3
https://i.imgur.com/Z20Zs8L.png

**Comment by Yamza** [comment]
Evidently an incompatibility with JEID.
https://github.com/McJtyMods/LostCities/issues/152
https://github.com/McJtyMods/LostCities/issues/146
