### ISSUE TITLE
Essence of Scornful Oblivion

### ISSUE THREAD

**Issue by TYPyz** [AllTheMods/ATM-3#750]
Hi, i cannot craft the "Essence of Scornful Oblivion". JEI will auto-fill the recipe into a Crafting Table no problem if you have the items to make it, but there'll be no result to pull out. Tried on all crafting table but nothing. Can someone help me? I tried a fresh download of the modpack but again....nothing and i tried to craft it just one-at-a-time too but nothing...
The recipe:
[https://i.imgur.com/FmD283e.png](url)
First try
[https://i.imgur.com/dnkV7r9.png](url)
Second try
[https://imgur.com/a/FFTjVwW](url)

**Comment by Darkere** [comment]
Confirmed not working in test pack with just magic bees installed. Reporting to mod author.

**Comment by Darkere** [comment]
So apparently the recipe requires a dragon egg in the middle which does not show up in JEI. Works if you do put it there. Still bugged as it's not supposed to consume the dragon egg upon crafting.
