### ISSUE TITLE
6.0 ptr3 - Forgemicro blocks "missing" in jei

### ISSUE THREAD

**Issue by Chocopuffs** [AllTheMods/ATM-3#751]
As title says.
I'm not sure if deliberate or not, but JEI does not have any of the microblocks so i just have to get the saw out and hope it has integration.

## Expected Behavior
That i can see the different materials i can make into microblocks

## Current Behavior
I can only see the saws and one stone cover

## Possible Solution
Revert back to what ever the coding was for 5.9.8 worked a treat then...

Probably low priority but bugs are bugs...

https://imgur.com/a/GjuQwxM

It used to show in the JEI what you could cut... and because you can cut the wood, you should be able to cut the leaves. but thats not the case. the leaves are uncuttable

**Comment by LowcaX** [comment]
You can change this in cofig. Too much materials to show it is better when off. You can cut probably all blocks so why you want to see this in JEI.

**Comment by Chocopuffs** [comment]
Because you can't cut all the blocks.... I'm not going to go through them all but botania vivid grass can't be cut.

**Comment by Chocopuffs** [comment]
Applied energistics covers are in jei so I don't see why you'd not have forge micro blocks... That's way less patterns

**Comment by LowcaX** [comment]
this is not painful to put in crafting, like i sad a lot of block can be cut so too much pages in JEI. Just change config in your minecraft.

**Comment by Yamza** [comment]
The other patterns can be enabled in jei via config "multipart". The "leaf" items are unable to be crafted.

Remix: Only "covers" show in JEI. Items can still be crafted as expected.
5.9.8d: Can not craft leaves, all items show in JEI., recipes do not show.

**Comment by Yoosk** [comment]
You can enable it in config by yourself.
