### ISSUE TITLE
[6.0prt3] Thermonic Fabricator does not accept Wax Casing

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM-3#752]
Wax Casing can not be placed in the correct slot. https://i.imgur.com/eDYXn8g.png

Sample recipe: Beer Mug https://i.imgur.com/J1mYq9a.png

**Comment by NebulouStorm** [comment]
It works with just jei and fo
![capture](https://user-images.githubusercontent.com/28715287/44881071-02ebed00-ac74-11e8-8f9e-a45ed0dd3b44.PNG)
restry.

**Comment by turret001** [comment]
I can confirm this bug. Tried on both Sinleplayer and Multiplayer. 

http://i.hizliresim.com/PDVqQd.png

**Comment by Yoosk** [comment]
Temporarily changed to other recipe.
