### ISSUE TITLE
[5.9.8d] Extreme Reactors - Reactor Casing

### ISSUE THREAD

**Issue by EsTaNG9** [AllTheMods/ATM-3#754]
So i'm on version 5.9.8d and I'm not able to craft the Reactor Casing.

http://prntscr.com/kotvdl

Thank you

**Comment by FallenEagle1** [comment]
Is this on a server? If so, if you type into jei `@pam` does anything show up?

**Comment by EsTaNG9** [comment]
Yes I'm playing on a server with a friend and when I type @pam it doesn't show up anything.

http://prntscr.com/kp62pq

**Comment by Yamza** [comment]
In that case, you'll have to manually add the correct version of Pam's to it. 
`Pam's HarvestCraft 1.12.2u` from https://minecraft.curseforge.com/projects/pams-harvestcraft/files.

**Comment by EsTaNG9** [comment]
Thank you
