### ISSUE TITLE
Mod takes about 2 hours to load w/ about 7 gigs of ram

### ISSUE THREAD

**Issue by AXGNDevilDealer** [AllTheMods/ATM-3#758]
When I downloaded the mod nothing was wrong, but when I open the mod pack it keeps filling the 7 gigs and stopping during loading.

I've only got the game to load once and it was running smooth and then I got a sudden crash.

**Comment by Yamza** [comment]
See here: 
https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

If that doesn't help, upload your crash report to pastebin or github.com and link it.

**Comment by AXGNDevilDealer** [comment]
Thank you I will try this

**Comment by FallenEagle1** [comment]
Going to assume since nothing more has been said that the proposed fix above worked.

**Comment by AXGNDevilDealer** [comment]
Yes sorry I haven't replied thank you so much
