### ISSUE TITLE
Unable to create AE2 processors

### ISSUE THREAD

**Issue by chooven** [AllTheMods/ATM-3#76]
No matter what circuit I put in the inscriber I get calculation processor out. Also lots of issues clicking items into the slots in the gui of the inscriber. Sometimes redstone will not go in the middle slot the silicon won't click in.  Also,  can't remove the press most of the time.

**Comment by JamieKG** [comment]
i'm having kind of the same issue but U get logic processors when I try to create engineering processors

**Comment by JamieKG** [comment]
I just looked on AE2 github for issues and it looks like it may have been fixed in rv5.alpha.2

**Comment by chooven** [comment]
I hope you're correct, the comment says "Fix inscribers".  It looks like it is fixes for the problem with items not going into the correct slots and also extraction from the GUI so not sure. fingers crossed since this one required to use AE2 in 1.12

**Comment by chooven** [comment]
Just confirmed with rv5-alpha-2 build of AE2 I was able to make all 3 types of processors in ATM3.
