### ISSUE TITLE
Mystical Agriculture + JAOPCA integration fail.

### ISSUE THREAD

**Issue by Chocopuffs** [AllTheMods/ATM-3#761]
**Mystical Agriculture + JAOPCA integration fail.**
https://imgur.com/a/iLp4D0d
First image shows a seed bug with dimensional seeds, (still agricraft'able) but also drop themselves when harvested...

second and third image show two seeds for the same ingot. i'd get rid of the (JAOPCA) because it likely may have the same bug as the Dimensional seeds.

**Comment by Yoosk** [comment]
susposed to be in atm3 - remix issues
