### ISSUE TITLE
Server crashes on startup with new beta.

### ISSUE THREAD

**Issue by Syer10** [AllTheMods/ATM-3#766]
## Expected Behavior
Server starts up

## Current Behavior
Server crashes with "java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)" error.

## Steps to Reproduce
1.Start the server
2.
3.
4.

## Log
https://gist.github.com/Syer10/417feb95de427a21232826a66be7fb18
https://gist.github.com/Syer10/3359222d5e9bd38eacaae77393acff9b

## Detailed Description
I think there is some mod that changes the server system so that it unloads or closes the server if it hangs to long. This is not viable for modpacks because it takes long to start up and when the world load there are mods that load a few things at that time.

**Comment by Syer10** [comment]
I was lookming around in configs and saw this inside foamfix's config"    # The amount of time FoamFix should wait for a world to be deemed non-unloaded. [default: 60, range: 10-3600]
    I:checkNonUnloadedWorldTimeout=60"
I believe that is the issue. I will test.

**Comment by Syer10** [comment]
I changed the line to 3600, still crashed.

**Comment by Yoosk** [comment]
Edit `max-tick-time=` value in `server.properties`, it should be at very least 90000, not sure why you ended up with 60000. It's counted in milliseconds and maybe your machine needs to set it higher like 120000 or more.
