### ISSUE TITLE
Crash on Startup, or shortly after startup

### ISSUE THREAD

**Issue by Ibrulz** [AllTheMods/ATM-3#767]
## Expected Behavior
Game should load to menu.

## Current Behavior
Game will crash while loading, or it will load to menu, only to crash a few minutes later. Does not always crash. Issue is only occasional, but same crash report.

## Steps to Reproduce
1. Launch Twitch app. Go to All The Mods 3 pack in modded MC Section. Click play and play again on the jar launcher.
2. Allow the game to load.
3. Game crashes, or if not step 4
4. Game will load, then crash a few minutes after, or the game will run fine, and only crash sometimes after disconnecting from a server.

## Log
https://pastebin.com/dPjRBQyz

**Comment by FallenEagle1** [comment]
Try updating and see if the problem persists.

**Comment by Ibrulz** [comment]
Try updating what?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by FallenEagle1** [comment]
The modpack. Looking at the versions of things you have, you are running atm3 5.9.8d. The latest version of the pack is 5.10.1

**Comment by Ibrulz** [comment]
Ah. I see. It’s a BETA release. The problem is I use an Akliz server, but they only offer 5.9.8d as the latest pack.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Yoosk** [comment]
You can update your server manually on akliz. And for that error i would suggest clean, fresh instance
