### ISSUE TITLE
Game Crashes Whilst Initializing Game

### ISSUE THREAD

**Issue by srchallenge** [AllTheMods/ATM-3#769]
When trying to initialize the game, it crashes at "ModelLoader: Baking (Parellel)" and I get this error message:

https://gist.github.com/srchallenge/1f8d325d84f3b3f73164e837d2e9e70f

**Comment by Yamza** [comment]
See here to fix your settings: https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
