### ISSUE TITLE
[Modpack v2.6] [Mekanism] Lasers not working 

### ISSUE THREAD

**Issue by TheClonker** [AllTheMods/ATM-3#77]
The Mekanism Lasers are not breaking Blocks or charging the Laser Amplifiers. 
Tested in Singleplayer and Server.

The Laser is accepting RF, the internal Buffer is full and the charging Sound is heard but no Laser is shown and the Amplifier is not charging

**Comment by whatthedrunk** [comment]
This should be fixed in the new version put to today. Thanks for the report.
