### ISSUE TITLE
Startup crash -  thermal foundation

### ISSUE THREAD

**Issue by MrRolvi** [AllTheMods/ATM-3#772]
## Expected Behavior
  the game should load to the main menu

## Current Behavior
game crashes during loading and I get a message:  
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)
## Log
https://gist.github.com/MrRolvi/c9d17d970e4ea820c7d1e7ba2caeca05

**Comment by Yamza** [comment]
Do this to fix your settings on twitch: https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
Also what pack version is this about? If it's 5.9.8d you have the wrong forge version.

**Comment by FallenEagle1** [comment]
Multiple things here. Looks like you are using twitch. The first thing is that twitch screwed up what version of forge the modpack is trying to use. It is using 2760, and it should be using 2715. Also, the java version is quite old, so going through that link yamza posted will help with that. Also, the ram amount is a little high. It is bodrderline to the point where it will start negatively affecting minecraft unless you are running a resourcepack.
