### ISSUE TITLE
Growth essence is impossible to craft

### ISSUE THREAD

**Issue by breadbull** [AllTheMods/ATM-3#773]
Playing the modpack in simplified mode and trying to make growth essence to make Draconic fusion crafting injectors.

## Current Behavior
Making growth essence requires Draconic level fusion crafting injectors, which are impossible to get since the injectors need to be crafted with growth essence.

## Possible Solution
Make the growth crystal be crafted with Wyvern fusion crafting injectors.

**Comment by FallenEagle1** [comment]
This was fixed in dev yesterday.
