### ISSUE TITLE
Botania flowers not generating

### ISSUE THREAD

**Issue by breadbull** [AllTheMods/ATM-3#774]
I was trying to find mystical flowers for Botania, looked for ages and couldn't find any. So I looked it up on JEI and found that WorldGen apparently has 0.00% chance of spawning the flower. Is this intended behaviour and the only way to get them now is through EnvironmentalTech's miner or a bug?

![untitled](https://user-images.githubusercontent.com/35699509/46073241-e8475e00-c1b6-11e8-8298-380111b09f88.png)

**Comment by FallenEagle1** [comment]
I dont know if they were set at all to spawn in the mining world, never check tbh. But they should spawn in the overworld, that should be default and it wasn't changed. If for some reason they are not showing up, there is also floral fertilizer that will spawn some around where you right click it on the ground. It's like bonemealing grass, except you get botania flowers instead.

**Comment by breadbull** [comment]
@FallenEagle1 For the record, they were spawning in the last version I was using (3.5.9.8d) however this behaviour has changed since I updated to the latest beta version (3.5.10.1beta).

P.S. The WorldGen still says 0.00% for the Overworld.
![untitled](https://user-images.githubusercontent.com/35699509/46080623-01f3a000-c1cd-11e8-818b-90595e4b4c72.png)

Some flowers also have that page missing entirely.
![untitled2](https://user-images.githubusercontent.com/35699509/46080713-3ebf9700-c1cd-11e8-86ba-62573a0ba2a8.png)

**Comment by SpeedSlider** [comment]
This appears to be a JEI integration issue. verified that botania flowers spawn in the overworld. They do not spawn in mining dim. All spawns will tend to be at surface level. Additionally, floral fertilizer can be crafted with bone meal and four vanilla dyes and some other dyes. Using floral fertilizer on grass blocks will spawn botania flowers.
