### ISSUE TITLE
[5.10.1] Abyssalcraft needs updated

### ISSUE THREAD

**Issue by leelawd** [AllTheMods/ATM-3#776]
When entering an abyssalcraft biome or portal, the server will promptly crash.

it was reported here and fixed.
https://github.com/Shinoow/AbyssalCraft/issues/322

**Comment by FallenEagle1** [comment]
I will make sure its updated in the new pack update. Should be, but will double check.

**Comment by Yoosk** [comment]
Every mod is always updated to latest version with pack update, unless it causes severe issues.
