### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by LZsomi** [AllTheMods/ATM-3#777]
## Expected Behavior

The game should look like minecraft.

## Current Behavior

The textures from afar look like absolute dodoo, the pack is still playable, this happens with most larger modpacks though. Take a look at the boat for example:
![image](https://user-images.githubusercontent.com/28954520/46257239-bbe15980-c4b6-11e8-860a-f6daf33ee164.png)
Or the foliage on the trees and the blocks:
![image](https://user-images.githubusercontent.com/28954520/46257276-3f02af80-c4b7-11e8-86d5-f623bc565108.png)
(Make sure to zoom in on the pic)

## Possible Solution

Wrong videocard, old java

## Steps to Reproduce

1. Idk how to reproduce this bug...

**Comment by LZsomi** [comment]
I changed the videocard but the problem still persists.

**Comment by Glendening** [comment]
Did you make sure your graphics settings in game are set to fancy? The screen shots just look like it is set to fast.

**Comment by LZsomi** [comment]
> Did you make sure your graphics settings in game are set to fancy? The screen shots just look like it is set to fast.

I tried that aswell but to no avail.

**Comment by Glendening** [comment]
Can you provide a copy of the options.txt file in your game folder please?

**Comment by FallenEagle1** [comment]
I would first update your java. It is using quite an old version, 1.8.0_51 and latest is 1.8.0_181. This link would be a good thing to go through. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
It might be something that deals with anti-aliasing, might be something to try toggling that to see if that fixes it as well.

**Comment by martmists** [comment]
Additionaly, see if changing antialiasing or mipmap depth changes anything.

**Comment by malagrond** [comment]
> Additionaly, see if changing antialiasing or mipmap depth changes anything.

Looks like either mipmap setting or anisotropic filtering. Probably mipmap.

**Comment by SpeedSlider** [comment]
This issue is being closed due to inactivity. For further troubleshooting of this issue please visit or discod Frequently Asked Question and/or Help Desk channel.
