### ISSUE TITLE
Immersive engineering creosote bucket dupe

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/ATM-3#78]
creating treated wood planks bucket of creosote was not used up could created as many planks as needed

**Comment by jc2xs** [comment]
Is your server using spongeforge?  If so that is your problem.  I've seen this reported for other packs as well.  All of them were using sponge.  I can't duplicate this on a pure forge server.

**Comment by OrdinatorStouff** [comment]
looks like for both iron and clay bucket the fluid is consumed properly now (vanilla crafting table)
