### ISSUE TITLE
ArrayIndexOutOfBoundsException from Forestry?

### ISSUE THREAD

**Issue by flann** [AllTheMods/ATM-3#781]
Launching from Twitch client, the latest release has an intermittent failure with an ArrayIndexOutOfBoundsException.
It happens at forestry.storage.models.ModelCrate.bake(ModelCrate.java:76)

## Expected Behavior

Umm. It shouldn't crash.

## Current Behavior

Crashes with an ArrayIndexOutOfBoundsException.

## Possible Solution

Sometimes restarting it works.

## Steps to Reproduce

1. Start All the Mods 3 from the Twitch Client using the native launcher
2. Wait for the crash
3. I'm also using Sphax resource packs, which may be contributing to the issue.
4. I maxed out memory (12G).

## Log

https://gist.github.com/flann/ae12a3e7ff6478ca28b565b582a2ba5d

**Comment by FallenEagle1** [comment]
I would start by updating your java and making twitch not use the native launcher. This link has a guide of how to step through this. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by flann** [comment]
Yeah, I usually don't use the native launcher. Switching to it seemed to make it a little more stable. I'm already using the latest Java 8.
FYI - Removing the Sphax resource packs seems to help.

**Comment by FallenEagle1** [comment]
From the log that you gave, it shows java 1.8.0_51 being used, that's why I mentioned it. Even if you have the latest java, minecraft won't use it if the native launcher is being used. it instead uses the prepackaged version it has.

**Comment by flann** [comment]
Okay, I switched over to the jar launcher and used the recommendations in the reddit link above. (Surprised the java packaged with the twitch client is that old). I used the recommended command switches and added optifine also.
Started up okay, so I added the Sphax resource packs back in.
Crashed in the exact same place (at forestry.storage.models.ModelCrate.bake(ModelCrate.java:76).
Gonna have to run without Sphax, I guess.
Seems to start okay about every other time with Sphax. I removed the resource packs and it started up okay without them a couple of times.
Still pretty anecdotal, but maybe enough info to chalk it up to a problem between forestry and sphax.

**Comment by Yamza** [comment]
Can you post a new log.

**Comment by flann** [comment]
Sorry, I didn't save that last one. I'll post another as soon as it happens again.

**Comment by flann** [comment]
Sorry for the delay. Finally happened again. Had been pretty stable for a while even after I added the Soartex Fanver Modded and Soartex Fanver Vanilla resource packs.
Here's the log:
https://gist.github.com/flann/ceed4156e83fe79697f9eefd8b19c52b
Again, ArrayIndexOutOfBoundsException in the exact same place.

**Comment by flann** [comment]
And here it is again with no resource pack and a fresh modpack install.

https://gist.github.com/flann/d2e7dea80280420c061dfd5bb1625a44

I'm going to try disabling foamfix since it shows up in the stack trace.

**Comment by flann** [comment]
Yeah, removing foamfix works...okay...as long as you don't have any resource pack. I'll give foamfix lawful a try.

**Comment by flann** [comment]
Don't see any recent lawful builds. So I set B:forceDisable=true in the foamfix config, which is supposed to have the same effect as using lawful.
Should this bug report be posted elsewhere? Is this a foamfix bug, then?

**Comment by FallenEagle1** [comment]
I think it's already known about, but can double check
