### ISSUE TITLE
[5.10.1] Server start up fails after starting complex Refined Storage recipe

### ISSUE THREAD

**Issue by ffgda** [AllTheMods/ATM-3#782]
I automated the crafting of the biggest Reborn Storage disk in a Refined Storage system, which involves a ~30 step recipe.
After I started the crafting process, the server crashed after a couple of seconds.
Ever since, I cannot get the server to start again.

## Expected Behavior
The server should still be able to start up.

## Current Behavior
The server start up eventually crashes with the message "ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)", apparently caused by a Refined Storage thread

## Possible Solution
Manually cancel the crafting process, if that's somehow possible? Anything else should be a Refined Storage issue.

## Steps to Reproduce
---

## Log
crash-report: https://gist.github.com/ffgda/cb18a0d58be83c4d8ca7b4bf7467fb1e
log: https://gist.github.com/ffgda/adf7c91e67ce0dddef1f1ec5a5ad2e17
The stall-report mentioned in the log simply contains the same thread dump as the crash-report.

**Comment by Darkere** [comment]
Did you change any configs? Default Refined storage configs should stop you from starting too complex recipes. 

For now, you can go to server.properties and change the max-tick-time. -1 for infinite or just something higher if you want to avoid freezing.

**Comment by ffgda** [comment]
> Did you change any configs? Default Refined storage configs should stop you from starting too complex recipes.

No, I did not change any configs. But I read that Refined Storage autocrafting was re-written in its current version (that is also used by the current version of ATM3), maybe that feature doesn't work as intended anymore.

> For now, you can go to server.properties and change the max-tick-time. -1 for infinite or just something higher if you want to avoid freezing.

I will try that and see if it let's the server start again, thank you.

**Comment by ffgda** [comment]
Setting max-tick-time=-1 did the trick. That one tick took more than 100000ms...
I'll open an issue on Refined Storage's side for that.

Thanks again @Darkere

**Comment by Darkere** [comment]
> No, I did not change any configs. But I read that Refined Storage autocrafting was re-written in its current version (that is also used by the current version of ATM3), maybe that feature doesn't work as intended anymore.

Nevermind, that config is not even in a release yet....
The feature was introduced in the latest auto crafting changes and worked fine in 1.6.4. Haven't seen it happen in 1.6.5 yet but also haven't tried.
