### ISSUE TITLE
Crash with hover on Filing Cabinet block with folder in it

### ISSUE THREAD

**Issue by generolas121** [AllTheMods/ATM-3#783]
## Current Behavior
Game crashes once the filing block containing empty phial folder is hovered over with a mouse.

## Steps to Reproduce
1. Place filing cabinet
2. Open it
3. Insert empty phial folder
4. Proceed to crash
5. Reload
6. Get back in game
7. Hover over the filing cabinet again
8. Proceed to crash, again.

## Log
https://gist.github.com/generolas121/9104bb1e82332102702e6cf9f53d9bf3

**Comment by martmists** [comment]
This should probably be reported on the [Real Filing Cabinet Github](https://github.com/bafomdad/realfilingcabinet) instead
