### ISSUE TITLE
Basic Capacitor Bank losing charge

### ISSUE THREAD

**Issue by SusiKette** [AllTheMods/ATM-3#784]
I noticed a few moments that my Basic Capacitor Bank is losing charge at about -2µI/t. All connected machines are idle and has full charge, so I believe this might not be intended. I tried messing around with configurations of the sides of the machines, but this seems to stop only after I disconnect the cable from the Capacitor Bank. Something is indeed draining the power, but taking the situation, this most likely is unintended.

Here is a picture of my current setup:
https://i.imgur.com/fsyZgQP.png

**Comment by Darkere** [comment]
Simple enderIO machines loose charge while Idle.

**Comment by FallenEagle1** [comment]
What you are describing all sounds like normal interactions. The simple enderIO machines lose a little bit of power while just sitting, and the upgraded ones do not. The amount lost sounds correct, and I believe says the amount lost in the gui for the Eio machines.
