### ISSUE TITLE
[5.10.1] Issue with Ender I/O conduits and Tinker I/O machines

### ISSUE THREAD

**Issue by Zettac** [AllTheMods/ATM-3#785]
I can't get Ender I/O conduits to connect to any of the Tinker I/O machines, specifically the Ore Crusher and Smart Output.

They don't connect at all, so I can't access the interface for input/extract or redstone signal.

As a side note: Thermal Expansion Itemducts and Servos will connect to but won't extract from the Tinker I/O machines. 

I'm using:
ATM-3 v5.10.1
Ender I/O v5.0.31
Tinker I/O v1.12.2

**Comment by Yoosk** [comment]
Everything seems to work properly in my dev instance.
[Check it out in this video.](https://dl.dropboxusercontent.com/s/5fhsloq11czq28g/2018-10-25%2013-56-53.mp4)
