### ISSUE TITLE
Minor Problems I've found with the modpack.

### ISSUE THREAD

**Issue by ErnieBernie10** [AllTheMods/ATM-3#79]
- When using an actually additions drill with max speed augments, the blocks become phantom where they still exist but you can't see them. It happens 50% of the time.
- When loading a world, playing for a while, exiting and try to load it again makes minecraft get stuck on loading world with 0% CPU usage.

These are some issues I've found that we're annoying. It would be great if they could be fixed. It could be just a problem for me, but I'd rather let you know anyway.

**Comment by OrdinatorStouff** [comment]
I was unable to reproduce the phantom block issue but could be related to lag, especially on a server.

As for the "loading world" issue -- that is something I've heard multiple reports of but have no idea how to track that down. Going to need some more time and luck figuring out what that is.

**Comment by DietmarKrause** [comment]
> When loading a world, playing for a while, exiting and try to load it again makes minecraft get stuck on loading world with 0% CPU usage.

I have this problem, too, from the very beginning of ATM3 and only in ATM3. And not internittend, always. There is no way to save /quit and restart a world without having to restart the pack from twitch.

**Comment by DietmarKrause** [comment]
perhaps related: https://github.com/MinecraftForge/MinecraftForge/issues/4297

**Comment by DietmarKrause** [comment]
perhaps related: https://github.com/MinecraftForge/MinecraftForge/issues/4353

**Comment by whatthedrunk** [comment]
Is this still an issue? I know I had the issue before but haven't noticed it recently.

**Comment by Boomflex** [comment]
Forge related issue.

Updated versions of Forge fixed.

**Comment by DietmarKrause** [comment]
still an issue in latest version
