### ISSUE TITLE
[5.10.1] Three recipes use the unavailable Tech Reborn Copper Cable

### ISSUE THREAD

**Issue by lhw** [AllTheMods/ATM-3#791]
## Expected Behavior
Tech Reborn copper cables should be oreDictionaried with IndustrialCraft2 copper cables as they are a direct replacement.

## Current Behavior
They are not

## Possible Solution
oreDictionary the copper cables or change the three recipes that make use of the Copper Cables/Insulated Copper Cables from Tech Reborn to use the IndustrialCraft2 ones.

## Detailed Description
The following recipes use the Tech Reborn cables:
1. @techreborn Alarm
2. @techreborn Incandescent Lamp
3. @industrialwires Small Jacob's Ladder

**Comment by Yoosk** [comment]
How did you obtain tech reborn cables in first place? Can't seem to be able to craft them usual way.

**Comment by Yoosk** [comment]
Never mind, now i see it, those recipes use cable that doesn't exist to craft.

**Comment by lhw** [comment]
Thanks for the quick fix.
It's probably a switch in techreborn to disable the duplicate cables in case industrialcraft2 is available.
The Jacobs Ladder had the same cables as well btw. The one from industrialwires. I don't actually know what the block does but I noticed it also uses those wires.

**Comment by Yoosk** [comment]
Seems that third one was resolved by some mod update, cause it looks just fine in my dev instance.
