### ISSUE TITLE
5.11.0 Wireless Crafting Terminal needs to be RV6

### ISSUE THREAD

**Issue by Russiandood** [AllTheMods/ATM-3#793]
## Expected Behavior
WCT should be working and should have the ability to use it.

## Current Behavior
Wireless Crafting Terminal is almost completely unusable and broken

## Possible Solution
Found that WCT was not updated to a compatible version of the updated version of AE2. RV version needs to match. AE2 is on RV6 in 5.11.0 and WCT is on RV5. 

## Steps to Reproduce
1. Create a Wireless crafting terminal
2. Link it to an AE2 System
3. Try to extract, insert or craft items. Will not work

**Comment by Yoosk** [comment]
That's why it is labelled as beta... always have to give few days before stable release.

Np and yes, you can manually update with unlocked profile, if you don't play on server.
