### ISSUE TITLE
Server Crashing on startup - Climate data issue?

### ISSUE THREAD

**Issue by sshawnsamuell** [AllTheMods/ATM-3#795]
Server is crashing on startup after upgrading from 5.10.1 to 5.11.1.
Server worked perfectly fine up until upgrading. 

## Expected Behavior
Server starts

## Current Behavior
Server doesn't start

## Log
https://gist.github.com/sshawnsamuell/fc127633b6eb6ce04575b7e40709ee5c

**Comment by FallenEagle1** [comment]
Looks like all of the mods were loaded on the server, so it crashed when trying to load the world. Have you tried letting the server just make a world to make sure it works? If so, it might be something with the world itself.
