### ISSUE TITLE
Mekanism Bins ID conflict

### ISSUE THREAD

**Issue by Atahal** [AllTheMods/ATM-3#797]
When i want to auto-craft an Ultimate Bin with Applied Energistics 2, the crafting process get stuck when it tries to craft the advanced Bin.

The crafting plan view from the computer never detects the Bin needed for the craft, even when they are in stock, so the next step is perma-scheduled.
The computer is able to craft the basic bin without issue.

My guess is, basic, advanced, Elite, and ultimate mekanism bins all share the exact same id (9278/6). Pretty sure this is not supposed to be like that.
Because of that, AE2 crafting plan doesn't know how to identify them.

Thanks

**Comment by Yamza** [comment]
You'd have to input a crafted one to make the recipe work properly since it needs to contain the correct NBT data.
