### ISSUE TITLE
Refined Stoarge, Client Crash If I type "@" or change sorting in the Grid

### ISSUE THREAD

**Issue by benjiben55** [AllTheMods/ATM-3#799]
All the mods Version v5.11.1 an Nitrado Server with max 4 Player ressource.

Hello,
when I type "@" or sort the items in Refined Storage the game crash immediately, with no "Crash LOG".
That is only happend when I have Environmental Miners in action.

To reproduce the obselence:
Start the Environmental Miner with each of them (4pieces)
Try to type "@" or change the sorting in the crafting grid or other grids from Enviromental.
The client crash immediately.

Possible Solution
I don't know :)
but I think, the fast in and output is a problem. 
I find a post but with no reason.

PS: 
Another Bug is also from Refined Storage.
When i connect a crafter with the crusher from Mekanism and start a process,
the hole world on a Nitrado Server is lagging so hard.
I cant do anything in the world.
When i mine the crafter, the world is ok again.

Thanks for help and sorry for my bad english knowlege.

**Comment by FallenEagle1** [comment]
Do you have a crash-report?

**Comment by benjiben55** [comment]
I have a link to the latest.log
but when I start to reproduce the error the log didn't write it.
https://gist.github.com/benjiben55/24c441f8953c4875614e91d0e9376c5b

**Comment by Darkere** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/2062
