### ISSUE TITLE
CTD On Start "Exception loading model for variant quantumstorage" (And others)

### ISSUE THREAD

**Issue by Tyler799** [AllTheMods/ATM-3#8]
Here's the log itself: https://paste.ee/p/V39MP

It seems to be crashing pretty far to the end of loading. Around "phase 4" or "phase 5" according to forge.

**Comment by OrdinatorStouff** [comment]
link returns "paste not found"
![image](https://user-images.githubusercontent.com/6283913/30012846-b58f8672-90f7-11e7-8130-91282100bd07.png)

If still an issue in latest version please re-report with new log
