### ISSUE TITLE
Mekanism PRC

### ISSUE THREAD

**Issue by greatmonkey** [AllTheMods/ATM-3#801]
When 2 liquid/gas go into the machine, no mater what type, it makes it unusable if they are not a craftable one.

## Expected Behavior

Ether prevent the liquids/gas mix into it or be able to dump what is inside it.

## Current Behavior

unable to use the machine

## Possible Solution

prevent the incorrect liquid/gas mix into it or add a shapeless crafting recipe to put the PRC in and you get a fresh one in return.

## Steps to Reproduce

1.put water in one tank
2.put oxygen in the other
3.slap  yourself for realizing you hook the cables up wrong
4.

**Comment by FallenEagle1** [comment]
That is not something we can change packside. That would be something that would have to be changed in the mod itself. BUT, it is still usable. Make a gauge dropper, and in the prc gui, click the gauge dropper on the liquid/gas you want to remove.
