### ISSUE TITLE
Cobalt 3x3 crafting recipe results in cobalt ore instead of cobalt block

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-3#805]
## Expected Behavior

Most metals in the game come in nugget, ingot, and block form. Each version taking nine of the previous to make by filling the 3x3 crafting grid. I expected that Cobalt would follow this recipe trend and allow me to make a cobalt block with nine cobalt ingots by filling a 3x3 crafting grid.

## Current Behavior

Instead of producing the expected cobalt block, it produces a cobalt ore block.
![lolcobalt](https://user-images.githubusercontent.com/241127/48668547-c5457600-eaa4-11e8-8f28-ec9af6061b9a.png)

## Possible Solution
Might need to register a recipe override to place back in the cobalt block recipe behavior over this.

## Steps To Reproduce Exactly As I Did
1. Obtain a stack of cobalt ore from a tier 1 void ore miner.
2. Use an enhanced SAG mill to process the cobalt ore into cobalt dust
3. Use a normal alloy smelter from Ender IO to cook the cobalt dust into cobalt ingots
4. Use a tinker's construct crafting table to try to make a cobalt block by filling the crafting grid with nine ingots in a 3x3 form.

ATM3 modpack v5.11.1 from Twitch launcher is being used.

**Comment by cjm721** [comment]
Issue comes from cobalt block having an ore dictionary reference of oreCobalt (it also has oreArdaite).

**Comment by SpeedSlider** [comment]
confirmed to still exist in 5.12.1

**Comment by FallenEagle1** [comment]
Fixed in 5.12.2
