### ISSUE TITLE
ATM3 crashing on start up

### ISSUE THREAD

**Issue by brodiechan** [AllTheMods/ATM-3#808]
Stuck on 1/7 : Loading - Constructing mods
3/294 : Contruction - Forge Mod Loader

Have already - Updated Java
Removed DiscordSuite
Added Max ram usage to 8G

Recent log: https://pastebin.com/0uzRHJpw

help x

**Comment by Yamza** [comment]
Didn't really need to repost tho..

Looks like you are using native launcher which forces old java `Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51`

First step would be to follow this guide: https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

If it still does not work at that point I would recommend reinstalling the mod pack and repairing minecraft (done by clicking on a modpack to open it's profile, click the ... under your twitch name, click "repair minecraft"

Also, if your computer only has 8GB of RAM you can not set it all, see the guide for why.

If it still doesn't work after all of this, change the install directory to somewhere not in the documents folder, C:/twitch would work for instance.

**Comment by SpeedSlider** [comment]
Issue due to inactivity. If this issue is still a problem make sure you are using the latest version of the pack before reopening/resubmitting. Additionally, these issues may get quicker resolution if you use the frequently asked questions and/or help desk on our discord channel.
