### ISSUE TITLE
[ATM3] [2.6] Inferium/Prosperity Ore not generating

### ISSUE THREAD

**Issue by savosdarkran** [AllTheMods/ATM-3#81]
It seems that Mystical Agriculture ore is not generating.  I think I read the config right that it's supposed to gen in the nether?  I was all over and couldn't find any.

Maybe I'm derping?

**Comment by DietmarKrause** [comment]
As far as i know both ores are deactevated in the config in the overworld. In the Nether they are rare (75% off by default). They only appear in the end. It would rather have them in some amount in the overworld as the mod-author wants it. 
https://github.com/BlakeBr0/MysticalAgriculture/issues/86

**Comment by DietmarKrause** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/86

**Comment by savosdarkran** [comment]
Thank you! :)

**Comment by whatthedrunk** [comment]
Yeah that's correct and once you get a few you should be golden.
