### ISSUE TITLE
Mekanism Energised Smelter produces NuclearCraft graphite bars

### ISSUE THREAD

**Issue by Peliex** [AllTheMods/ATM-3#813]
## Expected Behavior

Mekanism produces a disabled ingot from NuclearCraft instead of the correct Extreme Reactors ingot when put into an energised smelter or smelting factory from Mekanism

## Current Behavior

Obtain a completely useless ingot

## Possible Solution

Change the mekanism smelting recipe

## Steps to Reproduce

1.Create nuclearcraft graphite dust
2.place into a smelting factory
3.obtain wrong ingot
4.

## Detailed Description

Change the Mekanism recipe internally to generate the correct ingots

**Comment by Rithsagea** [comment]
What are you putting into the smelter?

**Comment by Yoosk** [comment]
I will take a look at that.

**Comment by FallenEagle1** [comment]
This inherently gets fixed in the update as graphite in the mods gets changed up some.

**Comment by SpeedSlider** [comment]
Confirmed this issue is fixed in 5.12.1. Issue resolved.
