### ISSUE TITLE
Mekanism's Wind Generators have a very low power output (7.5 RF/t)

### ISSUE THREAD

**Issue by NanobotZ** [AllTheMods/ATM-3#815]
As an early-game power generation I've decided to go for Mekanism's Wind Generators.
I was weirded out that those generators generate only 7.5 RF/t (max height), which IMO is very bad and basically not worth the materials used to craft them.

## Expected Behavior
Mekanism's Wind Generator making more than 7.5 RF/t on max height (probably like 60 RF/t)

## Current Behavior
Wind Generators making 7.5 RF/t

## Possible Solution
Bumping up the generation amount.

## Detailed Description
I've noticed that in the config it's set to 60 on max Y level, but I believe it's specified in Mekanism's Joules, and Joule : RF ratio is 8 : 1.
I guess it's just a mistake made by a person configuring Mekanism.

**Comment by FallenEagle1** [comment]
Nope, this is intended. Mek is fairly powerful for what it costs to get, so it was nerfed.

**Comment by DKnightADRI** [comment]
I believe this is intended. It was a known thing to be abused because of the low cost/high production rates. Not to mention they caused lag.
