### ISSUE TITLE
ATM3 v5.11.2 Orb of Transcendence not craftable

### ISSUE THREAD

**Issue by chengheipui** [AllTheMods/ATM-3#816]
## Expected Behavior
the orb of transcendence should be able to craft in celestial altar

## Current Behavior
i put all the ingredients in the altar and right clicked the celestial altar with resonating wand
but nothing happen im sure all the ingredients are match ,
in the recipe ,the soul shard's nbt only have [Tier5]
my soul shard is [tier5] [killcount:3200]  [bound:skeleton]
im not sure its the problem or not

## Detailed Description
the altar
![image](https://user-images.githubusercontent.com/34737547/49434709-bfaf9600-f7ef-11e8-9b14-1eede022397a.png)
recipe
![image](https://user-images.githubusercontent.com/34737547/49433986-2b90ff00-f7ee-11e8-8ccf-e671af611cd7.png)
![image](https://user-images.githubusercontent.com/34737547/49434046-482d3700-f7ee-11e8-822f-f12d76cf1000.png)

![image](https://user-images.githubusercontent.com/34737547/49434123-6d21aa00-f7ee-11e8-9b5f-8a831e52fff7.png)

![image](https://user-images.githubusercontent.com/34737547/49434087-5f6c2480-f7ee-11e8-906b-110eedb1a322.png)

**Comment by FallenEagle1** [comment]
Didn't get a chance to talk to you about it in discord, was away. Looks like the crafting syntax was updated and hasn't been changed yet. It will be fixed in the update.

**Comment by Yoosk** [comment]
Double checked, seems fine now.
![2019-02-26 23-14-10-javaw](https://user-images.githubusercontent.com/4502802/53450447-1e159a80-3a14-11e9-8896-c658d69298e6.png)
