### ISSUE TITLE
Not sure if a oversite or by design but no Aluminium Ore

### ISSUE THREAD

**Issue by chooven** [AllTheMods/ATM-3#82]
With all the changes in Ores and mods we have lost Aluminium in the oregen.  Thermal Dynamics has it but it is not defined configs. It used to be part of NoMan I believe and maybe Embers but now the only way I see to get it is TechReborn bauxite and a couple machines to process it.  It makes it pretty much impossible to make Aluminium-Brass for TiC modes in the early game since gold is hard to find and requires a higher level pick.

Also, Aluminium is require to make the blueprint in the Garden Cloche recipe

**Comment by whatthedrunk** [comment]
New chunks should have both versions of bauxite for now, thanks.
