### ISSUE TITLE
[ATM3 v5.11.2] Advanced Rockertry asteroids not customized by modpack, so you only get the defaults.

### ISSUE THREAD

**Issue by Greyhawk0** [AllTheMods/ATM-3#821]
## Expected Behavior
The default config for Advanced Rockery is supposed to be configured to provide asteroids with ores for non-vanilla ores. Currently, only redstone, iron, gold and rarely iridium ores can be obtained, which is the default settings in asteroidConfig.xml. One would expect adding more of the ores from "All the Mods".

## Current Behavior
No matter how good the observatory is, it will only generate default asteroids. Even though there are dozens of ore types in the pack.

## Possible Solution
Configure asteroidConfig.xml to make it worth while to mine asteroids. Since the cost of setting up the system is pretty high only then to find out that it is a waste.

## Steps to Reproduce
1. Build an observatory multi-block structure and power it (use lens and elite motor to get the best scan distance).
2. Launch a optical satellite to get at least 100 distance data on a data stick.
3. Upload the data to the observatory (via data stick in the data bus in the multi-block), turn it on and wait for night.
4. Scan asteroids and notice the lack of variety.

## Log
No crash

## Detailed Description
I propose adding more asteroids of varying sizes and ores, would really help make Advanced Rocketry a better experience. The main points of that mod are space travel, building a station, building a capital ship, mining asteroids and extracting gasses from certain planets. So by not configuring asteroidConfig.xml, a good chunk of the mod is useless in this pack. It takes a lot of time and resources just to go to one asteroid for mining, so it would be nice if the rewards were higher and more varied.

Ideas include adding these ores: Copper, Tin, Silver, Lead, Uranium, Titanium, Aluminum, Magnesium, Boron, Lithium, Inferium, Prosperity and Dimensional Shards. Rarer ores require better range observatory, show up less often and are less massive than more common ores for balancing.

**Comment by FallenEagle1** [comment]
Some of the asteroids were customized now in remix, and atm3 isnt getting any more big updates besides updates/fixes.
