### ISSUE TITLE
RefinedStorage auto complete recipe kick 

### ISSUE THREAD

**Issue by aolsen96** [AllTheMods/ATM-3#822]
## Expected Behavior

It should put the recipe in the crafting grid

## Current Behavior

it kicked me from the server
gives me the error: Internal Exception: java.lang.illegalArgumentException: Payload may not be larger then 32767 bytes

## Steps to Reproduce

1.Auto complete the recipe for a chest(there are more)
2.get kicked

**Comment by Yamza** [comment]
Would probably help to specify what recipe it was that did this, but I'm going to assume I already know the answer here. Any recipe using a sapling (or other wood derivative) causes this issue in RS. No solution is known so you'll have to avoid doing that.

**Comment by SpeedSlider** [comment]
This is now a know issue with the mod when using the oredict option when creating the pattern for items that have a significant number of oredict options (e.g. planks). This issue can avoided by specifying a single type and not clicking the oredict option when making the pattern (e.g. use oak planks in the recipe and make sure oredict is unchecked).
