### ISSUE TITLE
OpenComputers NanoMachines CRASH on DisintegrationBehavior

### ISSUE THREAD

**Issue by ro5490** [AllTheMods/ATM-3#823]
Pretty much you crash and then get locked out of a SP/MP server if you activate the "DisintegrationBehavior" effect via OpenComputers Nanomachines.

## Expected Behavior
Not too sure, but if you activate DisintegrationBehavior it should do something normal not crash?

## Current Behavior
You immediately crash on DisintegrationBehavior activation and then cannot reconnect to the server, either SP or MP til your playerdata OCNM file is deleted.

## Possible Solution
Remove DisintegrationBehavior?

## Steps to Reproduce
https://streamable.com/4s8d9
1. Make an OpenComputer setup that has a wireless card in (also install OpenOS and OPPM onto the computer, and use OPPM to install NN using " oppm install nn "
2. Make some OpenComputer Nanomachines and use them on yourself
3. Check if the DisintegrationBehavior effect is listed for your current nanomachines with /oc_nanomachines   if not then drink some Grog and try again from 2.
4. If it is, use the OpenComputer to "turn on" the correct numbers to activate DisintegrationBehavior by using nn commands (example: nn on 11)
5.???
6.Crash
7. Open playerdata and delete .OCNM to get back into the server (this removes your nanomachines data)

## Log
https://gist.github.com/ro5490/9b8216121dcd87873b1cc0929570343e

**Comment by martmists** [comment]
Please [open an issue](https://github.com/MightyPirates/OpenComputers/issues/new) on the OpenComputers repository instead, this isn't something we can fix on pack level.
