### ISSUE TITLE
Embers Wildfire Core is not craftable.

### ISSUE THREAD

**Issue by nowifi4u** [AllTheMods/ATM-3#825]
Embes Wildfire Core which is used for creating the "Orb of Transcendence" is not craftable. 
Reason: Embers Copper Plate used in the recipe is not craftable (using Embers Hammer and Embers Stamper give ThermalFoundation Copper Plates)

Modpack: All The Mods 3 ver. 5.11.2

There is a workaround though (while Uncrafting Table is even a thing):
1. Obtain Uncrafting Table from TwilightForest.
2. Craft something with available Copper Plates (from ThermalFoundation).
3. Uncraft that item in Uncrafting Table, but use small arrows in the bottom left corner to select a recipe with Embers Copper Plates.
4. Use Ore Dictionary Exchanger from IndustrialForegoing to exchange ThermalFoundation Copper Plates into Embers Copper Plates, provided you placed a previously made Embers Copper Plate into "Examples" slot of the machine.

_Originally posted by @nowifi4u in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ1MDE2MDk1Mw==/timeline/issue_comment#issuecomment-450160953_

**Comment by FallenEagle1** [comment]
Something I forgot to ask. Is this on a server? If so, does trying to make it in singleplayer result in any differences?

**Comment by FallenEagle1** [comment]
Bug in the mod, will be fixed in update.
