### ISSUE TITLE
Download not working,

### ISSUE THREAD

**Issue by Cryillic** [AllTheMods/ATM-3#827]
Heya, 
I have just downloaded 'All The Mods 3' from the twitch.tv app, (thing) and loaded the minecraft launcher, I clicked play and everything worked. but then about halve way through the initial first time start up it gave me this message ;
![image](https://user-images.githubusercontent.com/46247631/50540896-5de61000-0b92-11e9-8a4e-d7688bb19845.png)

Ive allocated as much RAM as i can to the java.exe, as much as 7GB.
What should i do?

Sincerly - Cryillic.

**Comment by FallenEagle1** [comment]
7 Should be fine. I would guess that wherever you are changing it, the application is not respecting it for some reason. To help with this and see if it fixes the issues, follow the instructions in this link:
https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
It has a number of changes to help run modpacks on computers. In there it covers ram allocation as well, but it also has checks for java (to make sure you don't have 32 bit java) If 32 bit java is used, it limits the max ram to 2 Gb.

**Comment by Cryillic** [comment]
> 
> 
> 7 Should be fine. I would guess that wherever you are changing it, the application is not respecting it for some reason. To help with this and see if it fixes the issues, follow the instructions in this link:
> https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
> It has a number of changes to help run modpacks on computers. In there it covers ram allocation as well, but it also has checks for java (to make sure you don't have 32 bit java) If 32 bit java is used, it limits the max ram to 2 Gb.

Thanks for the help
