### ISSUE TITLE
"ForgeDownloadURLNotFound"

### ISSUE THREAD

**Issue by CoryJS** [AllTheMods/ATM-3#828]
## Expected Behavior

The server should load up and install forge, etc, etc.

## Current Behavior

The ServerStart.bat can't find "ForgeDownloadURL" and then closes even though there's a weblink to forge in the folder.

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

![image](https://user-images.githubusercontent.com/40577274/50563487-2653a100-0d15-11e9-89d5-130c63fcf711.png)

**Comment by Yamza** [comment]
Try downloading the forge version it is looking for and placing it in the folder. You can find the version it wants in the settings.cfg file.

**Comment by Yoosk** [comment]
Our latest server packs are updated and working fine. Forge universal installer is shipped with said pack and there's no need to download it.

**Comment by Dragoholic** [comment]
I am having the exact same problem. @Yoosk, I am not sure that's helpful advice since I am having trouble too and your response does not offer any solutions, could you be more specific on how to fix this?

**Comment by Yoosk** [comment]
Is it run on windows or linux machine?

**Comment by Dragoholic** [comment]
Windows

**Comment by Yoosk** [comment]
and version of the pack?

**Comment by Dragoholic** [comment]
I downloaded the latest server file, from here: https://minecraft.curseforge.com/projects/all-the-mods-3/files/2521709. I am running the latest version of All the Mods 3 through the Twitch app, and that version is 5.11.2

**Comment by Yoosk** [comment]
That's not latest, its outdated by at least 20 versions and almost a year.
That is the latest. https://minecraft.curseforge.com/projects/all-the-mods-3/files/2639211

**Comment by Dragoholic** [comment]
Okay, wow, thanks! Although now I have run into the problem of "Could not find "eula = true" in eula.txt file.

**Comment by Dragoholic** [comment]
Okay, fixed that, sorry, the eula.txt file popped up later.
