### ISSUE TITLE
No Diamonds in the Mining Dimension?

### ISSUE THREAD

**Issue by HolyUnix** [AllTheMods/ATM-3#829]
No Diamonds in the Mining Dimension, there are only Emeralds spawning

Is this intentional? Because the config is changed so Diamonds don't spawn, but it just seems kinda unbelievable.

**Comment by FallenEagle1** [comment]
Where are you seeing this? The only thing I am seeing is this line in the aroma dimension json, and it is disabled.
![image](https://user-images.githubusercontent.com/22630113/50694253-9eacb180-0ff6-11e9-8dd7-c9dbaf6cd54a.png)
I'll do some quick testing, but I hadn't seen issues with getting diamond before.

**Comment by HolyUnix** [comment]
My bad, I overlooked the enabled part, but I still can't find ANY diamonds at all in the Mining Dimension. Might be a bug, idk.

**Comment by PrexorDev** [comment]
used Digital Miner in Mining World got like half a stack of diamonds so far
