### ISSUE TITLE
[v2.7] Reset configs for Water Strainer

### ISSUE THREAD

**Issue by Ruuubi** [AllTheMods/ATM-3#83]
Hey. The config files for water strainer are outdated. Please make sure you delete them before publishing the next update so the default ones are generated.

You may also remove the recipe change from Crafting Tweaks for the Garden Trowel and the net.
The default recipes were changed and should no longer conflict with recipes from Chisel and Rustic.

Thank you.

**Comment by whatthedrunk** [comment]
Fixed in the next update, thanks!
