### ISSUE TITLE
Resplendent Prism [Astral Sorcery] broken in 1.9.4

### ISSUE THREAD

**Issue by arketec** [AllTheMods/ATM-3#830]
The enchantment enhancments are broken in the version of AS installed in ATM3. See this issue:

[Resplendent Prism +X Levels to all Existing Enchantments not being applied](https://github.com/HellFirePvP/AstralSorcery/issues/841)

## Expected Behavior

Prism should increase enchantment level on gear

## Current Behavior

Nothing happens

## Possible Solution

Updating AS to the latest version will fix this issue as HellfirePVP has already fixed this.

## Steps to Reproduce

1. Create Resplendent Prism's in AS until you get +X to all existing enchantments

## Detailed Description

Simply update AS and this issue will be fixed. Thanks!

**Comment by FallenEagle1** [comment]
Mod is updated in the modpack update, the modpack is just going through testing. So you will see the updated Astral Sorcery soon.

**Comment by arketec** [comment]
sweet, thanks!
