### ISSUE TITLE
[5.11.2] Interfaces emptying themselves after a few seconds

### ISSUE THREAD

**Issue by xhatz** [AllTheMods/ATM-3#831]
Hello!

Basically the title says it all, when I open some interfaces (example are the boxes from Immersive Engineering or the Thaumcraft tables), the items in it are shown, but then after a few seconds, all the items disappear. I either have to click on an invisible item (empty slot but occupied previously by an item) to make everything appear again, or leave and join the interface again...

Thank you!

**Comment by FallenEagle1** [comment]
Is this on a server, have you tried relogging, what have you tried? If it is on a server, have you tried the same thing in singleplayer?

**Comment by Yamza** [comment]
Would recommend following this guide if you haven't yet. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by xhatz** [comment]
> Is this on a server, have you tried relogging, what have you tried? If it is on a server, have you tried the same thing in singleplayer?

Hey! This is on a multiplayer server, and I have optifine on my client, I didn't try without or on singleplayer yet...

**Comment by FallenEagle1** [comment]
I would see if the new updates have fixed this, if this isn't already resolved
