### ISSUE TITLE
[5.11.2] Trashcan Icon Blocking OpenBlocks Menu

### ISSUE THREAD

**Issue by Stannks** [AllTheMods/ATM-3#835]
## Expected Behavior

You should be able to select the 'Auto eject' checkbox in the OpenBlocks Auto Anvil menu.

## Current Behavior

You are not able to select the checkbox in the OpenBlocks menu because the trash icon is perfectly covering it. Image demonstrating issue: https://imgur.com/a/w0LkVIh

## Possible Solution

Toggle whatever overlay is covering the checkbox.

## Steps to Reproduce

1. Right click the Auto Anvil when placed in the world from OpenBlocks.
2. Attempt to select 'Auto eject' from the bottom-most side tab.

## Solution

Have a shortcut/button to temporarily disable the overlay that controls the trash can.

**Comment by FallenEagle1** [comment]
Fixed in 5.12.2
