### ISSUE TITLE
Server crash on boot 

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [AllTheMods/ATM-3#837]
Server starts ok then after a minute or two crashes and continues in a crash loop. 
https://pastebin.com/vVseF531
Am running sponge however it was working fine until an automatic restart occured. After that it goes into a start - crash loop. No changes were made to anything and a rollback of the world was tried but no change to the crash loop.
!--- For game help join the discord and ask there-->

## Expected Behavior

Server starts and players can join like normal

## Current Behavior

Starts wait 2 mins then crash

## Steps to Reproduce

1. None available. Not even sure of it's cause.
2.
3.
4.

**Comment by martmists** [comment]
Have you tried removing sponge? I am aware you said it worked fine before, but do try disabling it as it might be one of the plugins (or even just sponge) causing this.

**Comment by nzminecraftDOTcom** [comment]
Managed to solve it. Removing sponge did solve it as it does most of the time, however it is now working again with the exact same configuration set up, I am not entirely sure what happened. I did update to the latest version of forge (newer than what the pack uses) and believe that there may have been an update or something. 
Issue closed.
