### ISSUE TITLE
Mobs don't spawn in certain world conditions

### ISSUE THREAD

**Issue by minecraftsteve** [AllTheMods/ATM-3#838]
## Expected Behavior
I created a Realistic world and settled in Badlands biome. I thought everything would be normal like when night falls monster will spawn.

## Current Behavior
When it is the world's nighttime, monsters don't almost at all spawn despite the darkness (animals pre-spawned I think), and neither do they when it is JourneyMap's time (JourneyMap's time doesn't synchronize with the world's, but still indicates day and night).

## Possible Solution
I think it is either something in the game files that can be changed to stop this or my computer has something messing with the game. (I believe the first one though)

## Steps to Reproduce
1. Create a Realistic world
2. Find a Badlands or other biomes (I live in Badlands)
3. Wait till night
Note: Might not happen to all players.

## Detailed Description
I suuggest some game files related to mob spawning be changed (or maybe just tell me how to alter them)

**Comment by Yamza** [comment]
There is no way to alter mob spawning. What has likely happened is that the mobs have hit the spawn limit by spawning in caves near/below you. You can find the recommended solution at the end of this guide https://www.reddit.com/r/allthemods/comments/9ugu6s/server_profiling/

**Comment by minecraftsteve** [comment]
I do not find any in the caves either. The biomes nextby also gets this.

**Comment by minecraftsteve** [comment]
And I'm not sure if I understand that guide.

**Comment by Yamza** [comment]
"Add these commands to command blocks and set them up with a timer to run at whatever time period you prefer, 1 hour is a good place to start."

`cofh killall`
`cofh killall item`
`kill @e[type=xp_orb]`

**Comment by minecraftsteve** [comment]
I'm in singleplayer by the way. Will it work?

**Comment by Yamza** [comment]
Yes. You need to have cheats enabled to do this of course.

**Comment by minecraftsteve** [comment]
It worked! Thank you.
