### ISSUE TITLE
Tech Reborn machine frame should be disabled. atm3 v. 2.7

### ISSUE THREAD

**Issue by meerple** [AllTheMods/ATM-3#84]
Hi. A ring of iron plates makes a Tech Reborn machine frame, which can't be used to make IC2 machines. The IC2 machine frame can be used for TR machines. The recipe for TR machine frames should be removed.

I added recipes.remove(<techreborn:machine_frame>); to the CT script and that fixed it I think.

**Comment by whatthedrunk** [comment]
Added to the next update, let me know if anything else comes up to add, thanks.
