### ISSUE TITLE
Server Crash Report

### ISSUE THREAD

**Issue by ThatDeathKnight** [AllTheMods/ATM-3#842]
## Expected Behavior
The server crashes on load

## Current Behavior
The server shouldn't crash on load

## Possible Solution
Not sure, looks like an AE2 auto crafting issue?

## Steps to Reproduce

1. Hit start on server
2. Wait
3. Crash

## Log

https://gist.github.com/ThatDeathKnight/2d960ecf019a03316dd84cbaae7fa114

**Comment by Yamza** [comment]
Your RAM is capping out `1565309416 bytes (1492 MB) / 2983723008 bytes (2845 MB) up to 2983723008 bytes (2845 MB)`

Are you using serverstart to run the server, it should be setting 5GB min by default.

**Comment by ThatDeathKnight** [comment]
Fixed, cheers dude
