### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by VentusKami** [AllTheMods/ATM-3#843]
## Steps to Reproduce

1.
2.
3.
4.

## Log

https://p.teknik.io/h4KFB

**Comment by VentusKami** [comment]
how do I fix this

**Comment by Darkere** [comment]
>C:\Users\ventu\Documents\Curse\Minecraft\Instances\All the Mods 3\config\enderstorage.cfg (The process cannot access the file because it is being used by another process)

Easiest way is probably to just restart you PC. 

Also please post Crashlogs to a website like pastebin.com and link it here. That crashreport is also missing important information.

**Comment by Yoosk** [comment]
Please provide full log, otherwise I'll be forced to close issue as it is invalid.

**Comment by SpeedSlider** [comment]
Due to inactivity and improperly filled out issue report, you did not follow the prompted field to provide necessary information, this issue is being closed.
