### ISSUE TITLE
Downloaded ATm3 to .minecraft mods folder, still won't show up in game

### ISSUE THREAD

**Issue by xoxEmilyLovelyxox** [AllTheMods/ATM-3#844]
## Expected Behavior

I am unsure why ATM isn't showing up in game. It is the 1.12.2 version, right? If so, it should definitely be showing up

## Current Behavior

It doesn't show up in game

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
I'm not even sure what you mean not showing up. Please describe things. How/where are you getting the pack? Also, if you are messing with the .minecraft folder, I'm going to assume that you are trying to use the vanilla launcher. I would strongly recommend using a launcher that is meant for modded minecraft, it makes things much easier. Two options that we support are Twitch and Multimc. Instructions on how to use these can be found here: https://www.reddit.com/r/allthemods/comments/970n2e/how_to_install_twitchmultimc/

**Comment by PulseBeat02** [comment]
Are you using optifine?

**Comment by SpeedSlider** [comment]
Insufficent information provided in issues please follow the format and prompts for information in each section. Additionally, it appears you tried downloading the mod zip file directly to your vanilla client mod folder. Based upon my understanding this will not work and you need to use a client like twitch or MultiMC. Installation methods can be found in our Frequently Asked Questions discord channel or the link provided in the initial response.

**Comment by SpeedSlider** [comment]
Preliminary troubleshooting steps and recommendations provided. Based upon inactivity and insufficent information provided this issue is being closed.
