### ISSUE TITLE
"Could not reserve enough space for object heap" On Server with Plenty of Ram

### ISSUE THREAD

**Issue by Isaiahfeldt** [AllTheMods/ATM-3#846]
Currently trying to run All the Mods 3 on a vps server I rent.

Unzipping and installs fine but when I launch the **ServerStart.bat** I get the **error** as shown here
[Gyazo Screenshot](https://i.gyazo.com/3e0a32e81cedc548556c609cf1940d9b.png)

> Administrator: All The Mods 3 Server Running
Starting All The Mods 3 Server...
DEBUG: Attempting to execute java-Xmx4096M -Xms 2048M -d64 -server [DEFAULT settings.cfg stuff]
14.23.5.2815-universal.jar" nogui
Error occurred during initialization of UM
Could not reserve enough space for object heap
WARN: All The Mods 3 Server was stopped (possibly crashed>...
At 20190306:141357 Server has stopped.
Server has 1 consecutive stops. each within 600 seconds of eachother...
Server will re-start automaticallyx in less than 30 seconds...
Restart now 〈Y〉 or Exit 〈N〉 [Y,N]?

My machine has **7GB** of ram and I'm only trying to start the mc server with **4GB**. 

Things I've tried that did not work:
- I do not have a _JAVA_OPTIONS variable set in my system settings. 
- Restart the VPS/machine
- Check available ram to see I have enough
- Updated my Java to the newest version
- Use 64bit Java
- Google this issue
- Use an older server version of All The Mods 3

Here is the start log
[serverstart.log](https://github.com/AllTheMods/ATM-3/files/2938168/serverstart.log)

**Comment by Yamza** [comment]
5GB is recommended, have you tried setting to that?

**Comment by Isaiahfeldt** [comment]
> 5GB is recommended, have you tried setting to that?

Yes

**Comment by Yamza** [comment]
Open a command prompt on the server, type in `java -version` and copy the full result here please.

**Comment by Isaiahfeldt** [comment]
> C:\Users\Administrator\Documents\Servers\GameServers\Minecraft\AllTheMods3>java
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by FallenEagle1** [comment]
Vps server, who is the host?

**Comment by Isaiahfeldt** [comment]
Yes i use [NFO Servers](https://www.nfoservers.com/virtual-dedicated-private-server-rentals.php)

I also just tried running a FTB server with 5GB with no problem so I know I can normally run these type of things lol

**Comment by FallenEagle1** [comment]
Try removing the newsize and newratio java arguments in the settings.cfgfilr

**Comment by Isaiahfeldt** [comment]
Yeah that didn't change anything

> Starting All The Mods 3 Server...
DEBUG: Attempting to execute [ java -Xmx5G -Xms2G -d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -Dfml.readTimeout=90 -jar "C:\Users\Administrator\Documents\Servers\GameServers\Minecraft\AllTheMods3\forge-1.12.2-14.23.5.2815-universal.jar" nogui ]
Error occurred during initialization of VM
Could not reserve enough space for object heap
WARN: All The Mods 3 Server was stopped (possibly crashed)...
At 20190306:160409 Server has stopped.
Server has 1 consecutive stops, each within 600 seconds of eachother...

This is a real bummer

**Comment by Isaiahfeldt** [comment]
I manually set -Xms to 900M and it passed the initial fail point but eventually crashed again. Not sure why it thinks my machine only has that much,

**Comment by Isaiahfeldt** [comment]
Okay so I purchased more ram from my provider to increase the total to 9GB. **And without changing any settings** the server is **magically starting to work**. I do not understand why adding two additional gigs of ram that it doesn't even touch helps

If you need anymore sort of info from me feel free to ask
