### ISSUE TITLE
hunger bug after updating

### ISSUE THREAD

**Issue by Acidboy92** [AllTheMods/ATM-3#847]
After updating from a few previous versions which did a new install, after copying saves across as soon as I load up that save my hunger bar will empty in a few seconds from full even after getting my nutrition up too 100%

**Comment by Acidboy92** [comment]
Still need help with this issue as it makes the game unplayable

**Comment by Yamza** [comment]
Known issue with the current version of Nutrition currently. Will need a pack update to fix it.

**Comment by ReiDaTecnologia** [comment]
And Yoosk already did it in the dev.

**Comment by Yoosk** [comment]
In dev for remix. Not for legacy.

**Comment by Acidboy92** [comment]
can this be fixed manually by installing a previous version of nutrition

**Comment by Yamza** [comment]
That or updating, only works for single player though unless the server owner and all players update for a server situation.

**Comment by Acidboy92** [comment]
it is only single player so that's not a problem, thanks to all.

**Comment by SpeedSlider** [comment]
Based upon review of comments this issue is resolved for the specific player and is not intended to be resolved for ATM3 due to legacy status of pack.
