### ISSUE TITLE
Corrupted Chunk

### ISSUE THREAD

**Issue by PsiOvertake** [AllTheMods/ATM-3#85]
Good evening!

We're using the latest version of ATM3 and are experiencing a corrupted chunk, in that Refined Storage controller causes a crash when right-clicked, many Extra Utilities 2 machines will have a red X on them, items placed on the walls (lanterns, drying racks) will be turned sideways, itemducts don't appear connected to each other, Iron Chest chests won't appear until moused-over, etc.

I read at one forum that it was caused by the Pam's Harvestcraft Presser, which was a new item added to the base between the corrupted world and an older uncorrupted save.  We removed it, saved the world, and loaded it back up, but the issue persists.

I believe the crash error message is that the controller was in an invalid energy state, but I can get a more exact error message, or anything else that might be helpful, if additional info is needed.

Thanks!!

**Comment by PsiOvertake** [comment]
Issue persists with the latest update.

**Comment by PsiOvertake** [comment]
The chunk goes back to normal after removing Pam's Harvestcraft Presser and Market.

**Comment by OrdinatorStouff** [comment]
I think this was a know problem with some Pam's blocks and I think that Covers has made a PR to help fix that from happening going forward. IF you see more issues with Pams' blocks causing trouble please report them again. 

thanks~
