### ISSUE TITLE
Errors breaking EnderIO Enlightened Fused Quartz in creative

### ISSUE THREAD

**Issue by nanonator102** [AllTheMods/ATM-3#850]
## Expected Behavior
The expected behaviour is for the block to break.

## Current Behavior
If the block is originally placed in creative then broken in creative, the block will 'ghost' and appear invisible while still physically being there. Server may also crash (but does not always). Breaking the glass in survival breaks it as expected. Placing and/or breaking the block in survival works fine, placing the block in survival then breaking it in creative works fine and placing the block in creative and breaking it in survival also works fine.

## Steps to Reproduce
NOTE: THIS WAS DONE ON A DEDICATED SERVER RUNNING MODPACK VERSION 3.5.12.0
1. Place enlightened fused quartz in creative mode
2. Attempt to break in creative mode

## Log
https://gist.github.com/nanonator102/ad5fe9f872167ede1c7b179cfc88d9b3
This log contains both the crash report generated by the server and the error that was shown in the console when attempting to break the glass.

**Comment by SpeedSlider** [comment]
Verified this issue does not occur in single player by placing all 16 varients and breaking while in creative mode the whole time. Unable to test in server instance at this time.

**Comment by FallenEagle1** [comment]
Unable to reproduce, would be curious to see if it still occurs in latest (5.12.2) modpack version
