### ISSUE TITLE
PSI mod crashes game on world load

### ISSUE THREAD

**Issue by mario610** [AllTheMods/ATM-3#851]
## Expected Behavior

world should load without crashing

## Current Behavior

Crashes on world load

## Steps to Reproduce

1. Load into world
2. It just crashes
3.
4.

## Log

https://pastebin.com/WMRsrHTw

**Comment by FallenEagle1** [comment]
I see your github issue that is on the psi github as well. Vazkii/psi#492 
This was also fixed in the mod already, as shown with Vazkii/psi#485 so when the mod is updated and the modpack is updated it will be fixed
