### ISSUE TITLE
Unable to open the all the mods's multiplayer server

### ISSUE THREAD

**Issue by mangostart** [AllTheMods/ATM-3#852]
I use twitch in to the multiplayer server I built ,but i show this
 **The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error**

[crash-2019-03-03_15.51.26-client.txt](https://github.com/AllTheMods/ATM-3/files/3023349/crash-2019-03-03_15.51.26-client.txt)
I can't find which mods is wrong.

**Comment by Yamza** [comment]
Are you using Sponge on your server?
Also you're using old java and your RAM is set to the lower end of what works
`	Java Version: 1.8.0_51, Oracle Corporation`
Recommend going through this: https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by mangostart** [comment]
I didn't use Sponge.
I follow the method you gave,but it still error
[crash-2019-03-30_00.22.13-client.txt](https://github.com/AllTheMods/ATM-3/files/3023552/crash-2019-03-30_00.22.13-client.txt)

**Comment by Lartza** [comment]
You didn't follow the instructions fully, you are still using the native launcher.

As for the crash, it's fixed in Advanced Rocketry 1.12.2-1.4.1-114. As a workaround that doesn't involve updating you can set PlanetSkyOverride, StationSkyOverride, and overwoldSkyOverride to false and it should stop the crashing.

**Comment by mangostart** [comment]
I found that I modified it, but it will still using the native launcher.
i was set PlanetSkyOverride, StationSkyOverride, and overwoldSkyOverride to false.
[crash-2019-03-30_00.23.13-client.txt](https://github.com/AllTheMods/ATM-3/files/3025064/crash-2019-03-30_00.23.13-client.txt)

**Comment by Yamza** [comment]
Still have old java being used. Better double check those settings are set to false.

**Comment by mangostart** [comment]
ok. thank u
