### ISSUE TITLE
Pressure plate remains powered

### ISSUE THREAD

**Issue by legitairsoft123** [AllTheMods/ATM-3#853]
Wooden pressure plate should become unpowered when there is no longer an item on it. However, when an item is picked up the plate remains powered. Bug is not due to a block update. Does not matter if taken by a machine (endoflame and charcoal in my instance) or by a player. Does not matter if dropped on by a machine (open crate in my instance) or by a player.

Steps to reproduce:
1. Place wooden pressure plate
2. Drop item on pressure plate
3. Pick up item from pressure plate

**Comment by SpeedSlider** [comment]
Placed various items on a wooden pressure plate and removed them manually, via vacuum hopper, and endoflame. all instances appeared to work. Additionally, I used a redstone lamp, mana spreader, mana pool, and redstone lamp to verify status of wooden pressure plate. It should be noted that I used an oak pressure plate and did not verify any other form of pressure plate. If this is an issue please provide more information including pack version, single or multiplayer, etc. in new issue.
