### ISSUE TITLE
Server doesn't want to load sponge 

### ISSUE THREAD

**Issue by coolkid787** [AllTheMods/ATM-3#854]
Even with Sponge enabled through config, it refuses to load it up. I have the correct version and it's in mods folder. 

## Steps to Reproduce

1. Put sponge in mod folder
2. enable it with config
3. load up server
4. The custom launcher gives this error.

**** ERROR ****
SPONGE has been enabled in settings.cfg but necessary files were not found…

To use Sponge:

“MODS” folder must have a SpongeForge JAR matching Forge 2768
**** PLEASE NOTE ****
YOU MAY NOT RECIEVE SUPPORT from modpack devs if you use Sponge
Use at your own risk OR DISABLE SPONGE in settings.cfg

^ When I press to continue, it just shuts down the server.

**Comment by FallenEagle1** [comment]
Do you have a log?

**Comment by martmists** [comment]
Make sure to install sponge on the server **MANUALLY**
This is not quite explained explicitly, but sponge still needs to be installed for it to be loaded.

**Comment by coolkid787** [comment]
> Make sure to install sponge on the server **MANUALLY**
> This is not quite explained explicitly, but sponge still needs to be installed for it to be loaded.

Do you mean having all the files already fully loaded? How would I manually install it?

**Comment by coolkid787** [comment]
> Do you have a log?

It doesn’t crash, it just doesn’t load it up, I can’t find anything saying it cannot load

**Comment by FallenEagle1** [comment]
Just a log of any sort, a server startup or a latest log.

**Comment by coolkid787** [comment]
> Just a log of any sort, a server startup or a latest log.
When I get home, I’ll send it over

**Comment by martmists** [comment]
@coolkid787 simply head over to the [SpongePowered Downloads](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2), download the jar and put it in the mods folder

**Comment by coolkid787** [comment]
> @coolkid787 simply head over to the [SpongePowered Downloads](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2), download the jar and put it in the mods folder

I did that and it still doesn’t load up

**Comment by martmists** [comment]
Make sure to prefix the jar name with an underscore to make it load before any coremods

**Comment by coolkid787** [comment]
> Make sure to prefix the jar name with an underscore to make it load before any coremods

So like SpongeForge_ or _SpongeForge

**Comment by coolkid787** [comment]
> Just a log of any sort, a server startup or a latest log.
Here's the log;
[serverstart.log](https://github.com/AllTheMods/ATM-3/files/3026062/serverstart.log)

**Comment by FallenEagle1** [comment]
The issue called out in that log is that the sponge jar file was not being found in the mods folder like expected. While you are looking into that, I strongly suggest moving the server files off of your desktop. Desktop can have issues with permissions.

**Comment by coolkid787** [comment]
> The issue called out in that log is that the sponge jar file was not being found in the mods folder like expected. While you are looking into that, I strongly suggest moving the server files off of your desktop. Desktop can have issues with permissions.

Ok I did that and still it doesn't want to load for some odd reason. I'm out of ideas

**Comment by FallenEagle1** [comment]
You said you did that, which part, or both parts? If you did, I would grab a new log.

**Comment by Yamza** [comment]
Just want to point out two things here. 
The first being that the current version of sponge is built for Forge 2768 and the current version of ATM3 is on 2815. That alone could be a possible cause of issues as I know of one other server running Sponge that is not able to update our other pack Remix to the same Forge version.

The second thing is that Sponge is known for breaking several mods outside of this issue.

**Comment by coolkid787** [comment]
> You said you did that, which part, or both parts? If you did, I would grab a new log.

So I moved it out of my desktop, I downloaded a completely new setup of the server and everything, I still get the "files not found" error. The log says the exact same thing

**Comment by coolkid787** [comment]
> Just want to point out two things here.
> The first being that the current version of sponge is built for Forge 2768 and the current version of ATM3 is on 2815. That alone could be a possible cause of issues as I know of one other server running Sponge that is not able to update our other pack Remix to the same Forge version.
> 
> The second thing is that Sponge is known for breaking several mods outside of this issue.

I did downgrade it to that version and still same error, I'll give the lower version a try, but it doesn't make sense due to other server being updated.

**Comment by Yamza** [comment]
You cannot simply downgrade forge. That would cause several mods to no longer work and crash.

**Comment by coolkid787** [comment]
> You cannot simply downgrade forge. That would cause several mods to no longer work and crash.
Worth a shot I guess. I'm going to give a later version of the server a try downloaded with everything downloaded properly to the correct forge version

**Comment by coolkid787** [comment]
> You cannot simply downgrade forge. That would cause several mods to no longer work and crash.

Still get the same error, says it can't find it in the mods folder, it's clearly in there...

**Comment by Blueletric** [comment]
Sponge wont run on the latest ATM3, if you want sponge you have to look for the one running forge 2768

**Comment by Blueletric** [comment]
Other than that you will continuously crash

**Comment by coolkid787** [comment]
> Sponge wont run on the latest ATM3, if you want sponge you have to look for the one running forge 2768

Ok I did downgrade to the 2768 for both forge and the server files/mods, It's launching fine right now. I will go in game and see if i can type /sponge

**Comment by coolkid787** [comment]
> Other than that you will continuously crash

Ok, So some good news. The server launches and works, bad news, sponge still doesn't load up.

**Comment by Blueletric** [comment]
What specifically are you looking to do with sponge? There are some mods in the pack that already take over functions of some basic sponge plugins

**Comment by coolkid787** [comment]
> What specifically are you looking to do with sponge? There are some mods in the pack that already take over functions of some basic sponge plugins

I was looking to start a little fun public server. So stuff like Ultimate core mod, Luck perms, Anti-Grief, etc. Is it just this mod pack is something that it just won't work well with?

**Comment by Blueletric** [comment]
FTBU takes over most of those, not sure about Ultimate core mod, never used it. Sponge doesnt work well with this modpack in general because it has problems with multiple mods in it.

**Comment by coolkid787** [comment]
> FTBU takes over most of those, not sure about Ultimate core mod, never used it. Sponge doesnt work well with this modpack in general because it has problems with multiple mods in it.

Ok, interesting, I see. I think Sponge is kinda hopeless on this modpack, It loads in the server, but no files are created.

**Comment by Omnoid** [comment]
From my testing it's the Chisel mod
