### ISSUE TITLE
Extremely fast growth with EnderIO Farming Station/Mystical Agriculture/Acceleration Wand

### ISSUE THREAD

**Issue by lmcintyre** [AllTheMods/ATM-3#855]
## Expected Behavior
The EnderIO should harvest fully grown plants faster than usual when using the acceleration wand is used on it. Essentially, it should just cover its area in a fraction of the time.

## Current Behavior
All plants in the area of the EnderIO Farming Station grow at an extreme rate.

## Steps to Reproduce
1. Create a 15x15 area where a max range upgrade EnderIO Farming Station can harvest.
2. Populate its area with seeds of plants it can plant and harvest.
3. Automate item retrieval from output and supply plenty of power.
4. Hold Shift+Right click with the Acceleration Wand on the Farming Station. Crops will grow at an extreme rate.
Link to a video of this in action: https://www.youtube.com/watch?v=f6JLsRnYKlo
I realized after the fact that I never had a "control" sample, a clip of the crops without this occurring. Trust me when I say they grow nowhere near as fast normally.

## Detailed Description
I believe I've explained everything, but I should clarify I don't supply this farmer with Fertilized Essence, nor is the Fertilized Essence able to be used on the Tier 6 crops anyways, so it's not like it's using that on the crops to speed them up. Besides, this occurs on normal crops as well. That essence goes straight into my refined storage system anyways. If it slows down at any point, I can swap through the Acceleration Wand's speeds to make it happen again.

**Comment by FallenEagle1** [comment]
There is nothing really we can do about this, and this would be better to let the enderio devs know about it, as I'm pretty sure a fix for this will require some coding changes. That's an interesting bug though.
