### ISSUE TITLE
SERVER CRASH

### ISSUE THREAD

**Issue by umutcantkn** [AllTheMods/ATM-3#856]
WARN: All The Mods 3 Server was stopped (possibly crashed)...
At 20190904:232935 Server has stopped.
Server has 1 consecutive stops, each within 600 seconds of eachother...

it crashes all the time i can't open a modded server in my computer. please help i cant play with my friends
[crash-2019-04-09_23.31.43-server.txt](https://github.com/AllTheMods/ATM-3/files/3060858/crash-2019-04-09_23.31.43-server.txt)

**Comment by Yamza** [comment]
Guessing it's not installed properly, I would try reinstalling it. https://www.reddit.com/r/allthemods/comments/9cv2u7/server_setup/

**Comment by umutcantkn** [comment]
I reinstalled, but nothing changed.

**Comment by Darkere** [comment]
Try what is recommended here

https://github.com/brandon3055/Draconic-Evolution/issues/749

**Comment by umutcantkn** [comment]
-Duser.country=US -Duser.language=en where should i paste it? in setting.cfg ?

**Comment by Darkere** [comment]
Oh right the Script....
Yes in settings.cfg in the line about JAVA arguments. Put them at the end but before the ";".

**Comment by umutcantkn** [comment]
Thank you.
