### ISSUE TITLE
Error on 20 mods

### ISSUE THREAD

**Issue by KelloggsCereal03** [AllTheMods/ATM-3#858]
Every time i load up All the mods 3 on the twitch app, after i load it from the launcher it comes up with an error saying that some mods dont have the right requirements or its the wrong version. i dont know if this is a bug or not but im not sure on what to do

**Comment by FallenEagle1** [comment]
I would reinstall the pack, and if the error shows up again, grab the crash report or log that is generated and link it here (don't copy and paste it directly into here, makes it hard to read) so that we can have some indication of what might be wrong.

**Comment by KelloggsCereal03** [comment]
seems to have worked
