### ISSUE TITLE
All blocks loading as ether green blocks or white blocks

### ISSUE THREAD

**Issue by zerg360** [AllTheMods/ATM-3#859]
Been a few days since i played the game but when i loaded it up on April 20th 2019 and tried to launch a new world all the blocks loaded up as ether bright lime green blocks or white blocks. tried loading some old saves and the same issue occurred. the only thing different that i did from what i normally do was to accidentally load up the base minecraft game while trying to load up something else.

![Screenshot (88)](https://user-images.githubusercontent.com/49823876/56464038-beee5980-63b6-11e9-82b2-66f7ee7cd8d2.png)

![Screenshot (89)](https://user-images.githubusercontent.com/49823876/56464040-cada1b80-63b6-11e9-852c-f7ace352018c.png)

Two screen shots of what it looks like.

Looking for any help at all at solving this problem.

**Comment by FallenEagle1** [comment]
Usually when this problem occurs, it seems like outdated graphics drivers are the primary issue of this. That would be the first thing I would check.

**Comment by zerg360** [comment]
Loaded up the game a day later and everything went back to normal so i am going with my graphics card being the issue has been act up recently.
