### ISSUE TITLE
Portal to Aroma1997 Dimensional World bugged

### ISSUE THREAD

**Issue by chooven** [AllTheMods/ATM-3#86]
I had to re-light mine after the 2.8 update and now when I get into it I glich out unable to move and have to relog to recover

**Comment by DietmarKrause** [comment]
perhaps related https://bitbucket.org/Aroma1997/miningworld/issues/132/112-b46-crash-after-returning-from-aroma

**Comment by seattleda** [comment]
I'm having the same problem although the world was started fresh with 2.8 update.  Here is a video showing the problem.  https://youtu.be/lOAPi_CaL90

Please note - I tested this in Single Player and it works fine.  Bug only happens on my ATM3 multiplayer server.

**Comment by mfczureal** [comment]
I am seeing the exact same behavior that seattleda posted a video of in my multiplayer world.  I've tried recreating the portal, relighting it, etc, but in 2.8 I cannot enter the portal.  I've deleted both the DIM6 and the DIM-6 folders, changed the aroma1996sdimension.cfg file to show the actual dimension as both 6 and left as -6, but I continue to get the same issue.

**Comment by seattleda** [comment]
Updating Aroma from .46 to .48 version fixes the issue.

**Comment by OrdinatorStouff** [comment]
Fixed in later versions of mod.
