### ISSUE TITLE
Twitch not downloading pack clientside

### ISSUE THREAD

**Issue by TehEpicDuckeh** [AllTheMods/ATM-3#860]
Instead of installing normally, it gives me the error cannot find dependency 277047.

![image](https://user-images.githubusercontent.com/49884015/56528991-e8b59680-6504-11e9-855d-8c10eee46de5.png)

**Comment by Yoosk** [comment]
That's one of Twitch issues that's entirely random and we can not help with it. You can only retry until it works, or try to use [MultiMC](https://multimc.org/) instead.
