### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Kriust** [AllTheMods/ATM-3#862]
It crashes all the time I try to restart it, It worked fine for over a week.

28.04 18:35:58 [Server] Server thread/INFO [packcrashinfo]: No manfiest present, attempting to load the minecraftinstance.json file.
28.04 18:35:58 [Server] Server thread/ERROR [packcrashinfo]: No manifest or minecraftinstance.json present

[crash-2019-04-28_18.35.57-server.txt](https://github.com/AllTheMods/ATM-3/files/3125203/crash-2019-04-28_18.35.57-server.txt)

**Comment by Yamza** [comment]
Same as this one. https://github.com/AllTheMods/ATM-3/issues/845
