### ISSUE TITLE
Server Not Loading Nitrado

### ISSUE THREAD

**Issue by avthomas6mm** [AllTheMods/ATM-3#864]
i just bought a server on nitrado and i've had many failed attemps to direct join the server. I matched the server version and the version I am playing on but it still says out of date.

**Comment by FallenEagle1** [comment]
This isn't really enough info to be able to help with. Do you have any logs that show the login attempt? If so, I would put them on gist.github then link them here. I'm not even sure of what version(s) of the modpack you are trying to work with.
