### ISSUE TITLE
Server crash & corrupts? world folder on cobblegen itemduct hookup to compacting drawer

### ISSUE THREAD

**Issue by paulmcode** [AllTheMods/ATM-3#865]
## Expected Behavior

The cobblestone generator should begin pumping cobblestone through the itemduct to the drawer.

## Current Behavior

The server crashes, and refuses to load. After deleting the world folder, it works.

## Steps to Reproduce

1. Place cobblestone generator.
2. Above cobblestone generator, place itemduct.
3.Above itemduct, place compacting drawer.
4.Crash.

**Comment by Yamza** [comment]
Might be helpful to include a crash report when reporting a crash.

Open the pack instance folder by right clicking the ATM pack icon on Twitch then Open Folder
Inside the crash-reports folder find the latest crash.txt, or in the logs folder find the latest.log
Copy the contents of the log and paste it into one of the following upload websites:
Largest Size Limit: https://gist.github.com/ or https://pastebin.com/, https://hastebin.com/, etc.

**Comment by FallenEagle1** [comment]
This seems like the compacting drawer and minecolonies bug. Should be fixed in the 5.12.2 update
