### ISSUE TITLE
Quantum Entangloporter - Explosion Noises

### ISSUE THREAD

**Issue by JayceStorm** [AllTheMods/ATM-3#866]
I have a Quantum Entangloporter (QE) connected to the bottom of a Vibrant Capacitor Bank (VCB).  When power is running from the QE into the VCB, their is a visual and audio explosion.  No blocks are destroyed.  If I stop the VCB from sending/receiving power, the explosions stop.

This started with the lastest update version v5.12.1.  The previous version did not have this problem.

**Comment by Yamza** [comment]
See this issue, and let them know what you think of this feature: https://github.com/SleepyTrousers/EnderIO/issues/5107
