### ISSUE TITLE
carbon plate and random explotions

### ISSUE THREAD

**Issue by Skazz1** [AllTheMods/ATM-3#867]
have an old world that i play in on and off, after being away a couple of months i decided to build a reactor from the extreme reactor mod. The carbon plate that is needed cant be crafted. 

Also there are random explosions from some of the machines, my base is a rats nest of cables and i have mob grief turned off so im not 100 % sure but i think its the ender io machines.
[crash-2019-05-14_14.55.58-client.txt](https://github.com/AllTheMods/ATM-3/files/3178680/crash-2019-05-14_14.55.58-client.txt)

**Comment by FallenEagle1** [comment]
There is a way to craft it, look at the other option than carbon plates. Should be the ic2 carbon fiber iirc. As for the enderio machines, it is, and that is being turned off in the next update. The devs added that "feature" and we missed that it was a thing when updating. Basically eio machines explode if rf is over sent to them, being mekanism or one other mod in particular that seems to do this.

What's with the crash report, any context to go with? If it is an issue, more info would be nice.
