### ISSUE TITLE
Mekanism x IC2

### ISSUE THREAD

**Issue by Evilestraider** [AllTheMods/ATM-3#868]
My universal cables from mekanism NO LONGER work with my IC2 equipment (matter replication system) I have made sure config is correct. enderio cables don't work either. This has only happened recenty before everything worked fine.

**Comment by Evilestraider** [comment]
This is only for power*

**Comment by FallenEagle1** [comment]
More info please. Is this on a server, or just single player? What version of the modpack is this? Did anything change between when it worked and now? Have there been any changes to the pack? Do you have a pic of your setup?
