### ISSUE TITLE
Sorry, how do I change the /Home cooling time?

### ISSUE THREAD

**Issue by SakuramuraYC** [AllTheMods/ATM-3#869]
Sorry, how do I change the /Home cooling time?

**Comment by SakuramuraYC** [comment]
Applied Energistics 2 Sky stone chest How to get it?
 can not find

**Comment by Darkere** [comment]
You can change the /home cooldown by editing the ranks. 
The permission you want to edit is called ftbutilities.homes.warmup.
Here you can find the commands to edit them. https://minecraft.curseforge.com/projects/ftb-utilities/pages/ranks/commands

Applied Energistics 2 meteors (that contain the chests) can only be found in the Mining Dimensions. ( Use the ae2 compass)

**Comment by SakuramuraYC** [comment]
> 您可以通過編輯排名來更改/ home冷卻時間。
> 您要編輯的權限稱為ftbutilities.homes.warmup。
> 在這裡，您可以找到編輯它們的命令。https://minecraft.curseforge.com/projects/ftb-utilities/pages/ranks/commands
> 
> Applied Energistics 2個流星（含有箱子）只能在採礦維度中找到。（使用ae2指南針）

Set the config?

**Comment by FallenEagle1** [comment]
There is a ranks.txt file where you can manually input the settings that you want different ranks to have. This page here https://gist.github.com/LatvianModder/5426786c7579df0296ec is an example of this. The link that Darkere posted is another way that this file can be edited, and is done while in game with those commands.

**Comment by SakuramuraYC** [comment]
Ok  but i would like sacn the Applied Energistics 2 Sky stone in Mining Dimensions
Mining Dimensions is Extra Urilities 2 ?

**Comment by FallenEagle1** [comment]
Nope. Mining dimension as in from the mod aroma's dimension. Type into jei `aroma` and you should see a couple items. Make a portal using the blocks there, and light it with the tool. That portal will allow you to teleport to the mining dimension. It is a dimension that has more ore generation in it than the overworld, and in this case, the ae2 meteors spawn there as well.
