### ISSUE TITLE
ID of Aroma1997 Mining world is changed in v2.8

### ISSUE THREAD

**Issue by grandrolf** [AllTheMods/ATM-3#87]
In version 2.7 of the pack the mining world has ID 6

In version 2.8 it's set to "-6"

Works for new servers, but becomes an issue when updating the pack from an older version.

**Comment by OrdinatorStouff** [comment]
This is an annoying change and I could change it BACK to -6 but I think since it's already been on positive 6 for a bit now we'll leave it at that.
