### ISSUE TITLE
Server is not loading properly anymore

### ISSUE THREAD

**Issue by crisischris9** [AllTheMods/ATM-3#870]
I was playing on my server perfectly fine last night, I could load it up no problem. 
Now today when I started my server every time it stops and a message in yellow says:
 [BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
 I have not changed anything on my computer since I played last night, please let me know if you can help me out with this at all.

**Comment by FallenEagle1** [comment]
Will need the full crash report (if there is one) or the latest log. That line does not indicate any potential issue of why the server won't work
