### ISSUE TITLE
Pulverizer (Thermal Expansion) produces Bauxite dust from Aluminum Ore instead of Aluminum Dust

### ISSUE THREAD

**Issue by GreenGhost21** [AllTheMods/ATM-3#871]
## Expected Behavior

The Thermal Expansion Pulverizer should produce Aluminum Dust from Aluminum Ore.

## Current Behavior

The Pulverizer produces Bauxite Dust instead of Aluminum Dust

## Steps to Reproduce

1. Insert Aluminum Ore found in worldgen into Pulverizer
2. There is no step 2.

## Log

Not needed

## Detailed Description

The Pulverizer is the only machine (that I could find) of the type that crushes ores into dust to produce Bauxite dust instead of Aluminum dust from Aluminum ore. I imagine that changing this will help consistency and prevent confusion.

EDIT June 5th: I was using All The Mods 3: Lite (latest)

**Comment by SpeedSlider** [comment]
What version of ATM3 are you using. I placed all three available aluminum ore in JEI in a Thermal Expansion Pulverizer and only got aluminum dust.

**Comment by GreenGhost21** [comment]
I was using the latest version of All The Mods 3: Lite. I apologize for any confusion I caused.

**Comment by SpeedSlider** [comment]
https://github.com/AllTheMods/ATM3-Lite/issues/35#issue-452967471

Moved issue closing this one.
