### ISSUE TITLE
Friend and i tries to open a server with Decocraft.

### ISSUE THREAD

**Issue by Judisten** [AllTheMods/ATM-3#872]
So my friend and I tries to open a server with one extra mod, called Decocraft. Apparently, it will crash if that mod is in, any way to fix that? 

Crash report: https://gist.github.com/Judisten/45305fe93b672d92a8bbab3d35f5e2cf

**Comment by Darkere** [comment]
Did you add PTRlib as well as decocraft needs that?

**Comment by Judisten** [comment]
I fixed it. I forgot to install PTRLib, so now it's working! HAHA! Have a great day!
