### ISSUE TITLE
Insanely high amounts of items for crafting recipes

### ISSUE THREAD

**Issue by twothe** [AllTheMods/ATM-3#874]
In our server world running v5.12.1 we have the issue that sometimes suddenly recipes require insane amounts of resources to craft. I.E. crafting a fluxduct suddenly requires 30 redstone instead of 3. The confusing thing is that the problem is not only visual, the Refined Storage crafter actually does remove the amount of redstone shown. The item is however still craftable with the normal resources in manual crafting tables.

The extra high crafting materials are also shown in JEI, they are written to patterns, already existing patterns suddenly "update" their requirements even though they have been in the crafter for hours working perfectly fine.

Restarting the server does not fix the problem, restarting the client does temporarily fix the issue, but at some point it reappears and then instantly breaks all crafting recipes. I cannot find any pattern to when the issue appears. We even hat situation where one player had the normal recipes and the other one had the bug, and whenever the bugged player looked into a crafter, all those recipes became corrupted as well.

The resources affected are exclusively redstone and ingots (as far as I can tell), other stackable don't seem to be affected.

**Comment by FallenEagle1** [comment]
Have you tried reinstalling the server files for the server?

**Comment by Darkere** [comment]
Here is how you can fix this.
https://gfycat.com/jealousseriousleech

**Comment by twothe** [comment]
Thank you Darkere for the fix, I got it to work and to temporarily squelch the bug.

This seems to be related to whether or not you have oredict selected. When I have selected it the bug appears and the fix from above solved it. When I had it not selected the recipe was ok and the fix didn't work.

**Comment by twothe** [comment]
Small update: we have this issue now appearing an almost an hourly basis, which makes using this modpack difficult. We never had these kind of issues in other modpacks, so there has to be some relation to ATM at least, but I still can't tell why this is happening nor find any pattern on what is causing it to malfunction again.

**Comment by Darkere** [comment]
I've only heard of RS causing this. Basically when you do the opposite of what my fix is. Try making the patterns without oredict. You don't need it in 95% of cases anyway.

**Comment by twothe** [comment]
I have at some point accidentally done the opposite and as you said it actually doubled the problem. However the issue occurs with random resources about once every 2 hours without anyone actually adding new recipes. Suddenly things cost like 200 Redstone and when I check in JEI it confirms that the bug suddenly reappears.

I also already exchanged all crafting recipes that I could find that had oredict checked and removed the flag, still it did nothing to solve the issue.

**Comment by Darkere** [comment]
That sounds like a different issue. For RS this only happens when you press the make pattern button. You can "fix" the issue with RS but you would be fixing a bug with another bug. 

Take look at other autocrafters you have set up. They might have cached the broken recipe.

**Comment by Ranaark** [comment]
I'm getting this issue too on a singleplayer world, so far with iron, redstone and circuits and alloys from Mekanism. I tried your suggestion Darkere and it seems to have fixed it, will report back if it happens again
[https://imgur.com/a/JiWCxWa](url)

**Comment by Ranaark** [comment]
Ok it happened again after I restarted the game
