### ISSUE TITLE
Missing FORGEURL

### ISSUE THREAD

**Issue by RaineriZeppeli** [AllTheMods/ATM-3#875]
settings.cfg had FORGEURL=DISABLED so it couldn't find forge

just added https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2825/forge-1.12.2-14.23.5.2825-installer-win.exe to it manually and it worked

## Expected Behavior
The URL should be there already

## Current Behavior
The URL is not set which makes users have to do it manually

## Possible Solution
Put the URL in the settings.cfg file

## Steps to Reproduce
1. Download server files
2. Run ServerStart.bat

**Comment by Yoosk** [comment]
I would like to know which exact server pack files do not work, as they are supposed to use forge-installer that is already included within server pack files. as for FORGEURL downloading, it might not work on some systems due to certain circumstances.

**Comment by FallenEagle1** [comment]
Also, did you try to run the serverstart.bat file at all before using the installer-win file? The pack comes with a forge installer file that the installer win is unnecessary, assuming that the bat file didn't work for some reason.

**Comment by RaineriZeppeli** [comment]
Sorry i left out some details. I'm using the newest (2.12.1) server https://minecraft.curseforge.com/projects/all-the-mods-3/files/2699829

Tried ServerStart.bat multiple times, everytime it reports "ForgeDownloadURLNotFound" and quits. 
[serverstart.log](https://github.com/AllTheMods/ATM-3/files/3244372/serverstart.log)

In the freshly downloaded server, there's just ForgeMultipart-1.12.2.-2.5.1.81-universal.jar and Forgelin-1.8.2.jar but no installer.

**Comment by shremp** [comment]
I'm actually having a similar issue, I don't really know what to do. The serverstart.bat says "error code forgeurldownloadnotfound" and if i try to input it manually, the server files get stuck in a loop.

**Comment by FallenEagle1** [comment]
@shremp what version of the modpack, want exactly did you put in, and can you pastebin and link the serverstart.log file here?

**Comment by shremp** [comment]
So where im at right now is when i open the serverstart.bat file, i get this.

![161242cd964854dd21a30c2123ee4138](https://user-images.githubusercontent.com/24820932/58972365-6bc83e80-878b-11e9-8bcd-81c1adda89d4.png)

**Comment by shremp** [comment]
These are the server files i used
![31ee468782848e2978e37645fd73aee1](https://user-images.githubusercontent.com/24820932/58972442-96b29280-878b-11e9-8928-d5eed393973c.png)

**Comment by shremp** [comment]
I just did the recommended fix by the starting guy, but you may want to modify the server files to automatically pull that installer.

**Comment by FallenEagle1** [comment]
Yes, we know. Technically the serverstart file does, but about a week ago something changed on Forges end, and it broke that part of the script

**Comment by shremp** [comment]
Ok, cool, thanks for being so quick to respond I appreciate the help. You guys do a good job.
