### ISSUE TITLE
AE2 wireless terminals not functioning correctly

### ISSUE THREAD

**Issue by dantheman4700** [AllTheMods/ATM-3#877]
## Expected Behavior
<should be able to put infinity booster cards into any wireless terminal>

## Current Behavior
<crafting terminal is the only wireless terminal that will accept infinity booster card>

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yamza** [comment]
The boosters are specifically for the Wireless Crafting Terminal.

**Comment by dantheman4700** [comment]
In other modpacks I've played they were for any wireless terminal

**Comment by FallenEagle1** [comment]
Do you mind saying which modpacks? To my knowledge, it is only the wireless crafting terminal that is able to be anywhere, and in any configs I dont see an option to enable it for everywhere. If other modpacks are able to, I'd like to see how they are able to, to even consider it.

**Comment by dantheman4700** [comment]
in ftb revaltion v2.5.0 I was able to place the infinity booster card into to any terminal even universal

**Comment by FallenEagle1** [comment]
Just tested with ftb revelation v3.0.1 and am not able to do anything of the sorts.

**Comment by dantheman4700** [comment]
try 2.5.0 it just worked for me

**Comment by FallenEagle1** [comment]
2.5.0 also came out last september, before applied energistics changed and forced the mod for wireless crafting to change as well. Closing this for now, as I don't believe it is currently possible anymore. If it is, will have to give more information using updated mods.
