### ISSUE TITLE
World Corruption after breaking Ender IO Alloy Smelter with Atomic Disasembler from Mekanisim

### ISSUE THREAD

**Issue by Soloun** [AllTheMods/ATM-3#879]
## Expected Behavior
Block should break

## Current Behavior
Block breaks, minecraft crashes, world no longer loads

## Possible Solution
Stop world being ruined by fixing :)

## Steps to Reproduce

1. Place an Ender IO Alloy Smelter
2. Break Smelter using Atomic Disassembler from Mekanisim  
3.
4.

**Comment by Yamza** [comment]
Log?

**Comment by Soloun** [comment]
[crash-2019-06-15_21.06.54-server.txt](https://github.com/AllTheMods/ATM-3/files/3293643/crash-2019-06-15_21.06.54-server.txt)
Sorry forgot the log

**Comment by Yamza** [comment]
This has nothing to do with the things you posted. You have a magnet ring on which, when an enderio machine is broken, will cause you to crash. Until the pack is updated don't use a magnet ring when breaking enderio machines.

**Comment by Soloun** [comment]
Nice, thanks for the info, I wasn't aware of the issue with the magnet ring and the Ender IO machines.
