### ISSUE TITLE
[ATM3 V.2.8] Crash after returning from Aroma dimension to overworld 

### ISSUE THREAD

**Issue by DietmarKrause** [AllTheMods/ATM-3#88]
Single player world.
The Crash was not repeatable (i tried)
After first updating the modpack a few items from Aroma dimension were deleted and i had to rebuild the mining tool. I re-activated the pre-existing portal, found a new created, fresh dimension and did a little bit manual mining (with ender pouch leading to an ender chest at the overworld with automatic ore processing).
A few seconds after returning to the overworld, the game crashed. It seemed to crash while i was trying to walk throgh the portal without using the mining tool.

https://pastebin.com/BKkRwyCX

After that i tried to find out what happend and re-entered the dimension an came back this time without problem....

**Comment by DietmarKrause** [comment]
https://bitbucket.org/Aroma1997/miningworld/issues/132/112-b46-crash-after-returning-from-aroma

**Comment by OrdinatorStouff** [comment]
aroma's issue tracker indicated bug has been fixed. if new issues come up please let us know
