### ISSUE TITLE
Cactus Planks Recipe

### ISSUE THREAD

**Issue by Bladebearer** [AllTheMods/ATM-3#881]
When trying to craft cactus planks, (1 cactus in the center of a grid) it makes cactus sap from natura (currently both share the same recipe)

## Expected Behavior
Crafts 4 cactus planks

## Current Behavior
Crafts 1 Natura: Cactus Sap

## Possible Solution

This is what i wrote, and currently works (aside from the update needing to be done to jei)

    recipes.remove(<structurize:blockcactusplank>);
	recipes.addShaped("Cactus Plank", <structurize:blockcactusplank>*8, [
		[null, <minecraft:cactus>, null],
		[null, <minecraft:cactus>, null],
		[null, null, null]
		]);

## Steps to Reproduce

1. Put one cacti in the crafting grid, in the center location

**Comment by Xandavier** [comment]
I used the uncrafting table from the Twilight Forest mod, you place the cactus in the middle 3x3 and then use the up and down arrows on the right where the recipe output is and you can switch it from Cactus Juice to Cactus Planks

**Comment by FallenEagle1** [comment]
That works, but the uncrafting table's uncrafting function is disabled. A recipe will be implemented for it.

**Comment by Turbotowns** [comment]
Does that possible solution still work? Where do I paste that?
