### ISSUE TITLE
All the mods 3 Server crashing on over world loading

### ISSUE THREAD

**Issue by Shaun-Craddock** [AllTheMods/ATM-3#882]
Hello I run and host an All the Mods 3 server running 5.12.1 for me and a friend. We went to space and created a space station the other day and the server was fine. It got late so we came back to the over world, saved and backed up the server and shut it down for the night. Since then I have tried booting up the server which will boot up fine but when one of us tries to log into the server it crashes out and our games disconnect. I have tried restoring from a backup however it seems to be when we are in the over world the game crashes as the backups where we are in space the server will let us log in fine but when we try loading into the over world the server will crash.
We created the space station ages ago however we decided to "upgrade" the station and make it much bigger than it previously was. I have tried adjusting the server RAM to no avail. I originally had it set to 10 GB but changed it to different amounts to see if that helps. I even ran memtest86 on my PC just to make sure my RAM wasn't faulty.

I have included the crash, server cfg and world files in the hopes someone might be able to deduce why my server is crashing. I have put 14 days into this server so I would like to keep it going if possible.

Thank you
Craddrock

My system specs:
Intel i7 6700k (4 cores 8 threads) which is water cooled.
32 GB RAM.
Nvidea GTX 1070.
(More than enough storage).

Crash log:
https://drive.google.com/file/d/1J-D3uZ2mRgSZ8FMN6ThxaWRQfAu74bra/view?usp=sharing

Server cfg file:
https://drive.google.com/file/d/1zl9k_swjXWBbpY9F82MxMFAhZQfKvloP/view?usp=sharing

world file:
https://drive.google.com/file/d/1cWj0fzgopBRqiguSLQmE06kTTHycDMS7/view?usp=sharing

**Comment by Darkere** [comment]
Twilight forest is crashing you. In particular, there is an entity somewhere that loads something about the twilight forest that is crashing. 
We have seen a very similar case before but no real fix.

Try posting your crash on the Twilight forest github.

**Comment by Shaun-Craddock** [comment]
Thank you for the response. I will look at posting to there now. It wouldn't have anything to do with putting the twilight forest mobs into Ender IO soul vials?

**Comment by Darkere** [comment]
no it's an entity in the world

**Comment by Shaun-Craddock** [comment]
Would that include mob heads? or are they classed as blocks?

**Comment by Darkere** [comment]
the entity itself is not necessarily related to TF. Heads count as block if placed and as entity if dropped.

**Comment by Shaun-Craddock** [comment]
Right ok thank you
