### ISSUE TITLE
MineColonies and Cobalt

### ISSUE THREAD

**Issue by Alitabear** [AllTheMods/ATM-3#885]
Mine colonies cactus planks are not craft-able with the Natura cactus water recipe. Also Colbalt when poored from tinkers smeltery into block form will NOT turn into ingots, if placed back in the smeltery it will be treated as an ore. meaning 9 turns to 2 ingots. 

## Expected Behavior
cactus -> cactus planks (from MineColonies)
Cobalt blocks -> turn into cobalt ingots.. Also smelts back into 9 ingots.. not 2. 

## Current Behavior
Cactus makes Natura water
Cobalt Blocks do not make ingots, Are treated as "ore" in the smeltery.
JEI says all machines that double ore can use cobalt BLOCK as an ore. 
Quartz Grindstone can grind 1 cobalt block into 2 ardite dust.

## Possible Solution
To new to coding to honestly answer this.

## Steps to Reproduce
1. Throw Cobalt dust into smeltery x9
2. drain block
3. check jei to see block does nothing. Feel betrayed.
4. throw block back into smeltery. get 2 ingots. throw hands up in exasperation. 

## Log
I don't think this needs a log? This is my first bug report ever.

## Detailed Description
Please make cactus planks craftable, Please unlist Cobalt blocks as a ore? <3

**Comment by FallenEagle1** [comment]
Duplicates of both  #805 and #881. The one is recipe conflict, the other is believed to be unidict issue, but hopefully the next update will fix.
