### ISSUE TITLE
Thaumcraft Golem Press not working in Multiplayer 

### ISSUE THREAD

**Issue by DarkWolfLinux** [AllTheMods/ATM-3#887]
## Expected Behavior

The golem press should remove the items required to make a golem and then pull the machina essentia from a connected jar

## Current Behavior

Currently the press shows you have the required materials to make the golem but the second you hit the craft button nothing happens, no matter the wait time.

## Steps to Reproduce

1.Have the needed thaumcraft knowledge
2.craft golem press
3.make sure you have the right materials for the golem creation and have the right vis pipes connected
4.press the anvil button in the gui and nothing will happen

## Detailed Description

Just the bug being fixed because this is a decent chunk of thaumcraft and there is no work around without the bug being fixed

**Comment by FallenEagle1** [comment]
Could not reproduce this, so I would try updating and seeing if this still occurs.
