### ISSUE TITLE
Requesting Nutrition Update

### ISSUE THREAD

**Issue by WesCook** [AllTheMods/ATM-3#888]
Hey modpack devs!

I have a request.  Would you mind including an update for [Nutrition](https://github.com/WesCook/Nutrition) in your next ATM3 pack update?  The version you're currently including (v4.0.0) had a desync bug that was resolved in the next version.  I'm still getting issue reports for it today though, so I thought I'd shoot you a message.

You can grab the [latest release here](https://github.com/WesCook/Nutrition/releases/).  Remember to also clear your `/config/nutrition/nutrients/` directory so new food support will regenerate (unless you've customized it).

Let me know if you have any questions!  Cheers!

**Comment by FallenEagle1** [comment]
Will do. We have some customization, but it should be easy enough to regen and get the changes as well.

**Comment by FallenEagle1** [comment]
Modpack update with updated mod is now live

**Comment by WesCook** [comment]
Awesome, thank you very much.
