### ISSUE TITLE
ATM3 LITE crash with added mods 1.12.2 i have no idea what i am doing

### ISSUE THREAD

**Issue by morganh13** [AllTheMods/ATM-3#889]
HELP I downloaded ATM3 LITE due to my computer repeatedly slowing down in ATM3, I have added some mods from ATM3 to LITE because I want to have the same world and I enjoy these mods. However, when I startup I get an error log and am unsure how to read/fix it

any help would be great!

ERROR LOG AS FOLLOWS

## Expected Behavior
the game should start up and be my world from ATM3

## Current Behavior
i get a crash log from some of the added mods

## Possible Solution
honestly im not a modder i downloaded these mods from curse and added them straight into my twitch-minecraft-instances-ATM3 LITE-mods folder

## Steps to Reproduce

1.
2.
3.
4.

## Log
https://pastebin.com/5HASW3CW

## Detailed Description
I added mods Bewitchment, all 7 of the project reds, natura and fairylights, not sure if any of the other mods have the same issue but my error log only says project red and betwitchment i think

**Comment by Yamza** [comment]
I already replied to this post in atm3 lite. Why are you posting it here too?

**Comment by morganh13** [comment]
oh sorry i have never posted on here i didnt know which one to use

**Comment by SpeedSlider** [comment]
Closing this issue based upon it being ATM3 Lite issue and comments/contact has been performed by an ATM Team member
