### ISSUE TITLE
TechReborn recipes that don't use oredic machineBlock

### ISSUE THREAD

**Issue by meerple** [AllTheMods/ATM-3#89]
Hi. The TR machine block recipe was removed, but some TR recipes don't use ore:machineBlock*, just the TR machine block. They are Alloy Smelter, Industrial Blast Furnace, Implosion Compressor, Matter Fabricator and Advanced Machine Casing. [I fixed it (I think) with more CT scripting.](https://pastebin.com/wqswx89T)

**Comment by OrdinatorStouff** [comment]
Very nice script, thanks! IT seems as though this has already been fixed on the mod end however. I just checked all the recipes you mention and they're using the oredict machine block.

Thanks~!
