### ISSUE TITLE
Client kicked from server when activating ProjectRed Frame Motor [ATM3 5.12.1]

### ISSUE THREAD

**Issue by TigerWalts** [AllTheMods/ATM-3#890]
When activating a Frame Motor with a redsone signal the client will encounter an internal exception and disconnect from the server. The Frame Motor still works, but the client is sent a message with an invalid length.

## Expected Behavior
The Frame Motor to activate and the client to not encounter an exception.

## Current Behavior
The Frame Motor activates but the client is sent a message with an invalid length and causes an exception that disconnects the player. Any nearby players would likely get disconnected too.

## Possible Solution
This may be a bug in ProjectRed
https://github.com/MrTJP/ProjectRed/issues/1488

## Steps to Reproduce
1. Must be playing on a dedicated server
2. Place a Frame Motor connected to a moveable structure
3. Power the Frame Motor with redstone

## Log
Error in the client log:
https://gist.github.com/TigerWalts/2fe55ba84ffc0b1ec22b3db48091a662

**Comment by Yamza** [comment]
Please link a full log or crash report.

**Comment by TigerWalts** [comment]
- https://gist.github.com/TigerWalts/69f1d847c9f95bd24415ba42c942c176

The exception happens twice in this log, search for `NetworkDispatcher exception` to find the start of each.

**Comment by Yamza** [comment]
Seems like it's been reported numerous times and still isn't fixed. Nothing we can do. Even if it was fixed we haven't been able to update Project Red due to incompatibilities.
https://github.com/MrTJP/ProjectRed/issues?utf8=%E2%9C%93&q=motor

**Comment by TigerWalts** [comment]
The bug is not present in the latest release of ProjectRed `4.9.3.116`.

**Comment by Darkere** [comment]
> Even if it was fixed we haven't been able to update Project Red due to incompatibilities.

**Comment by FallenEagle1** [comment]
Project red has been updated since it finally came with a newer update. I would suggest updating the modpack and seeing if that fixes it.
