### ISSUE TITLE
Inventory Glitch - Can't Play

### ISSUE THREAD

**Issue by ShadowGaming1234** [AllTheMods/ATM-3#891]
The items in the inventory, only when I open it with E, doesn't happen when in chests etc., move up and down, no matter what is in the inventory, I cannot play because of this and I need it to be fixed.

This is a link to show what is happening:
https://www.dropbox.com/s/9dtmc44e72m9u1c/IMG_1025.MOV?dl=0

**Comment by FallenEagle1** [comment]
I would see if an update fixes this, and if not, try changing the betterfps algorithm and see what that does for you.
