### ISSUE TITLE
Exception in thread "Excore Thingy Display" when loading world

### ISSUE THREAD

**Issue by PoLoMoTo** [AllTheMods/ATM-3#893]
## Expected Behavior

Load into the world

## Current Behavior

Crashes with: Exception in thread "Excore Thingy Display"

## Possible Solution

No idea, looked into disabling excore but it seems that its probably required by mods

## Steps to Reproduce

1. Load modpack in MultiMC on Arch Linux
2. Launch profile
3. Attempt to start a new single player world

## Log

https://gist.github.com/PoLoMoTo/10c34b29a3a7fc1516941af407c53230

## Detailed Description

Using MultiMC on Arch Linux since the twitch app is not available for linux.

**Comment by PoLoMoTo** [comment]
Increased the RAM limit to 14GB and now the game with not launch at all and has a different crash log

https://gist.github.com/PoLoMoTo/eb6e5d5071da9cd565209e5b37525336

**Comment by Yamza** [comment]
Pack only needs 8GB set unless you have a resource pack, giving more ram isn't going to fix anything.
It seems like your errors are due to rendering, might want to check your drivers.

**Comment by PoLoMoTo** [comment]
How would I go about that?  I've never had an issue with graphics drivers and other games as well as steam's proton work without issues.

**Comment by PoLoMoTo** [comment]
It seems that this might be somehow related to MultiMC as it won't launch with MultiMC on windows either..

https://gist.github.com/PoLoMoTo/239131b610fe31e3913fa8c1dccbb384

**Comment by starlingfire** [comment]
I had this similar issue yesterday, and it was brought about after performing my weekly software update. I run Solus linux and they release updates every Friday, but anytime there is an Nvidia driver update, Minecraft doesn't work. I have to manually remove all the drivers, reboot, reinstall the drivers, and then the game works.

My game crashed the same way your latest one did, with line [4049](https://gist.github.com/PoLoMoTo/239131b610fe31e3913fa8c1dccbb384#file-gistfile1-txt-L4049) being slightly different to my using an Nvidia GPU.

As irritating as it is, I often have to uninstall/reinstall my drivers after an update, but afterward I can use MultiMC to launch the game and join my local world.
