### ISSUE TITLE
Crashed When Searching for Glove in JEI

### ISSUE THREAD

**Issue by TrueDakkon** [AllTheMods/ATM-3#896]
## Expected Behavior
It should either pull up all of the items titled glove, or just not show anything if there aren't any.

## Current Behavior
The game crashes before the letter "L" even appears in the JEI search bar.

## Steps to Reproduce
1. Load the game up.
2. Create a world or load into one.
3. Open your inventory.
4. try to search for "glove" in JEI.
5. Profit.

## Log
https://gist.github.com/TrueDakkon/289d08571be14ce2f247285a7b17d3cc

**Comment by Yoosk** [comment]
I would suggest to update your java or pick the correct one, using [our guide](https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/) as you are using ancient one from 2 years ago and that might be the issue.

**Comment by FallenEagle1** [comment]
Update java like Yoosk mentioned, and I would try updating to 5.12.2 to see if this still happens to you. Couldn't reproduce, but curious to see if the new update fixes it for you.
