### ISSUE TITLE
Crash from JEI

### ISSUE THREAD

**Issue by Trev19** [AllTheMods/ATM-3#897]
when in JEI and clicking to auto put the recipe from any mod into my refined storage crafting grid the game crashes. (Not every time. But most definitely if there is an item with an nbt. value) Well not technically a crash because I have to go into the task manager to kill Minecraft, so I have no crash logs.

**Comment by FallenEagle1** [comment]
Does the crash seem to happen when you have a sapling in the recipe? That one tends to get refined storage quite often, but too much nbt will get it as well. It's a known issue with RS and nothing we can do about it, it's on the mod devs side.
