### ISSUE TITLE
Error after changing recipe mode to simplified

### ISSUE THREAD

**Issue by CrazyPoro** [AllTheMods/ATM-3#898]
Got an error when connecting to my server after changing recipe from normal to simplified.

## Current Behavior

I got :
Error balance/atm_packmodes_simplified_fixes.zs20 : Could not resolve <bigreactors : dustmetals : 2>
Error balance/atm_packmodes_simplified_fixes.zs20 : Could not resolve <bigreactors : dustmetals : 2>
Error balance/atm_packmodes_simplified_fixes.zs20 : Could not resolve <bigreactors : blockmetals : 2>
Error balance/atm_packmodes_simplified_fixes.zs20 : Could not resolve <bigreactors : blockmetals : 2>

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
Sounds like you updated some mods as well? In any case, this is fixed in the next update.

**Comment by CrazyPoro** [comment]
Added some yup, big thanks.
