### ISSUE TITLE
Binnie's Mod's Woodworker causes crash when trying to open

### ISSUE THREAD

**Issue by Tizarian** [AllTheMods/ATM-3#90]
Crash Report: 
The game crashed whilst rendering screen
Error: java.lang.IllegalStateException: Tried to get sprite before it is registered.

**Comment by TickleMeSkelmo** [comment]
All of Binnie's machines originating from the Extra Trees mod give the same error and ctd.

**Comment by OrdinatorStouff** [comment]
Do you have a full crashlog you can share by chance?

**Comment by OrdinatorStouff** [comment]
Looks like it's just been fixed in a mod update.
https://github.com/ForestryMC/Binnie/issues/253

Thanks for the info we'll go ahead and close this issue since the next update (next day or two most likely) will have all mods updated
