### ISSUE TITLE
Radioactive bee doesn't produce radioactive combs

### ISSUE THREAD

**Issue by BonazTV** [AllTheMods/ATM-3#901]
Hell radioactive bee doesn't produce radioactive combs, ive tried alvearys(with frames) and gendustry apiarys(with production upgrades). I have given the bees the fastes trade for working, and tried for about 2-3 hours.
Thank you :)

**Comment by FallenEagle1** [comment]
Are they in the climate that they prefer, or just in the climate they tolerate? It makes a difference. Also, what version of the pack? (numbers please)

**Comment by JonasBladtkramer** [comment]
Im on version 1.4.9 of the pack, they are in a crag biome (which I think is cold climate), I should probably try to move them to another biome, I just assumed that they would work by giving them the Gendustry climate trait.
Thanks :)

**Comment by FallenEagle1** [comment]
There could still be a problem, I don't know. Just going through troubleshooting to see if it might be something specific

**Comment by BonazTV** [comment]
It worked moving them to a plains biome, tanks for the help :)
