### ISSUE TITLE
Infinite Crafting Glitch with Mystical Agriculture and Refined Storage

### ISSUE THREAD

**Issue by karami92** [AllTheMods/ATM-3#903]
## Expected Behavior

I created a Refined Storage grid to store various items from my base, and decided to use it to automate crafting of the higher tier essences with Mystical Agriculture. Following the guides, I set it up, expecting everything to go smoothly.

## Current Behavior

It went TOO smoothly. After creating the patterns, the Interface, and all the relevant crafting blocks, I was fiddling with the settings because I noticed it wasn't immediately doing anything. Once I clicked the toggle for 'No Damage' a couple times, the interface output was suddenly filled with full stacks of every essence tier, without having gone through the crafting process or using the correct amount of resources.

## Steps to Reproduce

1. Plant Infernium Essences
2. Create a storage network with Refined Storage
3. Set up auto-crafting for essences
4. After having one of each essence tier in the input section, click the No Damage option a couple of times, and it will automatically fill all stacks.

**Comment by Darkere** [comment]
Can you share more about your setup and what you have gotten out of it? I am unable to replicate this.

**Comment by karami92** [comment]
Sure. The server I play on is currently down, so I went into single player and quickly remade my build with Creative to show the process. The farm itself is as basic as it can be, with a farmer block that takes the materials gathered, sends them through an EnderIO Item Conduit, and into a storage crate, which is connected to my refined storage. For the storage system itself, I only have one Controller, one Disk Drive, one Crafter, one Grid, one Crafting Grid, one Pattern Grid, and the Interface with an External Storage cable feeding back to the grid(as was described in the tutorial).
![image](https://user-images.githubusercontent.com/53992191/62833244-30ba0f80-bc01-11e9-9d44-d89892a389d8.png)

For my patterns, I had a number of simple essence patterns set up, for Quartz, Gold, Iron, and the different tiers of essences.
![image](https://user-images.githubusercontent.com/53992191/62833272-8ee6f280-bc01-11e9-9849-20ee0700b123.png)

I pulled one of each tier of essence out of my main storage, and placed them in the Interface to designate them for auto-crafting. When nothing immediately happened, I wondered if I needed to adjust settings, so I started clicking the visible buttons. Nothing at all changed until I hit the "No Damage mode" button, after which all of the stacks were suddenly full. I knew that I didn't have enough essences for that, so I immediately pulled up my main Grid and looked at its inventory, seeing that almost all of my basic essences were still there.
![image](https://user-images.githubusercontent.com/53992191/62833279-af16b180-bc01-11e9-8f60-6640a6039b44.png)

For this test, I only had a stack of 64 basic infernium essences in my grid, along with one of each higher tier. So, it only made the extra 63 tier 2 essences, and the 1 tier 3. Normally, 64 infernium essences would only create 16 tier 2 essences

**Comment by Darkere** [comment]
Ah. Thank you I got it now. Gonna report that to the mod dev. At least it's not as bad as I was initially thinking :)

**Comment by karami92** [comment]
I mean, considering that you can craft higher tier essences into multiple lower tier ones, that's still pretty bad xD With just that demonstration, I could break down the 64 tier 2 essences into 256 tier 1, then run that process again to just fill up on top tier essences

**Comment by Darkere** [comment]
I was thinking it was a dupe bug. But it's "just" changing metadata and you need at least one of the things you want to transform into. Bad but not horrible.
