### ISSUE TITLE
Mods on twitch doesnt work after I tried to change RAM used in minecraft

### ISSUE THREAD

**Issue by fernandisco12** [AllTheMods/ATM-3#904]
I tried to intall all the mods 3 and the first time I initated it, it said that more RAM was needed. I found the way to change it in Twitch, but now when I try to play any mod, the game doesn´t even initiate. 
Do you have any idea what can I try?
I've already try to unistall and intall again, but i have the same problem of the RAM and I have to change it again.

**Comment by Yamza** [comment]
Sounds like you've done it wrong, but cant really be sure without some specific information. Follow this guide first and if you still have a problem tell us specifically what is happening. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
