### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by Jherodthejadeprince** [AllTheMods/ATM-3#906]
When trying to craft the 'Net' from Water Strainer the recipe only outputs 2 string for a loss of 1 string. I have tried every crafting table, and even inventory crafting from Cyclic. The problem seems to originate because string is listed in the Ore Dictionary as -cropFlax.

**Comment by Jherodthejadeprince** [comment]
The only work around I have found was to use a worktable from Forestry.

**Comment by FallenEagle1** [comment]
What modpack version (numbers please)

**Comment by Jherodthejadeprince** [comment]
v5.12.1

**Comment by FallenEagle1** [comment]
Update. This issue was fixed in 5.12.3
