### ISSUE TITLE
Add VanillaFix mod

### ISSUE THREAD

**Issue by twothe** [AllTheMods/ATM-3#907]
Please add the mod [VanillaFix](https://www.curseforge.com/minecraft/mc-mods/vanillafix) to the list of mods.

Aside from some minor performance enhancements this mod adds one crucial thing: it catches client crashes and allows you to continue to play or to return to title screen instead of instantly closing the client.

In a modpack that takes about 10 minutes to load this feature removes a lot of pain for players. Additionally it will give the player a nicely formatted error log link that can be posted here, which would be a benefit for you in deciphering player issues.

**Comment by martmists** [comment]
Vanillafix only catches non-breaking errors, which are ignored by forge by default. This wouldn't change anything. Additionally, It's been rejected on the mod lists for both ATM 3 and ATM 3 Remix already.

**Comment by Yamza** [comment]
The reload feature doesnt even work with the pack, and vanillafix adds as many issues as it fixes.

**Comment by twothe** [comment]
No it actually catches all the errors. I have this manually added and it prevent already a lot of otherwise client crashes. I also never had any issue with that mod, I am not sure what you are referring to.

**Comment by FallenEagle1** [comment]
It does not catch all errors (gracefully) but besides the point, we have other concerns for the mod that we do not wish to put it in the pack. On top of that, atm3 is only getting bug fixes at this point.
