### ISSUE TITLE
Wizardry unicorns

### ISSUE THREAD

**Issue by Camicazz475** [AllTheMods/ATM-3#908]
Unicorns don't spawn in wizardry dimension, wizardry github says this is an issue with the version used and is fixed in later versions. updating the mod manually would be a pain as around 8 of us play on a server so we would all have to do it ourselves. Any chance of the mod being updated in the modpack?

**Comment by FallenEagle1** [comment]
What version of the modpack are you using?

**Comment by Camicazz475** [comment]
5.12.1

**Comment by FallenEagle1** [comment]
Update. 5.12.3 is out and has the updated mods
