### ISSUE TITLE
actual additions empowerer dont work

### ISSUE THREAD

**Issue by flamingram** [AllTheMods/ATM-3#909]
## Expected Behavior

should beam energy to it to empower it

## Current Behavior

not doing that even though i have it in the right places and powered
![2019-08-17_17 03 14](https://user-images.githubusercontent.com/34726796/63218492-f248b700-c110-11e9-81e8-948bce2b8484.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
The one display stand is too far away (the farthest one in the picture)
