### ISSUE TITLE
Suggestion - Add PlusTiC

### ISSUE THREAD

**Issue by Lazarix** [AllTheMods/ATM-3#91]
would it be possible to add PlusTiC to the pack?
https://minecraft.curseforge.com/projects/plustic

**Comment by Landmaster** [comment]
@Lazarix [There's already a request to get that mod added in the official suggestions page.](https://github.com/AllTheMods/ATM-3/issues/1#issuecomment-322057488)

**Comment by OrdinatorStouff** [comment]
closing this favoring official suggestions page
