### ISSUE TITLE
Thermal Expansion Redstone Furnace Burns all Wood into Jungle Wood

### ISSUE THREAD

**Issue by FriscoBowie** [AllTheMods/ATM-3#912]
## Expected Behavior

Wood should be burned into Charcoal when placed into the Redstone Furnace.

## Current Behavior

Wood is burned into Jungle Wood when placed into the Redstone Furnace.

## Steps to Reproduce

1.Power up Redstone Furnace.
2.Place any Wood into Redstone Furnace.

**Comment by darkdice** [comment]
Just ran into this issue on multiplayer server as well. Breaking redstone furnace does not help. Regular furnaces will burn wood logs into charcoal correctly

**Comment by darkdice** [comment]
One possible solution: Change/Add recipe to mod of the furnace below..
"mods.thermalexpansion.RedstoneFurnace.addRecipe(<minecraft:charcoal>, <minecraft:logWood>, 400);"

**Comment by virtualdxs** [comment]
Reproduced on All The Mods 3 Remix in multiplayer. This definitely wasn't happening before.

**Comment by Pelotrio** [comment]
Seems to be working now
