### ISSUE TITLE
Server crash world gen?

### ISSUE THREAD

**Issue by taxoz504** [AllTheMods/ATM-3#915]
Hey, im not the best a reading minecraft crash logs so sorry about that first if all,

i have a server running with a frined we are just 2 players, the server got 7 GB of ram ( 5 GB of ram on the first crash )

The server is crashing when we move fast where the world has not been generated yet is there anything i can do?

i have attached the crash logs if any other files is needed to help me with this issue please tell me

( for pastebins )
Crash 1 https://pastebin.com/WqsTgGUf
Crash 2 https://pastebin.com/XTaEquNK

[crash-2019-08-23_18.50.42-server.txt](https://github.com/AllTheMods/ATM-3/files/3537774/crash-2019-08-23_18.50.42-server.txt)
[crash-2019-08-25_00.13.56-server.txt](https://github.com/AllTheMods/ATM-3/files/3537775/crash-2019-08-25_00.13.56-server.txt)

**Comment by Naoya99** [comment]
To avoid the crash, you must change an option in the server.properties
change max-tick-time=60000 to max-tick-time=1200000
