### ISSUE TITLE
Map doesn't have recipe to expand

### ISSUE THREAD

**Issue by TheNoobisHere** [AllTheMods/ATM-3#918]
Trying to expand the map doesn't work using vanilla recipe and I'm unable to find any modded way to do it.

## Expected Behavior
Surrounding a map with 8 paper should expand the map by one level

## Current Behavior
Surrounding a map with paper does nothing

## Possible Solution
Check check recipes to see if vanilla method was removed for some reason

## Steps to Reproduce
1. Create world in creative
2. Spawn crafting table, empty map, and 8 paper
3. Place crafting table down and surround map with paper
4. Activate (rightclick) on empty map to create actual map
5. Surround map with paper in crafting table again

## Log
N/A

## Detailed Description
Add the vanilla recipe for expanding the map

**Comment by Pelotrio** [comment]
Seems hard to track down. I will take a look at it

**Comment by Pelotrio** [comment]
Intended feature from the Bibliocraft mod
