### ISSUE TITLE
Client crash multiple users when loading into certain chunks

### ISSUE THREAD

**Issue by Gpauxe** [AllTheMods/ATM-3#919]
## Expected Behavior
I expect the game to load the chunk without crashing

## Current Behavior
It crashes

## Possible Solution
I have lots of crash logs if that will help.

## Steps to Reproduce
1. Walk too close/teleport to the chunk I have with lots of machines in it
2. Crash
3. Reload Game
4. flip a coin, heads crash tails load just fine until you leave the chunk load distance and then get close enough to it again.

## Log
https://gist.github.com/Gpauxe/07e6bc220af125af8504336e8f48f799
I have more crash logs if necessary (these are the most recent 4 out of the 24 crash logs)

## Detailed Description

Help I suppose

**Comment by Darkere** [comment]
In p455w0rdsLib.cfg disable the first 2 options.

**Comment by Gpauxe** [comment]
Is that in the server files or client config files?

**Comment by Darkere** [comment]
client

**Comment by Gpauxe** [comment]
I disabled enableshaders but EnableVanillaLightingEffects was already set to false by default those are the options you are referring to right? I'll test it out now.

**Comment by Gpauxe** [comment]
Update 1:
Issue appears resolved, will test accross the rest of the users next, would editing the server cfg file adjust it for the other players or would they still need to update their config file individually?

**Comment by Darkere** [comment]
The config only works client side. Changing it on the server will not help.

**Comment by Gpauxe** [comment]
Thank you for the help, I'll report back in tonight (in about 5 hours) to verify resolution and close the ticket.

**Comment by Gpauxe** [comment]
Issue resolved: Thanks to Darkere!
