### ISSUE TITLE
All The Mods 3 doesn't work at all

### ISSUE THREAD

**Issue by Wearelegion99** [AllTheMods/ATM-3#920]
## Log

https://gist.github.com/Wearelegion99/4396408f49359af4a8bd909d7e2f3c7a

The game wont load and launcher keeps crashing

**Comment by Darkere** [comment]
This is a twitch error. Restarting has fixed it for me before but plenty of other people have tried and it didn't work for them. Try restarting PC as well. 

As alternative MultiMc exists. https://www.reddit.com/r/allthemods/comments/970n2e/how_to_install_twitchmultimc/
