### ISSUE TITLE
Feeding two apples one after the other crashes the game

### ISSUE THREAD

**Issue by IDoNotExist3** [AllTheMods/ATM-3#923]
## Expected Behavior

What should happen is the fox should eat both apples when apples are right-clicked on it then I should go on my merry way.

## Current Behavior

On right-clicking the second apple the game crashes to the launcher and I get the following error message:
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemFood

## Steps to Reproduce

1. Tame mysticalLib fox
2. Feed two apples one after the other
3.Crash
4.

## Log

https://gist.github.com/IDoNotExist3/e78de14f145f301399044d324636dedb

**Comment by Yamza** [comment]
Gunna want to post a crash report.

**Comment by IDoNotExist3** [comment]
Ah my bad

**Comment by IDoNotExist3** [comment]
> Gunna want to post a crash report.
Do you mean the log?

**Comment by Yamza** [comment]
You said it crashed, so crash report.

**Comment by Yamza** [comment]
-Client Only:
Go to the Twitch App, click the `Mods` tab at the top, select `Minecraft`, then `Right Click` the pack icon and select `Open Folder`.

Open the crash-reports folder, if there is one, then find the latest crash.txt
OR
Open the logs folder, find the latest.log.
Copy the full contents of the log. (Right Click > Select All, then Right Click > Copy)

Go to https://gist.github.com/ (Make a free account if needed)
Paste the log into the provided space. Click Create Public Gist, Copy the URL in the address bar and paste it into chat.

If it is a crash report you may use: https://pastebin.com/ or https://hatebin.com/
latest.log WILL NOT FIT on those, use Gist!

**Comment by IDoNotExist3** [comment]
I accidentally hit ctrl + enter, so I posted it prematurely without the log, my bad. It's in there now

**Comment by IDoNotExist3** [comment]
https://gist.github.com/IDoNotExist3/e78de14f145f301399044d324636dedb 
Sorry my bad I was thinking of the error message it gave after I crashed, I didn't know it made a crash report in the files!

**Comment by Yamza** [comment]
Looks like this crash has already been fixed by the mod https://github.com/MysticMods/MysticalWorld/issues/33
You'll have to wait for a pack update to fix it unless you are in single player, if so you can attempt to update mystical world yourself, but it's usually not a good idea to randomly update mods so if you do backup first.

**Comment by IDoNotExist3** [comment]
Alright I'll wait, I'll try to not feed two many apples to my foxes. Sorry for the difficulty!
