### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Gpauxe** [AllTheMods/ATM-3#924]
## Log

https://gist.github.com/Gpauxe/d0514a08eeb6f07eb12953a3895b55cb

## Detailed Description

Me and my friends have been crashing the server at random when we are all on, I am unsure how it happens but I have 2 crash reports posted, any help is appreciated.

**Comment by Yamza** [comment]
Something about pnumaticcraft. Hopefully that can jog someones memory.
