### ISSUE TITLE
Downloading via Twitch failing due to timeout

### ISSUE THREAD

**Issue by OnesFortuna** [AllTheMods/ATM-3#926]
Upon attempting to download All the Mod 3 and All the Mods 3 Remix, they have both failed at the mod for the betweenlands, resulting in all prior progress being removed, and having to start the download from the begining. 

## Expected Behavior
It should download and not timeout.

## Current Behavior
The download timesout, and all progress is lost.

## Steps to Reproduce
1. Initiate download of All the mods 3 on twitch app.
2. Get to The Betweenlands 
3. Download will fail and the following will appear. Timeout attempting to download: https://edge.forgecdn.net/files/2743/842/TheBetweenlands-3.4.10-universal.jar

**Comment by FallenEagle1** [comment]
This is a twitch error, there isnt really anything we can do about it. If you keep trying it sometimes works, otherwise another launcher like multimc will work.
