### ISSUE TITLE
Java error for server

### ISSUE THREAD

**Issue by EldritchDragon** [AllTheMods/ATM-3#928]
I ran the ServerStart.bat and came up with this error. 
[debug.log](https://github.com/AllTheMods/ATM-3/files/3619424/debug.log)

**Comment by Hirsu** [comment]
Read the last line in your log.

[00:21:20] [main/INFO] [net.minecraft.server.MinecraftServer]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.

Your server won't start because you haven't set the EULA to true yet.

**Comment by EldritchDragon** [comment]
That was from when I accidentally ran the minecraft_server.jar, but this error came up when I ran the batch file. https://i.imgur.com/2ZYW3qx.png

**Comment by Yamza** [comment]
Update Java to the latest 64-Bit version here. Select Windows Offline (64-bit).
https://java.com/en/download/manual.jsp

**Comment by EldritchDragon** [comment]
I did follow the link, and updated java. It still gave me the same error.

**Comment by EldritchDragon** [comment]
[serverstart.log](https://github.com/AllTheMods/ATM-3/files/3622063/serverstart.log)
I don't know if this is needed

**Comment by Yamza** [comment]
To check java version open a command window (windows key + r, type cmd, press enter)
Type `java -version`
You want to see 1.8.0_ on line 1 and 64-bit on line 3 like so:
```
Java Version "1.8.0_201+"
Java(TM) SE Runtime Environment (*build 1.8.0_201-b09*)
Java HotSpot(TM) "64-Bit-Server-VM" (*build 25.201-b09, mixed mode*)
```

**Comment by EldritchDragon** [comment]
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode, sharing)
Is what I got

**Comment by Yamza** [comment]
So do what I said previously, you dont have 64 bit.

**Comment by EldritchDragon** [comment]
Ok, thank you. Then am I looking for the offline 64-bit download from the Java site?
