### ISSUE TITLE
Alkahestry Override Incorrectly Typed, Missing Charging and Crafting GrowthEssence

### ISSUE THREAD

**Issue by strategist1164** [AllTheMods/ATM-3#929]
## Expected Behavior

ATMTweaks Growth Essence charges Tome of Alkahestry: Per commit d5c0585, where Tome of Alkahestry charging recipes were balanced, .jsons for glowstone and redstone were disabled and the enabled ones since then are for ATM Star and Growth Essence.

## Current Behavior

Tome of Alkahestry is not capable of being charged by Growth Essence

## Possible Solution

Both the below .json files identify the growth essence as "item": "minecraft:item_material", "data": 1 but it should be "item": "atmtweaks:item_material", "data": 1

config\xreliquary\alkahestry_overrides\charging\growthessence.json
config\xreliquary\alkahestry_overrides\crafting\growthessence.json

## Steps to Reproduce

1. Have Tome of Alkahestry and Growth Essence
2. Be unable to charge Tome with Growth Essence
3.
4.

## Detailed Description

While searching for a way to charge the Tome, I discovered that ATM3 overrode the materials for balance reasons. It seems balanced to me having both the Growth Essence for a small charge and the ATM Star for a full charge, but currently only the ATM Star works. 

Also, the nether star and growth essence crafting only gives 1 of the item while also eating 1 of that item, I imagine that means you don't want those to be duped for balance. Why have those as crafting options? disable them, change the output to 2 in order to dupe once, or change the charge cost to 0 since all the crafting recipe is doing at the moment is wasting charges.

**Comment by FallenEagle1** [comment]
We talked about this a while back and had decided not to have growth essence charge it either, so it was a happy accident and we didn't change/fix it. End goal for the tome is figure out a solid, balanced way to use the tome, but that hasn't happened, so it's just stayed the way it has for now

**Comment by strategist1164** [comment]
Well, from a balance point of view compared to mystical agriculture... I set up an auto inferium seed setup and let that go while I did some grinding on thaumcraft and getting the mats for the tom. By the time I got the tome, I had all the mystical agriculture seeds through tier 4, tier 5 seeds requires some Growth Essence to which I have not gotten to. The moment I get Growth Essence, I'll be able to make the tier 5 and 6 seeds of mats that I already have, including nether star seeds. One of the most useful and perhaps cost efficient uses of the tome is duping diamonds. To take that as an example, I can get all the diamonds I will ever need with mystical agriculture after I make tier 5 seeds. I can already get all the diamonds I will ever reasonably need with the digital miner and a couple relocates. Anything that the digital miner can get makes duping those items with the Tome much much less OP. Now, as for Nether Stars even if the recipe was in the game to be able to dupe for one more, it certainly doesn't seem OP. Why? If the only way to charge the Tome is with the ATM Star, there is no point since one of the ingredients to make the ATM Star needs Nether Shards from mystical agriculture, the very stuff used to craft a nether star from mystical agriculture. So currently, progression wise, in order to use the tome the player would already have the capability of making as many nether stars as they want quickly with the phytogenic insolator from thermal expansion. There is currently no reason to waste the resources to make an ATM Star to charge the tome other than saying that you have done it since by that point anything the tome can be used to dupe, the player has in abundance. This is tantamount to simply disabling the tome is the modpack. Perhaps you guys have already thought all this through, but the balancing of the tome can be quantified by material cost, charges, and progression improvements that it would provide (currently none). Since the tome cannot dupe nether stars currently, it seems like a no brainer to allow growth essence to charge it. Allowing both growth essence to charge the tome and it to dupe nether stars would allow someone to acquire just one in order to get the four necessary to craft a mystical agriculture seed (progression improvement). If that is not acceptable, require the recipe to have 4 nether stars and the tome to output 5 (net +1) and have the charge cost be greater than added by a growth essence requiring the charges of at least 2. There, balanced with mystical agriculture where you need 4 nether stars and 2 growth essence. Mystical Agriculture is much better at creating items out of thin air than the Tome and if you think it is balanced but cannot balance the Tome, then someone is overvaluing the Tome. Allowing growth essence to charge to the Tome should be fine, balancing should be in the form of the number of charges it gives. As I am unsure how difficult getting royal jelly is, 50 charges may be too much, but then again I don't even see using growth essence to charge the tome until I've made the tier 5 and 6 mystical agriculture seeds which makes the Tome redundant. As a programmer, every programmer should know that it is impossible to get every feature in and perfect so it should be workable. Setting the Tome requirements so high as to be irrelevant does not seem workable to me. Either someone is being unreasonable about the balancing of the Tome (overvaluing it and refusing to compromise) or you guys should just decide on some sort of workable balance and do that. In the mean time, I'll adjust my own configs to enable the growth essence to charge since I only made the Tome to get around the need, for the moment, to make growth essence for the nether star seeds. This still forces me to make them to dupe nether stars, but I'll grudgingly (because bees) admit that this is more balanced than charging the Tome with redstone or glowstone.

**Comment by FallenEagle1** [comment]
There was plans for adding more items, but it wasnt high on the priority list, so it wasnt done in favor of fixing bugs instead. Things you mentioned in that long section were already thought of. Theres just only so much time to work on things and it hasn't happened, so it was left as is until time could be found.

**Comment by FallenEagle1** [comment]
Also, realized that this is in atm3 and not in remix. Atm3 isnt getting much for changes, mainly just mod updates as they fix bugs. If there are any changes to the tome, it will be in remix and not atm3
