### ISSUE TITLE
Wrong Modifier

### ISSUE THREAD

**Issue by meXc** [AllTheMods/ATM-3#93]
Mod: Tinkers' Construct
What happened: Ardite Plate gives the Head modifier when crafting a Hammer -> Stonebound
Expected: Extra Modifier -> Petramor
Source: Materials and You

**Comment by OrdinatorStouff** [comment]
according to boni in [this issue ](https://github.com/SlimeKnights/TinkersConstruct/issues/2811#issuecomment-287535064) this is intended behavior: "Large plates are head components for the hammer, hence they give the head trait."
