### ISSUE TITLE
Client Disconnects and cannot reconnect after trying to charge Wireless crafting Terminal with Flux-Infused JetPlate after updating to 1.5.0

### ISSUE THREAD

**Issue by Arudinne** [AllTheMods/ATM-3#930]
Hello,

Recently the server I am playing on updated it's mod pack to All The Mods 3 - Remix 1.5.0,

After updating I encountered several issues where I would get disconnected. Following that anytime I tried to rejoin I would get disconnected immediately and the only way to resolve my issue was to restore my playerdata from a backup.

It looks like anytime I selected my Wireless Crafting Terminals 2 Wireless Crafting Terminal on the hot bar my client would disconnect me from the server and state "Internal Server Error"

Working with one of the admins we traced the error the charging function of my Flux-Infused Jetplate. Once I turned the charger off, I stopped having the issue. Below should be the relevant log data.

## Expected Behavior
Client is disconnect from the server and cannot reconnect until their player data is restored from an older version where the wireless crafting terminal is not the last selected item

## Current Behavior
Client does not disconnect

## Possible Solution
I opened an issue with the Mod Author - they have a published a fix:
https://github.com/Tomson124/SimplyJetpacks-2/issues/143

## Steps to Reproduce
1. Have Flux-Infused JetPlate (have not tested any other Simply JetPack)
2. Craft or Pickup a Wireless Crafting Terminals 2 Wireless Crafting Terminal
3. Select it on your Toolbar
4. Crash

## Log
https://pastebin.com/FG0XAgYd

## Detailed Description
The admin's on my server said that it wouldn't be easy to backport the fix and that we'd need a pack update to more easily implement it. Is it possible to release a hotfix?

**Comment by martmists** [comment]
I believe this was fixed in the 1.5.1 hotfix, give that one a try and if the issue persists, open an issue on the wireless crafting terminal repository.

**Comment by johnb432** [comment]
ATM3 1.5.1 still has this problem for me. It crashes when the charging ability of the Flux-Infused Jetplate is turned on and when you put any of the wireless crafting terminals from AE2WTLib into your hotbar.
