### ISSUE TITLE
ATM3 Unknown CTD

### ISSUE THREAD

**Issue by NazTDragN** [AllTheMods/ATM-3#931]
## Expected Behavior

Initial World Creation

## Current Behavior

Lock on blank background prior to world load then CTD after about 2-3min.

## Possible Solution
Unknown

## Steps to Reproduce
Unknown

## Log

https://gist.github.com/NazTDragN/a68aaa515dcef2cb73aefada89d8db6c.js

## Detailed Description
I'm not too sure on what I'm supposed to be looking for in the crash log, so I have no idea as to what steps I should try. Crash is just prior to the initial World Generation, during the blank background that has the "Tip:" across the bottom.

**Comment by Yamza** [comment]
Were you in a world or on a server prior to attempting to make/join another world?
