### ISSUE TITLE
F7 Light level overlay not working.

### ISSUE THREAD

**Issue by jordantheranga** [AllTheMods/ATM-3#932]
while playing SSP the overlay will not work.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
Go into the controls and look for dark spots, and it probably will say none. Switch it to f7 and then it should work. For some reason with some clients it is not set all of the time.

**Comment by jordantheranga** [comment]
Awsome thanks, i check the controles but must of missed that one.
