### ISSUE TITLE
AE2 autocrafting ultimate induction provider fallback crashes server

### ISSUE THREAD

**Issue by Mstori** [AllTheMods/ATM-3#933]
Trying to auto-craft one ultimate induction provider on my AE2 network causes this repetitive fallback message on server, eventually crashing and corrupting world. Needed to fallback to backup file.

This happens every time I try to craft one or more ultimate induction providers from mekanism. I attached the parts of the log that show the version of the game and the repetitive fallback message. 

[log.txt](https://github.com/AllTheMods/ATM-3/files/3666281/log.txt)

**Comment by FallenEagle1** [comment]
Known issue with the circuits needed to make the parts. Currently I'm not aware of a fix for this, and have just suggested manually crafting that particular part in the mean time.

**Comment by Mstori** [comment]
Alright at least its known. Thanks
