### ISSUE TITLE
Game crash, Psi ParticleRenderDispatcher error

### ISSUE THREAD

**Issue by Sticcia** [AllTheMods/ATM-3#934]
## Detailed Description

Game crashes with no "crash report" but creates a log (attached below).
Crash is pretty random, often happens when I load the world or when I sort a chest or inventory.
Reading through the log i noticed line 79:
`J 72476 C1 vazkii.psi.client.fx.ParticleRenderDispatcher.onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V (104 bytes) @ 0x000000000bcdb56c [0x000000000bcd9820+0x1d4c]`
Which makes me think it's a Psi related issue.

## Possible Solution

Probably removing the mod would solve the issue but I have not played with Psi itself yet, I would love to try it out so I wish to not remove the mod completely.
Another solution could be removing particles for Psi?

## Steps to Reproduce

1. Load the game
2. Open a saved world
3. Game crashes randomly during playthrough
4. Check instance folder for log

## Log

https://gist.github.com/Sticcia/2c1aae6d35bd21443ee7418e61b7019d

**Comment by martmists** [comment]
ATM 3 is fairly unmaintained, does this still happen for you on ATM 3 Remix?

**Comment by FallenEagle1** [comment]
Atm3 is maintained for bugs. It's just not getting new mods or concepts added. That looks like something went wrong with java itself (because of a mod, but still) so I would go through this and see if it fixes it. The java being used is quite old. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by Sticcia** [comment]
I'm using Java 8 update 221 which is the recommended version on the official Oracle website.
Should I be using a newer one instead?
I noticed, on the post you linked, a suggestion to try install Optifine, I thought installing Optifine could cause more issues, I might try that.
At the moment I am playing the modpack without Psi and MagicalPsi but I'm considering switching to ATM3:Remix.
Do you think it's a bad idea to move the saved world across modpacks?

**Comment by Darkere** [comment]
You are using the version of Java that comes prepackaged with Minecraft which is version 51. The -version1.8 argument in that post allows you to use the java that you have installed. 

There is large potential for things to break when moving from atm3 to remix. But it depends on what you've done, explored and built.
