### ISSUE TITLE
Mekanism Thermal Evaporators cause screen bug.

### ISSUE THREAD

**Issue by AverageOtter** [AllTheMods/ATM-3#937]
## Expected Behavior

Assemble a thermal evaporator, pump in water makes brine everything is good.

## Current Behavior

Makes thermal evaporator (any size through my testing) add water via ender conduits or pipes from a sink. and a screen bug happens blinding me 360 degrees within a ~5 block radius. As I move away degrees shrink giving me an actual view. At about 50 blocks (roughly) I have the full view back. Disable the evaporator (via destroying a block) bug disappears. No UI or escape menu. The color of the blackout mimics the sky color.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tth05** [comment]
Same here
