### ISSUE TITLE
Able to place IC2 Forge Hammer into Morph-O-Tool

### ISSUE THREAD

**Issue by Stifling-Bossness** [AllTheMods/ATM-3#940]
## Expected Behavior
Should not be able to place a consumable tool into the morph-o-tool.

## Current Behavior
Able to place a forge hammer into the morph-o-tool, and use as a normal forge hammer. Once expended, the entire morph-o-tool is deleted.

## Possible Solution
Add Forge Hammer to blacklist.

## Steps to Reproduce
1. Make Morph-O-Tool
2. Make Forge Hammer
3. Add Forge Hammer to Morph-O-Tool by placing them both into a crafting table.
4. Switch to Forge Hammer in the Morph-O-Tool by crouching and scrolling the mouse wheel.
5. Make lots of plates with the Morph-O-Tool'd Forge Hammer.
6. Observe as the Morph-O-Tool disappears entirely upon consuming the Forge Hammer.

**Comment by Pelotrio** [comment]
Its not possible to blacklist a single item in the morphtool config.
