### ISSUE TITLE
Crash while puttin filter upgrade on EnderIO conduit

### ISSUE THREAD

**Issue by Solid-Metal** [AllTheMods/ATM-3#941]
## Steps to Reproduce
1. go to end realm
2. try to put filter upgrade to item conduit

not yet try it again on overworld

## Log
https://gist.github.com/Solid-Metal/08da0b0013a59e7dd4966f7d6131494a

**Comment by Sakata-MC** [comment]
https://github.com/NillerMedDild/Enigmatica2Expert/issues/1311

**Comment by Sakata-MC** [comment]
Hopefully we'll get an update to ATM3 soon-ish, this appears to be sorted in mod

**Comment by Solid-Metal** [comment]
yeah, i figured if i put the item/fluid conduit first and then put the filter and set it, and then after that put the redstone conduit and set those, it works fine
