### ISSUE TITLE
Game Crashing (Remix)

### ISSUE THREAD

**Issue by JamesMuhammad** [AllTheMods/ATM-3#942]
I can start ATM 3 into the game menu, but when I open my world, it crashes. 

Video: https://youtu.be/K00-BISY93Y (It crashes at the end (Recording Software Stops Recording Automatically))

Log:https://gist.github.com/JamesMuhammad/5ae2cc1b7407c6795e315f24efc7cc08

**Comment by martmists** [comment]
If this is a remix issue, open it on the ATM 3 Remix github instead.

**Comment by Pelotrio** [comment]
Report in ATM 3 Remix repo.
