### ISSUE TITLE
Server Crash NoSuchMethod

### ISSUE THREAD

**Issue by GoldiePlay** [AllTheMods/ATM-3#943]
When Trying to start a Server with Version 1.6.1 it keeps crashing.

## Log

https://gist.github.com/GoldiePlay/0a1620282817d9e71dedd69f7a212cf5

**Comment by Trinsdar** [comment]
Looks to be an issue with nature's compass

**Comment by GoldiePlay** [comment]
Sry I somehow managed to post the issue here instead of in the Nature Compass Issue Tracker. I am sorry :)
