### ISSUE TITLE
Project: Red Tin Ingots being produced from blocks instead of ThermalFoundation

### ISSUE THREAD

**Issue by TheAlchemist606** [AllTheMods/ATM-3#944]
As the title suggests, Tin Ingots crafted from Tin Blocks become Tin fro Project: Red rather than ThermalFoundation.

## Expected Behavior

UniDict should unify the recipes such that ThermalFoundation is the only mod from which ingot types should stem from, save for ingots that ThermalFoundation does not have.

## Current Behavior

Crafting tin ingots from ThermalFoundation yields Project: Red ingots.

It is to note that this not only happens with tin, but every other metal that Project: Red handles (copper, silver, etc.).

## Steps to Reproduce

1. 
![ATM3 Wrong Tin](https://user-images.githubusercontent.com/11202263/69923186-cd364500-1470-11ea-82ef-2ed3431f449d.png)

2.
3.
4.

**Comment by daradermody** [comment]
I'm seeing this too. Having two types of ingots for different materials is very annoying.

**Comment by Pelotrio** [comment]
I will see if I can fix that.

**Comment by Pelotrio** [comment]
Fixed in newest version
