### ISSUE TITLE
System cannot find the file settings.cfg

### ISSUE THREAD

**Issue by Rominou78** [AllTheMods/ATM-3#945]
Hi everybody !

First of all I'm so sorry for my english because I'm french... lol
So for a while I'm trying to create a ATM3 Remix server and just after unzip the server and lauch the file ServerStart.bat, my cmd crash and closes. I try to screen what's displayed and in first line, we can read (in french lol) that "System cannot find the file settings.cfg". So if someone have the solution I'll take it ^^

Thank you !

![cmd](https://user-images.githubusercontent.com/59176168/71370098-13348380-25ad-11ea-9594-5e81ebc4f094.png)

[serverstart.log](https://github.com/AllTheMods/ATM-3/files/3995648/serverstart.log)

**Comment by Crown-afk** [comment]
Hey ! Sorry for the late answer, (again sorry if I do some mistakes but I'm french :D) Did you decompress your zip file ?
