### ISSUE TITLE
Failed To Load

### ISSUE THREAD

**Issue by PiZzAPlayz** [AllTheMods/ATM-3#947]
When I load the mod-pack up the launcher shows this error:

`Failed to download file, the file contents differ from what was expected.`
`Name: jna-4.4.0.jar`
`URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar`
`Filename on disk: jna-4.4.0.jar`
`Path: C:\Users\nikol\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar`
`Exists: File`

I was wondering if I have to download something else or if I have to restart my computer. Here is also a screenshot: 
![ScreenshotMinecraftError](https://user-images.githubusercontent.com/59452769/71688618-c77c9980-2d65-11ea-9c8d-6555c54db9af.jpg)

**Comment by martmists** [comment]
What launcher are you using for this? This does not seem like any of the officially supported launchers for ATM-3
