### ISSUE TITLE
Certain Item Duplication Bug [ATM3-Remix Version 1.5.2]

### ISSUE THREAD

**Issue by Guthix777** [AllTheMods/ATM-3#948]
When using the Destructive enchantment from Thaumcraft and you destroy an enchanced alloy smelter you get 2 enhanced alloy smelters instead of 1. I assume this is because the block really fills 2 block spaces and the destructive enchantment then destroys and drops 2 blocks.

## Expected Behavior

The Destructive enchantment should NOT drop 2 items when destroying a "2 for 1" block.

## Current Behavior

If a tool with the Destructive enchantment destroys a "2 for 1" block, then that block drops 2 items instead of 1. This seems to only work when destroying the original block that was placed, for example an iron door only drops 2 items when the bottom part is destroyed.

## Possible Solution

Self explanatory, just remove the duplication. Im not a developer so I dont have any idea how to di that.

## Steps to Reproduce

1. Add the Destructive enchantment to a tool. (If you try and break wood with a pickaxe that has the enchantment this wont break 3x3)
2. Place a block that takes up 2 places in the world. (Example: Door, Enhanced alloy smelter)
3. Break the block that was originally placed with the enchanted tool
4. 2 Items are now dropped instead of 1

**Comment by Pelotrio** [comment]
This is probably not fixable without changing enderio or Thaumcraft itself
