### ISSUE TITLE
[ATM3 3.0] Reproducable Client-Crash when opening Acclimatiser's GUI

### ISSUE THREAD

**Issue by msoehnchen** [AllTheMods/ATM-3#95]
Issue: Client-Crashes with "Error: java.lang.NullPointerException: Rendering screen" after accessing the GUI from the 'Acclimatiser' from 'Binnie's Genetics'

The Block itself causes no Problem, only the GUI of the block makes the client Crash.

ATM3-Version: 2.8 and also on 3.0

Additional files:
[Crashlog]http://paste.ubuntu.com/25355441/
[latest.log]http://paste.ubuntu.com/25355450/

for contact, ask 'maradu' ingame on the ATM3-Server (atm.g.akliz.net) or mail to m.soehnchen@gmail.com

**Comment by ellis-** [comment]
This not only affects the Acclimatiser but a lot of Binnie machines.
Latest version of the mod is supposed to fix the issue.

https://github.com/ForestryMC/Binnie/issues/253

**Comment by OrdinatorStouff** [comment]
many binnie's issues have been resolved in these recent updates.
