### ISSUE TITLE
Simplified packmode doesn't affect all recipes

### ISSUE THREAD

**Issue by mikius2** [AllTheMods/ATM-3#950]
When I change packmode to simplified in the cfg, it reverts most recipes, but not all of them. Specifically, I noticed the gendustry recipe for energy bee is still disabled in JEI. I tried activating the default recipe in mutatron anyway and it didn't work. This is all on 1.5.3 version.

## Expected Behavior
All the recipes should revert to the recipes in the mods.

## Current Behavior
Some of the recipes (well, I only really noticed one - energy bee, could be others of course) remained disabled / changed.

## Steps to Reproduce

1. Switch mode to simplified in packmode.cfg
2. Open JEI, check the recipes.
3. Some recipes are now simplified (angel ring for example)
4. The energy bee is still uncraftable through gendustry.

## Detailed Description
If possible, it would be best if simplified mode affected the energy bee recipe as well. If that is unfeasible, it would help to get some instructions on how to change that recipe back on my own.

Thank you!

**Comment by Pelotrio** [comment]
You have to remove the energy bee from this blacklist https://github.com/AllTheMods/ATM-3/blob/4de8c6970fde760e30554b1b2336e3dd2dac63b2/overrides/config/forestry/apiculture.cfg#L42
