### ISSUE TITLE
Item Filter Block Crashes Client/Server

### ISSUE THREAD

**Issue by qdaniel05** [AllTheMods/ATM-3#951]
## Expected Behavior

You place down the item filter block, games continues on as normal, it shouldn't crash.

## Current Behavior
I place down the item filter block from RFTools then my client stops responding, and crashes. Same thing occurs with a server I purchased and i can't boot it back up.

## Possible Solution
crash report states exception in server tick loop.

## Steps to Reproduce

1. Start ATM3 
2. Load into a minecraft world in creative or survival
3. Place down the item filter block from RFTools

## Log
https://gist.github.com/qdaniel05/45f065234956e2824c1fb9f54b9b1e58

## Detailed Description
maybe incorporate it in the next update?

**Comment by Pelotrio** [comment]
Seems to be working fine now
