### ISSUE TITLE
Server lagging like crazy early game

### ISSUE THREAD

**Issue by craftboy1012** [AllTheMods/ATM-3#952]
I've been playing on a server with my gf for about a day or two
I set up a builder and a lava pump for energy and resources
Yesterday I had no problem playing and left the server open so my TiC tool could upgrade

I connect now and it takes a good 10-20 seconds before something loads.
I have the chunks loaded through FTB all dimentions have 20 tps,

The server is giving no feedback of issue with ticks and I have 4G of ram for the server

**Comment by aqualxx** [comment]
You should probably put some more ram
