### ISSUE TITLE
ForeverStranded There was an Error, Code: "ForgeDownloadURLNotFound"

### ISSUE THREAD

**Issue by Amboss11** [AllTheMods/ATM-3#956]
![unknown](https://user-images.githubusercontent.com/62813264/77832675-07baa080-7138-11ea-8e04-49db14f692f6.png)
Does not Install forge
Its the newest Server Pack(Forever Stranded-1.9.9.1)

![unknown (1)](https://user-images.githubusercontent.com/62813264/77832785-cb3b7480-7138-11ea-9dae-691a0fbdefdd.png)

**Comment by KingCreb** [comment]
go int your settings file and paste 
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2511/forge-1.10.2-12.18.3.2511-installer.jar
where it says DISABLED in Forgeurl

**Comment by Lutenmake** [comment]
doesnt work and i tried everything i could find besides the discord server cause i couldnt find a link
