### ISSUE TITLE
ATM3:Remix Fetching addPacket for removed entity when breaking redstone

### ISSUE THREAD

**Issue by laserdragon23** [AllTheMods/ATM-3#957]
Server spams "[Server thread/WARN] [net.minecraft.entity.EntityTrackerEntry]: Fetching addPacket for removed entity"
Only seems to occur when we break Redstone ore.
Cause the server to lag hard server side making delay in item pickups and actions like breaking blocks talk twice as long

## Current Behavior
Causes large lag spikes when broken

## Possible Solution
I've read it might have been a removed mod conflicting but I'm not sure. 
Just a note, this is a new world on the 1.5.4 version of the pack.

## Steps to Reproduce

https://imgur.com/a/TOsXprM

1. Place Redstone. 
2. Break it.
3. Lag.

**Comment by Worthers7** [comment]
Bump this, I am also seeing this issue.

**Comment by btbenedi** [comment]
Bump, also seeing this

**Comment by Pelotrio** [comment]
Reopen if its still a problem

**Comment by fnar** [comment]
What was the fix? Was there a commit which addressed this issue?
