### ISSUE TITLE
Golden Bag of Holding sometimes deletes all contents when in creative.

### ISSUE THREAD

**Issue by Clonephaze** [AllTheMods/ATM-3#96]
Golden Bag of Holding sometimes, looks like it depends what slot it's in in your inventory, deletes all contents when in creative, including when you switch from survival to creative. I experienced this using Extra Utilities 2 version 1.5.2 in the current pack version

**Comment by OrdinatorStouff** [comment]
I see you have [reported it on EXU2 github](https://github.com/rwtema/extrautilities/issues/1660) as well, thank you.

[Apparently](https://github.com/rwtema/extrautilities/issues/1507) [this](https://github.com/rwtema/extrautilities/issues/1366) [looks](https://github.com/rwtema/extrautilities/issues/1351) [like](https://github.com/rwtema/extrautilities/issues/1294) [it's very common](https://github.com/rwtema/extrautilities/issues/1283)

So for now we could disable the bag OR just continue with the warning that contents are not safe.
