### ISSUE TITLE
Linux start script fails on clean install

### ISSUE THREAD

**Issue by thiakil** [AllTheMods/ATM-3#961]
## Expected Behavior

- Unzip server pack from curse (`ATM3-5.12.3_Server-FULL.zip` used)
- `chmod +x ServerStart.sh`
- Run `./ServerStart.sh` 
- Script installs forge ready for start

## Current Behavior

- Script unable to find bundled forge installer
- Script downloads the _universal_ jar, and saves it as `-installer`
- "installer" fails because it's not the installer (MC classes not found)
- process repeats because it still confuses the installer filename

## Log

https://gist.github.com/thiakil/38b36beee978823fa09b344baac14324

**Comment by whatthedrunk** [comment]
I just went though the process of getting all the updates we could into a new 6.0.0 release and updated the scripts to work like they do for ATM5. If you are still even playing and have issues let me know!
