### ISSUE TITLE
New Version 5.12.3 wont install, twitch app

### ISSUE THREAD

**Issue by Thomsn22** [AllTheMods/ATM-3#962]
## Expected Behavior
it should install version 5.12.3

## Current Behavior
it installed 5.12.2 again

## Possible Solution
IDK?

## Steps to Reproduce

1. install 5.12.2 and try to upgrade to newer version
2.
3.
4.

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/ATM-3/issues/964 
Follow the comment on there and also give 6.0.0 a shot.
