### ISSUE TITLE
Server crashes when loading in at a certain player's base

### ISSUE THREAD

**Issue by cruciex** [AllTheMods/ATM-3#963]
## Expected Behavior
Being able to play the game without the server crashing.

## Current Behavior
Server crashes when walking into a certain player's base area or using a waypoint to teleport there. Basically anytime I try going there the server crashes. The server generally doesn't crash when this player is at his own base, but sometimes it still does. For some context on the latest crash(es), I tried going to his base to use his portal to the mining world and crashed as I was using the teleporter. I rebooted the server and logged back in and my character died from being stuck in a wall immediately. I revived and tried to make my way back to retrieve my stuff but the server crashed as soon as I got there and I haven't been able to log back in without the server crashing.

## Possible Solution
I legit have no idea I don't know how to read crash logs and I'm not sure what is causing the crash.

## Steps to Reproduce

1. Walk into or teleport to player's base
2. Eventually looking at blocks generates the "waiting for server" prompt instead of giving details on the block you're looking at, like it is lagging out
3. Voila, server crash
 OR, in this specific instance where I can't log back in:
1. Start server
2. Log in
3. Server crashes and disconnects player

## Log
Edit: gave wrong crash report, provided link for correct one
https://gist.github.com/cruciex/ea6084e72d1e9cce29758991a6137fae 

## Detailed Description
We have already tried turning off mob spawners and his tree farm. Helped but isn't a full solution. Unsure what to do now.

**Comment by Pelotrio** [comment]
Your server is lagging so badly it forces a shutdown.
