### ISSUE TITLE
Problem with downloading 5.12.3

### ISSUE THREAD

**Issue by The-Heckening** [AllTheMods/ATM-3#964]
## Expected Behavior

it should download 5.12.3

## Current Behavior

Currently 5.12.2 is downloading in the place of 5.12.3

## Possible Solution

Fixing how to modpack downloads or fixing the downloaded version

## Steps to Reproduce

1. Go onto twitch
2. Click on the ATM 3 and go to versions
3. Download the pack for 5.12.3

**Comment by whatthedrunk** [comment]
I was able to install just fine but I recently also had to go though and do the following.
Backup all worlds you are about outside of twitch. 
Delete all folders where twitch files are.
Uninstall Twitch.
Make sure AppData\Roaming\Twitch is gone.
Install a fresh version of Twitch Launcher from the website.
Install Minecraft addon.
Increase RAM to 8GB.
Install and play.

**Comment by whatthedrunk** [comment]
Also if that does not work try  MultiMC but either way report on your progress.
