### ISSUE TITLE
[v6.0.0) Server and Client Scripts and Configs not matching

### ISSUE THREAD

**Issue by BSG-Ori** [AllTheMods/ATM-3#965]
Server owner updated the pack to 6.0.0 and we went to join. gave a "Fatally missing registry entries." A server error including something about the minecraft:wooden_door recipe. Tried with fresh client and server installs.

## Expected Behavior
Server should load and client should connect. They were fresh installs.

## Current Behavior
Server Loads, but client immediately disconnects, giving "Fatally missing registry entries" the first DC and displays a message saying that the mincraft:wooden_door recipes dont match the following times.

## Possible Solution
Copy client config and scripts folder and overwrite them in the server.

## Steps to Reproduce

1. download the v6.0.0 version of the modpack and serverfiles.zip
2. change eula.txt to true and start the server using the batch file.
3. start your client
4. attempt to join server and anguish at the fact that the game hates you.
5. (optional) spend 3 hours with someone else scouring the internet for answers and spend it in frustration.

To fix.
1. copy config and scripts folder to server files. 
2. start it. 
3. connect. 
4. relish in joy.

## Log
server does not give an  error. this is the client displayed message of error when connecting a second and subsequent time:

exception com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@172ca6a) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@1978eab7

## Detailed Description
Fix the scripts and/or config mismatch between the client files and server files.

**Comment by whatthedrunk** [comment]
Server files updated to Simple Server. Just tested a new world and it worked fine, let me know if you have any issues.
