### ISSUE TITLE
Placed an item sorter that crashed the game, and now I cant open the world again

### ISSUE THREAD

**Issue by ObnoxiousPancake** [AllTheMods/ATM-3#966]
I have poured so many hours into this world :(
i have backups, i just have no idea how to do a rollback, or remove the offending item.
crash report:

https://gist.github.com/ObnoxiousPancake/7d2a4db96bcc524e6d50b97c313b3ee4

**Comment by Pelotrio** [comment]
You can delete the world folder and then one of the backups. The other option would be to edit the region files and and delete the block. If the problem is still present I can help you further on the atm discord [https://discord.gg/K5FBPYa](url)
