### ISSUE TITLE
[ATM3][1.12.2]Ore dictionary bug - cobalt ore

### ISSUE THREAD

**Issue by guyleaf** [AllTheMods/ATM-3#969]
## Expected Behavior

The ore dictionary entries of cobalt ore should only have oreCobalt.

## Current Behavior

The ore dictionary entries of cobalt ore has oreArdite.
![2020-08-31_23 54 34](https://user-images.githubusercontent.com/43506966/91740106-6acbca00-ebe5-11ea-8d4c-e120061f7604.png)

## Possible Solution

Remove ore dictionary tag

## Steps to Reproduce

1. Get SAG Mill and energy
2. Get cobalt ore
3. Put cobalt ore in SAG mill
4. Get ardite dust.

## Log

None

## Detailed Description

When I'm crushing the cobalt ore by using SAG mill, I always get Ardite dust.
Does anyone know this problem?
ATM3
![2020-08-31_23 54 43](https://user-images.githubusercontent.com/43506966/91740117-6f907e00-ebe5-11ea-96da-22f8b9c720dc.png)

**Comment by Pelotrio** [comment]
#978
