### ISSUE TITLE
how to deicate more ram for a server

### ISSUE THREAD

**Issue by jal21** [AllTheMods/ATM-3#97]
im trying to run a server and i have the need for more ram to it how do i do so on your crazy server start.bat or is there another why

**Comment by OrdinatorStouff** [comment]
settings.cfg has the settings you'd want to edit -- we intentionally made it that way so you **didn't** have to edit the crazy serverstart.bat

**Comment by OrdinatorStouff** [comment]
The readme here https://github.com/AllTheMods/Server-Scripts has details on what the different options are but generally you probably only ever want to modify the RAM setting
