### ISSUE TITLE
Serveur V6.0.0

### ISSUE THREAD

**Issue by Skillington** [AllTheMods/ATM-3#970]
So, with the server files, I'm looking to upload them to my server. However, there's only simple server files for 6.0.0, is there no way to obtain just the server pack?
 i dont understand what is to do with the v6.0.0 server "files".
what i have to do with the manifest.json, modlist.html and overrides??? do i can delete them, how can i download the full server files?

**Comment by Pelotrio** [comment]
The simple server files are designed to automatically download and install the pack. You have to run the starserver.bat or startserver.sh for it to do that.
