### ISSUE TITLE
Cannot join server

### ISSUE THREAD

**Issue by FaserArgentum** [AllTheMods/ATM-3#974]
I installed ATM3 v6.0.0 via the twitch launcher and opened a server via a website for me and a few friends to play on, we were unable to join the server and I contacted the websites support, after a few attempts they were unable to assist me and say the issue is client side rather than server side and they cannot help me.

When I try to join the server, I get error messages, sometimes it will say "Fatally missing registry entries" and sometimes it will give me a long error message, I have included screenshots. 
![error 1](https://user-images.githubusercontent.com/74488676/99181242-184e7400-2725-11eb-9cd1-de5897d36610.jpg)
![error 2](https://user-images.githubusercontent.com/74488676/99181246-1dabbe80-2725-11eb-86e1-33298e36f9ad.jpg)

**Comment by adrianomars** [comment]
I have the same problem

**Comment by Pelotrio** [comment]
There is a mismatch between the client and the server registry. I will close this for now
