### ISSUE TITLE
Akashic Tome cannot open Patchouli Guide Book

### ISSUE THREAD

**Issue by TheOneWayTruth** [AllTheMods/ATM-3#975]
## Expected Behavior

Akashic Tome should display and open Patchouli Guide  Book.

## Current Behavior

The Book cant be opened and the Icon is broken.

![2020-12-10_16 11 13](https://user-images.githubusercontent.com/12105754/101790196-7abb4a00-3b02-11eb-8ad1-d8e60048d776.png)

## Steps to Reproduce

1. Start the Game open the Book

**Comment by Pelotrio** [comment]
Will be fixed in the next version
