### ISSUE TITLE
Cannot open Draconic Evolution Tablet

### ISSUE THREAD

**Issue by TheOneWayTruth** [AllTheMods/ATM-3#976]
## Expected Behavior

The Book should be opened and displayed right.

## Current Behavior

![2020-12-10_16 16 13](https://user-images.githubusercontent.com/12105754/101790696-0cc35280-3b03-11eb-9331-a46fbb47b661.png)

## Steps to Reproduce

1. Start the Game open the Book

**Comment by xZa-k** [comment]
I'm also having this issue on my server, it may be related to https://github.com/NillerMedDild/Enigmatica2Expert/issues/1314 but as of now I haven't been able to resolve it

**Comment by Pelotrio** [comment]
Your launcher is defaulting to an older version of java. this is a common problem on some launchers. go into the launcher minecraft settings and add -version:1.8+ to additional arguments.
