### ISSUE TITLE
JavaVersionOrPathError

### ISSUE THREAD

**Issue by ab12321** [AllTheMods/ATM-3#977]
I changed my JAVA_HOME and path environment variables on my PC for school work and now the batch file ServerStart will not run. Upon trying to run the server, I am met with the error message, "could not find valid java version installed" and the error code, "JavaVersionOrPathError".

I have never had issues starting the server before and the issue started immediately after making this switch so I am very confident this is the problem.

I found a line in the settings SFG file labeled "JAVA_PATH" and it is set to = DISABLE. I tried changing this setting to ENABLE in hopes this would check my pc for my new JAVA_HOME, but with no success. 

Any suggestions on how to remedy this without resetting my PC environment variable JAVA_PATH would be greatly appreciated.

Other details:
-My mincraft_server executable file is 1.12.2
-I am using jre1.8.0_271
-I downloaded my atm3 serverfiles folder from the curseforge files page

**Comment by Pelotrio** [comment]
Nor a problem with the pack itself
