### ISSUE TITLE
Ardite Ore duplicate oredict entries

### ISSUE THREAD

**Issue by labradoe** [AllTheMods/ATM-3#978]
Ardite has an extra oredict that conflicts with Cobalt causing it not to be generated with Environmental Tech Miners, Mekanism Combiner, or Industrial Foregoing Laser.

## Expected Behavior
Ardite should only have the oredict entry <tconstruct:ore:1> so it can be generated appropriately by other mods using OD:oreArdite

## Current Behavior
Ardite doesn't get generated with ET Miners, Mekanism Combiner, or Industrial Foregoing Laser.

## Possible Solution
Add line to atm_oredict_ores.zs:

`<ore:oreArdite>.remove(<tconstruct:ore>);`

## Steps to Reproduce
1. Use /ct hand with Cobalt ore in hand and it shows both oreCobalt and oreArdite
2. Use /ct oredict and check the logs to see two entries for <ore:oreArdite>:

```
Ore entries for <ore:oreArdite> :
-<tconstruct:ore>
-<tconstruct:ore:1>
```

## Log
N/A

## Detailed Description
Add a line of code in _atm_oredict_ores.zs_ to remove the extra ore entry in oredict for Ardite that's conflicting with Cobalt.

**Comment by Pelotrio** [comment]
Will be fixed in the next version
