### ISSUE TITLE
[ATM3 3.0] Crashing when switching mode in AE2 pattern terminal (crafting/processing)

### ISSUE THREAD

**Issue by mbbk** [AllTheMods/ATM-3#98]
When i switch between crafting or processing in my AE2 pattern terminal sometime my server close and i have to restart it.
Here is the crash log if somebody can say me if i can fix that i would appreciate : https://paste.ubuntu.com/25379921/

**Comment by OrdinatorStouff** [comment]
I couldn't find related issues on AE2 tracker but this does seem like a legitimate bug of some kind in AE2. This is out of scope for us at the pack level but I'm not sure if the details and report are enough for them to track down.

**Comment by Boomflex** [comment]
No longer an issue.

Please ensure to be on the latest pack updates.
