### ISSUE TITLE
Iron Backpacks Mod doesn't have all backpack upgrades

### ISSUE THREAD

**Issue by BetaCrasher** [AllTheMods/ATM-3#984]
The mod is supposed to have 23 different upgrades. this mod pack only contains 4.

## Expected Behavior
All 23 different upgrades should be craftable and visible through JEI

## Current Behavior
Only 4 of the upgrades are there

-Damage Bar Upgrade
-Latch Upgrade
-Extra Upgrade Point
-Everlasting Upgrade

## Possible Solution
Recipies might not have been added in JEI

## Steps to Reproduce
1. Open JEI
2. type '@iron @backpacks'

As you can see, there are only 4 possible upgrades
![image](https://user-images.githubusercontent.com/54913524/119911353-2f1d2100-bf27-11eb-9241-99ea01f137c9.png)

**Comment by Pelotrio** [comment]
I will check that out later

**Comment by Pelotrio** [comment]
This the fault of the mod because only these 4 upgrades exist. My guess is that the mod was abandoned after porting it to 1.12 but at the current state there are definitely only 4 upgrades.
