### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by leumas1960** [AllTheMods/ATM-3#985]
This isn't related to this modpack really, but bear with me. I'm having a weird server side crash caused by thermal dynamics in my modpack, this modpack had a similar issue, but a newer version fixed it:
https://github.com/AllTheMods/ATM-3/issues/160

The versions of the modpack referenced aren't downloadable, as far as I know. So, what changed? How was it fixed?

Any help would be much appreciated, really want to be able to use itemducts and fluiducts.

Please note, this issue happened in my, later version of thermal dynamics (latest version for 1.12.2 when I wrote this), and the linked issue was a much older version, but same issue, so this is likely a bad mod interaction.

Crash log:
https://gist.github.com/leumas1960/042e043a298b449d5c3ad68f15c91ddf

**Comment by Pelotrio** [comment]
Probably an issue with another mod. Logistic pipes could be the issue so I would try to upgrade/remove the mod and test that. Else you just have to trial and error with removing mods to find the cuase

**Comment by Pelotrio** [comment]
Good luck with that.
