### ISSUE TITLE
Compact Machine Preview is faulty

### ISSUE THREAD

**Issue by Magentanide** [AllTheMods/ATM-3#987]
# Overview
It is possible to preview the contents of a Compact Machine by right clicking, which brings up a navigable 3D representation of its contents. This is useful in remembering what's actually in the machine without needing to face the loading time of going to check.

# The Problem
The walls of the compact machine itself is rendered, obscuring the view. Thankfully(?), the blocks do not render correctly, and the preview believes that the walls are in fact iron doors. While this does mean something is visible inside, the doors obscure the GUI and this is far from ideal.

![doors1](https://user-images.githubusercontent.com/32601565/121932679-0e353800-cd3d-11eb-8f7c-cfff97ad92d8.png)

It looks like a number of blockIDs are faulty inside Compact Machines. For instance, the Foresty Apiary that appears in this image is an RFTools Redstone Receiver, and what appears to be a Forestry Farm block is an RFTools Power Monitor. These bugs are all visual, the actual contents is saved correctly when broken and replaced.

![doors2](https://user-images.githubusercontent.com/32601565/121932988-666c3a00-cd3d-11eb-9ac1-d4e5c1046942.png)

Present in release version 6.1.0

**Comment by Pelotrio** [comment]
CompactMods/CompactMachines#396
