### ISSUE TITLE
Post this modpack om mcbbs.

### ISSUE THREAD

**Issue by nsdnsg** [AllTheMods/ATM-3#988]
Hello,I'm a minecraft player from China.
Your ATM-3 modpack is really good,but it is not too famous in China.
Can I post it on mcbbs(a most Chinese minecraft forum,here's lot of people on it)？I think it can make your modpack famous.
I will credit you.
Thanks for your agree.
(My English may not be very good, please forgive me.)

**Comment by Pelotrio** [comment]
You can link to the official download on curseforge that is fine. You should not upload the whole modpack to the website.

**Comment by nsdnsg** [comment]
> You can link to the official download on curseforge that is fine. You should not upload the whole modpack to the website.

Sure,I will never creat any other download link on any other website,and use your link on curseforge.
