### ISSUE TITLE
Game crashes and world breaks when breaking forestry hill cherry leaves with silk touch.

### ISSUE THREAD

**Issue by NQMIS** [AllTheMods/ATM-3#989]
## Current Behavior
When breaking a hill cherrry leaf from forestry (with silk touch) without cherrys in it  it drop a leaf with the name 'trees.gramar.leafes.type'
When breaking a hill cherrry leaf from forestry (with silk touch) with cherrys in it the game frezes and then crashes.

## Steps to Reproduce

1. Open ATM3 version 6.1.0
2. Break a hill cherry leaf with silk touch

## Log
Crash log:
https://gist.github.com/NQMIS/5231f3e0cc953b380d5ca8063b32c4d9

**Comment by Nomis33** [comment]
If someone could help me recover my world I would be very thankful!

**Comment by Pelotrio** [comment]
This looks like a bug from Forestry they probably dindnt think about silk touch. If you want to recover your world you would have to kill the item entity. If you are on a server that is quite easy and if not you would have to edit the region file. If you need further help on how to do that I would recommend you join our discord server where I can help you to do that.

**Comment by Nomis33** [comment]
> This looks like a bug from Forestry they probably dindnt think about silk touch. If you want to recover your world you would have to kill the item entity. If you are on a server that is quite easy and if not you would have to edit the region file. If you need further help on how to do that I would recommend you join our discord server where I can help you to do that. 

Yes I would need help with that I'm on the discord my tag is NQMIS#2001.

**Comment by Pelotrio** [comment]
[](https://discord.gg/K5FBPYa) You can come to the official atm server if you need help.

**Comment by Pelotrio** [comment]
This has been resolved but the bug in forestry persists.
