### ISSUE TITLE
Cherry Leaves Silk touch Crash

### ISSUE THREAD

**Issue by SchlobinExE** [AllTheMods/ATM-3#996]
When you break a Cherry Leave from Forestry with a silk touch tool fron Thinkers Construct your game will crash. If your Playing on an server that item can end up in your Inventory and if you open that with the bugged leaf then your game also crashes.

## Expected Behavior

fix it lol

## Current Behavior

???

## Possible Solution

take out the cherry tree from forestry, there are one or two cherry trees from other mods
(maby easiest possibility)

## Steps to Reproduce

1.Silk Touch Tool from Tinkers Construct
2.Find a Cherry Tree
3.Break A leave with the Tinkers Construct Tool from above
4.Crash
5.If it dropped in your inventory your lucky, drop your hotbar Stuff, DIE, and never touch that gravestone again.
     5.2 if it didnt have fun crashing every single time you want to join the Game/Server

## Log

https://gist.github.com/SchlobinExE/0ae2727fb9840e176c03b87e9ef59c19

**Comment by Airfirewall** [comment]
#989
