### ISSUE TITLE
Twilight Oak Door Losing Texture

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-3#997]
twilight oak door and some other doors（like canopy door...)  lose textures for ATM3-v6.1.1

## Expected Behavior

you know~

## Current Behavior

The  current behavior is shown in pictures below
[2022-02-12_00.03.18.png](https://s2.loli.net/2022/02/12/urIPJgNdeOpx7af.png)
[2022-02-12_00.03.26.png](https://s2.loli.net/2022/02/12/yBhTWqpCofPDF5L.png)

## Steps to Reproduce

1.Start any world
2.Search door

**Comment by Pelotrio** [comment]
This looks like a bug from Twilight Forest itself or from your texture pack. There is not much I can do about it.

**Comment by ghost** [comment]
> This looks like a bug from Twilight Forest itself or from your texture pack. There is not much I can do about it.

ok, it is the same when i try without resourcepack,thanks anyway

**Comment by Pelotrio** [comment]
@XinChenzi I just tested it in an environment with just a few mods and it still has no texture. So it looks like a bug from Twilight Forest itself.

**Comment by Pelotrio** [comment]
@XinChenzi  Take a look at this issue, the models don't even exist yet.
https://github.com/TeamTwilight/twilightforest/issues/711
